### ISSUE TITLE
consider renaming init

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1004]
init on linux is process 0, so forgetting the ./ causes grief.. also since menu editor is there, and user editor, there's reason now it's more than just init.

also that'd make the command ```init --initialize`` seem less funny

**Comment by granitepenguin** [comment]
So what would we call it instead?

setup  -  conflicts with Windows
wwivconf
wwivconfig
config
tools
sysoptools
wwivtools

throw any ideas in here and let's see what sticks

**Comment by wwivsoftwareservices** [comment]
If it matters, I like wwivconfig.exe.

The rumors of my demise are greatly exaggerated.

**Comment by k5jat** [comment]
wwivsetup or wwivconfig make sense to me.

**Comment by AlPrunty** [comment]
MakeWWIV.exe

**Comment by wwiv** [comment]
wwivconfig works for me.

**Comment by ericpareja** [comment]
+1 on wwivconfig
