### ISSUE TITLE
separate UI from serving part of wwivd

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1007]
Since I want wwivd to work well on windows too, the best thing to do (for all platforms) is to move the UI from the daemon part of wwivd.  Right now wwiv-server has both.

so talking to wwivd to do things like "get status" to update a UI will be a simple call like 
```
GET /status HTTP 1.0\r\n
```

and it'll return something like [headers] + content-type: text/json\r\n + 
```
{ "status" : [ { "2" : "idle" },{ "3" : "connection from 127.0.0.1" }, { "binkp" : "idle"} ] } 
```

**Comment by granitepenguin** [comment]
do we want this to be a general-purpose "bind to all IPs" thing, or just a "bind only to localhost for our own purposes" setup?

**Comment by wwiv** [comment]
probably I'll start with localhost for now, then add unix domain socket on linux.  may open the status operations to all ip's, but only allow operations on localhost or domain socket. (i.e. disconnect node)

**Comment by wwiv** [comment]
added /status handler in https://github.com/wwivbbs/wwiv/commit/3c9d05af98316f9c47648285b1d40f11780c1444

**Comment by wwiv** [comment]
Implemented for 1st cut of features in https://github.com/wwivbbs/wwiv/compare/5d8ced1ce041...2fe612f8d91b
