### ISSUE TITLE
wwivd logging to root directory

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1017]
OS: Linux

Running wwivd via systemd, I noticed that most of the logs are going to /var/log/syslog as expected, but it is also dumping some info to wwivd.log.  The problem is wwivd.log is not in the WWIV directory, it's in the root directory.  Need to figure out how to fix that (define working directory for systemd, or something).

**Comment by wwiv** [comment]
http://stackoverflow.com/questions/933850/how-do-i-find-the-location-of-the-executable-in-c may have some good ideas

**Comment by granitepenguin** [comment]
That's a bit heavy-handed.  I think adding 
``WorkingDirectory=<wwiv_dir>``
to the systemd service file will work well enough.

**Comment by granitepenguin** [comment]
Assigning to myself to update the wwivd.service file that gets placed for systemd

**Comment by wwiv** [comment]
I don’t see this happening on my server.  Is it fixed?

**Comment by wwiv** [comment]
I see that working directory set in the service config file for wwivd

**Comment by wwiv** [comment]
Should be fixed with the new install instructions/files
