### ISSUE TITLE
Compile fails on wwivd

### ISSUE THREAD

**Issue by k5jat** [wwivbbs/wwiv#1018]
I pulled the latest and greatest down and this is what happened when I tried to compile it:

Scanning dependencies of target wwivd
[ 93%] Building CXX object wwivd/CMakeFiles/wwivd.dir/wwivd.cpp.o
[ 93%] Building CXX object wwivd/CMakeFiles/wwivd.dir/wwivd_unix.cpp.o
Linking CXX executable wwivd
../core/libcore.a(http_server.cpp.o): In function `wwiv::core::HttpServer::SendResponse(wwiv::core::HttpResponse&)':
http_server.cpp:(.text+0x608): undefined reference to `wwiv::sdk::daten_to_wwivnet_time(long)'
collect2: error: ld returned 1 exit status
wwivd/CMakeFiles/wwivd.dir/build.make:112: recipe for target 'wwivd/wwivd' failed
make[2]: *** [wwivd/wwivd] Error 1
CMakeFiles/Makefile2:1162: recipe for target 'wwivd/CMakeFiles/wwivd.dir/all' failed
make[1]: *** [wwivd/CMakeFiles/wwivd.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Running Debian 8 with gcc 4.9.2

**Comment by wwiv** [comment]
I see it in the jenkins build too.

https://build.wwivbbs.org/jenkins/job/wwiv/label=linux/2514/console

**Comment by wwiv** [comment]
Fixed inhttps://github.com/wwivbbs/wwiv/compare/5d8ced1ce041...2fe612f8d91b
