### ISSUE TITLE
Changes to the new "wwivd Configuration" don't save

### ISSUE THREAD

**Issue by k5jat** [wwivbbs/wwiv#1019]
When I change them, and hit escape, the changes don't save and defaults are still there.

**Comment by wwiv** [comment]
Just worked for me, I'll add a dialog if the thing fails to save.

**Comment by k5jat** [comment]
I don't know. I noticed that in irc you said that wwivd would create a wwivd.json file. Mine never did.

**Comment by wwiv** [comment]
It's under the WWIV data dir

**Comment by k5jat** [comment]
I found it. I edited it by hand and it seemed to do the trick. One interesting note, it was read only when I first went to edit it. That could have been why it wasn't saving.

**Comment by wwiv** [comment]
that'd do it. not sure why it would have been read only. if you can solve that mystery - let me know.

**Comment by granitepenguin** [comment]
Most likely reason is different user created the file. How did it originally get created (i.e., what user ran wwivd, etc)?

**Comment by k5jat** [comment]
I have systemd set to run it as wwiv. The only other user it could run under on that system is root, but the file is owned by wwiv.

**Comment by wwiv** [comment]
well i changed the code to not ever write it as wwivd, maybe that'll fix it. holler if you see that happen again.
