### ISSUE TITLE
wwiv-linux-5.2.2430.tar.gz broken archive

### ISSUE THREAD

**Issue by streaps** [wwivbbs/wwiv#1025]
wwiv-linux-5.2.2430.tar.gz is kaput:

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by granitepenguin** [comment]
I'm assuming this is the one from the Releases page.

fixed.

**Comment by streaps** [comment]
yes, it was the one from the release page. thanks for fixing it.
