### ISSUE TITLE
chains (doors) not displaying in SyncTERM

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1031]
OS: Linux

For quite a while now (around the time of some of the I/O changes) running doors in dosemu no longer display output to syncterm. They are running, you just can't see them or interact with them.  If you ssh directly to the system and run ./bbs, the doors display and act as expected.

**Comment by granitepenguin** [comment]
actually, this is a chain I/O issue in general.  I have a test chain that simply runs a shell script

```bash
trap "echo" SIGHUP SIGINT SIGTERM

echo "Environment before sourcing"
env
echo

echo "Environment after sourcing"
. ~/.wwivrc
env

echo "screen size: `stty size`"
sleep 5
```

and even that doesn't display anymore in syncTERM.  So this is NOT a dosemu issue, it's a Chain I/O issue.

**Comment by wwiv** [comment]
not a bug. You can't just use bash like this to send the display locally.

As of yesterday, STDIO support on linux works, and this will work for stdio doors. For dosbox you need to pass the socket handle to it.

**Comment by granitepenguin** [comment]
So is it documented anywhere how to actually use this on linux?
Like how to let dosemu use it?
