### ISSUE TITLE
Unable to make a conference available

### ISSUE THREAD

**Issue by k5jat** [wwivbbs/wwiv#1035]
I added a WWIVnet conference, added a bunch of subs to it, and now I can't make it available. I've checked file permissions and they're correct.

I'm using Debian 8 with the latest git.

**Comment by wwiv** [comment]
Did you enable conferencing for your user in (D)efaults?

**Comment by k5jat** [comment]
I enabled it for my user, and can now use conferences which is weird. But yet, I go into the //sysop menu, choose [J] Conference editor, select 1 for subs, hit M for modify, and select B for my WWIVnet conference, and I can not change the O) option for Available from No.

**Comment by wwiv** [comment]
Since you've commented to problems with conferencing in https://github.com/wwivbbs/wwiv/issues/1043 I take that to mean you've gotten past this issue and it may be closed

**Comment by k5jat** [comment]
Nope, I still can't get //SYSOP->[J]->[1]->Modify->Chosen Conference (B in this case)->[O] Available to change from No to Yes. Why are they unavailable to start with?

Also just pulled a few minuted ago.
