### ISSUE TITLE
User Editor displays deleted on active accounts

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1039]
If you are scrolling through your list of users and come across one that's been deleted, all users after that will display deleted even though they aren't (i.e., the [[ DELETED USER ]] text doesn't refresh)

![screen shot 2017-03-06 at 11 47 56](https://cloud.githubusercontent.com/assets/913430/23622155/3010eeaa-0263-11e7-943d-3f156bc1d0d5.png)

**Comment by wwiv** [comment]
also there's no way to delete an account in this editor too... Working on that now, but it's a bit of work to move some of the code outside of the bbs.

The plus side is then we can build command to delete accounts or restore accounts into wwivutil.  (example, no call in a year gets deleted, etc).

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/compare/fe7361378d70...4e688fb10b4c
