### ISSUE TITLE
Handles not being used in the message base. 

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1047]
Version being used 2536

It seems that handles are not being expressed as default in the bbs. My real name is being used 100% in the bbs.

**Comment by wwiv** [comment]
I don't see that. My handle is rushfan and realname is "Rushfan RealName" and don't see it.  I'll need more data to go on.

**Comment by wwiv** [comment]
@granitepenguin do you see this?

**Comment by granitepenguin** [comment]
I have not seen it either. Is this all subs, FTN only? Are there places where it works and others that it doesn't?

**Comment by mmunson** [comment]
All subs. Or is there a flag in the //BE that i can configure for handle only? Do you want a copy of my user database file?

**Comment by wwiv** [comment]
can you screenshot what's wrong.
also are you sure your userfile has real names in it that are different from the handles?

**Comment by granitepenguin** [comment]
From what I can see, this has always been the case.  It looks like your posts have always been your name.  I don't even know what your handle is (don't think I've ever seen it).  Here's a sub post from 2014 showing your name.


![screen shot 2017-03-10 at 08 40 15](https://cloud.githubusercontent.com/assets/913430/23799247/815bb44a-056d-11e7-8e62-4066bb0b63f4.png)

**Comment by wwiv** [comment]
I can't reproduce this, please open it with more information to debug your setup
