### ISSUE TITLE
wwivd is not reading wwivd.ini?

### ISSUE THREAD

**Issue by larsks** [wwivbbs/wwiv#1053]
I am using wwiv compiled from source (440b25cda7dfc004ac9eaa9e42eb17a91040ffb6).  I have in my `wwivd.ini`:

```
$ cat wwivd.ini 
;=============================================================================
;
;                 WWIVd Version 5.3.0 Initialization File
;
;              Lines begining with a semi-colon are ignored
;=============================================================================
;
[WWIVD]
telnet_port = 23
ssh_port = 22
binkp_port = 24554
end_node = 4
```

But when I start `wwivd` I see:

```
$ /opt/wwiv/wwivd --wwiv_user=wwiv
2017-03-16 14:11:29,569 INFO  wwivd - WWIV Daemon.
2017-03-16 14:11:29,570 INFO  Listening to TELNET on port: 2323
```

And in fact if I run that under the control of `strace`, there is never any attempt to open or otherwise access `wwivd.ini`.  The only files I see it trying to access in the wwiv directory are:

```
27420 open("/srv/wwiv/config.dat", O_RDONLY) = 4
27420 open("/srv/wwiv/data/wwivd.json", O_RDONLY) = -1 ENOENT (No such file or directory)
27420 access("/srv/wwiv/data/nodeinuse.0", F_OK) = -1 ENOENT (No such file or directory)
27420 access("/srv/wwiv/data/binkpinuse", F_OK) = -1 ENOENT (No such file or directory)
```

**Comment by granitepenguin** [comment]
wwivd.ini is old, it is not used anymore; just delete it.  The settings are maintained under the init program (option W).

**Comment by larsks** [comment]
I see.  I was following https://docs.wwivbbs.org/en/wwiv52/linux_installation/. Is there something else I should be reading?

**Comment by granitepenguin** [comment]
It depends.  If you are using wwiv52 directions, you should be building from 5.2 source (you appear to be using 5.3 source). If you built from the 5.2 source, the wwivd.ini would still work.

**Comment by larsks** [comment]
I am using the current `master` because with the 5.2 release I was getting
a floating point exception from the `bbs` binary, and the fix for that
appears to have merged only recently.

**Comment by granitepenguin** [comment]
There is some lag between docs and code with 5.3 (part of the hazard of 5.3 being bleeding-edge).  I'll get that part of the docs updated.  If you are going to use the 5.3 code, use the 5.3 docs; it will be more consistent (but probably not perfect).

**Comment by granitepenguin** [comment]
FWIW, 5.3 has been working well for everyone using it.  It's reasonably stable.

**Comment by larsks** [comment]
Thanks, I'll go look for the 5.3 docs.
