### ISSUE TITLE
Hide fido kludge lines by default.

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1055]
we probably should hide as an optional like the AREA: tag as well as SEEN-BY: (and any other kludge lines that aren't ^A prefixed.

**Comment by ghost** [comment]
It would be cool if by optional you mean it's still in the message just hidden by the message reader, then you could have a button to hide/show them in the reader. When you reply to a message with them shown they appear in the quote data, when hidden they don't.

**Comment by AlPrunty** [comment]
Definitely needed... it's aesthetically unpleasing to see all the control line gunk.

Allen

**Comment by wwiv** [comment]
Does mystic allow you to show them? I can't find where.

@AlPrunty Do you know?

I'll mark them as internal control lines (^A0 + LINE) for now, then it seems reasonable to add a command to show all of these lines (WWIV networking has a slew of them too)

**Comment by AlPrunty** [comment]
WWIV,

Mystic does show you the kludge and hidden lines... it's an undocumented feature.  From any sysop account in the mail reader simply press "V" and it will display all hidden information.

Allen

**Comment by wwiv** [comment]
Thanks @AlPrunty !

**Comment by wwiv** [comment]
ok, they are hidden now. I'll open a FR later to give some way to show wwiv control lines
