### ISSUE TITLE
Upgrade from 5.3.2556 to 5.3.2558 failed

### ISSUE THREAD

**Issue by AlPrunty** [wwivbbs/wwiv#1057]
All programs are giving...

The program can't start because api-ms-win-core-rtlsupport-l1-2-0.dll is missing from your computer.  Try reinstalling the program to fix this problem.

I have searched for the DLL can't find it.  I've re-installed ALL of the Visual C runtimes... does not work.

WWIV-UPDATE won't load can't roll back.  Had to delete my installation of wwiv and start over due to this.  

Consider this an URGENT bug as I can't find the .dll anywhere to fix this.

Allen

**Comment by wwiv** [comment]
you can roll back by unzipping the older binary into your wwiv directory

**Comment by wwiv** [comment]
https://build.wwivbbs.org/jenkins/job/wwiv/label=windows/2556/artifact/wwiv-win-5.3.2556.zip is the URL to download the older version.  http://build.wwivbbs.org has all of the older builds on it.

**Comment by wwiv** [comment]
Also that's a universal CRT runtime piece, make sure you have the ucrt installed.
https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows has it.

**Comment by wwiv** [comment]
other things to try, delete ucrtbase*.dll from the wwiv dir.  ditto for concrt*.dll

**Comment by wwiv** [comment]
Also what OS are you on?

**Comment by AlPrunty** [comment]
It says that updt (the URL above) is already installed.  Is there going to be another release soon?

Allen

**Comment by AlPrunty** [comment]
I am running windows 7 professional 32 bit.

**Comment by wwiv** [comment]
This is the same as #1059
