### ISSUE TITLE
See if maxmsgs per sub can be uint16_t max not int16_t max

### ISSUE THREAD

**Issue by AlPrunty** [wwivbbs/wwiv#1061]
Not sure if this is correct size, but most of my usenet retention is set at 50,000

Allen

**Comment by wwiv** [comment]
It's actually 16384.  The max # of messages set for a wwiv type-2 message area is a short (2 bytes).  I could see if I can bump it to 32k, but need to make sure nothing else in wwiv is using a signed short.

Long term I plan on adding JAM message base support to wwiv as a type-3 message format (type-1 is like the fido MSG format and no longer supported as of 5.0, type-2 is what we use now,  type-3 will be JAM).  We can probably bump up that limit to 1M or whatever with JAM

**Comment by wwiv** [comment]
Let's leave this and rename it to see if we can at least get 32k

**Comment by AlPrunty** [comment]
JAM is unlimited.

**Comment by BloodStoneBBS** [comment]
Could this be why I have a sub that has Max Msg set to 500 but has over 30,000 messages?

**Comment by wwiv** [comment]
is it still growing, or is the size now fixed?

**Comment by BloodStoneBBS** [comment]
Not sure. Currently at 39261. I'll keep an eye on it.

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/7781255ff4f196809cee635eefbe7cdb3d68fefe

It's now uint16_t max.
