### ISSUE TITLE
Zone 2 reporting that FTS Message lines are terminated with ☺

### ISSUE THREAD

**Issue by AlPrunty** [wwivbbs/wwiv#1063]
Paul,

This is something that will not be accurate.... for instance I'm managing two ☺
nets at the moment and when I took over Net 2320 most of the net that existed ☺
when I was NC in 2007 was still intact when I took the helm again in 2016.  I ☺
had to drastically clean house because the BBS's in the nodelist were not even ☺

----

Note:  I see this in GOLDED... synchronet and mystic do not terminate the line with ☺

----

Michel Van Der Vlist stated this... (Note he's hostile towards anything Z1)

Speaking about crappy legacy software... Your message does not comply with
Fidonet standards. It terminates each "line" with a Space, CR, hex 01
combination.

--------------

Allen ON again

I am willing to take the heat for putting your tosser through it's paces.  I just hope, unlike the Mystic author, you will support me in trying to identify any weaknesses either real or perceived by either fixing them or helping me debunk them.

This one I can repeat, and the FTSC nerds will point out any problems they will find with it.

Allen

**Comment by wwiv** [comment]
I wonder if it's related to quoting or something. I just created a new FTN message from the bbs, then ran ```networkf .5 export``` (this is my 5th network) to export to to a PKT file.

Looking at the PKT file (both with emacs hex mode and wwivutil fido dump <filename> | less (so I see the unprintable chars), I see this.

```
msg_type:2
cost:    0
to:      All(1/2)
from:    Rushfan(21:1/1)
subject: New Test
date:    19 Mar 17  11:57:36^@; [19 Mar 17  10:57:36]
text:

AREA:RF
^APID: WWIV 5.3.0.development
^ATID: WWIV NET51.development
^AMSGID: 21:1/1 00000017
^ACHRS: CP437 2
Let's look at those EOL chars
What do we say?
line5
line 7
Rushfan
^D1
-----------------------------------------------------------------------
        Mystic Rhythms BBS   *   telnet://mystic.wwivbbs.org
-----------------------------------------------------------------------
^D5
^D6
--- WWIV 5.3.0.development
 * Origin: Rush's Workshop (21:1/1)
SEEN-BY: 1/1
```

Here's emacs:
```
000000e0: 6c6f 6f6b 2061 7420 7468 6f73 6520 454f  look at those EO
000000f0: 4c20 6368 6172 730d 0d0d 5768 6174 2064  L chars...What d
00000100: 6f20 7765 2073 6179 3f0d 0d6c 696e 6535  o we say?..line5
00000110: 0d0d 6c69 6e65 2037 0d0d 5275 7368 6661  ..line 7..Rushfa
```

I don't doubt that the chars got there somehow, but I can't figure out where.  I'm using the latest networkf from today (an hour old).
Any help is appreciated.

**Comment by wwiv** [comment]
always happy to help fix things, just bear in mind time constraints since this is just a hobby

**Comment by AlPrunty** [comment]
I totally get that... this was from 2446.  All I can do is post a test message in FIDOTEST to see if it reappears.  I can extract the message from golded and post it here as a raw file but I only see it in golded.. synchronet and mystic ignore it.

Allen

**Comment by wwiv** [comment]
once you post it in wwiv, wwiv will make a s32675.net file that has it.  Then when you run networkf it'll convert it into a PKT or su? file for sending.  copy off both of those as well as the message in golded. That'll help figure out where it's getting borked along the way.

also when you say you get it from golded, how? do you get it from mystic's jam database?

**Comment by AlPrunty** [comment]
WWIV tosses to Syncrhonet (my hub) which tosses to Mystic 

Everything circulates through Synchronet.

Here's a message that went through it's showing as an @ sign now. not at the quote but at the end of lines that appear to be wrapped.

I'm going to post a test message and see how it progresses.

 Msg  : 31082 of 31082                      
 From : ALLEN PRUNTY                        1:2320/103      19 Mar 17 21:13:14
 To   : Rick
 Subj : Re: Caught up with Last Wendsday...
===============================================================================
RE: Re: Caught up with Last Wendsday...
BY: Rick(0:0/0)

R> Yeah, they've really screwed up her character, and for no good reason.  I
R> get that they are trying to show a typical messed up, self-centered
R> teenager
R> who doesn't really know what she wants.  But the problem is they are

They seem to have also forgotten that Claire is not a teenager anymore... now @
they are in college which implies they are now older than 18... and should be @
mature enough not to act that way.

**Comment by AlPrunty** [comment]
It does show the @ as a smiley face when read in golded.  However posted a new message in fidotest and the smiley face is on every line in the s32675.net file... please take a look at it.

Since it won't allow .pkt and .net files I'm zipping them
[s32675.zip](https://github.com/wwivbbs/wwiv/files/853836/s32675.zip)
[19222806.zip](https://github.com/wwivbbs/wwiv/files/853838/19222806.zip)

Of course the characters will appear when tossed so I am not going to bother tossing them to fidonet to get people bitching about a "broken tosser" that we are trying to get fixed.

Please let me know if this helps.

Allen

**Comment by wwiv** [comment]
Thanks @AlPrunty That helped a ton. I now found this:

from read_message.cpp
```
// A line ending in ^A means it soft-wrapped.
```

Looks like we need to strip trailing ^A characters when packaging it up for FTN networks.

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/compare/f76df8f17f62...d68acc37edf7
