### ISSUE TITLE
WWIV Edit

### ISSUE THREAD

**Issue by AlPrunty** [wwivbbs/wwiv#1067]
Can you post the exact wwivedit files needed?  I found them on another website and followed instructions to the letter... it would not work.

Allen

**Comment by granitepenguin** [comment]
Which instructions did you use?

**Comment by AlPrunty** [comment]
The ones on the documentation... would be great to create an install of WWIV that already had it installed :-)

**Comment by askpatrickw** [comment]
The documentation is part of WWIV so I'm gonna call this closed.
