### ISSUE TITLE
Quoting on QUICKBBS style editor...

### ISSUE THREAD

**Issue by AlPrunty** [wwivbbs/wwiv#1069]
I am using TIDE, A Quickbbs style editor since I can't get the working package of WWIVEDIT ... the package I found just won't work even with your config changes.

Anyhow... when I quote a message it's not creating the 

  xx> Initials and > character before the quote... 

WWIV should advance all previous quotes by adding a caret >> and then at minimum put a carat on all new quoted lines... or the initials of the quoter.

Tide makes it easy since all I need to do is put xx> on the first line of the quoted paragraph and do a control d and it will re-wrap, but it would be nice to have it quote the message text properly.

Thanks

Allen

**Comment by wwiv** [comment]
where can I get tide?

**Comment by AlPrunty** [comment]
Here...

[tide111.zip](https://github.com/wwivbbs/wwiv/files/853968/tide111.zip)

**Comment by AlPrunty** [comment]
Tide is my favorite editor of all time... it has some very unique features.  WIsh you could wrap the To/From features into qwkbbs like Synchronet does.  It shows you the to/from subject in the header.

Allen

**Comment by wwiv** [comment]
ah, that's a difference in how wwiv style editors work and I guess QBBS editors.  WWIV editors add the quote lines, didn't realize that.

**Comment by wwiv** [comment]
This is fixed now.
