### ISSUE TITLE
Bink-P Protocol returns following with Bink-D

### ISSUE THREAD

**Issue by AlPrunty** [wwivbbs/wwiv#1072]
It does not recognize 1:2320/103 the node that I use on WWIV.  I get...

- 02:15 [1652] OPT CRAM-MD5-cafebabecafebabecafebabecafebabe
+ 02:15 [1652] Remote requests MD mode
- 02:15 [1652] WWIVVER 5.3.0.2565 (Mar 20 2017, 03:43:30)
- 02:15 [1652] SYS LiveWire WWIV Test System
- 02:15 [1652] ZYZ Allen Prunty
- 02:15 [1652] VER networkb/5.3.0.2565 binkp/1.0
- 02:15 [1652] LOC Unknown
- 02:15 [1652] OPT CRC
- 02:15 [1652] WWIV @1.fido
+ 02:15 [1652] addr: 20000:20000/1@fidonet
? 02:15 [1652] called 1:2320/103@fidonet, but remote has no such AKA
+ 02:15 [1652] done (to 1:2320/103@fidonet, failed, S/R: 0/0 (0/0 bytes))
  02:15 [1652] session closed, quitting...

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/464b2ee24b12cd95cf4955aa3de0a5b6c2b1b967
