### ISSUE TITLE
Environement Variables for proper operation of external editors.

### ISSUE THREAD

**Issue by AlPrunty** [wwivbbs/wwiv#1073]
The docs to install Tide say to use command line 

TIDE -N%5 yet there is no %5 in the INIT config... when I try it does not work.

I can get it to edit the theoretical text file by doing a TIDE %1

Allen
/s

**Comment by AlPrunty** [comment]
OK... figuring out why the external message editor isn't working.

The following event variables work.

%1 - Path c:\wwiv\temp\msgtmp
%2 - Columns - 80
%3 - Rows - 24
%4 - Max Lines - 124 (not used)

---

%5 may have at one time passed the node number... this is ABSOLUTELY needed... can we please have a node number variable?

I have been able to make Tide work correctly (with the exception of the advanced quoting that WWIV should be passing which is a separate issue that will effect ANY other external editor) by using the following batch file.

-----
C:
cd \wwiv\temp\1
c:\wwiv\tide\tide.exe -n1
------

If I had the environment variable to pass I would simly replace the 1 with a %1 which would pass %5 (if %5 was the node number in the environment variable) all would work properly.

Allen

Thanks

Allen

**Comment by AlPrunty** [comment]
OK... Used bat as above...
Called in INIT as TIDE.BAT %N
changed one to %1

Looks like %N was the magic bullet.  Docs are referring to %5 incorrectly.  Tried to edit doc and it created a fork.

Would like access to edit documentation I can help you there... I can't program my way out of a wet paper bag but I can write useful docs.

**Comment by wwiv** [comment]
The docs are all here:
https://github.com/wwivbbs/docs

looks like tide is here: 
https://github.com/wwivbbs/docs/blob/master/docs/quickbbs-editors.md

You can end a pull request to request changes be merged.

**Comment by AlPrunty** [comment]
Thank you I will do it after resting from my Chemo this morning.
