### ISSUE TITLE
Necessary ^A Kludge line is stripped when using external editor.

### ISSUE THREAD

**Issue by AlPrunty** [wwivbbs/wwiv#1074]
OK... Tide places a Kludge on all messages edited by it.  When it's saved to the BBS it's stripping the ^A Kludge.

Tide places the following line on the first line of the message.

^ANOTE: TIDE 1.11

The ^A in this case should not be stripped and it should be hidden with the rest of the kludge lines.  I'm sure someone will nit-pick this but I'm going to roll with it anyhow.  I wonder if the changes in the fido networking will strip this even if this is imported in the message base correctly.

Allen

**Comment by wwiv** [comment]
Can you find docs on this kludge line?  

My recent change strips a trailing ^A, not a leading ^A.  WWIV uses ^Dn (n is in '0' .. '9') as it's hidden kludge lines.  ^A is apparently used at the end of a line to say it's been word wrapped.

**Comment by AlPrunty** [comment]
I can't find the docs on this kludge line... only that after the message is saved it is displaying the 

NOTE: TIDE 1.11

Which is usually kludged out on every other BBS Software with teh ^A

Allen

**Comment by wwiv** [comment]
We need to do the ^A -> ^D0 kludge conversion when using a QBBS style editor.
