### ISSUE TITLE
Possible Issues with MSGID Calculation

### ISSUE THREAD

**Issue by AlPrunty** [wwivbbs/wwiv#1076]
On Monday March 20 2017 01:47, you wrote to me:                               
                                                                              
 AP> @MSGID: 1:2320/103 00000013                                              
                                                                              
The sequence number in the MSGID is suspiciously low. My educated guess is that
a counter is initiated at first run and then increased with each message. While
technically, OK, this method carries the risk of losing the counter and       
repeating numbers. Something better is proposed in FSP-1029.                  
                                                                              
http://ftsc.org/docs/old/fsp-1029.002    par 4.8

**Comment by ghost** [comment]
This is a good idea. Except it will overflow in 2038, but then we could get "system time" from the date it overflows, and the msgid only has to be good for three years.

**Comment by wwiv** [comment]
I have a serial number file now (it's binary not text), it's in \bbs\data\msgid.dat

I could seed it from the current time, that's fine.  it's a 32bit unsigned number, not signed (actually doesn't matter). time_t is signed (31 bits) and will overflow in 2038, uint32_t could last till 2106 (WWIV uses uint32_t as daten_t internally for all of it's dates, so we can down-cast from 64 bit time_t to wwiv's datent_t and be good till 2106. I won't be working on wwiv by then, so past that date is someone else's problem.

**Comment by AlPrunty** [comment]
I probably won't be around in 2038

**Comment by wwiv** [comment]
here's the latest version of the doc (It's renamed a FRL, whatever that means)
http://ftsc.org/docs/frl-1029.002

**Comment by AlPrunty** [comment]
It's Fido Reference Library... same thing as FSP - Fido Standards Proposal just the Library is "adopted preference"

**Comment by wwiv** [comment]
actually using either a int32 or uint32 is fine, since we can simply seed it from the current time in int64 && uint32_t max to get the lower 32 bits.  After 2016 the worst that'd happen is we duplicate against a message from now or 1970's.  Seems reasonable.

**Comment by wwiv** [comment]
In https://github.com/wwivbbs/wwiv/commit/b7e13697e33b1cf9d3abba69c1fe7032fbd09abf I always jump the next msgid serial number to at least the time_t now value.. This will hold to 2038 (and which time it'll still work, but reset to a lower msgid value since we'll only use the low 32-bits when writing to the 8 byte hex number.  And I'm sure I'll change it by then to do what sync does, since that makes more sense than this way anyway.
