### ISSUE TITLE
REPLY Kludge should be immediately below MSGID line

### ISSUE THREAD

**Issue by AlPrunty** [wwivbbs/wwiv#1078]
When replying to a message in an FTS echo a new MSGID is generated for the new message, but to maintain the integrity of the message threading a REPLY kludge must be referenced with the MSGID of the message that one is replying to.

See http://ftsc.org/docs/fts-0009.00 for information.

**Comment by wwiv** [comment]
That should have been happening already, looks like we're not picking this up as a reply.

https://github.com/wwivbbs/wwiv/blob/master/bbs/msgbase1.cpp#L214 has the code to add it.

http://ftsc.org/docs/fts-0009.001 is the right link

**Comment by wwiv** [comment]
```
^APID: WWIV 5.3.0.development
^ATID: WWIV NET51.development
^AMSGID: 11:1/211 00000019
^ACHRS: CP437 2
RE: Re: Testin
BY: Jimmy Mac #1@707.Wwivnet(11:1/101)

JM> T> This is a test....
JM> 
JM> Made it here!

Cool!
^D1
-----------------------------------------------------------------------
        Mystic Rhythms BBS   *   telnet://mystic.wwivbbs.org
-----------------------------------------------------------------------
^D5
^D6
^AREPLY: 11:1/101 58CEB7FD

--- WWIV 5.3.0.development
 * Origin: Rush's Workshop (11:1/211)
SEEN-BY: 1/211

```

Here's what I get when I replied to a post. I wonder if it's a FSED related problem?

**Comment by wwiv** [comment]
nope, also still see a reply line using openedit.

**Comment by AlPrunty** [comment]
I see the problem...

The Reply kludge needs to be positioned directly under the MSGID for it to work properly.  I have ran into this with Platinum Express back in the day.  Other tossers will not detect and process it properly if it's not directly underneath the MSGID.  Like this...

^AMSGID: 11:1/211 00000019
^AREPLY: 11:1/101 58CEB7FD

**Comment by AlPrunty** [comment]
Is this fixed now?

**Comment by wwiv** [comment]
should be.  Now:

WWIV will:
========
* Convert inbound ^A lines to ^D0
* Add ^D0 Reply: line if needed

NetworkF will:
==========
* Convert outbound ^D0 lines to ^A
* Add MSGID *only* if one doesn't already exist.
