### ISSUE TITLE
wwiv-server no longer loads crashes --- where's the log file??

### ISSUE THREAD

**Issue by AlPrunty** [wwivbbs/wwiv#1080]
Can not find log file to see if there's an error messge.  WWIV-Server loads and then immediately crashes.

**Comment by wwiv** [comment]
there should be a wwivd.log.  Is anything printed?

**Comment by wwiv** [comment]
probably from wwiv-server.exe (the C# one).

**Comment by wwiv** [comment]
I can't reproduce it, closing as obsolete.
