### ISSUE TITLE
names.lst contents not correct

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1087]
I've noticed a few users where the data does not match what's in names.lst

for example, 

```
Name/Handle  : SKULLOWL #3 
Real Name    : SKULLOWL
```

But when you look at data in logs, it shows different information (Gp1 # 3):

```
739: Gp1 #3 18:14:32 04/04/2017   KB - 2 (1)

  /O
   SKULLOWL hung up.
```

It looks like the incorrect data is coming from names.lst.  I don't think user name changes in the user editor are being written to names.lst properly

**Comment by wwiv** [comment]
yes, that's from names.lst

**Comment by wwiv** [comment]
looks like running wwivutil fixed it.
