### ISSUE TITLE
dosemu doors under linux don't produce output to terminals

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1088]
dosemu doors on recent version of WWIV on linux no longer work since the reworking of IO to telnet.

If you are local (either on the console, or connected directly to ssh and running ./bbs directly) doors work as expected.

**Comment by wwiv** [comment]
They do if your door handles the socket handle or you enable stdio support.  GP claims it's not processing LF -> CRLF.

**Comment by granitepenguin** [comment]
shell stuff is definitely not working "as expected" but dosemu at least looks like its trying to do the "right thing".  Might just need some tweaking/fiddling to get output.

**Comment by granitepenguin** [comment]
it looks like once it gets into dosemu itself, the CRLF issue is working better.   Note how the dosemu drivers have the CR, even though stuff in the shell script before it does not.  

```
                                                                          Please
 adjust your terminal to 80x25 and try again.

                                             If you are using SyncTERM, make sur
e you have your
               Screen Mode explicitly set to 80x25, not "Current"

                                                                 Thanks.

                                                                        --
                                                                           The M
anagement


         DOSEMU 1.4.0.8 (2013-01-05), configured: 2013-01-05 15:35:04 -0800
                                                                           Pleas
e test against a recent version before reporting bugs and problems.
                                                                   Submit Bugs &
 Patches to linux-msdos@vger.kernel.org or via http://dosemu.org.
                                                                 Starting MS-DOS
...

dosemu XMS 3.0 driver installed.
dosemu EMS driver rev 0.5 installed.
```

It's still failing to produce any output after that point, but it's closer

**Comment by wwiv** [comment]
So they do now, https://github.com/wwivbbs/wwiv/wiki/wwiv-5.4-dosemu-door-example-(global-war) documents how to do it.
