### ISSUE TITLE
wwivd should pass verbose flag to bbs binary

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1091]
fixing #1089 noticed that setting verbose flag --v on wwivd doesn't get passed to the spawned bbs binary. 

We need to set it up so the verbosity level of the spawned bbs binary can be set.

**Comment by wwiv** [comment]
I think you just configure the --v flag in init for the bbs, right? It's possible since wwivd now supports matrix logons, that -v isn't valid for the bbs.
