### ISSUE TITLE
network3 doesn't generate valid network config for mark

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1093]
Need to figure out why.  @MarkHofmann11 can you help me out here?

**Comment by wwiv** [comment]
I tried with his datafiles and things looked fine to me.

**Comment by MarkHofmann11** [comment]
Wanted to verify you tried using the network files I am using
(NETWORK3.EXE), etc.  I'm still on the legacy beta builds before you did
the re-write.

**Comment by wwiv** [comment]
no, I only tried with the latest win32 network3.  Should I try with the DOS one? If so, why? I thought the problem was that the win32 one didn't work for you?

**Comment by MarkHofmann11** [comment]
I'm still using the old DOS Network software.  Since I'm the hub, was
unsure about going to the latest.  Maybe I should give that a shot again
soon.

**Comment by wwiv** [comment]
Sounds like it's net37 only, won't fix
