### ISSUE TITLE
can´t compile

### ISSUE THREAD

**Issue by JPRuehmann** [wwivbbs/wwiv#1095]
Hello
if I try make I get the following what I´m doing wrong?
```
make                                                                                                                                                                                       
[  0%] Cryptlib makefile target.
LDAP interface detected, enabling LDAP support
[  0%] Built target build_cryptlib_lib
[  1%] Built target gtest
[  2%] Built target gtest_main
[ 14%] Built target core
[ 15%] Built target core_fixtures
[ 23%] Built target core_tests
[ 37%] Built target sdk
[ 40%] Built target localui
[ 41%] Built target bbs_lib
[ 41%] Linking CXX executable bbs
CMakeFiles/bbs.dir/bbs_main.cpp.o: In Funktion `main':
bbs_main.cpp:(.text+0x1c): Nicht definierter Verweis auf `bbsmain(int, char**)'
collect2: error: ld returned 1 exit status
bbs/CMakeFiles/bbs.dir/build.make:101: die Regel für Ziel „bbs/bbs“ scheiterte
make[2]: *** [bbs/bbs] Fehler 1
CMakeFiles/Makefile2:430: die Regel für Ziel „bbs/CMakeFiles/bbs.dir/all“ scheiterte
make[1]: *** [bbs/CMakeFiles/bbs.dir/all] Fehler 2
Makefile:127: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

**Comment by wwiv** [comment]
Not sure why bbsmain(int, char**) would be undefined. It's in bbs.cpp

What compiler/OS are you using?

**Comment by JPRuehmann** [comment]
I am using gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

**Comment by wwiv** [comment]
do you have bbs.cpp is bbsmain in there?

**Comment by JPRuehmann** [comment]
Yes, Tey´re both in the bbs Subfolder.

**Comment by wwiv** [comment]
I don't have any ideas. Maybe make clean ? hopefully something is just out of sync and make isn't building the bbs.o?

**Comment by wwiv** [comment]
I don't have ubunutu setup but re-compiled it on both debian8 and debian9 and those worked for me.  Ditto for the continuous build server.

**Comment by wwiv** [comment]
@granitepenguin any ideas?

**Comment by granitepenguin** [comment]
What are the full steps you have done to create the issue?  For example:
1. Where did you get your source code (what URL, is it a tarball, a Git repo, etc)?
2. What version are you trying to build?
3. What directions are you following?

What is your Ubuntu source?  I'll see if I can set up the same env and try to reproduce it.  I assume it's Ubuntu Desktop 16.04.4 (i.e., not Ubuntu server)?

**Comment by JPRuehmann** [comment]
Hello
Sorry that it took so long to answer.
I´ve found the problem
I´ve Downloaded the Source from here.
what I don´t know and did not see anywhere in the Documentation is that this sources are incomplete.
after I´ve cloned my_basic and pdcurses into the respective folders I could compile normaly.
Would be a good Idea to tell that and how in the Documentation.
The point that directed me in the right direction was ccmake that said at the end of the generation of the build files that the my_basic Directory is empty
Thanks,
