### ISSUE TITLE
Connection closed at sending Email

### ISSUE THREAD

**Issue by JPRuehmann** [wwivbbs/wwiv#1098]
Hello
Here is my next Problem.
if I try to send an Email the connection gets closed.
What I do wrong?
I entered the Address and got disconnected.
Thanks,

**Comment by wwiv** [comment]
can you add a screen capture? anything interesting in the logs? Sounds like a crash, can you run the bbs under gdb?

**Comment by wwiv** [comment]
please reopen with screen capture, logs, and/or ideally run under GDB to see what's going on. Sorry, I don't have any other ideas
