### ISSUE TITLE
WINS BETA 10

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#11]
This has been an on going issue.

Even if there are NO packets already prepared for 
delivery, EXP writes the note, "packets already in 
outbound area for deliver" or some such.

Arthur

Original comment by: seacrest

**Comment by askpatrickw** [comment]
All the linked bugs have been closed. Is this still an issue?

**Comment by wwiv** [comment]
I doubt it

**Comment by ericpareja** [comment]
Those aren't linked issued. It's the issue tracker interpreting the gdb output as references to issues when there's a hash mark before a number.
