### ISSUE TITLE
Can't select conferences

### ISSUE THREAD

**Issue by billsimon** [wwivbbs/wwiv#1106]
I divided groups of subs into conferences and assigned with //je. Access levels permit anyone to join any conference.

Menu keys J, { and } which should let me switch conferences do not work. I am always stuck on the first conference, which shows all subs (even though I assigned them to different conferences).

WWIV 5.3 development on Linux

**Comment by wwiv** [comment]
Is conferencing enabled for your user in (D)efaults?

**Comment by billsimon** [comment]
No. OK, it works when you enable it.

Now that we've established I'm a knucklehead... I thought this was by default enabled. How do I set it so for all (new) users?

**Comment by billsimon** [comment]
Nevermind - I found an example in the code where it's set default off.

`  u->ClearStatusFlag(User::conference);`
