### ISSUE TITLE
DSO aus der Kommandozeile fehlt

### ISSUE THREAD

**Issue by JPRuehmann** [wwivbbs/wwiv#1107]
Hello

I can´t compile
get the following error
anyone knows why?

I am on Kubuntu 16.04 (32Bit)
using the source tarball from your HP
since the github clone not compiling allready and the Binarys not working (format error)
I´ve run `pushd deps/cl342; make; popd > /dev/null  ` first.

```
[ 63%] Linking CXX executable bbs
/usr/bin/ld: ../deps/cl342/libcl.a(odbc.o): undefined reference to symbol 'dlopen@@GLIBC_2.1'
//lib/i386-linux-gnu/libdl.so.2: error adding symbols: DSO aus der Kommandozeile fehlt
collect2: error: ld returned 1 exit status
bbs/CMakeFiles/bbs.dir/build.make:101: die Regel für Ziel „bbs/bbs“ scheiterte
make[2]: *** [bbs/bbs] Fehler 1
CMakeFiles/Makefile2:430: die Regel für Ziel „bbs/CMakeFiles/bbs.dir/all“ scheiterte
make[1]: *** [bbs/CMakeFiles/bbs.dir/all] Fehler 2
Makefile:127: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```
Thanks,

**Comment by granitepenguin** [comment]
More details from IRC


01/22 17:29 < JPRuehmann> I am using **Kubuntu 16.04 (32Bit)**
01/22 17:30 < JPRuehmann> Both (Github and Tarball are not working
01/22 17:32 < JPRuehmann> The Error is "/usr/bin/ld: ../deps/cl342/libcl.a(odbc.o): 
                          undefined reference to symbol 'dlopen@@GLIBC_2.1'"
01/22 17:32 < JPRuehmann> What can I do to resolve this?

01/22 17:40 <&GranitePenguin> what link are you using to get the source ?
01/22 17:41 < JPRuehmann> github https://github.com/wwivbbs/wwiv.git
01/22 17:42 < JPRuehmann> tarball https://github.com/wwivbbs/wwiv/archive/wwiv_5.2.0.tar.gz

01/22 17:43 <&GranitePenguin> Which documentation link are you following?
01/22 17:45 < JPRuehmann> https://docs.wwivbbs.org/en/wwiv52/

01/22 17:49 <&GranitePenguin> what version of g++ do you have?
01/22 17:56 < JPRuehmann> gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)

**Comment by wwiv** [comment]
try rebuilding libcl.a
something like:

```
cd deps/cl342
make clean
make -j4
```

**Comment by JPRuehmann** [comment]
I´ve just tried it out.
Did not change anything.
Thanks,

**Comment by wwiv** [comment]
I'll try it on ubuntu 32-bit not kubuntu (should be the same result).  kubuntu isn't downloading at more than 1k/s for me (on a 250MB pipe).  ubuntu is ~250k/s.

**Comment by wwiv** [comment]
latest github pull for 5.3 worked for me on ubuntu 16.04(32-bit)

I did this and it worked.
```
cd deps/cl342
make clean
make -j8
cd ../..
mkdir _build
cd _build
../debug.sh ..
cmake --build . -- -j8
```

Maybe the flags passed to gcc from cmake are better than what we had before? i don't know.

This looks like https://github.com/TigerVNC/tigervnc/issues/7
or
https://askubuntu.com/questions/334884/while-compiling-truecrypt-i-get-undefined-reference-to-symbol-dlcloseglibc

You can try this:
Set the environment variable LIBS to -ldl:  
```
LIBS=-ldl make
```

This seems to be a common problem on 32-bit linux distros.

Hope this helps.

**Comment by wwiv** [comment]
however pulling from latest in github didn't reproduce this for me.

**Comment by wwiv** [comment]
Maybe a fix like this would work if it fails for you.

See https://github.com/halide/Halide/pull/2235/files

**Comment by JPRuehmann** [comment]
Tried that out, no change.
Is a git pull in the ~/wwiv/ folder enough for update?
export LIBS=-ldl changes nothing
../debug.sh .. from ~/wwiv/_builds throws the amentioned error.
The Links give me no Clue.
Thanks,

**Comment by wwiv** [comment]
@granitepenguin any ideas?

**Comment by ericpareja** [comment]
@JPRuehmann you might need to do ***git submodule init*** and ***git submodule update*** in ~/wwiv/ folder first.

maybe docs on linux build needs an update

**Comment by wwiv** [comment]
I think cryptlib won't work on 32-bit os'es.  Not sure why it didn't fail for me, I saw complaints in the synchronet irc on this

**Comment by wwiv** [comment]
I have no more ideas here.  I don't think wwiv as-is today will build on 32-bit os on linux
