### ISSUE TITLE
networkf import returns 0 if nothing imported

### ISSUE THREAD

**Issue by billsimon** [wwivbbs/wwiv#1108]
```
$ ./networkf .3 import
2018-01-28 13:39:25,699 INFO  NETWORKF for network: fsxNet
$ echo $?
0
```

Feature request - have networkf return a non-zero value if nothing is imported

**Comment by wwiv** [comment]
Interesting.  Usually I prefer to only return non-zero on error and didn't consider this an error. In most unix commands it's not (like with find), however zip does treat it as an error.

I can't think of a case where the script executing this should continue if nothing is found.  I'll hold for a bit and see if it's easy to do, also see if anyone else has any thoughts on it.

@granitepenguin WDYT here?
