### ISSUE TITLE
qwk is not working in later versions 2703

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1115]
I did //qwk and tried to download a packet in the latest build i downloaded where the bbs hangs and crashes. I tried resetting qscan and no luck.

**Comment by mmunson** [comment]
I noticed that changes in build 2636 likely broke qwk.

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/4348a086ea54a61b4aa5bf4fac9291d7649c8600
