### ISSUE TITLE
sh: 1: network1: not found

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1116]
After running network -n1, here's what I got. Had to run network1 or networkc manually.
```2018-06-15 04:37:35,846 INFO  renamed file: '/wwiv/wwivnet/s513.net' to: '/wwiv/wwivnet/p1-0-0.net'
2018-06-15 04:37:35,846 INFO         executing: network1 --v=0 .0
sh: 1: network1: not found
wwiv@bbs:/wwiv$ ./network1
```

**Comment by granitepenguin** [comment]
That looks like your path is off.  Remember, in Linux your current directory is NOT in your path.

**Comment by wwiv** [comment]
yup, I didn't... doh,  Fixed by setting my path to include ```/home/wwiv/bbs``` as documented.
