### ISSUE TITLE
Menu editor not working

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1122]
OS: Linux
Build: 5.3.0.2705

I was looking into how to make ANSI menus work (see [FB posts](https://www.facebook.com/groups/314823385196005/) about it) and discovered that the sysop commands for editing the menus don't work (//EM //SYSOP -> M, etc)

The commands are accepted, but they don't do anything; the system just immediately returns to the menu.

**Comment by wwiv** [comment]
//EM was removed from the default menu set now in https://github.com/wwivbbs/wwiv/commit/468fb362aec1e0566607a6b3ce07ed2f96eeb087

In 5.3 you have to use wwivconfig for this.
