### ISSUE TITLE
Creating Sysop Account on New Fresh Install - Name etc blank

### ISSUE THREAD

**Issue by dunnaway** [wwivbbs/wwiv#1127]
When creating the sysop account on new fresh install of 5.3  -  everything is blank.

No idea what needs to be entered.  Had to go into user editor after wwivconfig finished new install to enter sysop info.

**Comment by wwiv** [comment]
we create a default account and ask for the name in init. What else would you like be auto-added/prompted when you run wwivconfig for the1st time?  Happy to make this better!

**Comment by dunnaway** [comment]
It's not the fact of prompting for it, it's that you can't see what it's prompting for.  There was no prompt, only blank lines.  
I had to hit enter 4 times to get back to the main menu.
I installed twice just to verify.  Win7/32

**Comment by wwiv** [comment]
Got it - thanks!  Fixed in both 5.3 and 5.4.

5.3.2739 should have the fix once the build finishes and available at https://build.wwivbbs.org/jenkins/job/wwiv53/lastBuild/label=windows/ (for windows)
