### ISSUE TITLE
Not removing existing MSGID from posts when adding a new one

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1134]
As seen by some grumps on FTN
```
Hi Ward,

On 2018-07-15 22:20:23, you wrote to Matt Munson:

 WD> {at}MSGID: 2:292/854 171b2652
 WD> {at}REPLY: 1:218/109 5B41B1FA
 WD> {at}TID: WWIV NET51.2738
 WD> {at}CHRS: CP437 2
 WD> {at}TZUTC: -0700
 WD> {at}MSGID: 1:218/109 5B41B1FA
 WD> {at}REPLY: 1:261/1304 5B40AE57y way to run my classic setup.  The nodes map

This is even worse! A double and different MSGID: and REPLY: kludge.

And some random text behind the REPLY: kludge ???

 WD> You software sucks...

 WD> ***************************************************************************
 WD> **
 WD> Date: 07 Jul 18  23:40:57
 WD> From: Matt Munson
 WD>   To: Mark Hofmann
 WD> Subj: Re: D'Bridge 3.99/SR32 released and avai
 WD> ___________________________________________________________________________
 WD> _
 WD> ***************************************************************************
 WD> **

 WD> Whakky reply-kludge.


Bye, Wilfred.

--- FMail-lnx64 2.1.0.18-B20170815
 * Origin: FMail development HQ (2:280/464)
SEEN-BY: 103/705 154/10 203/0 221/0 1 6 360 229/426 240/5832 280/464 5003
SEEN-BY: 292/854 320/219 423/120 633/267 280 640/384 1384 712/132 620 848
SEEN-BY: 770/1 2320/100
@PATH: 280/464 221/0 640/1384 384 712/848 633/267
```

**Comment by wwiv** [comment]
Hey @mmunson Can you send me your d'bridge sub from your bbs looks like the original text was missing a line end or something, I;d like to take a look to see. thanks!

**Comment by mmunson** [comment]
Is that all you need?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by wwiv** [comment]
Yes Matt that’s it I think.  Both sub and dat files

**Comment by mmunson** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by wwiv** [comment]
@mmunson those files didn't include the latest posts, including theone from ward, do you have a newer copy you can share? I specifically want to look at why the replyid had part of another text line behind it.

**Comment by wwiv** [comment]
btw - I *think* I fixed the issues mentioned in here, and have tests that verify it.

**Comment by mmunson** [comment]
I don’t think we’ll be getting much snarky replies from the fidonet folk for awhile.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
