### ISSUE TITLE
Many ANSI messages don't look right in the full screen reader.

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1135]
I think we need to display them to a virtual screen buffer, then display that screen buffer to the user in the scrolled window.

**Comment by ghost** [comment]
I've had a crack at this today, and got no where. It's in my fork a branch called ansimsgs, it's displaying ordinary messages fine, but appears to be displaying ansi messages all on the same line or something.

I don't understand why it's not working. Will try again another day.

**Comment by wwiv** [comment]
I started that here:
https://github.com/wwivbbs/wwiv/commit/9c884d662a473bce29e192119e78a49efbf49b12

 it’s merged into master as of last night.  I also made a vscreen interface between the ansi code and framebuffer so I could drop in a real screen and dropped in the curses or win32 based localio class so wwivutil print can dump it to the screen.  Maybe I’ll let wwivutil serialize the franebuffer too for grins.

**Comment by granitepenguin** [comment]
testing wwivutil with the stock welcome.ans file, it's mostly correct.  You can see it's fine up to the very end; here's a comparison of using wwivutil vs in the BBS (wwivutil print is on the bottom).

![screen shot 2018-08-14 at 09 46 24](https://user-images.githubusercontent.com/913430/44099043-557d4138-9fa7-11e8-84a3-e4030e310bad.png)

**Comment by wwiv** [comment]
I think with https://github.com/wwivbbs/wwiv/compare/c848a6998a78...40d4a0049b2a things are good enough to close this.  I’ll work on cleaning up the code for a bit more to move the heart, pipe and macro code into some filter classes that’s shared here and with the output class.
