### ISSUE TITLE
5.4.0.2794 Win7 Last callers time displaying / instead of :

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1136]
Not latest version but just in case.
Time displaying hh/mm instead of hh:mm

![image](https://user-images.githubusercontent.com/13243281/42884260-c12f17a4-8a52-11e8-88e6-20c333ba5280.png)

**Comment by wwiv** [comment]
new entries will be written to laston.txt correctly.

Thanks!

**Comment by BloodStoneBBS** [comment]
Yep! Working as expected. Thank you!
/s
