### ISSUE TITLE
WFC_SCREEN = N creates blank display

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1140]
OS: Debian 9
WWIV: 5.4.0.2830

I tried WFC_SCREEN = N
 all I get is a blank screen and when I hit "q" it quit out and I  saw this:
```
wwiv@beaglebbs:~$ ./bbs
/bin/sh: 1: /bbs/wwiv/networkc--quiet: not found
/bin/sh: 1: /bbs/wwiv/networkc--quiet: not found
```
looks like it's stuck trying to run network stuff at startup, but it can't find "quiet" output versions

**Comment by wwiv** [comment]
Setting WFC_SCREEN=N is working as intended (ie. you get a blank screen).

I'll fix the networkc--quiet thing
