### ISSUE TITLE
internal editor quoting mangled

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1151]
OS: Debian 9
WWIV: 5.4.0.2872 

Somewhere in recent code, the internal editor is mangling messages when I quote them

Original message
![screen shot 2018-08-18 at 09 42 11](https://user-images.githubusercontent.com/913430/44300335-0625c700-a2cb-11e8-97a9-5091adab3a08.png)

My quote
![screen shot 2018-08-18 at 09 40 57](https://user-images.githubusercontent.com/913430/44300329-f1493380-a2ca-11e8-80d1-2fb1d0dff9aa.png)

**Comment by wwiv** [comment]
This is now fixed
