### ISSUE TITLE
Build 2876 - Can no longer login. Win 32.

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1152]
Makes connection just fine but entering user number or name fails on pressing enter. PW jumps up a line and password is not accepted. Not even given the option to type it in 

![image](https://user-images.githubusercontent.com/13243281/44403129-7c633d00-a508-11e8-9100-942ba30433d7.png)

Rolled back to 2872, login fine.

**Comment by BloodStoneBBS** [comment]
Working fine in 2874.

**Comment by BloodStoneBBS** [comment]
This issue occurs in 2875 and later.

**Comment by wwiv** [comment]
Oops!  I’ll try to look tonight.  Can you post in the wwivdev sub to warn people.

I missed this since I fast login all the time

**Comment by wwiv** [comment]
Hmmm. I see the PW on the same line but my password works both locally and through netrunner.

**Comment by BloodStoneBBS** [comment]
Have you tried SyncTerm?

**Comment by wwiv** [comment]
https://github.com/wwivbbs/wwiv/compare/399b61aca4da...0a5ae2b8fdbe Fixes it

**Comment by BloodStoneBBS** [comment]
Well THAT was quick!
Thanks!

**Comment by wwiv** [comment]
I had fixed it this morning but forgot to update.  Realized you were using syncterm by the pic
