### ISSUE TITLE
Not able to add more than 23 subs without bbs.exe crashing...

### ISSUE THREAD

**Issue by dewalters1** [wwivbbs/wwiv#1157]
I used a fresh install of the latest release of 5.3.  Added subs via WFC screen.  When I got to sub 23, I filled out the info and tried to save.  bbs.exe would then crash with the following error:

bbs.exe has stopped working

A problem caused the program to stop working correctly.
Windows will close the program and notify you if a solution is
available.

I'm running on Windows 7 SP1 with Visual C++ Redistributable 2015 & 2017, and .NET 4.7.   I've attached my subs.json file per Rushfan's request.
[subs.json.txt](https://github.com/wwivbbs/wwiv/files/2368925/subs.json.txt)

**Comment by wwiv** [comment]
Looks like the problem might be mismatch between subs.cnf and subs.json (I had a crash at logon because my subs.cnf has 43 subs and this one only has 25). (maybe delete the #'s >23) from it? back it up first.

That's probably it, otherwise it's hard to tell.  If you can run it under visual studio 2017's debugger you can get a full stacktrace which makes it eay too see. instructions are here: https://github.com/wwivbbs/wwiv/blob/master/README.md

Also @BloodStoneBBS is a pro at it and can help if needed. 

I can try to reproduce it here too with the subs.cnf too if you attach it as well. 

Thanks!

**Comment by dewalters1** [comment]
Here's some more info:

From WFC screen, pressed B, then Enter.  Selected D to delete, then entered 30 and pressed Enter.  bbs.exe crashed with the following error:

2018-09-13 08:00:20,488 FATAL BBS Terminated by exception: invalid vector<T> sub
script

and the below Windows error:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	bbs.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5b907e42
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.14393.2247
  Fault Module Timestamp:	5adc1a6f
  Exception Code:	40000015
  Exception Offset:	000891fa
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	371f
  Additional Information 2:	371f6a077f7fde300d611394f368de32
  Additional Information 3:	8df4
  Additional Information 4:	8df47115cfd7654bfea361c6dd772960

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
  
The bbs.exe was running fine until I added sub 30, WWSET.  I then logged into the bbs and when it got to the "Conference:" part of the menu prompt, it crashed.  It didn't display the conference name.

I hope this helps.  Please let me know if you have any further questions or need anything else from me on this.  Thank you!

[subs_files.zip](https://github.com/wwivbbs/wwiv/files/2380122/subs_files.zip)

**Comment by dewalters1** [comment]
Oh, and I upgraded to 5.4.0.2906 as well.  The errors and info above is after the upgrade.

**Comment by wwiv** [comment]
can you send your subs.cnf file?

**Comment by dewalters1** [comment]
It's in the attached zip file.
