### ISSUE TITLE
Intermittent: New user leaving feedback crashes session.

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1159]
Latest build 5.4.0.2920 on Win7 w32
Found hung node, possibly due to FSED defaults? 
Will try and replicate but I think this only began after I enabled WWIVedit and Open!Edit.

[1] [System Announcements]: F

E-mailing Jimmy Mac #1

To   : Jimmy Mac #1
Title: Feedback2018-09-29 11:25:47,807 INFO  ExecuteExternalProgram: errno: 2
2018-09-29 11:25:47,807 ERROR Trying to call WriteCurrentUser with user_number:
114; last_read_user_number_: 1
←[1;1H←[2J←[25;1H←[K←[0m←[1;37;44mMax Lines : 2789  ←[0m←[1;37;44mInsert Mode←[0
m←[37;40m←[1;1H←[K←[0m←[1;33;40mTitle : ←[0m←[37;40m|#1Feedback
←[K←[0m←[1;33;40mDest  : ←[0m←[37;40m
←[K←[0m←[1;33;40mTime  : ←[0m←[37;40m11:25:48 AM←[3;40H←[0m←[1;33;40mESC←[0m←[32
;40m to Save, ←[0m←[1;33;40mCTRL-O←[0m←[32;40m for Help←[0m←[37;40m
←[K[...|....1....|....2....|....3....|....4....|....5....|....6....|....7....|..
.]
←[0m←[37;40m←[0m←[37;40m←[5;1H←[6;1H←[0m←[37;40m←[24;1H←[K←[0m←[1;32018-09-29 11
:27:26,056 ERROR !connected(); threads_started_ = true;36;40mR←[0m←[1;33;40mesum
2018-09-29 11:27:26,071 VER-1 Invoked Hangup()[1;36;40mC←[0m←[1;33;40mheck Spell
ing, ←[0m←[1;36;40mT←[0m←[1;33;40maglines [ASRDCT] > ←[0m←[1;36;40m2018-09-29 1♪

**Comment by wwiv** [comment]
If you get this again, please reopen, I've not had it reproduce on anything recently. Maybe fixed in some other change?
