### ISSUE TITLE
CentOS 7 compile error

### ISSUE THREAD

**Issue by k5jat** [wwivbbs/wwiv#1160]
I have everything installed as needed, and this is error I get now. Note CentOS installs cmake 2.x as default, but epel installs cmake 3.x as cmake3 (current version is cmake 3.12.2).

![wwiv_compile_error](https://user-images.githubusercontent.com/764593/47689407-cb3beb80-dbb7-11e8-86ad-8174b1b92d37.png)

**Comment by k5jat** [comment]
Ok, I tried that. Now it's not finding GTest. This is on a fresh pull to my local Linux Mint laptop.

![wwiv error 2](https://user-images.githubusercontent.com/764593/48677762-376a9900-eb3f-11e8-846e-13e657ccb0ae.png)

**Comment by k5jat** [comment]
I just checked and the googletest directory in the zip file is empty as well.

**Comment by granitepenguin** [comment]
don't forget that deps are not magically populated because they are submodules, not part of the base tree.  If you are doing a git pull, are you also going to need to do 
```
git submodule init
git submodule update
```
to pull the contents of the dependent external modules.  It's documented somewhere, but I'm pretty sure it's not documented everywhere it should be.

**Comment by k5jat** [comment]
Yeah, that's not documented at all. I don't remember having to do that before on a new pull, and if submodules aren't coming in the zip file, it's basically broken there too.

**Comment by granitepenguin** [comment]
I’m not sure what it takes to have the zip contain the deps, but I’ll see about getting it added to all the places in the docs for git clones at least.

**Comment by k5jat** [comment]
I had to build and install libcl before compiling as well. So maybe a shell script would do well for a new wwiv pull/clone? Semi-automate the clone/pull, cryptlib compile/install, submodule update, and finally the compilation of wwiv.

It seems to compile now on my Linux Mint laptop. Next, I'll try on my CentOS VPS.

**Comment by wwiv** [comment]
Thanks for the issue - Yes centos needs  SCL to work, that's what we use for our build.

For Debian, debian9 or debian10 will be the 5.4 LTS.  Probably debian10 since I don't expect to release 5.4 for a while.  Either that or we'll cut 5.4 and fork off 5.5
