### ISSUE TITLE
Full-Screen Message Reader doesn't work for long Email

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1166]
Reading long email in Full-Screen Message Reader (more than 19 lines) doesn't work properly. Can't scroll to end. See screenshots of the same email viewed using Traditional and F-S Message Reading.

Probably related to #1112. Network3 messages are examples of messages more than the viewport height.

Here are screenshots of the email using Traditional view:
![screenshot from 2019-01-15 19-03-26](https://user-images.githubusercontent.com/188277/51176711-9ad33600-18f8-11e9-8de2-2678f3854622.png)
![screenshot from 2019-01-15 19-03-31](https://user-images.githubusercontent.com/188277/51176718-a161ad80-18f8-11e9-8f5f-ea7d98cd0988.png)

Here's the same email using Full-Screen Message Reader view:
![screenshot from 2019-01-15 19-03-09](https://user-images.githubusercontent.com/188277/51176725-a7f02500-18f8-11e9-91dc-1f256b8d5f91.png)

**Comment by ericpareja** [comment]
Hmmm... I tried using Enter or down arrow to no avail, but I'm using a local build. I'll try with a pre-built binary later.

**Comment by wwiv** [comment]
Right, that's why I disabled it for emails.  Too different on the backend
