### ISSUE TITLE
HandleMessageReply revision breaks AutoQuote

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1168]
Revisions to HandleMessageReply() in msgscan.cpp broke AutoQuote

Old AutoQuote headers on subs looked this way:

On Wednesday, January 30, 2019 at 1:17 AM, Xenos wrote:
..

Current AutoQuote headers on subs look this way:

On Wednesday, January 30, 2019 at 1:17 AM, [ctrl-D]0r 38rc6 - 01/29/19 12:27:37 Wwivn et ->1 wrote:

I suspect the read_type2_message that replaced the get_post works differently due to the new FTN handling. The bug is mainly visible only when using AutoQuote and an FSED.

**Comment by ericpareja** [comment]
in body of auto_quote, first line is assumed to be sender. maybe we can fudge this if it is a control line (prefixed by ctrl-d)?
will test hypothesis.

**Comment by wwiv** [comment]
yes, passing m.message_text[0] in there already has moved past the name line.
