### ISSUE TITLE
Fresh install of 5.3.1 - wwivconfig fails to properly configure language and menus

### ISSUE THREAD

**Issue by grichter** [wwivbbs/wwiv#1169]
Post install I could not log in because there were no configured menus for me to select from. In order to correct this I had to add a language in wwivconfig.

When I added the language it defaulted to English located in gfiles. However this still doesn't provide a working menu set as those have been moved to gfiles\menus\wwiv.

**Comment by wwiv** [comment]
Thanks, I just tried this on 5.4 and it seemed to work fine for me.  5.4 should become the GA release shortly

**Comment by wwiv** [comment]
Fixed in 5.4, 5.4 is the most recent GA release
