### ISSUE TITLE
using //JE to edit conferences wipes out access

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1171]
OS: Linux
WWIV: WWIV Bulletin Board System [5.4.0.2913]

Tried setting up some new subs and a new conference for them.  Editing seemed to work ok within //JE but the resulting subs.cnf was trashed.

This is the before:
```
/* !!!-!!! Do not edit this file - use WWIV's conf editor! !!!-!!! */

~A General
!0 0 255 0 255 0 255 0 2 - -
@0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 

```

and this is the after:
```
/* !!!-!!! Do not edit this file - use WWIV's conf editor! !!!-!!! */

~A General
!0 0 0 0 0 0 0 0 0
@0 1 2 3 4 5 6 7 8 9 10 11 13 14 15 16 17 18 19 20 21 

~B Ham Radio
!0 0 0 0 0 0 0 0 2
@12 22 23 24 25 26 27 28 

```
so you can see the permissions all got wiped out on the conferences.  It has the correct list of subs, but the "all zeros" breaks display output and access to the subs.

We can also see that there's no json file for conferences, only the old-style subs.cnf.  Probably just cleanup that was on the list but we never got to it.

**Comment by granitepenguin** [comment]
I think I found the issue.  When save_conf() is called, it has the following:

```c
  for (const auto& cp : info.confs) {
    f.WriteFormatted("~%c %s\n!%d %d %d %d %d %d %d %u %d %s %s\n@", cp.designator,
                     cp.conf_name.c_str(), cp.status, cp.minsl, cp.maxsl, cp.mindsl, cp.maxdsl,
                     cp.minage, cp.maxage, cp.minbps, cp.sex, word_to_arstr(cp.ar).c_str(),
                     word_to_arstr(cp.dar).c_str());
    for (const auto sub : cp.subs) {
      f.Write(StrCat(sub, " "));
    }
    f.WriteFormatted("\n\n");
  }
```
which includes calls to word_to_arstr(cp.ar).c_str() and word_to_arstr(cp.dar).c_str()
The problem is when ar and dar are empty, what's stored in the struct is 0

{designator = 65 'A',
      conf_name = "General", minsl = 0 '\000', maxsl = 255 '\377',
      mindsl = 0 '\000', maxdsl = 255 '\377', minage = 0 '\000',
      maxage = 255 '\377', sex = 2 '\002', status = 0, minbps = 0, **_ar = 0_**,
      **_dar = 0_**, num = 21, maxnum = 21, subs = std::set with 21 elements = {
        [0] = 0, [1] = 1, [2] = 2, [3] = 3, [4] = 4, [5] = 5, [6] = 6,
        [7] = 7, [8] = 8, [9] = 9, [10] = 10, [11] = 11, [12] = 13,
        [13] = 14, [14] = 15, [15] = 16, [16] = 17, [17] = 18, [18] = 19,
        [19] = 20, [20] = 21}

When we look at word_to_arstr(), we can see the logic to unwrap the ARs and DARs never gets called because !ar always returns an empty brace-enclosed-list

```c
/*
 * Converts an int to a string representing those ARs (DARs).
 */
std::string word_to_arstr(int ar) {
  std::string arstr;

  if (!ar) {
    return {};
  }
  for (int i = 0; i < 16; i++) {
    if ((1 << i) & ar) {
      arstr.push_back(static_cast<char>('A' + i));
    }
  }
  if (arstr.empty()) {
    arstr = "-";
  }
  return arstr;
}
```

The result is the subs.cnf gets corrupted because empty (D)AR fields do not get the "-" placeholder they need to keep the file valid.

Good line:
```
!0 0 255 0 255 0 255 0 2 - -
```
Bad line:
```
!0 0 255 0 255 0 255 0 2
```


Part of the problem is this function gets used in two places: displaying the (D)AR info in the conf edit, and writing the conf info to subs.cnf and they have different needs.  The empty list works in the edit screen, but it breaks the subs.cnf because it's looking for the "-" character as a placeholder.  I'm not sure yet what the correct fix is.  I have to look at the subs.cnf reader to see what it's expecting in those fields.

**Comment by wwiv** [comment]
Should be fixed in https://github.com/wwivbbs/wwiv/commit/b1cc63ff1835c187224ecf4f260f194d08f7503c

**Comment by wwiv** [comment]
Fixed?

**Comment by granitepenguin** [comment]
Yes
