### ISSUE TITLE
reordering subs doesn't update confs

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1173]
Just noticed that when using conferences, if you reorder your subs, it doesn't redo the mapping in the conferences.  It just kindof drops the sub from the conferences.

It would be nice if the system was smart enough to understand the sub numbering well enough to update the conf list to match the new numbering.

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/6453c886d2498747de10165a260e8d072dd1f463
