### ISSUE TITLE
using -h should display help

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1176]
using -? is weird for showing help in linux (nobody would ever guess to use it).  -h is what's expected in linux.  We should add that as an option for displaying help.

**Comment by wwiv** [comment]
in which binary? all?  --help works already IIRC

**Comment by granitepenguin** [comment]
it works by accident

wwiv@beaglebbs:~$ ./networkc -h
**Unable to parse command line.**
unknown_argument_error: Command: ; letter=H
./networkc [5.4.0.2928] for network: wwivnet
./networkc [5.4.0.2928]

**Comment by granitepenguin** [comment]
There's no reason -h can't be a first-class citizen with -? and --help

**Comment by toddcarnes** [comment]
When I'm in a Linux environment I would never think to use -h either. I
would automatically try to use --help... or a man page. :)

**Comment by granitepenguin** [comment]
show me a man page that does not have -h for help

**Comment by toddcarnes** [comment]
Since you didn't specify what kind of man page I was to show you...

http://man7.org/linux/man-pages/man7/libc.7.html

You really shouldn't take things so seriously, I was half joking about the
man page thing, though it's true I would try --help before I would have
ever thought to try -h.

**Comment by granitepenguin** [comment]
LOL
Well played.  :-)

The real point of this request is who in their right mind would ever try -?

**Comment by toddcarnes** [comment]
Then there are...

https://linux.die.net/man/1/ed

https://linux.die.net/man/6/ccurve

https://linux.die.net/man/1/sed

Actually, sed does have an h command, but it doesn't call a help screen. I
think you get the point though.

I could go on, but it would be pointless other than to make it clear that
getting snarky with me was totally uneccessary.

For what it's worth, I actually agreed with you over all. It certainly
couldn't hurt anything to make -h and official command switch.

Have a nice day,

Todd

**Comment by toddcarnes** [comment]
I totally agree with you.

I don't think I've seen that since the MS DOS days when they used /?.

**Comment by wwivsoftwareservices** [comment]
Apple Terminal understands /? In most cases.

 

Winderz still uses /? In the console but not many folks can even use that these days…. 😊

(Note that I only know this because they force me to use a winderz 10 laptop…)

**Comment by granitepenguin** [comment]
No harm, no foul.  If you can't take a little snark when you dish it out, you have no business dishing it out. ;-)

**Comment by toddcarnes** [comment]
LOL! True.

**Comment by granitepenguin** [comment]
This does make me wonder... should we create man pages?  The online docs are nice and all, but having local doc would be nice, too.

**Comment by wwiv** [comment]
Nice to hear from you @wwivsoftwareservices !

If we can auto-create man pages and online docs from the same source that's good, but otherwise we are duplicating work, and man pages don't work on Windows either.  If anyone has good ideas on that, I'm happy to read them.

**Comment by granitepenguin** [comment]
yeah, I have no intention of duplicating work. :-)

**Comment by wwiv** [comment]
bbs.exe already uses -H for handle (like elebbs did too)

**Comment by wwiv** [comment]
I could add it to the network tools only.

**Comment by wwiv** [comment]
actually that doesn't work. only one short key per long key.   Not going to address this one, --help and -? both work
