### ISSUE TITLE
net.ini not read for all network binary defaults

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1178]
While trying to debug some network issues, discovered a couple things that need to be addressed related to net.ini.

1. It doesn't support all available CLI options.  Looking at networkb/net_util.cpp, These are the only options it currently supports setting

```cpp
bool NetworkCommandLine::LoadNetIni() {
  const auto net_tag = network_cmd_name(net_cmd_);
  const auto net_tag_net = StrCat(net_tag, "-", network_name());

  auto ini = std::unique_ptr<IniFile>(
      new IniFile(FilePath(config().root_directory(), "net.ini"), {net_tag_net, net_tag}));
  if (!ini || !ini->IsOpen()) {
    // This is fine and can happen.
    return true;
  }

  SetNewBooleanDefault(cmdline_, *ini, "skip_net");
  SetNewBooleanDefault(cmdline_, *ini, "crc");
  SetNewBooleanDefault(cmdline_, *ini, "cram_md5");
  SetNewBooleanDefault(cmdline_, *ini, "quiet");
  SetNewIntDefault(cmdline_, *ini, "semaphore_timeout");
  return true;
}
```

We should add options for at least:
```
--skip_delete
--configdir
--bindir
--logdir
--v
```
and probably anything else that's useful as a tunable

We should also set it up so a default for all binaries can be set in one section, and allows overrides in all the other sections.  For example, the below would set v=0 for all network? binaries (networkc, networkf, etc), but set only networkb to --v=2.  I figure the [network] section is a good place for defaults because the network binary is just a wrapper to call everything else anyway, so CLI settings for it should pass through already.

```ini
[network]
skip_net = N
crc = Y
v = 0
logdir = /bbs/wwiv/logs

[networkb]
v = 2
logdir = /bbs/wwiv/debuglogs
```

I can't tell yet, but what's the order of precedence?  It looks like the contents of the ini file would override options entered at the command line, which is probably not what we want. I would expect anything in the ini file to be the base, and manually entered stuff to override the ini file.

We should probably also move net_util out of networkb and into a core location.  It doesn't make sense for all the network? binaries to be including networkb/net_util.h  I would think core or sdk instead?

**Comment by wwiv** [comment]
The ini file is just defaults, so anything on the actual commandline always wins
