### ISSUE TITLE
Problem Selecting message number in [S]can Current Msg Base.

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1183]
Running WWIV Bulletin Board System 5.4.0.2936  on Windows 10 w32 but this problem has been around a long time, just now getting annoyed enough to mention it.

When in a SUB and selecting S to bring up a list of messages, the prompt auto populates with a 1 forcing the user to backspace before tying in the message number.
Irritating, especially in those subs that have hundreds or thousands of messages.

**Comment by ericpareja** [comment]
Confirming that this is the behavior in 5.4.0-current, even in the Linux build.
I checked with build 2651, and it isn't that way.

How do you think the dialog should work?

**Comment by granitepenguin** [comment]
JM is correct.  This behavior sucks.  Sometime in the recent past, the dialog introduced a pre-populated character into the input that _always_ has to be backspaced before you can start typing.  

There's a related odd behavior where backspacing displays a red 0 (zero).  It is unintuitive what this is supposed to mean.

The correct behavior is the input field should be _empty_; there should never be characters already in _any_ input field that forces you to remove it before you can start entering numbers.  having a value pre-populated just gets in the way of what the purpose of the input is: quick access to a specific entry.

**Comment by ericpareja** [comment]
As an aside, how do trace which commit corresponds to a build number? I haven't looked at our build workflow just yet. :/

**Comment by granitepenguin** [comment]
AFAIK, we don't.  There's no direct correlation that's written anywhere.  You just kind of "try to figure it out" by looking at the commit dates in Git compared to the build date.

**Comment by ericpareja** [comment]
It appears that the "bug" first occurs in commit c2e58f8452e37372ca07f69e309beceef326eeb5 (Finish input number), where input_number_hotkey() is introduced into bbs/msgbase1.cpp. I'll mess around with this a bit. There are other places where this happens, I know, so the correct measure would be to fix the input_number_hotkey function to produce the expected behaviour for all other occurrences.

**Comment by BloodStoneBBS** [comment]
It appears that this is also impacting a few of my Door games as well. 
Not in all though. Chain Reaction for example, now requires hitting the backspace before typing in your word or the entry, while displayed correctly will be incorrect.
Have not rolled back to b2651 to confirm though.

**Comment by BloodStoneBBS** [comment]
Awesome!!   Thank you!
