### ISSUE TITLE
posts to subs requiring network validation get sent before getting validated

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1184]
posting to a network sub configured with network validation required sends post out even if unvalidated. bug visible in 5.3 and 5.4. bug not in 5.0.

**Comment by wwiv** [comment]
Seems to work right - just remember if  you are a limited co-sysop or higher, the messages are not blocked for validation.

**Comment by wwiv** [comment]
Please reopen if you can provide steps to reproduce with a non-co-sysop user
