### ISSUE TITLE
define default log file location for all binaries in wwivconfig

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1185]
We have introduced --logdir for command line changing of log locations
--logdir               Directory where log files are written.

but we should also add this somewhere (wwivconfig or an ini file) so that we can alter the default location for logs.  Right now, it defaults to the current directory, but this makes a mess if you are writing to a logs directory for some things, because one-off runs (eg, running ./bbs to check something, or ./wwivconfig to change settings) tend to pepper it in other places.

I was thinking maybe add a "Logs" entry to the "System Paths" section of wwivconfig, or make WWIV_LOG_DIR in /etc/wwiv/config global (i.e., read by all binaries).

**Comment by granitepenguin** [comment]
It's worth noting that you can fake this by exporting env variables in a .bashrc or something, but it seems like it would be cleaner to have the binaries be designed to check for this on their own.

**Comment by wwiv** [comment]
Make all calls of Logger::Init call the one that takes  LoggerConfig
Add a callback into the LoggerConfig that can set some default values
call that from Logger::Init
then re-call Parse() again.

That way we can inject a logdir from config.dat
