### ISSUE TITLE
File Uploads hang with File_ID.DIZ in Zip File

### ISSUE THREAD

**Issue by rickdeluco** [wwivbbs/wwiv#1187]
I am using WWIV buiild 5.4.0.2939.  I am the Sysop. 1@120 WWIVNET.   When I go to upload a ZIP file that contains a file_id.diz in the archive the file uploads normal then right after the upload the Telnet Side Hangs....  When I look at the Sysop side  The Window is waiting for a response asking what to do with the file_id.diz ...  I have attached screen shots of the error and also the settings in Archive in wwivconfig.exe .. 

![Capture](https://user-images.githubusercontent.com/53355602/61984445-6987a100-afd2-11e9-8991-ae4eab24f7f2.JPG)

![Capture1](https://user-images.githubusercontent.com/53355602/61984454-73a99f80-afd2-11e9-9331-c86ef38e40ec.JPG)

The zip.exe and the unzip.exe are the files that are packaged in the released build.

This response request is not be displayed on the user telnet screen. all the user sees is a flashing cursor. Also, if I look at a zip file in the Transfers ares and ask to view the zip the files are not displayed, however when watching the user from the sysop side where the Waiting for caller is at I and see the files in the zip displayed.  So the zip is not being displayed from a user Telent View.

**Comment by rickdeluco** [comment]
![Capture3](https://user-images.githubusercontent.com/53355602/61984635-46112600-afd3-11e9-8c34-3f3b720c64fd.JPG)

**Comment by rickdeluco** [comment]
In continuing information on this issue .... If I remove the file_id.diz out of the .zip file. This error does not happen.  The file uploads as normal.

**Comment by BloodStoneBBS** [comment]
It looks like the file already exists.
If this is the case, it will be necessary to set something up that will delete the file_id.diz prior to unzipping the newly uploaded file.
Maybe a custom .bat file for the extract archive will work?

**Comment by granitepenguin** [comment]
maybe change the CLI options to tell it up front how to resolve file conflicts instead of prompting.  Doesn't change that we need to be more graceful about it.

**Comment by BloodStoneBBS** [comment]
Agreed, some versions of UNZIP allow the use of -o to overwrite without prompt.
unzip -o
Will try to confirm when I'm at the BBS.

**Comment by BloodStoneBBS** [comment]
Easy to replicate.

[cid:image001.png@01D54D3D.DDF32160]

**Comment by BloodStoneBBS** [comment]
Changed the UNZIP command to "unzip -o %1 %2" and my uploads completed successfully without prompting to overwrite file_id.diz.

**Comment by BloodStoneBBS** [comment]
Where did you find the -J -C ? Those are not defaults according to my install.

**Comment by BloodStoneBBS** [comment]
Looking over the UNZIP commands:
You can leave the -j and -C, just add -o
---
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
  Default action is to extract files in list, except those in xlist, to exdir;
  file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).

  -p  extract files to pipe, no messages     -l  list files (short format)
  -f  freshen existing files, create none    -t  test compressed archive data
  -u  update files, create if necessary      -z  display archive comment only
  -v  list verbosely/show version info       -T  timestamp archive to latest
  -x  exclude files that follow (in xlist)   -d  extract files into exdir
modifiers:
  -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
  -o  overwrite files WITHOUT prompting      -a  auto-convert any text files
  -j  junk paths (do not make directories)   -aa treat ALL files as text
  -C  match filenames case-insensitively     -L  make (some) names lowercase
  -$  label removables (-$$ => fixed disks)  -V  retain VMS version numbers
  -X  restore ACLs (-XX => use privileges)   -s  spaces in filenames => '_'
                                             -M  pipe through "more" pager
See "unzip -hh" or unzip.txt for more help.  Examples:
  unzip data1 -x joe   => extract all files except joe from zipfile data1.zip
  unzip -fo foo ReadMe => quietly replace existing ReadMe if archive file newer

**Comment by rickdeluco** [comment]
> Changed the UNZIP command to "unzip -o %1 %2" and my uploads completed successfully without promp

**Comment by rickdeluco** [comment]
> Changed the UNZIP command to "unzip -o %1 %2" and my uploads completed successfully without prompting to overwrite file_id.diz.

I also changed the wwiv.ini file DIZ to  =Y and tried the upload again with the suggested setting and it worked without issue ...  I do believe this solved the issue ...   Attached is a screen shot of my settings  from WWIVConfig > Archive Configuration > ZIP


![image](https://user-images.githubusercontent.com/53355602/62668254-3db4d580-b959-11e9-86fa-a8301d6e9754.png)

**Comment by BloodStoneBBS** [comment]
That's great news! 
Reading up a little, you may want to add the -j and -C back. They will help prevent junk folders and uppercase/lower case issues.

**Comment by rickdeluco** [comment]
> That's great news!
> Reading up a little, you may want to add the -j and -C back. They will help prevent junk folders and uppercase/lower case issues.

ok ... I added the -j and -C  and tested again. Uploaded perfect. Errors Gone.   

Another Note.  Once I uploaded, I selected to View the archive. Once the Telnet Screen it displayed nothing, however  watching the session screen I can see the archived list just fine.   my session never crashed, it went right back to the prompt.    Your Thoughts ?

**Comment by granitepenguin** [comment]
There's obviously a disconnect in the output stream where it's being redirected instead of going to the telnet session.  The question is where.

**Comment by wwiv** [comment]
From the comment in xferovl1.cpp

```C
// TODO(rushfan): This is probably completely broken
bool get_file_idz(uploadsrec * u, int dn) {
```

**Comment by wwiv** [comment]
but it looks like it's trying to delete the files first, I'd expect that to work but not the parsing of the text file... anyway adding ```-o``` may be bad for other things.
