### ISSUE TITLE
Event Schedule

### ISSUE THREAD

**Issue by rickdeluco** [wwivbbs/wwiv#1188]
In working with the event schedule within the wwiv.ini, I placed in the begin day event c:\wwiv\bbs.exe /e   both inside a .BAT file and on command line.  I also uncommitted the line.  On the External Programs Options.

BEGINDAY_CMD   = c:\wwiv\bbs.exe /e    ; beginday even

The BBS v5.4.0.2939 does not run this even at  Midnight, however if I manually run the Batch File the event works. I also tried this as a spawn option and it did not work.

However, If I placed this into the EventEditor //EE ot alt-H, the event(s) run as scheduled no issues as long as in the WWIVServer panel the local node is 1 ..... if your run local node as node 4 the //EE does not run.

**Comment by wwiv** [comment]
Thanks, the events support will go away at some point, but this usecase is one that needs to work, let me think about how to make it easy and obvious. thanks for filing the issue

**Comment by rickdeluco** [comment]
Thank for the follow up ...  I also submitted Ticket # 1187.

Also, The documentation is rally vague on setting up FidoNet.  you would
not have any procedures other then what is already published in order to
successfully get FidoNet to work?

**Comment by wwiv** [comment]
Looks like if you want to have bbs -e also call the beginday event from a node number other than 1 in wwiv.ini, BEGINDAYNODENUMBER also needs to be set to a node number.

i.e.:
```
BEGINDAYNODENUMBER=4
```

I'll update the wwiv.ini to set this to 0 so beginday will work on any node.  I think that'll make several things work better.

**Comment by wwiv** [comment]
That change to wwiv.ini was done in https://github.com/wwivbbs/wwiv/commit/599d01b26256a448aca52712bd147d3453a18386
