### ISSUE TITLE
logdir evaluation is inconsistent

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1190]
WWIV Bulletin Board System [5.4.0.2947]
OS: linux

Playing around after #1185 was implemented, it looks like some log writing is inconsistent.  For example, I'm seeing networkc write to both the base wwiv directory and the wwiv log directory depending on what task is firing it off.  It's also interesting because some entries are in UTC and others are in CDT (local time); the two entries below are only 9 minutes apart.

```
2019-08-15 04:09:04,705 START command line: --v=0 --bbsdir=/bbs/wwiv --bindir=/bbs/wwiv --configdir=/bbs/wwiv --logdir=/bbs/wwiv --quiet  --process_instance=2 .0

2019-08-14 23:00:29,086 START command line: --v=0 --bbsdir=/bbs/wwiv --bindir=/bbs/wwiv --configdir=/bbs/wwiv --logdir=/bbs/wwiv/logs --quiet --process_instance=1 .0
```

**Comment by granitepenguin** [comment]
Checked logging overnight and I can see all the binaries logged to the correct log directory.  The last time things wrote to the "wrong" directory was last night while testing.  I have a feeling this may be because of using WFC for testing.

**Comment by wwiv** [comment]
what's invoking networkc in both of those cases?

**Comment by granitepenguin** [comment]
that's what I don't know.  It's hard to tell, maybe a --v=3 will help determine that?
What possible things could call it?

**Comment by wwiv** [comment]
that looks like how bbs calls it in CreateNetworkBinary.

One thought is that maybe bbs is being invoked differently, maybe passing in logdir to it from some binary?

**Comment by wwiv** [comment]
we actually don't need to pass logdir if we assume that the networkc will get the preferred location from config.dat.  We only passed it in to chain it down from wwivd -> bbs -> network*.   That may be an all around better option. WDYT?

**Comment by wwiv** [comment]
I think I fixed this by letting each binary figure it out for itself.
