### ISSUE TITLE
Hitting "Y" to answer the "Are you there?" prompt tries to download file

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1197]
When viewing a message in a sub, I left it alone for a while and got the system Bell with the prompt "Are you there?"  That's fine, but the prompt does not take a Y/N as you would expect.  The input goes straight back to the system, which is confusing.  For example, hitting Y (the obvious choice) prompts for filename to download, which is certainly not what the end user is expecting.

We either need to change the prompt to a safer question (eg, ask, bt also tell the user what to press that's safe), or change the behavior to actually evaluate the keypress to return to the current state, not start the hotkey process for whatever letter is pressed

**Comment by wwiv** [comment]
Any ideas what'd be better to say? I think this is left over from 4.x and its not really at a place to eat a keypress.

**Comment by granitepenguin** [comment]
maybe just:  "Press space if you are still there"
