### ISSUE TITLE
linking failure with Clang

### ISSUE THREAD

**Issue by PaddyMac** [wwivbbs/wwiv#1201]
I just checked out the git code this evening and tried compiling under FreeBSD 12.1 with Clang 8.0.1. Compilation failed with "unable to find library -lstdc++fs" during the linking phase. I had to do some reading to figure out what was going on, but the fix was simple. I edited core/CMakeLists.txt and edited line 53 so that it became

target_link_libraries(core c++fs)

Compilation then completed successfully. I tested with both Clang 8 and 9, and this change was necessary for both versions.

**Comment by wwiv** [comment]
Ugh, clang uses libc++, gcc uses stdlibc++

Also gcc9 and later include the filesystem code in their standard stdlibc++.   It looks like from https://solarianprogrammer.com/2019/01/13/cpp-17-filesystem-write-file-watcher-monitor/ that clang9 doesn't need this c++fs at all either. an you confirm? (just remove the c++fs for clang9)?

**Comment by wwiv** [comment]
https://gitlab.kitware.com/cmake/cmake/issues/17834 is where this is tracked in cmake with no real great answers yet

**Comment by wwiv** [comment]
Can you try it with this change in place: https://github.com/wwivbbs/wwiv/commit/0d27986a32b9540aa751782df44c0dfcc8d7e9bb

I *think* I got it to work for clang with this change.  If it works, please close this.

**Comment by PaddyMac** [comment]
I tested with Clang 8 and 9. The new commit fixes compilation with Clang. I can also confirm that Clang 9 does not need -lc++fs added to the command line, but leaving it in doesn't seem to cause any errors.

**Comment by wwiv** [comment]
gcc is the same way, with gcc9 it can be removed.  Since we're not on gcc9 yet on our base platform (debian10), I'll remove that entirely with wwiv 5.6 or 5.7 which will probably be based on deb11 at that point.
