### ISSUE TITLE
//QWK is broken in later builds.

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1203]
I finally found out that later builds in the 5.5 version where //QWK does crash the program  3010+.  I am using the windows edition of WWIV. I surmise that some of the code cleanups broke up the feature. Its working in builds 3009 and under.

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/7e157e308f932ff87ec7a6b3dfb997d943ebd822
