### ISSUE TITLE
Registration number under Defaults won't allow user to type

### ISSUE THREAD

**Issue by robertstinnett** [wwivbbs/wwiv#1205]
Go into "D"efaults and hit "W" for WWIV registration number.  Will no longer allow me to type in anything, or hit enter.  Hitting backspace will allow me to type 1 character, but still cannot hit enter.  Entering a 0 does not abort loop either.  Field appears to be 1 character long.

**Comment by robertstinnett** [comment]
If I hit "q" it will break out of cycle

**Comment by wwiv** [comment]
Thanks for the issue!

looks like bbs/input.h is broken on unsigned values
