### ISSUE TITLE
won't compile on VS2019 Community

### ISSUE THREAD

**Issue by ghost** [wwivbbs/wwiv#1207]
won't compile on VS2019 Community. What do I need on Win10 1909, example what VS workloads should I have installed.

The error I receive is about connecting to a remote server. I get about 11 declaration warnings.

ran it 3 times.

**Comment by wwiv** [comment]
I use VS2019 community myself to build WWIV.  I have the C++ workloads and CMake installed I open the folder containing WWIV in visual studio then do a build.  This invokes cmake to do the actual compile steps.

Not sure what errors you see, but please provide some more details, it shouldn't need to connect to a remote server for a windows build (only if it's trying to do a remote build on a remote linux)

**Comment by ghost** [comment]
Sorry, I couldn't figure out how to copy the errors here.  Will check my work loadx and give it another try.

**Comment by ghost** [comment]
> 
> 
> I use VS2019 community myself to build WWIV. I have the C++ workloads and CMake installed I open the folder containing WWIV in visual studio then do a build. This invokes cmake to do the actual compile steps.
> 
> Not sure what errors you see, but please provide some more details, it shouldn't need to connect to a remote server for a windows build (only if it's trying to do a remote build on a remote linux)

These are the errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		Unable to find a stored connection for machine '-950675526;localhost (username=rushfan, port=22, authentication=Password)'. Please add a new connection using Tools > Options > Cross Platform > Connection Manager.		C:\Users\Mark\source\repos\wwiv\CMakeSettings.json	74	

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:\Users\Mark\source\repos\wwiv\CMakeLists.txt:23 (add_subdirectory):
  add_subdirectory given source "deps/googletest/googlemock" which is not an
  existing directory.	wwiv	C:\Users\Mark\source\repos\wwiv\CMakeLists.txt	23	

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:\Users\Mark\source\repos\wwiv\CMakeLists.txt:35 (add_subdirectory):
  The source directory

    C:/Users/Mark/source/repos/wwiv/deps/fmt

  does not contain a CMakeLists.txt file.	wwiv	C:\Users\Mark\source\repos\wwiv\CMakeLists.txt	35	

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:\Users\Mark\source\repos\wwiv\CMakeLists.txt:38 (add_subdirectory):
  The source directory

    C:/Users/Mark/source/repos/wwiv/deps/pdcurses

  does not contain a CMakeLists.txt file.	wwiv	C:\Users\Mark\source\repos\wwiv\CMakeLists.txt	38

**Comment by wwiv** [comment]
Sounds like the original git clone command didn't include ```--recurse-submodules``` on the commandline, that's probably missing in the documentation Please let me know which part of the docs you followed and I'll fix that.

Also if you can, please try to clone the repo again (after deleting it) and add --recurse-submodules into the commandline. Thanks for sorry for the trouble.

**Comment by ghost** [comment]
WWIV Readme didn't mention that. i tried it again still didn't work

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_cryptInit referenced in function "bool __cdecl wwiv::bbs::ssh_once_init(void)" (?ssh_once_init@bbs@wwiv@@YA_NXZ)	C:\Users\Mark\source\repos\wwiv\wwiv	C:\Users\Mark\source\repos\wwiv\bbs_lib.lib(ssh.cpp.obj)	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_cryptCreateContext referenced in function "public: bool __cdecl wwiv::bbs::Key::Create(void)" (?Create@Key@bbs@wwiv@@QEAA_NXZ)	C:\Users\Mark\source\repos\wwiv\wwiv	C:\Users\Mark\source\repos\wwiv\bbs_lib.lib(ssh.cpp.obj)	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_cryptGenerateKey referenced in function "public: bool __cdecl wwiv::bbs::Key::Create(void)" (?Create@Key@bbs@wwiv@@QEAA_NXZ)	C:\Users\Mark\source\repos\wwiv\wwiv	C:\Users\Mark\source\repos\wwiv\bbs_lib.lib(ssh.cpp.obj)	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_cryptSetAttribute referenced in function "public: __cdecl wwiv::bbs::SSHSession::SSHSession(int,class wwiv::bbs::Key const &)" (??0SSHSession@bbs@wwiv@@QEAA@HAEBVKey@12@@Z)	C:\Users\Mark\source\repos\wwiv\wwiv	C:\Users\Mark\source\repos\wwiv\bbs_lib.lib(ssh.cpp.obj)	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_cryptSetAttributeString referenced in function "public: bool __cdecl wwiv::bbs::Key::Create(void)" (?Create@Key@bbs@wwiv@@QEAA_NXZ)	C:\Users\Mark\source\repos\wwiv\wwiv	C:\Users\Mark\source\repos\wwiv\bbs_lib.lib(ssh.cpp.obj)	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_cryptGetAttributeString referenced in function "bool __cdecl wwiv::bbs::GetSSHUserNameAndPassword(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?GetSSHUserNameAndPassword@bbs@wwiv@@YA_NHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)	C:\Users\Mark\source\repos\wwiv\wwiv	C:\Users\Mark\source\repos\wwiv\bbs_lib.lib(ssh.cpp.obj)	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_cryptKeysetOpen referenced in function "public: bool __cdecl wwiv::bbs::Key::Open(void)" (?Open@Key@bbs@wwiv@@QEAA_NXZ)	C:\Users\Mark\source\repos\wwiv\wwiv	C:\Users\Mark\source\repos\wwiv\bbs_lib.lib(ssh.cpp.obj)	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_cryptKeysetClose referenced in function "public: bool __cdecl wwiv::bbs::Key::Open(void)" (?Open@Key@bbs@wwiv@@QEAA_NXZ)	C:\Users\Mark\source\repos\wwiv\wwiv	C:\Users\Mark\source\repos\wwiv\bbs_lib.lib(ssh.cpp.obj)	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_cryptGetPrivateKey referenced in function "public: bool __cdecl wwiv::bbs::Key::Open(void)" (?Open@Key@bbs@wwiv@@QEAA_NXZ)	C:\Users\Mark\source\repos\wwiv\wwiv	C:\Users\Mark\source\repos\wwiv\bbs_lib.lib(ssh.cpp.obj)	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_cryptAddPrivateKey referenced in function "public: bool __cdecl wwiv::bbs::Key::Create(void)" (?Create@Key@bbs@wwiv@@QEAA_NXZ)	C:\Users\Mark\source\repos\wwiv\wwiv	C:\Users\Mark\source\repos\wwiv\bbs_lib.lib(ssh.cpp.obj)	1

**Comment by wwiv** [comment]
go into deps/cl342 and run ```msbuild crypt32.vcxproj /t:Build```
and then try the build again.  That's similar to what we have to do on the commandline builds: https://github.com/wwivbbs/wwiv/blob/master/builds/jenkins/wwiv/build.cmd#L110 (for example).

**Comment by wwiv** [comment]
Please reopen if that didn't fix this.  Thanks
