### ISSUE TITLE
WWIV Color codes not displayed in external description

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1211]
File_id.diz files with wwiv color codes do not display the color in the external description.

**Comment by wwiv** [comment]
Did this work in 4.3?  Got a http URL to  file with a DIZ with color codes?

**Comment by mmunson** [comment]
I made a file-id.diz with pipe colors in 4.30 and it displayed.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
