### ISSUE TITLE
QWK Upload Issues

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1214]
I tried to do my first qwk packet in awhile and I have noticed that yes, I can download my qwk packets. However uploading the packets are an issue.
![qwk-issue](https://user-images.githubusercontent.com/13500419/85206695-9c1c4580-b2d8-11ea-9ee5-b32b06076605.png)

File upload is never sent to the batch directory for processing.

**Comment by wwiv** [comment]
was anything in the batch directory?

**Comment by mmunson** [comment]
Its clean.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
