### ISSUE TITLE
File list header (the short one broken in later builds)

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1216]
Its a cosmetic bug, but here it is. 
![2975](https://user-images.githubusercontent.com/13500419/85213068-524e5200-b30e-11ea-8a7d-54f2242809e6.png)
How it should look above
![3118](https://user-images.githubusercontent.com/13500419/85213071-5aa68d00-b30e-11ea-9543-fb5c2d22d9c7.png)
How it is currently

**Comment by wwiv** [comment]
I'm dense, is it the colors?

**Comment by mmunson** [comment]
Its not the colors, there is a difference between both photos. The %54 in the later picture is a malformed macro.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
