### ISSUE TITLE
Cosmetic - Typo in "coutry"

### ISSUE THREAD

**Issue by fcreid** [wwivbbs/wwiv#1221]
wwivd_http and wwiv_non_http have typos on the word "coutry" versus "country" code. :)

**Comment by wwivsoftwareservices** [comment]
Hey Frank!

Happy 4th of July guys!

 

--Dean

**Comment by fcreid** [comment]
Likewise, Dean! Happy 4th to you and all. Hope all is well!

**Comment by MarkHofmann11** [comment]
Yes, Happy 4th of July to all of you!  Great to hear from you.  Are you
still in WWIVnet?

**Comment by wwivsoftwareservices** [comment]
Unfortunately not.  Time and resources have not allowed for many years.  Moved around for 6+ years.  Hard to run a BBS living in a 40’ motorhome…..  Now settled but more than full time work at the VA and full time grandparenting don’t leave much time for anything else.  What little free time we have is spent on the house and an occasional vacation, camping or kayaking trip.

**Comment by fcreid** [comment]
I’m trying to bring things up, Mark.

 

I think I’m configured as @2.wwivnet. My hostname is bbsdoors.com, for simplicity. I use “eagle” as PW in my callout.net. I don’t see an entry for @1 in address.net (“100” downloaded today).

 

I’ve forgotten more than I can remember. Thanks for steering me through. 😊


Frank
