### ISSUE TITLE
Birthday age not calculated correctly when making new account

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1224]
At new user creation, when user types their birthday, the age is not calculated. it just reads as (( years old).

It happens in windows and linux.

**Comment by wwiv** [comment]
IIRC I added a hack to 2-digit date to get is through 2020, which in 1999 seemed to be long enough. Apparently not?

**Comment by mmunson** [comment]
Maybe we could buy ourselves 20 more years?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by wwiv** [comment]
Not it, just a display problem
