### ISSUE TITLE
Logoff countdown after download not displaying

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1226]
This might be a cosmetic bug, but usually when you ask for the bbs to log you off it gives a 15 second count down, but right now its not displaying the timer.

**Comment by wwiv** [comment]
Huh? Where is that, I don't see where the bbs does that. I only remember that after you downloaded your batch of files.

**Comment by mmunson** [comment]
![logoff](https://user-images.githubusercontent.com/13500419/87226615-d2823900-c349-11ea-9362-b5cd3ed44e06.jpg)
Some context with the picture.

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/c7231059d258d935ddaa2905f19a1bfa351efb29
