### ISSUE TITLE
pcboard.sys is malformed (drop file)

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1227]
Either we should strip pcboard.sys support or mend it. I tried it with several doors such as Echo Request door and Legend of the red dragon.

**Comment by wwiv** [comment]
Do you have a good example or one and also the file format?  I can take a look, otherwise, ya, should probably remove it, I can't think of a door that doesn't work with door.sys, chain.txt or dorinfox.def

**Comment by mmunson** [comment]
A good example of a working pcboard.sys? http://wiki.bbs.nz/doors:dropfiles:pcboardsys fyi


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by wwiv** [comment]
realized it had some padding, should be fixed in https://github.com/wwivbbs/wwiv/commit/829c1b99b88842987f39794ddd2964290c1cdc31
