### ISSUE TITLE
Alignment of Archive Contents

### ISSUE THREAD

**Issue by fcreid** [wwivbbs/wwiv#1229]
Awesome work on the internal archivers, Rushfan! That's a void that's been itching to be filled for decades!

The display is a bit off on the end-of-line terminations (screenshot attached).

Nice work!

![Archive_Viewer](https://user-images.githubusercontent.com/10696845/88061643-c5c5c800-cb35-11ea-9e15-34201e6124a3.jpg)

**Comment by wwiv** [comment]
Thanks Frank!
