### ISSUE TITLE
Handles not honored in message bases

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1230]
No matter if its wwivnet or fidonet, real name is used instead of handle/account name. I even tried it on a virgin copy of wwiv on another partition.

**Comment by wwiv** [comment]
I can't reproduce this, just created a message in a wwivnet sub and here's my packet (using handle as expected)
```
^Z^A^@^@^@^A^B^A^@^Z^@^@^@^@^@~`^Z_<9C>^@^@^@^@^@WWIVDEV^@test^@Rushfan #1 @513
Thu Jul 23 21:15:58 2020
^D0R 53 - 07/23/20 21:16:07 wwivnet ->513
RE: test

^D0PID: WWIV 5.5.0.development
test
/s

```

**Comment by mmunson** [comment]
On both of my installs it does it on me. On my windows 64 partition and my windows 32 bit. It defaults to my real name instead of handle especially in wwivnet.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by wwiv** [comment]
seems  fixed
