### ISSUE TITLE
FSED: Add color map and basic instructions in border

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1239]
We should add a color map somewhere on screen so people can see what number is what color, and some basic commands to tell people to use ESC for accessing menu items.  Similar to what is on the line editor:

Colors: ^P-0123456789
Enter /Q to quote previous message, /HELP for other editor commands.

**Comment by wwiv** [comment]
Have you seen the Help I added last night in https://github.com/wwivbbs/wwiv/commit/018693fee5ec5cd614223fc5d65b543a66b0d4f4

It just mentions escape for menu, but I realized that there were zero instructions on how to get a menu or help

**Comment by granitepenguin** [comment]
yeah, I've seen the help.  I was talking more about telling people how to find it :-)

**Comment by wwiv** [comment]
Now it tells you to press escape for the menu and help by default, did you see that?

**Comment by granitepenguin** [comment]
yeah, that works
