### ISSUE TITLE
Extracting Post issues in message base

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1246]
Extract posts feature in the message base will not let a person quit the extract menu.
Also extract to transfer directory is not available as well.

**Comment by wwiv** [comment]
What is "Extract to transfer directory"

**Comment by mmunson** [comment]
After I get back from work I'll give you a screen shot. It's the first option in the prompt.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mmunson** [comment]
![the-issue](https://user-images.githubusercontent.com/13500419/90841403-7380ee00-e311-11ea-9027-7e3348db9cd1.jpg)
