### ISSUE TITLE
Unable to access email 

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1247]
x86 build of 5.5.0.3229 on Win10

viewing of ema
![Capture](https://user-images.githubusercontent.com/13243281/90941549-45f67c00-e3c7-11ea-90b8-ce1ea21b53ae.JPG)
il broken

**Comment by wwiv** [comment]
Try with 3237 or later and let me know how that goes. I added some guardrails in network number accessing in https://github.com/wwivbbs/wwiv/commit/cfb61198c30b5f34ccc5699b38bfb9a7aab8ec83 which may fix this, or at least help make it more clear where it's happening.  Let me know.

**Comment by BloodStoneBBS** [comment]
That seems to have helped!  No more crashes in WFC, and I am able to list and read the messages now.  Thanks!
