### ISSUE TITLE
WWIVD

### ISSUE THREAD

**Issue by rdfig** [wwivbbs/wwiv#1267]
I added fido in wwivd and when I try it I get the error "error invoking CreateProcess"  This is in version 5.50  Trying to invoke my Mystic bbs.

**Comment by wwiv** [comment]
I'll need some more info - when did it get this error? where was it trying to invoke mystic? In the matrix menu?

**Comment by rdfig** [comment]
In wwivconfig, wwivd – matrix

 

Attaching a pdf of screen shot of matrix

**Comment by wwiv** [comment]
The screen shot didn't make it into the github issue, can you attach it directly from github? Thanks

**Comment by rdfig** [comment]
![image](https://user-images.githubusercontent.com/16578563/92411010-caf1cd00-f10b-11ea-8519-44aa8e986b0c.png)

**Comment by rdfig** [comment]
Trying a second time, not sure last one worked.  This is my matrix for Mystic
![image](https://user-images.githubusercontent.com/16578563/92411131-45225180-f10c-11ea-98da-135bb7751488.png)

**Comment by rdfig** [comment]
Just did on git, I think I did it write.  I also have some issues with wwivnet.  I will check my logs first.  Does the wfc screen need to be up for mail of just the wwivd?

**Comment by wwiv** [comment]
This looks like you are trying to add a 2nd bbs into wwivd to handle telnet for? Is that correct?

This is unrelated to wwivnet.  For wwivnet, you can run wwivd to listen on binkp too.

**Comment by wwiv** [comment]
For the matrix settings, Looks like mystic wants the current dir to be set.  So I made a mystic.cmd and changed the matix settings to call that instead of mystic.exe.

Here's what was in that mystic.cmd
```batch
C:
cd \mystic
mystic.exe %1 %2
```

And here's my telnet comand:
```
Telnet Command: C:\mystic\mystic.cmd -n@N -tid@H
```

**Comment by rdfig** [comment]
I had to leave off the second %2 and it worked locally on the screen but did not show anything on the client side.

 

 

 

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net <mailto:rdfigsupport@rdfig.net> 

General Support:  rdfigueroa@gmail.com <mailto:rdfigueroa@gmail.com> 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net <http://www.rdfig.net/>

**Comment by wwiv** [comment]
make sure there's no space between -tid and @H 

Not sure, that worked for me, You can try moving the -n and -tid into the cmd file and remove them from the wwivd config to see if that helps.

You can also change the telnet port number to -1 to disable it, and just use wwivd to listen for wwivnet binkp sessions if that helps.

**Comment by rdfig** [comment]
No, just want to get mail going.  So where do I ell wwivd to listen on binkp also?   I looked at wwivconfig under wwivd configuration and typed in my port number of 24556

 

 

 

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net <mailto:rdfigsupport@rdfig.net> 

General Support:  rdfigueroa@gmail.com <mailto:rdfigueroa@gmail.com> 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net <http://www.rdfig.net/>

**Comment by rdfig** [comment]
I’ll double check all those and try your suggestions.  I was wondering, when I telnet to my Mystic,  I am using the Matrix logon if that makes any difference?

 

 

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net <mailto:rdfigsupport@rdfig.net> 

General Support:  rdfigueroa@gmail.com <mailto:rdfigueroa@gmail.com> 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net <http://www.rdfig.net/>

**Comment by wwiv** [comment]
Assuming the https://github.com/wwivbbs/wwiv/issues/1271 covers how to get mystic working under the matrix menu from wwivd?  If so, I'll close this one

**Comment by rdfig** [comment]
Thanks.  I’ll get it right

 

 

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net <mailto:rdfigsupport@rdfig.net> 

General Support:  rdfigueroa@gmail.com <mailto:rdfigueroa@gmail.com> 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net <http://www.rdfig.net/>
