### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by the-godfather-007** [wwivbbs/wwiv#1268]
Hi all,

I forked the repository, cloned to my harddrive, the folder shows in VS and can be selected, but the build icons never turn on to compile.  What step am I missing?  I'm using the Windows version (I'm on windows 10).

**Comment by wwiv** [comment]
I think you are hitting: https://developercommunity.visualstudio.com/content/problem/1142252/1670-hangs-using-open-folder.html with newer releases than 16.6

I stayed on 16.5.5 and it works.

**Comment by wwiv** [comment]
https://developercommunity.visualstudio.com/content/problem/1157854/vs2019-wont-open-folder-with-cmake-project.html looks possible too. There's a few of these

**Comment by wwiv** [comment]
maybe deleting cmakesettings.json will fix it?

**Comment by wwiv** [comment]
That did it. Delete the WSL stanzas out of cmakesettings.json.  I'll push that into the branches.

**Comment by wwiv** [comment]
A "git pull" get to the latest commit should fix it.

**Comment by the-godfather-007** [comment]
I’m using the desktop version, it’s new to me.  How do I do so within the desktop version?

**Comment by wwiv** [comment]
Try this out:

Also if possible, 
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/syncing-your-branch#pulling-to-your-local-branch-from-the-remote

**Comment by wwiv** [comment]
@DougCooper0612 
Did you get it working?

**Comment by the-godfather-007** [comment]
Not yet.  I can’t find the feature in git desktop to recourse-submodules .. and think my fork was done without that option.  I get 16 errors during compiling.


Doug Cooper

**Comment by the-godfather-007** [comment]
are there step by step command prompt options to fork, clone, and compile instead of using the desktop version?  I tried in git bash, but cmake (as instructed in wwiv comments) does not exist.  So ... it's been a while since I've played around in git.  sorry for the hassle.

**Comment by wwiv** [comment]
Ah, yes that'll do it.  You need the recurse submodules.

if you can be comfortable using the commandline, it's not bad.  You don't want to use git bash, but rather the
"Developer Command Prompt for Visual Studio 2019" (or something like that, it's in my start menu).

That has git, cmake (which ships with visual studio), and the compilers all in the path.  That's how I typically work too.

If you drop by IRC, we're in and out and happy to answer questions.  I use irccloud.com, so I'll see questions next time I'm online and check it  afew times a day.

**Comment by the-godfather-007** [comment]
which network within irccloud.com are you all in?  And thanks for the help.  I have just a couple of questions to refresh my memory.  I've only used git to push classwok for a js class I had been taking.

**Comment by wwiv** [comment]
irc.venomslair.com port 6697 (choose secure)/SSL.)  both irc.wwivbbs.org and irc.venomslair.com point to the same place.  Venom runs IRC for us.

We also list the info at the bottom of http://www.wwivbbs.org

**Comment by wwiv** [comment]
I worked around the isue with visual studio. If you start over from scratch it'll work, otherwise see if the docs on how to do a "git pull" fixes it for ya.  Also feel free to drop by to ask questions, always happy to help.
