### ISSUE TITLE
Fidonet

### ISSUE THREAD

**Issue by rdfig** [wwivbbs/wwiv#1270]
trying to import echo mail.  When I run networkf I geet this:
![image](https://user-images.githubusercontent.com/16578563/92415519-e87c6200-f11e-11ea-9905-b462f298c060.png)

my command line is:
networkf .1 --v=2 import
networkf .1 -- v=2 export
Not sure what the error message above means.

**Comment by wwiv** [comment]
Did you define your uplink in the network setting for the network in wwivconfig?
http://docs.wwivbbs.org/en/wwiv55/network/ftn_nets/ has some info.

Also maybe you need to run network3. 

Try
``` 
network3 .1 --v=2
```

**Comment by rdfig** [comment]
my screen look different that what i
![image](https://user-images.githubusercontent.com/16578563/92416802-dc939e80-f124-11ea-9c6d-d054416270c6.png)
s pictured on the doc link you sent me..

**Comment by rdfig** [comment]
I ran nework3 .1 --v=2 and got this
![image](https://user-images.githubusercontent.com/16578563/92416855-12388780-f125-11ea-8481-78e86c7f6044.png)

**Comment by wwiv** [comment]
Does it work now after you ran network3?

You define your uplink in the addresses section on the dialog you were in

**Comment by rdfig** [comment]
I'm getting this now and I think it is wwivnet
![image](https://user-images.githubusercontent.com/16578563/92417445-caffc600-f127-11ea-8493-38d571218e3f.png)

**Comment by rdfig** [comment]
Uplink is defined and It worked.  I have new mail from fidonet.    Do I need to do something to automate the import and export of fidonet mail?

 

 

 

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net <mailto:rdfigsupport@rdfig.net> 

General Support:  rdfigueroa@gmail.com <mailto:rdfigueroa@gmail.com> 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net <http://www.rdfig.net/>

**Comment by wwiv** [comment]
make sure you set the echo tag in the message base editor ("//BE" from the main menu, or B from the WFC), it looks like that is missing.   WWIVd will automate tossing mail once it receives it. If you do it manually, you can just run the networkf command like you do, then run "networkc .1" and that'll clean up everything network wise.

**Comment by rdfig** [comment]
Fixed and many thanks.  I still have not seen any traffic with wwivnet.  Checking out my setup, but it worked when I had 5.1 now it does not.

 

 

 

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net <mailto:rdfigsupport@rdfig.net> 

General Support:  rdfigueroa@gmail.com <mailto:rdfigueroa@gmail.com> 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net <http://www.rdfig.net/>

**Comment by wwiv** [comment]
We've made lots of progress since 5.1, so a few things changed. 
Glad it's working.

Post a message on wwivnet to test.
