### ISSUE TITLE
Backbone.na ftn message base importer

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1272]
I am wondering as a feature request, could it be where the file is loaded it would load it by echo tag and description would be the message area description and it would ask for your uplink and it would configure all the message areas from that said network. I know I'll need to elaborate more for it to come to fruition.

**Comment by mmunson** [comment]
Backbone file importer.

FTN Networks have an echo list or sub list where people can areafix to their local hub no matter
if its Micronet, Fidonet or fsxnet. 

eg:
SAMPLE.NA

FRENCH_TOAST		Breakfast Food Discussion
COMIDA_MEXICANO		Mexican Food Discussion

Instead of having to manually import 50+ message areas you can use an importer to help load the echos
to your bbs.

Sample steps.

1. Load *.NA file of your choice
2. Ask what network is these message bases for.
3. Ask what conference you want the message bases in
4. Ask who is your uplink for the network to fill out the missing elements in //BE
5. Import the message areas into board edit.

**Comment by wwiv** [comment]
Reference: 
* Mystic : http://wiki.mysticbbs.com/doku.php?id=mutil_import_fidonet_na
*  Sync: http://wiki.synchro.net/util:sbbsecho (See Import Areas in scfg)

**Comment by wwiv** [comment]
We'll move "wwivutil messages areas" to a new "wwivutil subs list" command.
Importing areas will be added as "wwivutil subs import" and possibly areas.bbs exporting via "wwivutil subs export".

"wwivutil messages" will remain as-is otherwise since that operates on messages (and not the subs.json).

**Comment by wwiv** [comment]
Got the first cut of this done:

**Comment by wwiv** [comment]
https://github.com/wwivbbs/wwiv/commit/dfb49a609957ef01541e7304e162f7a85c3e7c6c
