### ISSUE TITLE
Documentation issue?

### ISSUE THREAD

**Issue by devzzm** [wwivbbs/wwiv#1274]
When I am on http://docs.wwivbbs.org/en/wwiv55/ and click on either "Upgrading from WWIV 4.x" or "Linux WWIV Installation" i just get a 404

http://docs.wwivbbs.org/install/linux.md

http://docs.wwivbbs.org/install/linux.md

**Comment by wwiv** [comment]
Yes. Thanks for reporting it, looks like the links are absolute when should be relative. You can get to those pages from the sidebar on the left.  I'll submit a fix.

**Comment by wwiv** [comment]
Looks like mkdocs changed their behavior, and the absolute links never "should" have worked. See https://github.com/mkdocs/mkdocs/issues/1619

**Comment by wwiv** [comment]
Should be fixed in https://github.com/wwivbbs/docs/commit/de76ca956c69c62121648eaa884a221e1dc05ad0 once RTFD builds.

**Comment by wwiv** [comment]
Fixed, you may need to force reload the page, browsers like to cache previous versions.
