### ISSUE TITLE
Display Build Number in WWIV5TelnetServer

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#128]
This didn't seem to get migrated over, but its definitely not in the latest builds.
Would be nice to have it in the Title Bar maybe, but at least in Help.About.

Msg: [237/428] WWIVnet WWIV Development
Subj: Re: idea
Name: Rushfan #209 @1
Date: Mon Aug 18 01:35:51 2014
From: WWIVnet- Skulls & Crossbones [704-854-3076]
Loc:  Gastonia, North Carolina

RE: idea
BY: Matt Munson #1 @815

MM> For wwiv telnet server we should have the bild number listed.

Good Idea.  I'll forget so I went ahead and klogged it at
sf.net/p/wwiv/feature-requests/10

Rushfan

**Comment by TRI0N** [comment]
Currently Brainstorming This.. Stay Tuned...

**Comment by askpatrickw** [comment]
Feel like I saw you finish this... Am I correct?

**Comment by BloodStoneBBS** [comment]
Is this to display BBS build nuumber or WWIVTelnetServer build number? Both?

**Comment by TRI0N** [comment]
I have solved both ideas.. The WWIV Version is now in the Title Bar of WWIV5TelnetServer and if your click Help \ About it will display the Current WWIV5TelnetServer Version. Enjoy!
