### ISSUE TITLE
ncurses error

### ISSUE THREAD

**Issue by cwstephenson71** [wwivbbs/wwiv#1280]
I've done a fresh install from the lastest source. Using the Debian code. After installation if runing any binary I get the error "error while loading shared libraries: libform.so.6: cannot open shared object file: No such file or directory" Yet I have varified that I nave ncurses6 installed.

System:
OS: Manjaro Linux (Latest version)
Kernel: 5.8.6-1-MANJARO
QT: 5.15
OS Type: 64-bit
Processors: 4 x Intel Core i5-4570 @2.90
Memory: 14.6
Graphics: Mesa DRI Intel HD Graphics 4600

**Comment by wwiv** [comment]
Manjaro is based on Arch linux, it's possibly libform isn't part of the ncurses6 package and has to be added in addition.  I'm not familiar with Arch, but I see lots of hits on google for issues like this:.

here's one: https://github.com/microsoft/ProcMon-for-Linux/issues/44

**Comment by wwiv** [comment]
https://www.archlinux.org/packages/core/x86_64/ncurses/files/ lists the files there, there's only a libform.so not libform.so.6.  Maybe you'll need to recompile it on this system from the github source so that the so's linked in matches this system.

**Comment by cwstephenson71** [comment]
Thank you!
