### ISSUE TITLE
Broken docs.wwivbbs.org Link

### ISSUE THREAD

**Issue by cwstephenson71** [wwivbbs/wwiv#1281]
Here is the link: http://docs.wwivbbs.org/conn/telnet.md

I went to follow it so I can setup the WWIVD daemon.

Thanks

**Comment by wwiv** [comment]
which page had that link on it?

**Comment by wwiv** [comment]
http://docs.wwivbbs.org/en/wwiv55/conn/telnet/ is the right page

**Comment by cwstephenson71** [comment]
I stared following the directions for linux
