### ISSUE TITLE
File Delete Crash

### ISSUE THREAD

**Issue by ghost** [wwivbbs/wwiv#1282]
If a file area has only one file in it, and you try to delete it, it crashes the BBS node.

I added a second file, then a file could be deleted, but when there was only 1 left, deleting the file caused a crash.

This is using the delete command from the sysop command on the file listing WWIV 5.5 for windows.

**Comment by ghost** [comment]
As an update, it may have been caused by me not having the paths as the full path rather than the default relative paths.

**Comment by wwiv** [comment]
When I try to delete a file, and there's only 1 file, then nothing happens.

This is in (L) list files.  Then I hit (S) for the sysop menu, then (D) to delete.

Is there a different way that's working for you where it crashes?

**Comment by ghost** [comment]
Hmm, ok, that's what I was doing, however I tagged the one file first. 

This is in the sysop are by the way. Is there a way I can clean out that last file and have a fresh sysop area so I can try again and see if it's because I corrupted something.

**Comment by wwiv** [comment]
aha, I bet it was the tagging that caused it. Thanks for that detail.

**Comment by wwiv** [comment]
I think wwivutil can delete the files too.  Also if you just have one, find the DIRNAME.ext and DIRNAME.dir files in data/ and just delete those. WWIV should recreate them as needed with just the filearea header.

**Comment by ghost** [comment]
Thanks, that got rid of the file, I did some more experiments...

Uploaded a new file into the sysop area.

Just Delete did nothing (ie the file remains)

Tag + Delete crashed again, so I logged back in and tried to move the file and it said file not found. However the listing entry was still there and the file still exists on the disk oh after file not found it crashed again.

I logged back in, and tried tagging and downloading the file, that worked.

Hope that helps
