### ISSUE TITLE
TZUTC kludge should not have a +

### ISSUE THREAD

**Issue by ghost** [wwivbbs/wwiv#1284]
The TZUTC kludge should not have a + in timzones (it is supposed to have a - though).

for example my timezone is AEST which is +10:00 the correct TZUTC is 1000 not +1000

Andrew

**Comment by wwiv** [comment]
Fixed in https://github.com/wwiv/wwiv/commit/998758dbd96f6c951c2b0abe17756857ad8095d8

**Comment by wwiv** [comment]
Merged in https://github.com/wwivbbs/wwiv/commit/998758dbd96f6c951c2b0abe17756857ad8095d8
