### ISSUE TITLE
Unable to negotiate SSH

### ISSUE THREAD

**Issue by un-fuf-a-doo** [wwivbbs/wwiv#1287]
wwivd version: 5.6.0.3277
ssh version: OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020
operating system: CentOS 7
```
Unable to negotiate with x.x.x.x port 2022: no matching cipher found.  Their offer: 3des-cbc,aes128-cbc,blowfish-cbc
```
I am incredibly new to WWIV and am not sure I configured everything properly.  I don't see any previous issues reported with this specific error so I thought I would report it. Is there something I need to do or is this a limitation in this build.

**Comment by ghost** [comment]
This is a cryptlib issue (cryptlib uses old ciphers that openssh no longer supports) you could try using syncterm (it has ssh support) and is also built with cryptlib.

@wwiv Synchronet which also uses cryptlib but has patched it to work - could their changes be incorporated into WWIV?

**Comment by un-fuf-a-doo** [comment]
I did just try SyncTerm (not the same I know) and got the same error.  I'm on a mac so I have to compile Synchronet. I don't see it in Homebrew. I don't suppose there are plans to change to libssh?

**Comment by wwiv** [comment]
I’m not at my development machine but your GitHub change looks good to me.
I’d like to look at libssh one day but your 345 upgrade looks like a no
regrets move to do today.

**Comment by wwiv** [comment]
Should be fixed by https://github.com/wwivbbs/wwiv/pull/1288 in the 5.6 branch
