### ISSUE TITLE
Issue with archivers in latest 5.6

### ISSUE THREAD

**Issue by ghost** [wwivbbs/wwiv#1290]
Looks like the path work has broken the external archivers (at least on windows).

setting :
c:\wwiv\unzip.exe -o -j -C %1

(Adding %2 will not work, wwivconfig refuses to save the command with %2 unlike 5.5)

Unzipping changed to the directory for the output files, then unzips with a relative path (from where it changed from..)

eg:
fsxnet.dir\in\somepack.tu0

unzip -o -j -C fsxnetdir\in\somepack.tu0

fails to find somepack.tu0 because unzip is not executed with working directory C:\wwiv\

Andrew

**Comment by ghost** [comment]
You may have fixed this already in the most recent commit which was done after i checked out and before i posted the issue.

I have compiled the most recent commit and it works on my raspberry pi, (is using the fullpath) so probably can close this?

**Comment by wwiv** [comment]
Yes, I fixed this in https://github.com/wwivbbs/wwiv/commit/d5ec132a10d3cd5605440c0e73ae51e132da213a

"ensure net.dir is absolute".  It wasn't looking in the right place, since the current dir is a temp dir that we make for each run of networkb.
