### ISSUE TITLE
Fix for tGF's conference bug

### ISSUE THREAD

**Issue by ghost** [wwivbbs/wwiv#1292]
Line 180 of sublist.cpp should be

````
if (a()->uconfsub.size() > 1 && a()->uconfsub[1].confnum != -1) {
````

rather than

````
if (a()->uconfsub[1].confnum != -1) {
````

Other wise it fails with only one conference configured

**Comment by wwiv** [comment]
Fixed in both 5.5 and 5.6

Thanks Apam!
