### ISSUE TITLE
Unable to upgrade 4.2 to 5.5.0.3247

### ISSUE THREAD

**Issue by jhuettner** [wwivbbs/wwiv#1294]
I have an older v4.2 board that I just can't seem to upgrade to 5.5.  I tried on Linux and now Windows and ran into the same problem. 
   Board is v4.2.  Operating system is Windows 7 x32 fresh install in Hyper-V VM.  Installed vcc 2015-2019 redistributable to get around msvcc104.dll warning.  Copied original board files to c:\bbs .  Opened wwiv-win-x86-5.5.0.3247.zip and over-wrote all files with the ones in the zip.
   Running wwivconfig fails due to TEMP_DIRECTORY not being set.  Edited wwiv.ini and set TEMP_DIRECTORY = temp%n and BATCH_DIRECTORY = batch%n, NUM_INSTANCES = 1.
   Run wwivconfig, asks if you want to upgrade from 4.2 to 5.x, say yes.  Then asks if you want to upgrade config.dat to 5..2+ format.  Say yes.  No errors.  Quit.  No errors in wwivconfig.log.  Run wwivconfig again, same thing, do you want to upgrade config.dat to 5.2+ format over and over.  Can't start board, bbs.exe complains config not the latest version.  No error other than that in bbs.log.
   I can provide the config if you'd like.  Thank you all for the hard work, love WWIV!

**Comment by wwiv** [comment]
Hmm, if you don't mind, send me the config.dat and Ill take  look.  Something seems off, I know I did a 4.30 to 5.5 upgrade recently and it seemed to work in a test setup.

**Comment by jhuettner** [comment]
> Hmm, if you don't mind, send me the config.dat and Ill take look. Something seems off, I know I did a 4.30 to 5.5 upgrade recently and it seemed to work in a test setup.

Certainly!  It does have other people's addresses and passwords in it.  Do you have an email address I can send to, or a public PGP key I can use to encode and post?  Thank you!

**Comment by wwiv** [comment]
Oh, do not need nor want the userlist, just config.dat (and if you have 4.24 please change your system password first to something like "SYSOP". Nothing private shoudl be in config.dat

Then you can email it to rushfan at wwivbbs dot org.  I'll try it in a 4.24 I have.

**Comment by wwiv** [comment]
I just took a 4.24 stock build that I have, and ran through the upgrade steps.  It seemed to work.

I needed to add this to my wwiv.ini
```
;=============================================================================
;                        TEMPORARY DIRECTORY SETTING
;=============================================================================
NUM_INSTANCES        = 8
TEMP_DIRECTORY       = e/%n/temp
BATCH_DIRECTORY      = e/%n/batch
```

Then I could get into the bbs, but there was no WFC.DAT, nor swfc.msg help screen, nor menus in place.  

If possibly, it may be an easier upgrade to go from 4.2 -> 4.30, then 4.30 to 5.x.

If not, you'll need to add menus and a bunch of missing files that have been added in newer 4.2, 4.3 and 5.x releases.  Just copying files from gfiles that don't exist may be good enough.

**Comment by wwiv** [comment]
Alright, that worked> I had to make sure the bbs used it in the same directory as before (C:\bbs) and wwivconfig updated the datafiles.

I wonder if there's some permissions problem that kept the config.dat from being written to after wwivconfig?

**Comment by wwiv** [comment]
Let me know if you need help, I can't reproduce locally the problem you ran into.

**Comment by jhuettner** [comment]
I'm not sure what I'm doing wrong.  I tried renaming the folder to see if that would help, from c:\BBS to c:\BBS, still no luck.  I set the permissions to everyone: Full Control on the c:\bbs folder and all files.  Still every time I run wwivconfig it asks me if I want to upgrade to the latest version.  Maybe it has something to do with the other files in the folder?
   I tried creating a brand-new c:\bbs folder, extracted wwiv-win-x86-5.5.0.3247 into it, then copied in the config.dat and ran wwivconfig.  Wouldn't upgrade either.  I added your info to wwiv.ini and still no joy.
   Any way you could send me the converted config.dat?  Thanks for the help!

**Comment by wwiv** [comment]
Just replied to your email with an upgraded config.dat

I've had enough problems on recent windows with anything on the root of C:\ (i.e. C:\bbs), that I've given up using that
path myself and do this.

make a directory under my user dir for BBSING
i.e. mkdir C:\users\rushfan\bbs

Then subst a drive to it (I use U:)
subst U: Z:\users\rushfan\bbs

Then just use U:\bbs for WWIV, and all of the BBSing stuff lives in U:\...
Also helpful because I can mount U:\ in DOSBOX too for things that need dos.

**Comment by wwiv** [comment]
Let me know if that worked or there's something else that may help. Thanks!

**Comment by jhuettner** [comment]
Sorry, I just started a new job and it's been super busy!  I really appreciate your help, I'm so excited to be able to get my board back and I'm sure a ton of other people would be too!  I'm going to try your suggestions as soon as I get a chance.  But I never did get the email with that upgraded config.dat.  Any way you can email it directly when you get a chance?  email is j_huettner at hotmail dot com.  Thank you very much!

**Comment by wwiv** [comment]
I just forwarded it again, please let me know if you get it.  Good Luck!
