### ISSUE TITLE
Mystic expects MSGID on netmail

### ISSUE THREAD

**Issue by ghost** [wwivbbs/wwiv#1295]
Mystic bbs expects a MSGID in FTN netmail where it gets the return address from.

Without a MSGID mystic BBS lists the wrong return address when replying.

Seems to me this is a mystic bug, but thought I'd mention it in case you want to add a work around.

**Comment by wwiv** [comment]
Hmm, that's easy enough to add, I think I remember checking to make sure it's not netmail before adding it, it's likely easier to add it in all cases (but seemed to be against the spec)
https://groups.google.com/g/alt.bbs.mystic/c/uwfiDiSaPew/m/53rAM73rjZsJ has lots of discussion on this, but hard to read quickly for anything useful
