### ISSUE TITLE
networkf "system" weirdness

### ISSUE THREAD

**Issue by ghost** [wwivbbs/wwiv#1297]
Hey

I've been installing 5.6 on openSUSE 15.2

It works, but there is some strange behavior with the "system" command used to call zip / unzip...

It appears something installs a handler for SIGCHLD which makes "system" return -1 with errno set as ECHILD, which apparently means waitpid didn't work to set the correct return value.

I've fixed this by installing the default SIGCHLD handler in networkf 

signal(SIGCHLD, SIG_DFL) prior to calling system.

I'm not really sure why it's happening.

**Comment by ghost** [comment]
Ok, it seems wwivd is ignoring sig_chld, and that seems to be inherited by networkf, i commented out ignoring sig_chld and removed the signal commands in networkf and it seems to work.

Not sure if this is correct or what.

**Comment by wwiv** [comment]
Where was that in wwivd?

**Comment by wwiv** [comment]
```
2. By ignoring the SIGCHLD signal : When a child is terminated, a corresponding SIGCHLD signal is delivered to the 
parent, if we call the ‘signal(SIGCHLD,SIG_IGN)’, then the SIGCHLD signal is ignored by the system, and the 
child process entry is deleted from the process table. Thus, no zombie is created. However, in this case, the parent 
cannot know about the exit status of the child.
```

I suspect i did that to stop the numerous zombie bbs processes

**Comment by wwiv** [comment]
From https://pubs.opengroup.org/onlinepubs/9699919799/functions/posix_spawn.html:

```
If the SIGCHLD signal is set to be ignored by the calling process, it is unspecified whether the SIGCHLD signal is set to 
be ignored or to the default action in the child process, unless otherwise specified by the POSIX_SPAWN_SETSIGDEF
flag being set in the spawn_flags attribute of the object referenced by attrp and the SIGCHLD signal being indicated 
in the spawn_sigdefault attribute of the object referenced by attrp.
```

**Comment by wwiv** [comment]
so TLDR is I think wwivd should set the child to not ignore sigchld when calling posix_spawn.

**Comment by ghost** [comment]
Well, I'm glad you understand all that. I think I need another coffee  :)

I wonder why it's happening on opensuse but not debian

**Comment by wwiv** [comment]
The key sentence is this one " it is unspecified whether the SIGCHLD signal is set to 
be ignored or to the default action in the child process"

So OpenSUSE chose to do it one way, debian the other (would my guess)

**Comment by ghost** [comment]
I suppose, I would have assumed that would've been something decided by glibc. or possibly kernel.

**Comment by wwiv** [comment]
likely, not sure where.  I'm looking at the history on glibc now (https://github.com/bminor/glibc) , but don't see anything interesting

**Comment by ghost** [comment]
I guess it doesn't really matter, the important thing is it can be either/or.

**Comment by wwiv** [comment]
It's likely from this change to system that happened in the glibc between 2.26 (opensuse 15.2's version) and 2.28 (debian)
```
commit 5fb7fc96350575c9adb1316833e48ca11553be49
Author: Adhemerval Zanella <adhemerval.zanella@linaro.org>
Date:   Wed Oct 24 16:29:38 2018 -0300

    posix: Use posix_spawn on system

    This patch uses posix_spawn on system implementation.  On Linux this has
    the advantage of much lower memory consumption (usually 32 Kb minimum for
    the mmap stack area).
```

**Comment by wwiv** [comment]
is there any reason not to do this for all of the network commands?

**Comment by ghost** [comment]
not that i can think of. I had done it only in networkf because it was failing in calling zip, and i only have fsxnet on that bbs.

i ended up removing the SIG_IGN in wwivd and haven't had any zombie processes yet (that I can tell, using ps & htop), so haven't tried the change elsewhere.

**Comment by wwiv** [comment]
I fixed it in networkc too, which also called system.  Should be fixed for good with latest commit.
