### ISSUE TITLE
^A chars ending up in FTN packets

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1298]
```
> Many thanks for apam for the fixes.  I plan on a couple of more before we
 > call @
 > this done.  Ideally next Tuesday (Nov3) we'll call it done.
 >
 > If new bugs come up that are small, we can open up a 5.5.2 branch while @
 > continuing on 5.6

See the stray @'s in your message text? I'm not sure if those were in the
original message text or those were stray Ctrl-A characters that SBBSecho
auto-converted to '@'s. Anyway, just thought I'd show you what I'm seeing here.
--
                                            digital man                        
```

Looks like those are the ^A EOL wrapped character that WWIV uses.  They should be removed or converted to \x8d for FTN.

**Comment by wwiv** [comment]
@mmunson since this one came from your system, can you please post something that that again and grab the fidonet packet that gets generated with the message and email it to me?  Thanks!  I tried to reproduce on mine and couldn't see the characters.

**Comment by mmunson** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by wwiv** [comment]
Just got a new packet from Matt, can't see ^A in there.  Closing
