### ISSUE TITLE
Changing User Name/Handle (user #1) in wwivconfig appears to have no effect

### ISSUE THREAD

**Issue by robbiew** [wwivbbs/wwiv#1300]
System is......... WWIV 5.6.0.development
Host OS........... Linux 5.4.72-114496

After changing the Sysop User/Name handle in User Editor, it doesn't appear to "take." I'm unable to login with the new handle, and "Your User Information" still reflects the old name. The new name correctly appears in the User Editor in wwivconfig, however. I did stop/restart wwivd just in case -- no impact.

**Comment by wwiv** [comment]
Hmm, looks like we need to regenerate names.lst (the index of username -> usernumber) after editing the userlist.

To work around this:
* delete data/names.lst
* run ```./wwivutil fix uers```

The first will get rid of the index file, the second will regenerate it (since it's missing).

Hope this helps.

**Comment by robbiew** [comment]
That did the trick! I'll close this out, thanks.
