### ISSUE TITLE
No |CL |PA |PO support

### ISSUE THREAD

**Issue by the-godfather-007** [wwivbbs/wwiv#1303]
As a suggestion, not an issue, I would love to see pipe code support for clear screen, pause screen, and turn off pause, functionality built into WWIV.  I don't know how to program that, so thought I'd add the comment.  I am currently just adding the raw ansi codes when necessary, or coding the clear screens and pauses where necessary.

**Comment by ericpareja** [comment]
Are there any other pipe codes that aren't supported yet?

**Comment by wwiv** [comment]
what do you mean @ericpareja ? There's no standard list of pipe codes that's universally supported across BBSes

**Comment by robbiew** [comment]
Just referencing [Mystic's display code support](http://wiki.mysticbbs.com/doku.php?id=displaycodes), which is pretty robust. I don't think all of them are necessary. 

My top picks:
PA   - Send the pause prompt and wait for a key to be pressed
PO   - Used in display files to disable pausing for that display file
CL   - Clears the screen (ANSI 1,1 locate and [2J or ASCII 12)
CR   - Send a carriage return and line feed (move to next line)

Potentially useful:
PN   - Wait for a key to be pressed without prompting
RP## - Sets the internal screen pause line counter to ##

**Comment by ericpareja** [comment]
On Sun, Nov 08, 2020 at 01:29:47PM -0800, Rushfan wrote:
> what do you mean @ericpareja ? There's no standard list of pipe codes that's universally supported across BBSes

How about making it possible to add pipe code macros?
Isn't it like MCI(?) codes? non-standard but almost all BBSes have something like it.

**Comment by wwiv** [comment]
We have pipe code macros today:
http://docs.wwivbbs.org/en/wwiv55/cfg/displaying_text/#displaying-text

This is additional things in the pipe codes

**Comment by the-godfather-007** [comment]
-->Rush, The only two I see that would be great to add would be:  |@CL  clear screen |@PO no pause during long ansi display, usually put at the beginning of a long ansi, with a
 |@! Pause at the end of the file to then pause if desired. I can’t find in the docs how to control the ANSI’s baud rate (display speed,) nor how to do random ansi files (like random logoffs ..)  

I sware I read WWIV could do both?

**Comment by wwiv** [comment]
5.6 has a few things here that likely fix most of all of this, apart from prompting for a key without displaying anything.

(from http://docs.wwivbbs.org/en/latest/cfg/displaying_text/#text)

#### Pipe Screen and Cursor Control


WWIV pipe screen and cursor codes allow simple display manipulation to be
embedded in text without needing to implement ANSI codes, nor checking for
ANSI support from the user.


```|[nnX ``` is the way to display a pipe code macro to display session 
information.  

In all cases nn is optional and defaults to 1


| Code  | Information to display |
|-------|------------------------|
[nnA    | Moves the cursor up nn lines
[nnB    | Moves the cursor down nn lines
[nnC    | Moves the cursor right nn lines
[nnD    | Moves the cursor left nn lines
[xx;yyH | Goto screen position xx, yy
[K      | Clears the line from cursor position to end of line
[1K     | Clears the line from beginning of line to cursor position
[2K     | Clears the entire line, leaves the cursor position the same
[nnN    | Performs nn newlines (same as bout.nl(nn) in code)


#### Pipe Expression Language


WWIV pipe expression language allows more functions to be executed in the context
of displaying text.  All text that is not part of a string literal (i.e.
enclosed in double quotes) must be lower case.

These are of the format ```|{xxxxx}``` whre xxxxx is the expression text.

| Expression  | Action |
|-------------|------------------------|
set           | sets the next variable to the value that follows.  Example: set pause off
| pause       | displays the system pause.

Set can manipulate the values of several system variables.  The values can be
strings that must be enclosed on double quotes, numbers, or truthy values.  

Truthy values are for true are: 'true', 'yes', 'on'.  Every other value is false.

| Variable    | Meaning |
|-------------|------------------------|
pause         | sets the pause on page on or off
lines         | sets the number of lines displayed, this is used for pause calculation.  Currently only 0 is supported for a value.


Examples:
```
  |{set pause=off}
  |{set lines=0}
  Hello |@N! How are you today?
  |{pause}
```
