### ISSUE TITLE
Ar checking when one side is empty doesn't work

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1310]
@BloodStoneBBS reported this one

**Comment by BloodStoneBBS** [comment]
Thanks! This fixed the SUBS, but am now noticing a user is now unable to resetqscan.
"Insufficient ACS for menu item: RESETQSCAN "

Related? Worth a new ticket?

**Comment by BloodStoneBBS** [comment]
Disregard, I see that is actually SysOp only command.
