### ISSUE TITLE
Add option for doors for codepage

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1313]
Now on Windows, we set the codepage to 65001 (UTF-8).  This works great in WWIV, but locally some CP437 doors don't look right (everything is fine remotely).

Add an option to set the codepage for a door, or just force it to 437 for anything using syncfoss or netfoss.  But then it's unclear what do do for stdio and door32 doors?  Maybe just an option for those?

**Comment by dewalters1** [comment]
Perhaps make it a setting in the doors setup?

Sent from my Sprint Samsung Galaxy Note10+.
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wwiv** [comment]
Yes, that's likely the best approach.  It'll be a setting that is only enable don Windows since *nix doesn't have a local console.

**Comment by wwiv** [comment]
This is done, there's an option now on Windows
