### ISSUE TITLE
QWK does not store reply to from FTN bases

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1314]
Just noticed a missing feature in our QWK packer. Recently used Build 3339 and Multimail 0.52.

**Comment by wwiv** [comment]
In qwk.cpp we have this around line 566:
```
if (!qwk_info->in_email) {
    memcpy(qwk_info->qwk_rec.to, "ALL", 3);
  } else {
    auto temp = ToStringUpperCase(a()->user()->GetName());
    strncpy(qwk_info->qwk_rec.to, temp.c_str(), 25);
  }
```

likely here we should see if the message is addressed to someone and use it here.  May be easier to switch QWK to using the msgapi since it has this info handy at this point

**Comment by wwiv** [comment]
Still todo would be when you use a TO line in multimail to have that set in WWIV (somehow)

**Comment by mmunson** [comment]
I am not complaining, its good gradual progress. As stated in IRC earlier tonight.

**Comment by wwiv** [comment]
Yup, it's progress.
