### ISSUE TITLE
Net38b Binaries are 32-bit only

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#132]
The core WWIV Binaries do run on x64. I ran them on on my Window10 x64 box even.
Every .exe in the net38b.zip is 32-bit only.

Not sure if this is something you'll fix or not. I know many of the things anyone running WWIV will want to add-on are 32-bit only. Low-priority I'd say.

**Comment by wwiv** [comment]
They are actually DOS binaries (not 32-bit). You have to run them in DOSEMU or DOSBOX.
