### ISSUE TITLE
File Base - Inability to move files to other file areas

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1323]
I tried moving some stuff that should not have been in my door games area to the other bbs mods area and there was a logic error when I tried to move stuff from base 6 to base 11. It think I want to move it to file area 1. I explained a little bit about this in IRC earlier.

**Comment by wwiv** [comment]
looking in mmkey.cpp, for mmkey, it may be broken for all dir selection.  
Likely has been this way for a long time anytime we call:
```
mmkey(MMKeyAreaType::dirs);
```

**Comment by wwiv** [comment]
Looks like it was broke in August 2016 here: https://github.com/wwivbbs/wwiv/commit/26eaee5613f77dfca00795f3ab66d5a204799a19
