### ISSUE TITLE
Crash on login 

### ISSUE THREAD

**Issue by uriel1998** [wwivbbs/wwiv#1325]
Using the latest Jenkins build (3371) on Debian bullseye (I know), I get a crash on login with this stacktrace:

Program received signal SIGSEGV, Segmentation fault.                                                                                                                                              
                                                    UpdateUserStatsForLogin () at ../bbs/lilo.cpp:451                                                                                             
451     ../bbs/lilo.cpp: No such file or directory.                                                                                                                                               
(gdb) bt                                                                                                                                                                                          
#0  UpdateUserStatsForLogin () at ../bbs/lilo.cpp:451                                                                                                                                             
#1  0x0000555555623c38 in logon () at ../bbs/lilo.cpp:837                                                                                                                                         
#2  0x000055555559e8ce in Application::Run (this=0x555555da1920, argc=1, argv=0x7fffffffdde8) at ../bbs/application.cpp:1034                                                                      
#3  0x0000555555594fa2 in bbsmain (argc=1, argv=0x7fffffffdde8) at ../bbs/bbs.cpp:78                                                                                                              
#4  0x0000555555594e45 in main (argc=1, argv=0x7fffffffdde8) at ../bbs/bbs_main.cpp:22                                                                                                            
(gdb)

**Comment by wwiv** [comment]
The line of code is:
```cpp
 if (a()->udir[0].subnum == 0 && a()->udir[1].subnum > 0) {
```
