### ISSUE TITLE
WWIVconfig returns "744 ERROR Unable to load config.json or config.dat" on new install

### ISSUE THREAD

**Issue by robertstinnett** [wwivbbs/wwiv#1330]
Tried both CentOS 7 and Ubuntu; on running WWIVconfig (after using the install script) getting error of 744 ERROR Unable to load config.json or config.dat.  Cannot get around this error.  Verified all directories are writeable; and verified immutable flag was turned off on file(s).

This was using the latest Linux build as of 1-9-2021.  (wwiv-linux-centos7-5.6.0.3377.tar.gz)

**Comment by wwiv** [comment]
Thanks for the report - in the wwiv bbs directory, what exists for "ls config.*"?

**Comment by robertstinnett** [comment]
Nothing - no files at all matching that pattern.
________________________________

**Comment by wwiv** [comment]
Thanks

**Comment by wwiv** [comment]
Should be fixed in 3381. Thanks for reporting this issue!

**Comment by robertstinnett** [comment]
Awesome!
________________________________
