### ISSUE TITLE
Low priority:  C)ACS option in chain edit needs examples

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1333]
After upgrading, chain security is lost. No example for replacing SL with ACS.

![image](https://user-images.githubusercontent.com/13243281/104209430-8c845b80-53e6-11eb-8248-af3807b19df6.png)

**Comment by BloodStoneBBS** [comment]
Build 3380 on Windows 10 w32 but I've seen this since the change from SL to ACS.

**Comment by wwiv** [comment]
yipes, thanks.  

You should set this to:
```
 user.sl >= 100
 ```

**Comment by wwiv** [comment]
Is there any chance somehow the system deleted the chains.json and reconverted the chains.dat back to chains.json?  The "legacy" chains.dat we save out has no SL since I don't easily know how to parse the expression into something I can pull out the SL in.

**Comment by wwiv** [comment]
But will still add some examples. good idea
