### ISSUE TITLE
Compilation Failure - zmutil.h does not exist.

### ISSUE THREAD

**Issue by austinseraphin** [wwivbbs/wwiv#1348]
I cannot compile WWIV using the main branch. I run Slackware Linux and use GCC 9.2.0.

../bbs/prot/zmodem.cpp:44:10: fatal error: bbs/prot/zmutil.h: No such file or directory
   44 | #include "bbs/prot/zmutil.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
[129/490] Building CXX object bbs/CMakeFiles/bbs_lib.dir/qwk/qwk_ui.cpp.o
ninja: build stopped: subcommand failed.

It looks like a few files in the proto directory reference the nonexistent zmutil.h.

**Comment by wwiv** [comment]
Thanks for the issue! This should now be fixed in 4fd093ee7f38087c602260ade2df1e60731f3220.
