### ISSUE TITLE
undefined reference to symbol 'dlclose@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by austinseraphin** [wwivbbs/wwiv#1350]
Linking fails with:

[1/185] Linking CXX executable bbs/bbs
FAILED: bbs/bbs 
: && /usr/bin/c++  -g   bbs/CMakeFiles/bbs.dir/bbs_main.cpp.o  -o bbs/bbs  bbs/libbbs_lib.a  fsed/libfsed.a  common/libcommon.a  sdk/libsdk.a  local_io/liblocal_io.a  localui/liblocalui.a  -lncursesw  /usr/lib64/libformw.so  core/libcore.a  -lstdc++fs  ../deps/cl345/libcl.a  -lpthread  -lutil  -lz && :
/usr/bin/ld: ../deps/cl345/libcl.a(odbc.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[2/185] Linking CXX executable networkb/networkb
ninja: build stopped: subcommand failed.

A StackOverflow answer says that adding -ldl to the linking flags fixes the problem, but I haven't tested it.

**Comment by wwiv** [comment]
Thanks for the issue.

What linux distro/version is this on? On debian10, centos7, and ubuntu 20.04 seems to work without adding a new flag, curious where it's needed?

Thanks.

Also what version of cmake?

**Comment by austinseraphin** [comment]
I use Slackware current, running cmake 3.16.2. I have compiled numerous programs on this machine, but I don't nkow if I've used cmake. As it happens I also have a server running Debian, and it does compile successfully. I will use that for now, but I still consider the issue open. Let me know if you need me to test anything. Once I get things working I can help add Slackware support.
