### ISSUE TITLE
Invalid data in board edit ACS causes error

### ISSUE THREAD

**Issue by robertstinnett** [wwivbbs/wwiv#1354]
Typing in invalid data (such as user.sl >- 10) causes an error.  Unfortunately, the error message and other data quickly clear from the screen.  The invalid data is not saved, but the error message is hard to see and the user may not know an error has occurred unless they pay close attention to the data.

**Comment by wwiv** [comment]
What build is this with?

Here's what I get with the latest in 5.6, it includes the parser error (which admittedly isn't great for this specific error) a tond a pause.

What do you get? Also where do you get it (this was editing the post SL for a sub). I my have missed a place using the new input_acs function.  

Thanks!

```
 WWIV ACS Help
 ACS expressions are of the form: attribute OP value
 attributes are: user.sl, user.dsl, user.ar, user.dar, user.name, etc
 OP (operators) are: >, <, >=. <=, ==, !=

 Expressions can be grouped with () and combined with || (or) or && (and)

 Examples: user.sl >= 20
           user.sl > 100 || user.ar == 'A'

 For full documentation see: http://docs.wwivbbs.org/en/latest/cfg/acs/

New Post ACS?
:user.sl >- 10
Can't reduce stack with < 3 elements.
More? [Y/n/c]
```

**Comment by wwiv** [comment]
hey @dmxrob I can't reproduce this, I pasted in what I saw in the BBS - anything you can do to help me see/find what you saw?

Thanks

**Comment by wwiv** [comment]
hey @dmxrob I can't reproduce this, I pasted in what I saw in the BBS - anything you can do to help me see/find what you saw?

**Comment by robertstinnett** [comment]
@wwiv Sorry for the delayed response - this got lost in my inbox!

So what you pasted above - is exactly what I get, but it flies past - perhaps because I have pagination turned off.

**Comment by wwiv** [comment]
Hmm.. The pause is a forced pause there not an automatic pagination (so the pagaination setting should not matter).  

Does it happen the same via telnet and local console?  Trying to understand why the pause would not show up.

**Comment by wwiv** [comment]
Hmm.. The pause is a forced pause there not an automatic pagination (so the pagaination setting should not matter).

Does it happen the same via telnet and local console? Trying to understand why the pause would not show up.

**Comment by wwiv** [comment]
Can't reproduce this, tried again a few ways. Closing.
