### ISSUE TITLE
WWIV Linux - More than 1 instance

### ISSUE THREAD

**Issue by cwstephenson71** [wwivbbs/wwiv#1357]
I'm not sure if this a issue, or maybe a fault of my own.  I have 4 instances (I think) set up, but when I get more than 1 user signing on, they get message saying 'busy' 

Thanks for any help

**Comment by wwiv** [comment]
How do you connect to teh bbs? using wwivd?
What does the wwivd config look like? Can you paste a screen shot of wwivconfig's matrix page?

**Comment by wwiv** [comment]
Here's an example of mine from a test setup:
```
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒┌───────────────────────────────────────────────── Matrix Config: WWIV ┐▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│            Key: W                                                    │▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│           Name: WWIV                                                 │▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│    Description: WWIV                                                 │▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│    Working Dir: U:\wwiv\                                             │▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│ Telnet Command: bbs -XT -H@H -N@N                                    │▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│    SSH Command: bbs -XS -H@H -N@N                                    │▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│   Require Ansi: No                                                   │▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│     Start Node: 2                                                    │▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│       End Node: 4                                                    │▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│     Local Node: 1                                                    │▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒└──────────────────────────────────────────────────────────────────────┘▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒

```

**Comment by cwstephenson71** [comment]
Mine is exactly the same except: Start Node: 1
                                                      End Node: 4
                                                      Local Node: 4

The 'Local Node" was set to 1, same issue, so i tried 4.  
I also disabled in the wwiv.ini where it says 'make busy when sysop logs on' or something like that.

**Comment by wwiv** [comment]
where do you see busy?  

Can you run wwivd with --v=2 

i.e. 

```
./wwiv --v=2
```


Then  get a couple of folks to try at the same time in IRC, you can telnet into one node to keep it busy then ping us on IRC

afterwards, paste in what is in the log from wwivd

**Comment by cwstephenson71** [comment]
If someone is logged on,and someone else tries to log on (telnet or ssh) it says busy.  Ok, I'll see you on IRC in about 10. thank you!

**Comment by wwiv** [comment]
sounds good - what's the bbs telnet address?

**Comment by cwstephenson71** [comment]
Sorry for not getting back to you sooner. having some 'health issues' right now. SOON as I'm feeling better, I'll message you on IRC.  My BBS address is frontierbbs.net:2333 (it's in the Telnet BBS guide bbs list/syncterm list 
as the "WWIV Frontier BBS"

Thank you

**Comment by MorgulWWIV** [comment]
So, I may have seen this same issue.  I logged onto my BBS from my desktop on node 2.  When I went into the Transfer area, the system hung up and I had to close the window.  I tried reconnecting, and it gives me a busy error.  WFC on the BBS computer shows me still logged in on node 2.  I tried deleting the nodeinuse.2 file, but that didn't help.  I ended up sshing into the BBS computer from my desktop and issuing the command ./bbs -m -n2.  That cleared me off of node 2, but I'm still getting a busy signal when trying to telnet in.  WFC is showing node 2 status as 'offline'.   Not sure what to do next.

**Comment by wwiv** [comment]
Run wwivd with --v=2, and let's see from the logs what's happening?

I think then you may be having the autoblocker go wild, let's get this debugged so we know for sure and can fix

**Comment by wwiv** [comment]
The BUSY comes from wwivd BTW, not from the bbs

**Comment by wwiv** [comment]
Actually you may not even need --v=2, in almost every case (but 1) it's logged at INFO, which means why wwivd sent a BUSY is written to wwivd.log

**Comment by MorgulWWIV** [comment]
Looked in wwivd.log, nothing unusual found.  Tried logging in from the desktop at 9:45 am, it was refused.  The wwivd.log file was not updated from that attempt, so not sure if it's going to tell you anything.  Here's what it's showing for today.  9:07 am is when I rebooted the system, I believe.  The SIGNIT error has been there from the beginning, it's on every log entry since I brought the BBS up.

2021-01-29 09:04:02,914 ERROR Unable to install signal handler for SIGINT
2021-01-29 09:04:02,914 INFO  Listening to TELNET on port: 2323
2021-01-29 09:04:02,915 INFO  Listening to HTTP on port: 8081
2021-01-29 09:07:06,324 INFO  wwivd - WWIV Daemon.
2021-01-29 09:07:06,359 INFO  Loaded BBSES:
{[W] WWIV (WWIV)}

2021-01-29 09:07:06,359 ERROR Unable to install signal handler for SIGINT
2021-01-29 09:07:06,362 INFO  Listening to TELNET on port: 2323
2021-01-29 09:07:06,363 INFO  Listening to HTTP on port: 8081

**Comment by wwiv** [comment]
when refused, did you get "BUSY"?

**Comment by wwiv** [comment]
Maybe you are getting hte one place we don't log INFO.

try this

cd data/
mv badip.txt badip.saved

then restart wwivd.

if that fixes it, it's a blocking thing. We don't log blocked IPs to INFO since it was spamming the logs a lot.

**Comment by wwiv** [comment]
Maybe we should do:

```
BUSY (Blocked)
BUSY (Concurrent)
BUSY (Unavailable)
```

or something like that?  May be helpful for debugging this since we now have two cases?

**Comment by MorgulWWIV** [comment]
Yes, I get a BUSY when trying to connect.

I went into data and looked at badip.txt, and it's got a line in there saying "192.168.1.8 # Autoblocked by wwivd on: 2021-01-29T08:28:57"

That being the IP address of my desktop computer, and the time when this started.

Renamed the file, restarted wwivd, and that took care of it.  Don't know why I was autoblocked.  That session had locked up on me and I had to kill the telnet session, so maybe wwivd got an attitude with me.

**Comment by MorgulWWIV** [comment]
I'm a fan of logging as much as you can to help debugging!

**Comment by wwiv** [comment]
Alright, I have a bug open to improve autoblocking... I think I'll work off of that one.

For the logging, the "BUSY (xxx)" was actually not logging, but the socket response.  I think in this case the debuggability trumps fidelity to the old ways (so I'll add more info to BUSY".

Thanks for the debugging help on this!  Now @cwstephenson71 knows what to do (delete badip.txt)
