### ISSUE TITLE
Improve autoblocker in wwivd

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1359]
```
I just got myself blocked for attempting to connect too frequent to Kruptions' bbs
7:41 AM maybe our autoblocker is too aggressive
7:42 AM <&GranitePenguin> Rock hah
8:00 AM is the autoblocker permanent, or does it release after a while?
8:01 AM there probably is something weird in it, because I've had my IP blocked for my own BBS before
8:02 AM unfortunately, circumstances are anecdotal at best
8:12 AM <&rushfan> Rushfan it's unfortunately permanent at the moment
8:12 AM since we just append to badip.txt
8:12 AM may need to rethink that, and not autoblock there but keep those for sysop written out block lists
8:12 AM and make sure (I don't remember) it can handle cidr notation
8:13 AM i.e. 75.75.75/24
8:13 AM and then autoblock for a period of time, so need a new file for that, and also once that has date + ip
8:13 AM maybe a 5.7 thing
```

**Comment by wwiv** [comment]
Here's what I'm thinking so far:

* Split the notion of blocklist (badip.txt) with the autoblocking support.
* Autoblocked IP addresses should likely be for either X hours or X days, not permanent
* Either keep the autoblocked list in memory only, or checkpoint save it every hour or so if there's been changes.  We can load it on start.
* The values for X (how long to block) can be configurable.
* Open question: Should we keep track of how many times an IP has been blocked and maybe block it longer periods of time if it's a repeat offender? Could be a future enhancement.  Right now our autoblocking seems too strict and is likely costing callers.

**Comment by granitepenguin** [comment]
My gut feeling is to replicate (loosely) the model that fail2ban uses.  Granted, it's using iptables FW rules to drop incoming, but the important part is it does basically 3 things:
1 add a block based on X number of attempts in Y timeframe that expires after Z minutes (eg, 3 tries in 1 minute bans for 15 minutes)
2 increases the length of the ban for repeat offenders (1st 15min, 2nd 1 hour, 3rd 1 day)
3 adds a permablock for repeat offenders that don't get the hint (eg, this IP is in the ban log 3 times, ban it for good)

That blocks the script kiddies that will move on after banning, but will allow unbanning for the occasional oops.
a json file for the IPs with various stats shouldn't be terrible to manage?

**Comment by wwiv** [comment]
shouldn't be too bad. My badip.txt is ~1M in size, so triple that for JSON and extra data, assuming we ban permanently less should keep it ~10M for most cases over a long haul. That seems reasonable.

**Comment by wwiv** [comment]
irony is that when I ran wwiv the first time, I had a 10M HDD

**Comment by wwiv** [comment]
As part of this, we'll move the following out of blocking page into wwivd page:
* fake mailer mode (boolean)
* max concurrent sessions (int)

Then we can change blocking to just be blocking of the form:

Enabling blocking on X connections within Y:
Blocking durations: [time 1] [time 2] [time 3]:
time is of the form (int + char) where char is the time and one of (s)econd, (m)inute, (h)our, (d)ay 

Then we can follow the rules pretty easily.

Under the covers, we'll create anew json file in data/

wwivd.autoblock.json


Open question, should we shard the autoblock.json file by position where it is?

**Comment by wwiv** [comment]
Here's the mockup in WWIVD.  how does this look?

```
┌──────────────────────────────────────────────── Blocking Configuration ┐
│              Use goodip.txt? Yes                                       │
│               Use badip.txt? No                                        │
│               Use CC Server? No                                        │
│               DNS CC Server: zz.countries.nerd.dk                      │
│           Blocked Countries: [Press Enter to Edit]                     │
│                                                                        │
│        Enable Auto Blocking? No                                        │
│  # connects needed to block: 3             Within seconds: 30          │
│            Blocking Time #1: 15m    #2: 1h     #3: 1d     #4: 30d      │
└────────────────────────────────────────────────────────────────────────┘
```
