### ISSUE TITLE
NET.INI and ACT.INI missing from distribution .zip

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#136]
The NET.INI and ACT.INI that goes with the WINS binaries which are included in the WWIV5 zip is missing a SAMPLE NET.INI which is needed for WWIVNet configuration.

There are samples in \wwiv\wins\admin

**Comment by W7PEA** [comment]
You can use the sample from here:
https://github.com/wwivbbs/wwiv/wiki/wwivnetwin
