### ISSUE TITLE
Macro Editor in Linux WWIV not recognizing Ctrl-Z

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1360]
I'm running 5.6.0.3384 in Linux.  Logged onto the board, was playing around with my defaults and decided to make a macro.  Go in, make a macro, no problem....until I hit Ctrl-Z to finish.  I get a message that says "INFO: Unknown Key:407.

And right now, I've got not way to get out of it.  I'm logged on via console, and can't even F-5 myself.

**Comment by MorgulWWIV** [comment]
As a follow up, I telnetted in to the BBS and didn't have a problem.  It is just an issue when I was logged on from the WFC screen on linux.  So not really a big deal.

**Comment by wwiv** [comment]
Hmm, strange what terminal are you in? I can't reproduce this on the BBS VM via ssh into the debian VM nor on WSL on Win10 in bash.

**Comment by wwiv** [comment]
407 looks like curses KEY_SSAVE. No idea what that means.

**Comment by MorgulWWIV** [comment]
I'm not using a terminal, I'm using the local logon from the Pi itself.  Remotely from a terminal program, I don't have the problem.  It's only when I do it local.
"Doctor, it hurts when I do this" "Then don't do it!" 
:)

**Comment by wwiv** [comment]
Got it -

I'll put this into the "ideally we'd have a termcap type file that maps curses input to wwiv expected input to handle things like this, and backspace and delete and a few other random keys that map uniquely across distributions"
