### ISSUE TITLE
Add telnet or rlogin support to wwivd.

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1361]
The idea is instead of just spawning a binary and passing the socket to it, open a socket to another server and proxy the connection.

This would let Mark's OS/2 hosted DOS bbs work.

**Comment by wwiv** [comment]
@MarkHofmann11 FYI

**Comment by MarkHofmann11** [comment]
Awesome, thanks!!!  Would love to reverse what fronts the connections to my
BBS(s).  And have the xfers work again.  Appreciate it!
