### ISSUE TITLE
backspace char looses color code in fsed

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1364]
if you type:
```
^C1This is^H^His
```

The 'is' will be in color 0.

**Comment by MorgulWWIV** [comment]
I see this often.  Backspacing or hitting enter to start a new line loses the color code.  Having to change the color code and be interesting in the middle of a line, because sometimes as the line wraps on the screen, you lose the Control-P and just have the number starting the next line.

**Comment by wwiv** [comment]
@MorgulCian FYI
