### ISSUE TITLE
Files Transfer Issue

### ISSUE THREAD

**Issue by Kmdragon** [wwivbbs/wwiv#1365]
I have a clean install on Windows 10.  All Windows updates are installed.  Clean install of WWIV 5.6.  I created 16 directories using //DE.  I ran //uploadall to load them all into the system.  Then ran //readidz.  This seems to have worked until I log off and log back on.  Then the only area I can see is "Sysop".  If I try to list the files is locks up my terminal and I have to close the console on the BBS machine.  If I delete all of the directories and do it over I get the same results.    

There is a pop-up that is connected to the console, for the node I am logged into, that says there was a 255 error.  It doesn't seem to always state the 255 error in the toaster box, sometimes it is just a generic popup.  But it is always in the log file.  I will keep digging and see if I can provide anymore information.

I have already added myself to the admin group in Windows10, and made sure that nothing is read only.  It almost acts like I don't have the right DSL except that it locks up my terminal.  I tried to log on remotely and locally and have the same issue.  

![PXL_20210131_231624681](https://user-images.githubusercontent.com/78325834/106401335-3012cb80-63e9-11eb-9c71-cd8349088f6c.jpg)
![PXL_20210131_231525860](https://user-images.githubusercontent.com/78325834/106401340-3acd6080-63e9-11eb-9d1f-cdc44ea4146e.jpg)
![PXL_20210131_231542229](https://user-images.githubusercontent.com/78325834/106401348-44ef5f00-63e9-11eb-852e-d5d3f765d200.jpg)
![PXL_20210131_232124999](https://user-images.githubusercontent.com/78325834/106401350-4882e600-63e9-11eb-96bc-5f4cde4062fc.jpg)

**Comment by Kmdragon** [comment]
It also does not appear to affect anyone else trying to log in as I can re-connect and be just fine until I try to list the files again.

**Comment by wwiv** [comment]
Can you attach or email me your data/dirs.json?

**Comment by Kmdragon** [comment]
Incoming...  The only thing I noticed off the top was the mask is different?

**Comment by Kmdragon** [comment]
Fresh off the presses...

**Comment by wwiv** [comment]
Hmm the file attach to github doesn't work over email. email it to me rushfan at wwivbbs.org  or attach it using the webpage and you can drag and drop a file into the issue

**Comment by Kmdragon** [comment]
[dirs.json.txt](https://github.com/wwivbbs/wwiv/files/5901819/dirs.json.txt)

**Comment by Kmdragon** [comment]
I have the board down right now.  I tried to delete all the directories and start over.  Still had the same issue.  So I am am running full  memory/disk diagnostics, and full virus/rootkit scan just to make sure it's not something simple like that.

**Comment by wwiv** [comment]
None of them are part of any conference. Go add them all to conference A (or whatever the first conference you have is)

**Comment by Kmdragon** [comment]
Ok, so quick update.  I had an issue with the laptop and it is now defunct.  I loaded everything from backup onto a virtual Win10 machine and I am back up.  I copied some of the files from backup into the sysop directory and so far, so good.  I will test some more when I am off work.

**Comment by wwiv** [comment]
Thanks, I could reproduce failure with your dirs, and adding conf's to them fixed it.  I'll close this out
