### ISSUE TITLE
Forcing a network call from WFC using / doesn't work

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1366]
Running the linux version of WWIV.  I can't force a network call from wfc using the / key.  It asks for a node number, and I put 1, It flashes the command at the top of the screen (picture attached), then shows the network -help listing the varous commands and options, then goes back to WFC.
The network.log says:
2021-01-31 18:27:22,827 START network [5.6.1.development] for network: wwivnet
2021-01-31 18:27:22,828 ERROR Invalid node number: '0' specified.

Regular callouts from wwivd in the background work fine, I just can't force one from WFC.

![20210131_183531](https://user-images.githubusercontent.com/74803711/106401716-a0264f00-63f3-11eb-892d-ec8674db5cb9.jpg)

**Comment by wwiv** [comment]
aha, I suspect that's because / no longer works on UNIX (since otherwise I couldn't ever let a positional argument work for absolute path names.
