### ISSUE TITLE
Increase default # of subs/dirs

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1367]
right now it's set to 64.

Memory really isn't a problem anymore for this nor is file size (each increase in 32 is 33 bytes of storage per user). 

Let's increase it up 256 to start with, and don't let it go below that.  That'll get rid of the cases where people bump up against it now-a-days. 

Another option is to make it 1024 by default and make a wwivutil advanced command to set it higher.  Doubting that folks will ever need to.  Thoughts?

**Comment by dunnaway** [comment]
Sounds good to me
