### ISSUE TITLE
Minor document correction

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1369]
In the online documents, the WFC section ( http://docs.wwivbbs.org/en/wwiv56/wfc/ ), it mentions that F7 increases the users time online by 5 minutes, and F8 decreases it.  In actuality, it's the opposite.  F7 decreases the time by 5 min and F8 increases it by 5 min.

Minor detail.  I only caught it because I had to figure out how to give myself more time on my own board because it somehow ran out of time (think I had a node stuck open with me logged on.)

**Comment by wwiv** [comment]
Fixed.  Will be pushed to docs soon
