### ISSUE TITLE
Transfer Section - Sysop directory sometimes appears in conferences it's not a part of

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1371]
This is a hard one to replicate, sometime it happens, sometimes it doesn't.

Background - I have my Sysop directory, currently empty, in the [GEN] General Files conference.  That's the only conference it's in.

I'll be in the transfer section, in a conference going between the directories.  I noticed sometimes that when I get to the end of the conference and hit the > key, instead of taking me back to the 1st directory in the conference, it takes me to the SysOp directory.  However, there is no number in the [ ] at the beginning of the line.  Instead of "[0] Sysop Directory", it says "[ ] Sysop Directory".  I haven't encountered it when going backwards in the conference (using the < key).  Several times, if I try to do * to look at the conference, the instance hangs up and I have to kill the process.
Difficult to reproduce, but I'll keep looking into it and see if I see a pattern that might help.

**Comment by MorgulWWIV** [comment]
So much for "hard to replicate"

I went in and fiddled with my transfer section.  In every conference, when I'm on the last directory in that conference and press '>', it goes to a SysOp directory, and if I try to do a '*', it locks up.  It doesn't do it if I'm going from the first directory to the last by hitting '<', only the other way, using '>'.  And only from last directory to first directory.

**Comment by wwiv** [comment]
Can you email (to my wwivbbs.org address) your dirs.json please?

**Comment by MorgulWWIV** [comment]
done
