### ISSUE TITLE
Moving files in the transfer section while logged on causes bbs to crash

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1374]
I'd noticed that if I tried to move a file while logged in via a terminal program, I would get disconnected.  I thought that might be some wierd interaction with my terminal program.  However, this morning I logged on from the WFC screen on the computer itself, and when I tried to move a file from one transfer directory to another, the program crashed and dropped me back to the Linux prompt.
It shows an error "Caught std:out_of_range on pos: 19", then "FATAL Terminating in debug build"

**Comment by wwiv** [comment]
Is there a stack trace too displayed with that error?

**Comment by wwiv** [comment]
nevermind, I see it. When it's looking for the new file area, it's updating our "current file area"
