### ISSUE TITLE
/s not working in fsed

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1378]
/s works fine in the internal editor, but doesn't work (for me, at least) in the FSED.  I don't know if it's supposed to or not.  If it's not, it'd be nice to have the ability.

**Comment by granitepenguin** [comment]
It's not supposed to.  None of the / commands do, IIRC; they are all in the ESC menu

**Comment by wwiv** [comment]
That's correct, the internal fsed doesn't support slash commands.

**Comment by ericpareja** [comment]
Adding /s and other / commands (I use /esy a lot) would make it work like WWIVedit.

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/1ccb243c25bd1a8bf7cc8a0532dcd1120ef05341
