### ISSUE TITLE
Control-T and Control-Y (Time and Pause toggle) not working in many parts of the board

### ISSUE THREAD

**Issue by robertstinnett** [wwivbbs/wwiv#1382]
So just stumbled upon this one, but Ctrl-T and Ctrl-Y doesn't appear to be working in many parts of the board -- like main menu, message forums, BBS listings, etc.  The ONLY place I've found so far where it does work is in Defaults.  Still navigating the code, so not sure how the overlays come into play that provide that functionality so thought I'd post it here.

Not groundbreaking, but still... :-)

**Comment by wwiv** [comment]
ahh, I think its cause we use the new bgetch_event code that was added in 4.3. This handles arrow keys and such. I bet it doesn't handle those two.

**Comment by wwiv** [comment]
Think I found a fix that should work everywhere, we're early enough into 5.7 that if it causes issues in a couple of places we can call bin.oskey(false) around those places.

**Comment by robertstinnett** [comment]
Just downloaded the latest build, and it appears to be working!  Awesome!

Thanks,
Rob
