### ISSUE TITLE
file_id.diz auto-description case detection

### ISSUE THREAD

**Issue by uriel1998** [wwivbbs/wwiv#1384]
Works like a charm if it's FILE_ID.DIZ, and is missed if the filename is file_id.diz

**Comment by wwiv** [comment]
What's your extract command in archivers? The -C option should extract filename ignoring the case.

**Comment by uriel1998** [comment]
Upon attempting to reproduce the issue, it appears that the problem existed between the user and keyboard.  (The file_id.diz had a blank line for the first line, and I missed that difference.)  I apologize!
