### ISSUE TITLE
Users mentioning that the Main Menu is missing unless using ?

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1385]
Seems to be a glitch. Windows 10. w32 5.7.0.3420

Almost as though users have all been forced to use Xpert mode?

Selecting X does not revert.

**Comment by BloodStoneBBS** [comment]
Correction, selecting X does seem to work but why would all users suddenly change to Xpert mode? Even a brand new user was in Xpert mode.

**Comment by wwiv** [comment]
I can't reproduce this.   I just create a new user and logged in and theuser account wasn't in expert mode

**Comment by wwiv** [comment]
In wwivconfig -> Menus -wwiv - main.

What is set for "Display Help".

Here's what I have:
```
  Display Help: User Choice
```

**Comment by cwstephenson71** [comment]
I'm running WWIV/Linux (Latest build from last Friday). I've had that issue as well for over a month. I thought it was because of my custom ANSI menu(s). It only does occasionally when returning to the main menu while doing certain tasks from the Main Menu.

**Comment by wwiv** [comment]
Checkout what the menu shows.  It *used* to be display help first time only.  What do you see?

**Comment by wwiv** [comment]
In the JSON file look for : ```"help_type": "user_choice",```

I fixed the default menu a while back, maybe it didn't make it to your system?

**Comment by BloodStoneBBS** [comment]
This was set to never on all menus!  No wonder!?!

Will have the user try again.

**Comment by wwiv** [comment]
Ok thanks - that was a bug in some earlier menus, I fixed them but likely the updated ones never made it into your bbs.  Glad that was it
