### ISSUE TITLE
Easier validation of new users

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1388]
We've got the Auto-validation keys set up, can we do something where when you're reading a new users email, you can use those to automatically update them to the proper SL/DSL/AR/DAR/etc settings?

Right now, you hit 'V' and you manually enter each of the settings.  Being able to use the Auto-val settings to do it in one keystroke would be good.

**Comment by MorgulWWIV** [comment]
Added afterthought - since Autoval is stored in a .json file, maybe have a field for the SL Name.  i.e. "Regular User", "Visiting SysOp", "Donating User", etc mainly just to help keep track of which one you're using.

**Comment by wwiv** [comment]
great idea! I was also wondering how to know which one to use :)  I never used to use more than 2 in my youth
