### ISSUE TITLE
Network0.exe -? has no help output and runs the program

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#139]
This is what you get, the program runs.

```
C:\wwiv>network0.exe -?
net38RC3.0ƒ: Protocols Available:

!! No external transfer protocols found!
=> Using internal Y-modem...

Waiting for NET_RESP... <HANGUP>
No connection.  Hanging up.
```

Help on parameters is expected

**Comment by wwiv** [comment]
Added help in beta5
There's no way to change the fact that it runs the program since it's trying to receive via a modem, and wwiv 4.3 and earlier expect that.
