### ISSUE TITLE
FTN network data in net.log

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1393]
Would it be possible to write network connection data for FTNs in net log, like WWIV networks?

**Comment by wwiv** [comment]
Not without changing the file format. the ftn addresses just don't fit there.  We could just have a fake address like 32676 or something, but that's not super useful

**Comment by MorgulWWIV** [comment]
Personally, I'd be ok with a fake node number like @32676.Fidonet or @32676.FSXNet.  That at least lets me know at a glance what traffic I've had on those networks.  The specific node it came from is, to me at least, irrelevent, since I basically only connect to one node each.

**Comment by MarkHofmann11** [comment]
Not sure if Frank Reid is on this thread, but I use his Lastnet program as
one of the logon events.  It somehow pulls the FTN network information and
includes it in the WWIV* network connections.  I looked around to see if I
had the source code and can't find it, but would like to get that if he
still has it.

**Comment by fcreid** [comment]
I am and here you go, Mark. Sorry about that delay. I’m embarrassed even to look at that code, as I now know how terrible a programmer I was/remain! 😊 No idea whether it still builds… I suspect I was most recently building on BorlandC 5.X.
 
Lemme know if you need anything else!

Frank

**Comment by MarkHofmann11** [comment]
To me, you are an excellent programmer!  :)  Did you attach it to the thread?  I don't see it.  Maybe this doesn't allow attachments.  I would say email it, but I think Google won't allow that either.  Do you have google drive or a webserver I could download it from?

**Comment by fcreid** [comment]
I guess it removed it. ☹
 
See if https://nobodyguess.com/lastnet.cpp works.

**Comment by MarkHofmann11** [comment]
That worked.  I just cut and pasted it to notepad++ and saved it - thanks!!!  I wonder if it would compile with Borland C - the old DOS version I use for my BBS.  Will have to give it a shot at some point soon.  I have used lastnet forever it seems!  Still being used over here to this day.  I still remember mailing you the registration for it.  I was probably only 20 years old or something at the time.

**Comment by fcreid** [comment]
It should… it does look for the headers in vardec.h and net.h from a 4.X source if you can copy those from there. I need to tune out the real world and spend time learning the great things Rob’s done, including the SDK. It should be much easier today!
 
P.S. You’re only as old as you feel! 😊

**Comment by MorgulWWIV** [comment]
> 
> It should… it does look for the headers in vardec.h and net.h from a 4.X source if you can copy those from there. I need to tune out the real world and spend time learning the great things Rob’s done, including the SDK. It should be much easier today! P.S. You’re only as old as you feel! 😊 

Coding's come a long way since our day, Frank.  I'm a bit lost looking at the WWIV source code these days.  I wrote the code to print the last net connections similar to the last users.  It was kludgy, but it worked.  Rushfan took it, cleaned it up and streamlined it, and the code is now a work of art.  He's good! (and patient with me and my questions....)

-Morgul

**Comment by wwiv** [comment]
Eh you ask good questions :-)

but yes C++ has certainly evolved tremendously since back when 4.30 was new and shiny.
