### ISSUE TITLE
System crash when setting Transfer QSCAN

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1394]
When setting transfer qscan directories. if you hit the { or } to change conferences, the bbs crashes.  It's done it to me when I telnet in, but I tried it today logging in from WFC, and it did the same thing.  The only message that appears is "free(): invalid pointer"

**Comment by wwiv** [comment]
I don't see { } in the transfer qscan directory. 

I did T then 1 from the xfer menu, and see a different crash.

Screenshot?
