### ISSUE TITLE
Your user info blank on local

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1396]
OS: Linux (debian 10)
WWIV: 5.7.0.3435

when using "Y" to look at my user info; on local, none of the variables are populated

```
[3] [WWIVnet General Chat]: Y
Your User Information


Your name      :  #
Phone number   :
Mail Waiting   :
Security Level :
Transfer SL    :

Date Last On   :
Times on       :
On today       :
Messages posted:
E-mail sent    :
Time spent on  :  Minutes
Uploads        : k in  files
Downloads      : k in  files
Transfer Ratio :

|{pause}
```
Also note that the pause didn't work; it just displayed {pause}

When I ssh in via SyncTERM, it works as expected

```
[3] [WWIVnet General Chat]: Y
Your User Information


Your name      : GRANITEPENGUIN #1
Phone number   : XXX-XXX-XXXX
Mail Waiting   : 0
Security Level : 255
Transfer SL    : 255

Date Last On   : 02/24/21
Times on       : 3994
On today       : 9
Messages posted: 860
E-mail sent    : 22
Time spent on  : 119352 Minutes
Uploads        : 115k in 2 files
Downloads      : 643k in 10 files
Transfer Ratio : 99.998

More? [Y/n/c] 
```

**Comment by granitepenguin** [comment]
This also appears to be related to screen somehow.  If I try it local from a direct terminal, it works fine.  I'm only seeing this while running WFC inside screen.  tmux does not have a problem, either; that works fine.

**Comment by wwiv** [comment]
Hmm, can't reproduce with screen on WSL

**Comment by wwiv** [comment]
I still can't reproduce it with yourinfo.msg in gfiles and without on my production bbs instance using screen coming from my mac terminal via ssh to bbs (debian10)

Do you have this in your log or not?
```
2021-02-25 15:28:14,872 WARN  Legacy yourinfo used, please add yourinfo.msg to gfiles directory.
```

**Comment by granitepenguin** [comment]
I do not have that log entry, and I do have yourinfo.msg

```
wwiv@beaglebbs:~/gfiles$ cat yourinfo.msg
|#4Your User Information|[K|#0


|#9Your name      : |#2|@N |#9#|#2|@#
|#9Phone number   : |#2|@p
|#9Mail Waiting   : |#2|@M
|#9Security Level : |#2|@S
|#9Transfer SL    : |#2|@d

|#9Date Last On   : |#2|@L
|#9Times on       : |#2|@l
|#9On today       : |#2|@O
|#9Messages posted: |#2|@m
|#9E-mail sent    : |#2|@E
|#9Time spent on  : |#2|@o |#9Minutes
|#9Uploads        : |#2|@K|#9k in |#2|@U |#9files
|#9Downloads      : |#2|@k|#9k in |#2|@D |#9files
|#9Transfer Ratio : |#2|@z

|{pause}
```
I'm also not seeing this behavior anymore.  I generally use iTerm2, and when I tested with the Mac Terminal, it worked as expected.  When I went back to iTerm2, it's not doing it anymore.

There's some kind of gremlin that got excised somewhere.  I think we can close this for now and revisit if it resurfaces.

**Comment by wwiv** [comment]
Sounds good, certainly strange.  If you get it again, strace the process and let's see what's being read from the file and written. It's seems to be all '@' chars were missing from the file when reading from disk.
