### ISSUE TITLE
When "Real Name" is selected for a board, the name is in all caps

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1397]
I noticed this after I posted on a Fido board, that my name showed up in all caps.  I verified it on a local non-networked sub as well.  If the sub is set to real name, the name is done in all caps.  Can we change that to a properized name?

**Comment by wwiv** [comment]
By any chance is the real name field all caps (in user editor)?

**Comment by wwiv** [comment]
Looked like the prompt to create the sysop account was UPPER case only, fix it in useredit and then it should be fine from there on out, every other account uses proper case when entering it by default

**Comment by MorgulWWIV** [comment]
That would be it.  I went and checked, and the SysOp account real name was all caps, the other accounts weren't.  Problem solved!
