### ISSUE TITLE
Gfiles losing color codes at pause

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1398]
If you've got a file in your gfile section that's in color, if it's long enough that a pause interrupts the display, when you continue. the color disappears.

You can get it back by putting a pipe code at the beginning of the line where the break happens, but the break is causing the loss of the color code that you might have set several lines before.

**Comment by wwiv** [comment]
Hmm, Sounds like pausescr() should try to save/restore the color.  This won't work everywhere, but may be close enough since we set the color when we change it.

**Comment by wwiv** [comment]
Looks like it's already trying to do that - can you send me the gfile text fiel  you are using?

**Comment by MorgulWWIV** [comment]
Just emailed one to you
