### ISSUE TITLE
extracting email or messsages to a file only creates 0 byte file

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1404]
Trying to extract a message from a message sub or email using 'E' only creates an empty file with the name you want.  i.e. I go to extract a message and tell it I want to save it as testex.msg.  WWIV doesn't give me an error, and it seems like it completed it, but when I go look for the file, I have a textex.msg, but it's 0 bytes and empty.

**Comment by wwiv** [comment]
I  just did a text from a sub an it worked right.

Steps were: (Read message).
(E)xtract
(G)files (I also tried temp)
Enter Name
Look at file.


What steps did you try

**Comment by MorgulWWIV** [comment]
Same steps.  The file is created, but it's an empty 0 byte length file.  No content in it,

Maybe another ARM issue?

**Comment by wwiv** [comment]
Yes, strangely enough it reproduces on my RPI4, but not Debian10 x86 nor Windows.

**Comment by MorgulWWIV** [comment]
Well, it's not my imagination, at least!

**Comment by wwiv** [comment]
and it's working again with my most recent changes -- no idea why since nothing I changed should have impacted that.

**Comment by wwiv** [comment]
Not reproducible anymore....
