### ISSUE TITLE
Feature request for colored/non colored quoting. 

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1407]
I got a complaint from someone on fidonet about the message quoting where we have pipe color quoting, but not all bbs packages do this well. Could we have a toggle for non colored quoting by message base, so if I am on a fidonet echo I could have non colored quoting.

**Comment by wwiv** [comment]
We have options in network settings for FTN networks to convert wwiv pipe codes into standard ones, would an option to strip pipe codes (like the existing two conversion ones (convert pipe, convert heart) be the right approach?  

If systems's there can't deal with pipe colors, ideally we strip them.

**Comment by mmunson** [comment]
I am ok with receiving the pipe and heart codes, but some systems and system operators have fits. I was thinking of an option of do not send color codes for particular message bases as an example.

**Comment by MorgulWWIV** [comment]
Fidonet sysops have been whining about that for 30 years.  Some things never change.

A toggle to strip color would be good.  Per sub is best I think, but would be more work to program, I'm sure. Per network would  work.

**Comment by wwiv** [comment]
if convert heart code and convert wwiv pipe codes are both off (in wwivconfig), then we strip both.

**Comment by wwiv** [comment]
The usecase is to turn it off by default, but let things like the BBS ADS sub use them, (for example)

**Comment by wwiv** [comment]
If both is false, it is actually not stripping the wwiv pipe codes as expected, I'll add a setting for that at the network level

**Comment by wwiv** [comment]
This was fixed in [Add new setting to allow outbound pipe codes for ftn messages.](https://github.com/wwiv/wwiv/commit/b4b0dd0e7019685c0f6ee0c8126d26d485ef45f1)
