### ISSUE TITLE
BBS Node Number, Name, and Location for FTNs to display in messages

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1409]
In the message headers, we show the BBS node number, name and location for WWIv networks, but not for FTNs.  It'd be nice to have that information displayed as well for FTNs

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/b289f1bbfd3fe2eaa620a8465c55835c592ef77d
