### ISSUE TITLE
Let ini files support multi-line strings like TOML does

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1411]
This will be useful for the strings/language support.

Here's what we have today:
```
key = value
```

What I'd like is also:
```
key = """
value1
value2
value3

; or this:

key2 = """
value1
value2
value3"""
```

The result should be:
 key: "value1\nvalue2\nvalue3\n"
 key2: "value1\nvalue2\nvalue3"

**Comment by wwiv** [comment]
Another option could just be TOML (https://toml.io/en/) for the language files vs. our INI file code.   The big difference is TOML needs quotes around strings, we don't.  That could be a plus for strings through if you wanted trailing spaces.

**Comment by granitepenguin** [comment]
you already support json, why not just migrate to it?

when you say "This will be useful for the strings/language support." what aspects of it are you talking about (ie, what are specific examples of what you are trying to fix?)

**Comment by wwiv** [comment]
this is to let better customizable strings support without modding the BBS.

Example
```
LOGON_NN = NN:
LOGON_PW = PW:
LOGON_USER_NOTFOUND = """
|#6Too many logon attempts!!

|#9Would you like to leave Feedback to |#1|{bbs.sysopname}?
"""
```

**Comment by wwiv** [comment]
Without embedding the newlines in here, we could use the pipe code NL

```
LOGON_USER_NOTFOUND = |#6Too many logon attempts!!|[2N|#9Would you like to leave Feedback to |#1|{bbs.sysopname}?
```

Or in JSON (not using INI)
```
{ "str": 
  { "LOGON_USER_NOTFOUND" : "|#6Too many logon attempts!!|[2N|#9Would you like to leave Feedback to |#1|{bbs.sysopname}?" },
...
}
```
