### ISSUE TITLE
Toggle request - ability to enable/disable system.msg, logon.msg at new user login and display newuinst.msg

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1412]
Trying to bring new users to the BBS, I was thinking that unlike the good old days, there's going to be people that don't have a clue what a BBS is about.
I've written a basic set of instructions to guide them through the creation of a new user account, called 'newuinst.msg'

I'd like the ability to print that to the user at the beginning of the new user process, right after newuser.msg and logon.msg print.  

And I'd like to be able to toggle all three on/off in the new system toggles section of wwivconfig.  Default to 'on' for logon and newuser, and off to newuinst, so as to not change anyone elses settings unless they actively want to.

**Comment by MorgulWWIV** [comment]
Just so you can see the instruction file I've created.

[newuinst.txt](https://github.com/wwivbbs/wwiv/files/6119072/newuinst.txt)

**Comment by wwiv** [comment]
Looks like the bbs displays system.msg and then newuser.msg.  Why isn't this text in newuser.msg?

Then the question of should system.msg be displayed before newuser.msg.

Or am I missing something?

**Comment by MorgulWWIV** [comment]
Sorry, may have gotten the filenames mixed up.  I went with a different file because newuser.msg gets displayed elsewhere as well, I believe.  My original intention had been to use newuser.msg, but I only wanted it displayed at new user logon, right before account creation began.

It's been a bit since I looked at that, let me doublecheck that I'm not requesting something unnecessary.

**Comment by MorgulWWIV** [comment]
Well, maybe not.  I only found one other use of NEWUSER_NOEXT, that's in lilo.cpp for a new user.  Maybe I got something confused.  Let's shelve this suggestion for now, and if I figure out what my thought process was when I first came up with this weeks ago, maybe we can revisit it.

**Comment by wwiv** [comment]
sounds good we can reopen if needed
