### ISSUE TITLE
System name and location not showing up for your own system

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1419]
I noticed this tonight that the BBS Name and Location don't show up when you look at a message posted from your own system.  This happens on both wwivnet and FTN.  I know with FTN, it shows up s being posted from @1, and can't pull that from a node list - maybe have it recognize @1 on a ftn and put your own system information in?

**Comment by MorgulWWIV** [comment]
Also, and this is a very minor detail, but ftn systems that are points are showing up as unknown.  Any chance we can ignore the point number when retrieving system name and location?

**Comment by wwiv** [comment]
Hmm, the point may not be the same BBS as the primary node though.

**Comment by MorgulWWIV** [comment]
True, but I think most points are individuals using a QWK reader these days.  I guess it's not really that important, we've gt the majority of the systems showing up.
