### ISSUE TITLE
v5.7.0.3471 - 3474 - No login prompt text W10x86

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1435]
Both locally at console and remote using SynchTerm. User does not see text for username/num, or password. 
SysOp does see the SY: prompt.

**Comment by BloodStoneBBS** [comment]
Locally at console:
![Capture](https://user-images.githubusercontent.com/13243281/111910639-736bdc80-8a1f-11eb-9f8a-41be54cedfde.PNG)

Remote via SyncTerm
![Capture2](https://user-images.githubusercontent.com/13243281/111910705-b29a2d80-8a1f-11eb-99f5-7137423f13a1.JPG)

**Comment by MorgulWWIV** [comment]
Have you done anything in gfiles/bbs.str.ini?

Maybe bring over a default one and see if that fixes it

**Comment by wwiv** [comment]
Make sure you copy bbs.str.ini out from gfiles.ini into your gfiles/ directory

**Comment by BloodStoneBBS** [comment]
That was it!  Thank you.
Did not see that in the readme or what’s new txt.


Make sure you copy bbs.str.ini out from gfiles.ini into your gfiles/ directory

—

**Comment by wwiv** [comment]
You are right, I'll make it clear in the whatsnew.  I had posted this on WWIVDEV last Sunday:
```
It's here:
https://build.wwivbbs.org/jenkins/job/wwiv/label=linux-arm64-raspbian/lastSucce
ssfulBuild/artifact/wwiv-linux-arm64-raspbian-5.7.0.3459.tar.gz

When you update to 3455 or newer, please be sure to unzip the bbs.str.ini from
gfiles.zip. It's needed.

Also please don't make a lot of string modifications unless you want to merge
them back into new ini files.  This is new stuff and will be in flux for a
while (but please do try things out and give me feedback. that'll help get it
out of flux)

Have a good weekend.   
```

**Comment by wwiv** [comment]
added it to the release notes
