### ISSUE TITLE
When sending ftn email, try to limit nets by zone

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1442]
Right now when we go to send a FTN email, we'll ask the network based on all FTN networks.  Since net_networks_rec can hold the nodelist, let's try to load the nodelist and then match the zones.  

If we can't load the nodelist, we'll add it to the list anyway.

**Comment by MorgulWWIV** [comment]
I like this!

**Comment by wwiv** [comment]
Fixed in 524b15b2cabbd397ee1dd2d529ae9eb1b3c19337
