### ISSUE TITLE
Support interestingly formed Tic line with addresses

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1445]
Looks like at least one still living TIC processor adds the sysop name.

The area name looks sus too, likely it just mean't "INFO" on HobbyNet (aka HNET?)
Example:
```
Created by PXTIC/Win v7.0 (c) 2018 Santronics
Area [HNET] INFO
Origin 954:895/1
From 954:895/1
To Morgul, 954:895/5
File HOBBYNET.ZIP
Replaces HOBBYNET.ZIP
```

**Comment by MorgulWWIV** [comment]
Believe it or not, the file area (only one on this network) is listed as [HNET] INFO in the tic file, and HNET_INFO in the file.NA listing.
