### ISSUE TITLE
regions and zip-city not unzipped with default install on linux

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1455]

**Comment by BloodStoneBBS** [comment]
Where should they reside should we manually unzip them over an existing install?

**Comment by wwiv** [comment]
In directories under data/

See http://docs.wwivbbs.org/en/latest/install/upgrade/#copy-over-newer-datafiles

```
unzip -qq -o regions.zip -d data/regions
unzip -qq -o zip-city.zip -d data/zip-city
```

Also as  you upgrade, please be sure to update bbs.str.ini from gfiles.zip, it has some newer strings.

**Comment by BloodStoneBBS** [comment]
Thanks!
