### ISSUE TITLE
Incorrect BY: line when posting to a Fido sub

### ISSUE THREAD

**Issue by MorgulWWIV** [wwivbbs/wwiv#1460]
Noticed this tonight.  Posting a new post on a Fidonet sub, it adds a BY:ALL line at the beginning of the message.

Replying to an existing message works fine, but starting a new one gives the incorrect line.

![by all](https://user-images.githubusercontent.com/74803711/116332105-1b06c800-a79f-11eb-9ccb-64151f97c047.png)

**Comment by MorgulWWIV** [comment]
Fixed it.

Can't send changes upstream for some reason.

inmsg.cpp, line 374

Replace
 if (!to_name.empty()) {
With
   if (!to_name.empty() && to_name !="All") {

**Comment by wwiv** [comment]
Actually going to use:
```
    if (!to_name.empty() && !iequals(to_name, "All")) {
```
