### ISSUE TITLE
Found CRITICAL Vulnerability on your website

### ISSUE THREAD

**Issue by imchiragprajapati** [wwivbbs/wwiv#1462]
Hello I am Chirag Prajapati a Certified Penetration Tester and Ethical Hacker my License no is: 10188-161-078-1726.

I found a CRITICAL Vulnerability on your website: wwivbbs.org
For more information I request you to kindly revert me back so that I can share with you the report !

Email: imchiragprajapat@gmail.com

Looking forward to hearing from you !

**Comment by wwiv** [comment]
Thank you for the report!

The page mentioned has now been secured and the others addressed from software updates.

**Comment by imchiragprajapati** [comment]
Respected Team,
Thank you for the great Response I really appreciate it 🙏
I request you to please reward me *100$*
Sir, the reason I am finding the Vulnerabilities on your website because by
reporting it to you I can feed my Family from that rewards which you are
giving Sir nothing much more than to support my Family 🙏


*Paypal Link:    paypal.me/Chirag8969 <http://paypal.me/Chirag8969>*

*Looking forward hearing from you *

**Comment by wwiv** [comment]
Hi,

As a small, volunteer run open source project while not able to send a monetary award, happy to send a thanks email or add a note of thanks from our twitter handle.  Let me know.

Closing this issue as the credentials readonly page is secured (although it doesn't seem the credentials could have been downloaded from there, just their existence was known, and it doesn't need to be visible to un-logged in people)

**Comment by imchiragprajapati** [comment]
Respected Team,
No problem Sir I can understand.

Please tag my Twitter handles: *ImCHIRAG99*
*                                                  thecybertix*

*Looking Forward hearing from you !*

**Comment by wwiv** [comment]
https://twitter.com/wwivbbs/status/1395766420806377475
