### ISSUE TITLE
"/" from WFC defaults to 0 but will not toss unless changed to 1

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1466]
Windows 10 x86 Most builds 5.x
Would it be possible to have the "/" default to 1 and maybe launch in a clean window?
Unrelated - note the OS: display Has been showing Windowsr: for quite some time.

![toss](https://user-images.githubusercontent.com/13243281/121099174-33a9cb00-c7ac-11eb-9642-c28231459f92.png)

**Comment by Mustang-usa** [comment]
Honestly people just give it up.  Wives is history like all that other bbs
stuff.

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/ba9295fe46a531f5d448cb63214182499b4238ea

**Comment by BloodStoneBBS** [comment]
Thanks!  Your tip on the ANSI Callout was the fix on my side. Haven't upgraded to the latest build yet but will do so later today.
One thing I do see is that WWIVnet is not shown as the primary network.
![Capture1](https://user-images.githubusercontent.com/13243281/121190779-39d98f00-c820-11eb-973c-25c4f48de8d0.PNG)
