### ISSUE TITLE
Garbled display while connected locally (probably encoding issue)

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#1467]
OS: linux
WWIV: 3536

When logging in locally through WFC over an ssh connection, it looks like there's an encoding issue where non-alpha characters are not being displayed correctly.  

![Screen Shot 2021-06-09 at 10 49 04](https://user-images.githubusercontent.com/913430/121387529-5a811200-c910-11eb-970e-5e63dfe85502.png)

It looks fine over syncterm

**Comment by granitepenguin** [comment]
and for clarity, this is also affecting the local view in the BBS.  Note all the non-alpha characters are gone

![Screen Shot 2021-06-09 at 11 54 50](https://user-images.githubusercontent.com/913430/121396982-88b71f80-c919-11eb-8c67-cdad2b1f885f.png)

**Comment by wwiv** [comment]
Worked in 3510
Worked in 3515
Worked in 3516
Failed in 3517
Failed in 3519
Failed in 3523

**Comment by granitepenguin** [comment]
verified working in 3537 :-)
