### ISSUE TITLE
FOSSIL Drivers should be in the distribution zip

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#147]
Currently they are only available from SF
http://sourceforge.net/projects/wwiv/files/redist/sbbsexec.zip/download

**Comment by wwiv** [comment]
Yeah, it's GPL so [I think] it can't be bundled with Apache Licensed binaries... If I'm wrong then let's put the source to it and bundle it or whatever else we need to do.

**Comment by askpatrickw** [comment]
If I understand this, you can put Apache in GPL but not the other way.
http://www.apache.org/licenses/GPL-compatibility.html

**Comment by askpatrickw** [comment]
I created a repository with the code in it.
Someone needs to create a build on Jenkins for it.
https://github.com/wwivbbs/syncfoss
