### ISSUE TITLE
"install directory tree": 2: "install directory tree": Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by Cyberactive2** [wwivbbs/wwiv#1470]
Installation on my pi4 for the the latest June build in debian 10, I am receiving a syntax error for numerous attempts under different  install directories (not as a root user).  Thus I am not able to run wwivconfig and/or when I sudo into the config, it asks for sudo password for wwiv.  If I grant into sudoers, it still halts with the above syntax error.

**Comment by wwiv** [comment]
which command gives that error? install.sh or wwivconfig?  ANd where? I'm not sure where in the execution that error would happen. thanks

**Comment by Cyberactive2** [comment]
I was able to correct my problem.  User Error.  Thank you.
