### ISSUE TITLE
WWIVFSED end of line codes. 

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#1471]
If you use it locally as an editor for programs such as multimail it generates high ascii codes that look like a happy face or 
if you are on Windows. Maybe we need a command hook for non-wwiv mode that doesn't generate any special high ascii codes after each line. 
[REPLIES.txt](https://github.com/wwivbbs/wwiv/files/7193161/REPLIES.txt)

**Comment by wwiv** [comment]
Fixed in bc12ddebc9b084983ba4e0088ab5acfe696046b2

Add --wrap=none to your invocation of wwivfsed to turn off word wrapping
