### ISSUE TITLE
Feature request: ANSI display speed

### ISSUE THREAD

**Issue by andymhaworth** [wwivbbs/wwiv#1479]
Forgive me if this is already implemented somewhere, but is there a way to display ANSIs at a certain speed?

For example, borrowing the expression language syntax, something like this:

|{set baud=14400}

And that would slow down the display of longer ANSI files.

**Comment by andymhaworth** [comment]
Well, never mind, I do see there is a speed parameter in wwiv.ini -- although it would still be nice to be able to selectively slow down certain ANSIs. No worries.

**Comment by wwiv** [comment]
Good suggestion.

Adding support for this:
"{set bps=XXXX}"

This matches what we have in other places.  It'll be in 5.8 after this gets merged.
