### ISSUE TITLE
Excessive delay on first connect

### ISSUE THREAD

**Issue by norrinr** [wwivbbs/wwiv#1480]
WWIV 5.7.2.3552 on Linux

The first time a user telnets into the BBS, it takes 5 seconds for the logon screen to display. Subsequent connections have no delay. This happens remotely as well as connecting to localhost from the same system. Unknown yet how long it takes before the delay comes back again. SSH, on the other hand, takes 16 seconds every time.

**Comment by wwiv** [comment]
I'm pretty sure this is the country code lookup service being slow, I have it on my bbs too, it's been getting slower over time.

Go to wwivconfig
Select wwivd -> Blocking -> Use CC Server?
Turn that off.

See if that helps, that took the connection time from 5-10s for mystic.wwivbbs.org to <1s

**Comment by wwiv** [comment]
I believe the slowness in the CC server is causing this.  Closing

**Comment by norrinr** [comment]
Yes, sorry for the late response, since turning this off the other day I have not experienced the delay. Thanks.

**Comment by wwiv** [comment]
Awesome, thanks for confirming.
