### ISSUE TITLE
Unable to change password in Defaults menu

### ISSUE THREAD

**Issue by dotelpenguin** [wwivbbs/wwiv#1483]
Verified in 5.7.2.3552  and 5.8-Dev

Selecting 6 to change password, asks if you wish to close your  mailbox.

4) Mailbox           : Normal
5) Configured Q-scan                    6) Change password
7) Update macros                        8) Change colors
Defaults: 6

Do you want to close your mailbox?

**Comment by BloodStoneBBS** [comment]
OS version?  I cannot replicate in Windows 10 w32 using v5.8.0.3600

**Comment by dotelpenguin** [comment]
This was on Ubuntu/Linux.
