### ISSUE TITLE
FullScreenReader remains set in Defaults even when ANSI not enabled

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1484]
In Defaults, when Message Reader is set to Full-Screen, choosing to disable ANSI will not change the Message Reader Mode to Traditional. Full-Screen reader only works if ANSI is set. It looks like crap when ANSI is off.

**Comment by ericpareja** [comment]
Suggested fix in bbs/defaults.cpp:

in function void defaults(bool& need_menu_reload) {

```       break;
     case '2':
       input_ansistat();
+      if (!okansi() && a()->user()->HasStatusFlag(User::fullScreenReader)) a()->user()->ToggleStatusFlag(User::fullScreenReader);
       break;
 
```

**Comment by wwiv** [comment]
Thanks for the fix, I ended up not checking and just clearing the FSED flag.
