### ISSUE TITLE
Set main_type to 65535 when processing a message

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1488]
like this:

```
        header.main_type=65535;
```

We should do this so that we know the message is deleted, and then skip this when handling packets.  This is needed to remake lnet

**Comment by ericpareja** [comment]
i assume this is for the network packet handler? read wwivnet packet, if processed then rewrite packet with header.main_type=65535; process next wwivnet packet?

**Comment by wwiv** [comment]
Yes, you are absolutely correct.

After it's processed (I think network1),(and should be deleted), the net37 software would mark it as this main_type, so if the machine crashed and it got restarted, we wouldn't get duplicate messages processed.  This is also how lnet "deletes" a message (by marking it this type, and then just at the end renaming the packet to P1-L-NNN.NET and rerunning network1.exe).

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/7381d6bfa7e9cc267b4e229237ce9344cdb86d9f

**Comment by wwiv** [comment]
Actually network2 still needs to do this too in handle_file or handle_packet
