### ISSUE TITLE
Log in Prompt Labels not showing after upgrade from 5.6 to 5.7.x

### ISSUE THREAD

**Issue by SaintShaggy** [wwivbbs/wwiv#1489]
OS: Ubuntu 20.04 Server
Raspi ARM
Fresh fork and clone date 12/1/2022

After compiling from source, and upgrading the binaries from 5.6, the log on screen is no longer showing the Log in prompt labels for user ID or password. The SYSOP label password shows. The input field for all three work and show correctly.

Telnet to palace.brokedownpalace.online 2323

Could very well be something I did too. 

Shaggy

**Comment by BloodStoneBBS** [comment]
I vaguely recall the same. Have you run wwivconfig to update ?

**Comment by wwiv** [comment]
Can you copy over the "gfiles/bbs.str.ini" file from 5.7, there's new strings now.

**Comment by SaintShaggy** [comment]
@wwiv -- copying over the new bbs.str.ini file worked.

Thank you. Issue can be CLOSED!!

**Comment by wwiv** [comment]
Glad to hear it and thanks for reporting it!
