### ISSUE TITLE
WIKI Page for Upgrading from 4.X to 5.0 is Blank

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#149]
https://github.com/wwivbbs/wwiv/wiki/wwivupgrade

**Comment by BloodStoneBBS** [comment]
Looks like we have this one covered?
http://wwivbbs.readthedocs.org/en/latest/wwiv_4x_upgrade/

**Comment by TRI0N** [comment]
@BloodStoneBBS Has Pointed out the Correct Link for 4.x to 5.0 upgrade.
