### ISSUE TITLE
Optional lines in Full-Screen Message Reader displays line numbers above 2

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1504]
In the Full-Screen Message Reader, the optional lines gets displayed differently from the Traditional Message Reader.

Example:

Using the Full-Screen Message Reader:
![Screenshot from 2023-01-03 19-45-31](https://user-images.githubusercontent.com/188277/210351280-afc6af6a-7f67-4143-8911-6648674733ce.png)

Using the Traditional Message Reader:
![Screenshot from 2023-01-03 19-45-07](https://user-images.githubusercontent.com/188277/210351315-e38de049-7c60-43b4-bd90-94da29aef347.png)

**Comment by wwiv** [comment]
trying to step through this under a debugger, it seems that for some reason in the  FrameBuffer class it's thinking it's in a pipe code on here and that's causing issues.

**Comment by ericpareja** [comment]
it's odd that the Traditional Message Reader parses it properly, while the Full Screen Reader doesn't.

it's a difference between display_message_text() and split_wwiv_message() in the loop that handles optional lines. 
just for completeness, here's the .tag file used for that message.
[WWIVDEV.txt](https://github.com/wwivbbs/wwiv/files/10339973/WWIVDEV.txt)

The lines use WWIV heart codes (?) Ctrl-C for colors.

**Comment by wwiv** [comment]
The full screen reader has to write out the ANSI to a frame that can be scrolled, since absolute positions, etc don't work for a scrollable view.

**Comment by ericpareja** [comment]
OK. I tried making the same .tag file with Pipe codes in place of Heart codes and the Full Screen Reader rendered it more or less correctly (but the word-wrap messed up the formatting). Does the FS Reader count pipe codes or heart codes as multiple chars, or zero chars to add to the line length? I'm getting sleepy now, so I can't pursue this now.

**Comment by wwiv** [comment]
Will you attach your old .tag file here so I can try it out more easily?

**Comment by wwiv** [comment]
This seems to fix it, I still need to clean up it up a bit before i merge it in.

https://github.com/wwiv/wwiv/commit/9c12d7611856b4e57498aa029cb3d53fa3cbc891

**Comment by wwiv** [comment]
Fixed and merged in https://github.com/wwivbbs/wwiv/commit/94b38a00dcd55469b3b08975d02d07190d6da7e4
