### ISSUE TITLE
Birthday date not displayed correctly on newuser account

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1509]
In New User Registration, birthday is displayed as "January 01, 1970" if date is earlier than January 1, 1970.  Actual birthday date is stored.

~~Related to #1224.~~

![Screenshot from 2023-01-05 05-40-24](https://user-images.githubusercontent.com/188277/210655180-c271424d-6af6-4b96-a7f0-4a71236aed0e.png)

**Comment by wwiv** [comment]
Not related to that, I think it's because the birthday is bounced through time_t to be displayed.
This line is the problem (which we use to get the nice formatting)

```
          auto dt = c.user.birthday_dt().to_string("%B %d, %Y");
```

**Comment by wwiv** [comment]
Basically anywhere we use User::birthday_dt() we have issues. Fortunately it's only on display.

**Comment by ericpareja** [comment]
shouldn't struct tm be used instead of time_t?  (not yet looking into the code but jumping to conclusions i'm not even sure about.)

**Comment by wwiv** [comment]
I've got a fix
