### ISSUE TITLE
Auto-message dialog should display a "preview" before asking "Is this OK?"

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1510]
Current dialog accepts 5 lines for auto-message, then prompts:

Anonymous?
Is this OK?

Suggested cosmetic fix is to display the possible auto-message output before the "Is this OK?" prompt.

**Comment by wwiv** [comment]
SGTM, I'll look for the PR

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/a8da93a818252d7d5d865999749b387c3fe76fb0

**Comment by wwiv** [comment]
In the git commit message, I think you need this for it to auto-close.

```
Fixes #1510
```

The () around it confused the parsing I think
