### ISSUE TITLE
Chains display of sponsor lists first sponsor twice

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1513]
If chain is sponsored/registered, 1st entry is shown twice.

![Screenshot from 2023-01-07 03-55-02](https://user-images.githubusercontent.com/188277/211089701-c0843e6e-223f-40f5-8f9e-a6c778a76b0a.png)
![Screenshot from 2023-01-07 03-55-22](https://user-images.githubusercontent.com/188277/211089764-7726e7e0-3862-4015-832a-433c72b029b0.png)

**Comment by BloodStoneBBS** [comment]
Is this still enabled via wwiv.ini?

**Comment by ericpareja** [comment]
> Is this still enabled via wwiv.ini?

Last I checked, wwiv.ini doesn't affect this. If **any** of the chains has a sponsor, you get the three column display with DOOR name, SPONSOR, USAGE. If none have a sponsor, you get the two-column display. I'll see what I can come up with for what you want. This is for #1487 right?
