### ISSUE TITLE
newly created networked SUB marked auto-requestable is not requestable

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1519]
creating a networked sub flagged auto-requestable makes the sub available for requests, but SUB ADD REQUESTS get returned with SUB REQUEST RESPONSE of "Error Adding or Dropping Sub".

on investigation, the "nSUB.net" (aka subscribers) file is non-existent in the network directory.

suggested fix: add code to create null file "nSUB.net" in network directory if it doesn't exist in bbs/subedit.cpp modify_sub().

**Comment by wwiv** [comment]
Only if we're hosting this right?

**Comment by wwiv** [comment]
ALso in subs.cpp we should create these if they don't exist as well.

**Comment by wwiv** [comment]
Something like this    https://github.com/wwiv/wwiv/pull/new/b1519 I think.  WDYT?

**Comment by ericpareja** [comment]
looking good.
