### ISSUE TITLE
Win32 on 10, when in BE, modify Network, space to Quit does not.

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1521]
Build 5.8.0.3652 

Low impact but the option should work.

Noticed that when in BE, Selected J for the networking, then M for modify, the option to quit becomes space instead of Q however neither space or Q works to exit this mode.

![image](https://user-images.githubusercontent.com/13243281/212717873-08e77e88-ec9a-4a70-a6aa-33e2dce21eea.png)

**Comment by ericpareja** [comment]
Same behavior in Linux.

Possible fix:

```
diff --git a/bbs/subedit.cpp b/bbs/subedit.cpp
index 3488d0008..4bc1f5be4 100644
--- a/bbs/subedit.cpp
+++ b/bbs/subedit.cpp
@@ -335,6 +335,7 @@ static void modify_sub(int n) {
         }
         bout.print("{:c}), <space>=Quit? ", static_cast<char>('a' + a()->subs().sub(n).nets.size() - 1));
         std::string charstring;
+        charstring = " ";
         for (size_t i = 0; i < a()->subs().sub(n).nets.size(); i++) {
           charstring.push_back(static_cast<char>('A' + i));
         }
```
