### ISSUE TITLE
Should be possible to override official binkp.net entry with private node entry

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1522]
Some nodes in binkp.net as distributed by WWIVnet coordinator are **private**.
Add option in `wwivconfig`  callout.net editor to add an override address/port.
Will probably need to touch network code to provide override capability.

**Comment by wwiv** [comment]
we could create a new wwivnet_callout.json file in the network directory just like we have fido_callout.json there, and list in anything extra we want to add per network.

either network3 can merge in the data as it creates the wiwv datafiles, or possibly we'll just read it in as-needed by networkb or the other tools.

**Comment by wwiv** [comment]
I'm thinking "binkp.local.net" is a good name for this, thoughts?

**Comment by wwiv** [comment]
Fixed in 3c5bb2edad0ac5c1261537aafef661f3dd842b53

You can now add a binkp.local.net file next to binkp.net and entries there will override the ones in binkp.net
