### ISSUE TITLE
Chains display not updating properly after ChainEdit

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1526]
In chains, if you are SO(), you can enter *ChainEdit. After adding/removing a chain in ChainEdit, then returning to the chain menu, the chain display doesn't show the newly added chain. If a chain was removed, it causes the chain display to crash the BBS.

**Comment by ericpareja** [comment]
on reading the code, mapp should be read in again after chainedit() in line 238.

**Comment by dotelpenguin** [comment]
Verified this as well.  When editing chains with "*" within the chains menu.
Adding will not reload
Deleting will crash

**Comment by wwiv** [comment]
I dont think we need mapp anymore since the map has the total size, I'll clean this up.
