### ISSUE TITLE
network2 does not handle 'epreproc.net' file in network data directory

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1531]
network2 does not recognize 'EPREPROC.NET' file in network data directory. it does not run any pre-processors listed in the file.

from wwiv/specs/netdocs/network.txt:

> There are also local.net pre-processors allowed in       
net32.  The preprocessors are listed in the 'epreproc.net'  
file in the network data directory, one per line.  BEFORE   
network2 processes ANY of local.net, each preprocessor is   
run, in order, passing each the ".net_num" parameter to     
indicate which network is being processed.  The pre-        
processor may then scan through local.net, and mark as      
deleted (main_type=65535) any message processed by that     
preprocessor.  The preprocessor may even append additional  
messages to the local.net file, if that is desired.

from autosend.doc:

> If you want to manually install AutoSend on your networks, follow these
instructions:
>
> Create a file called EPREPROC.NET in >each< network data directory with the "AUTOSEND.EXE" on the first line.
> 
> If you are using PackScan or another preprocessor, you may already have an EPREPROC.NET in each of your network data directories.  You can simply add "AUTOSEND.EXE" either at the top or bottom of EPREPROC.NET.  Each program listing should be on a separate line.
>
> NOTE:  Do >NOT< include any parameters for AUTOSEND.EXE in the EPREPROC.NET
       files.  You should >only< put "AUTOSEND.EXE" on a line by itself.  If
       you add any of AutoSend's parameters, you can cause severe problems.

**Comment by wwiv** [comment]
I thought the epreproc.net was the older and deprecated way.

**Comment by ericpareja** [comment]
"eprogs.net" types is for new external type. "epreproc.net" is for pre-processing the whole packet. i'll experiment with whether "eprogs.net" will work in place of "epreproc.net."

from what i see, "epreproc.net" will process the entire bundle, reading all the packets, marking packets that it has processed by changing the pkt header in file.

"eprogs.net" will process individual packets.

given a bundle of 100 packets with mixed major types...
in terms of performance, "epreproc.net" will read through the 100 packets once then return to network2, while the "eprogs.net" processors will get called for each new_external_type packet that matches their minor_type.
