### ISSUE TITLE
FidoNet and OtherNets needs work

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#154]
https://github.com/wwivbbs/docs/blob/master/docs/other_nets.md

I'll do this when I setup ccbbs

**Comment by wwiv** [comment]
@W7PEA Can I assign this to you?

**Comment by askpatrickw** [comment]
Still slowly working on Usenet, but this is next on these list, so sure.

**Comment by askpatrickw** [comment]
I'm blocked from completing this by the utter futility of trying to contact the right people in Fidonet. No one replies. :-(

**Comment by askpatrickw** [comment]
Pulling from 5.1

**Comment by wwiv** [comment]
http://docs.wwivbbs.org/en/latest/network/ftn_nets/ is updated
