### ISSUE TITLE
network2 moves "deleted" packets to dead.net because identifed as UNKNOWN type.

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1540]
in net37 user doc, packets that have been handled by epreproc.net programs can be marked "deleted" by changing their main_type to 65535.

> The pre-processor may then scan through local.net, and mark as deleted (main_type=65535) any message processed by that preprocessor.  The preprocessor may even append additional  messages to the local.net file, if that is desired.   

network2 log entry:
> 2023-01-24 01:20:37,201 INFO  Processing message with type: UNKNOWN type #65535/0
2023-01-24 01:20:37,202 ERROR     ! ERROR Writing message to dead.net for unhandled type: 'UNKNOWN type #65535'; writing to dead.net
2023-01-24 01:20:37,202 INFO  write_wwivnet_packet: Writing type 65535/0 message to NetPacket: /home/wwiv/wwivnet/dead.net

deleted packets should simply be skipped over so that they are deleted along with the entire local.net when it is completely processed.

**Comment by wwiv** [comment]
oops
