### ISSUE TITLE
network2 doesn't use the DISALLOW.NET file

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1541]
From Net37 User Docs:

>   DISALLOW.NET (in the DATA directory) - lists system       
numbers that are NOT allowed to automatically subscribe     
/drop subboards.  If you want to keep a certain system      
from subscribing to any of your subs, place their system    
number in the DISALLOW.NET file.

**Comment by wwiv** [comment]
should we change this to read disallow.net from the network directory vs. data directory? I don't think it makes sense where it is (but likely started out in data before multiple networks was a thing).

WDYT?

**Comment by ericpareja** [comment]
Think network dir makes more sense now.

**Comment by wwiv** [comment]
plot twist, dissalow.net was always in net's data directory (not bbs's data directory)

**Comment by wwiv** [comment]
also the format seems to be the same as the subscriber file, so we can simply reuse that code to read the file and check for a node
