### ISSUE TITLE
The list of MODS which were rolled into the default functionality of 5.0 should be documented

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#155]
Just fill in the provided table

https://github.com/wwivbbs/wwiv/wiki/mods

**Comment by wwiv** [comment]
hard to tell, 5.0 forked from an 4.3 beta, then merged in the changes from 4.3 final.  I didn't roll in any mods per-se after 4.3 (4.3 was mostly mods on 4.24) but rather was just a win32 port of 4.30, then a linux port of 4.30.  

I added back in the //QWK support that was removed in 4.30.

**Comment by askpatrickw** [comment]
I didn't realize that that happened in the past not in 5.0. Le'ts call it dead then.
