### ISSUE TITLE
bbs crashes when in transfer section with zero directories

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1551]
doing *) list areas will cause the bbs to hang.
L)isting files will cause a segmentation fault.
etc.

suggested fix: close transfer section if 0 directories. there is nothing to see there anyway.

**Comment by wwiv** [comment]
I am running the latest and this is what I see (I deleted all areas in one of my test bbses) 

```
Time Left: 254 minutes
Conference: All Dirs
[] []: *
None.

──────────────────────────────────────────────────────────────────────────────
Select [1-0, ?=List Again, Q=Quit] :
```

**Comment by wwiv** [comment]
Ahh, (L) does crash though for me
