### ISSUE TITLE
WWIV macros don't work in FSED

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1554]
WWIV macros work in the Line Editor.
They should work in FSED too.

**Comment by wwiv** [comment]
they do, you have to hit control-P first.

**Comment by wwiv** [comment]
Hmm, only color change is listed in help, should add how to do macros
```
CTRL-P+0-9  Change Color to Digit
```

**Comment by wwiv** [comment]
It is listed in help, but I think that it fits on the 2nd page and scrolls away before you can read it.

**Comment by wwiv** [comment]
I see it locally, looks like I never updated fsed.msg on my bbs.  This has been addressed
