### ISSUE TITLE
'A'  email author of Last Message doesn't work on FTN type ECHOES.

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#1560]
On FTN type SUBS, A) email author of Last Message doesn't work.

Since FTN type subs have 0 as fromuser and 0 as fromsys (?), we can use snippets of the routine in readmail.cpp from lines 1000-1086.

**Comment by ericpareja** [comment]
this is a bug that i'm chasing down. in one of my setups running wwiv github current, there are FTN subs where A) Email Author of Last Post doesn't work. i just noticed that A) actually works in *some* of the FTN subs i have. i'll have to investigate what the difference is between the working and non-working subs.

**Comment by ericpareja** [comment]
ok. i figured it out. it isn't the sub that was "buggy". the posts that can't be 'A' answered in private were in a FTN sub and were posted before the change of FTN gateways from 32675 to 32765. because the ownersys of the post is no longer a valid node, it gets an "Unknown system number" output but quickly gets overwritten by the fullscreen reader.

**Comment by wwiv** [comment]
Aha, I forgot about that from the 5.2 what's new
```
! **!!*!*!*! You need to update the outbound sub by recreating the
  network node it's under in subedit (J, then M, then the letter, usually
  A, then retype the echo tag, or just edit data/subs.json and replace
  32675 with 32765 everywhere prettymuch (it's under host section))
```
