### ISSUE TITLE
File Transfer issue: fdsz.exe failing - looking for modem?

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1567]
Sorry, been noticing a few bugs recently. Today's is apparently a rarely used file transfer that is still looking for a modem.
No debug option for vstudio, but ignoring the error allowed a clean exit.

![image](https://user-images.githubusercontent.com/13243281/216622409-e96460e4-7c6c-48cb-a4a1-19c40d0eaabe.png)

**Comment by ericpareja** [comment]
I was testing if fTelnet/htmlTerm's Ymodem-G works as advertised. Sorry.

**Comment by wwiv** [comment]
You likely need to run a DOS virtual modem (like netfoss) to get fdsz to work, or just remove that protocol option from your BBS, it was likely there since 4.3x days (or earlier)

**Comment by wwiv** [comment]
5.x doesn't add any protocol calling fdsz
