### ISSUE TITLE
Linux Section for WWIVEdit is blank

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#157]
https://github.com/wwivbbs/wwiv/wiki/wwwivedit

**Comment by granitepenguin** [comment]
It's blank because it doesn't work.  I'll have to revisit testing to see exactly what doesn't work.  IIRC, it crashes pretty spectacularly.

**Comment by TRI0N** [comment]
It's not even stable in Windows. The default settings in the Docs on the MkDocs doesn't work either..

**Comment by wwiv** [comment]
and this wiki page is gone. closing. It doesn't work on dosemu AFAICT

**Comment by granitepenguin** [comment]
Closing because it didn't actually get closed
