### ISSUE TITLE
investigate pocketpy

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#1575]
https://github.com/blueloveTH/pocketpy may be interesting if we could get by with a partial python implementation and not a full install

**Comment by ericpareja** [comment]
yeah. the one line include is enticing. :)

**Comment by wwiv** [comment]
I don't think we'd likely go this way, it's good for scripting but not adding in any additional python libraries (which I think would be a common usecase).

Thoughts?

**Comment by ericpareja** [comment]
might be better to just have a wwiv.py module.
