### ISSUE TITLE
FSED anomalies

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1578]
Windows 10 w32, 5.8.0.3675

When using the FSED to send or reply to e-mail, if/when the text exceeds the initial visible window, the text falls behind the bottom bar.

![image](https://user-images.githubusercontent.com/13243281/217975582-9b20fdd1-d4b1-4c6f-9e96-f623a788d709.png)

Additionally, scrolling up and down, does not cleanly scroll. Example: scrolling from the bottom up to the start of the message (circled in red) you see previously entered text, not the actual text that should be displayed.

![image](https://user-images.githubusercontent.com/13243281/217975872-072c7a27-19c1-4974-85a2-7cbff4c470b6.png)

**Comment by BloodStoneBBS** [comment]
The line This is a test... is the actual beginning of the message. Nothing should be above that line

**Comment by ericpareja** [comment]
What is your screen size in Defaults?
/sn

**Comment by ericpareja** [comment]
Related to #1543, the "fix" is possibly what caused this. I'll investigate and attempt to fix this.
