### ISSUE TITLE
Q: are the SYSTEM EVENTS still supported? I don't see them on my site.

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#158]
https://github.com/wwivbbs/wwiv/wiki/eventmgmt

**Comment by wwiv** [comment]
No, these (all but the virus scanner command) were added to WWIV.INI in 4.24. Once in wwiv.ini, the values there would override what's in the menu,

Also the virus scanner one was never implemented but added in 4.3 as an option that did nothing.

In 5.0 I removed this from config.dat and only left wwiv.ini remaining.
Here's what's in the wwiv.ini I use

;=============================================================================
;                          EXTERNAL PROGRAM OPTIONS
;=============================================================================
; ***\* NOTE:  These setting have moved to the Event Editor/System Events.
; ***\* You can set them here but you are advised to make the changes in the
; ***\* editor instead.
;
;UPLOAD_CMD     =                           ; upload event
;BEGINDAY_CMD   =                           ; beginday event
;NEWUSER_CMD    =                           ; newuser event
LOGON_CMD      = Z:\bbs\logon.bat
;

**Comment by askpatrickw** [comment]
Updated the WIKI
