### ISSUE TITLE
Minor aesthetics to change in subs/messages - sysop options

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1598]
Latest build on Windows 10 w32

When selecting ? when reading a message in a sub, the SysOp options after selecting E to extract a message to file, display options 1-4, however the expected prompts are Q=Quit and (D,G,T)

In this case, I wanted to extract a message to GFILES, but '2' did not work. 'G' did.

![image](https://user-images.githubusercontent.com/13243281/235156461-47ec8693-ba0f-4e3a-bc32-2134f5016459.png)

**Comment by BloodStoneBBS** [comment]
Need to test 'T'. I do not know if that will Extract to Transfer Directory or TEMP.

**Comment by wwiv** [comment]
You need to update the gfiles\mextract.msg file that comes with the newer build, this was updated some time ago.

**Comment by BloodStoneBBS** [comment]
D'Oh!

In the voice of Roseanne Roseannadanna; "Never Mind...."

I haven't been updating those files as I have a few that I've customized over the years.

Is there a list of gfiles that have changed since 4.30 so I can review and upgrade where necessary?

J..

**Comment by wwiv** [comment]
There's not a good list, want to help make those or make a script to make
that list? I imagine some combination of find + diff or find + mdsum + diff
could be useful?

**Comment by wwiv** [comment]
I mean specifically to compare stock versions, or even just to know what
doens't match what you have.  Let me know what you think?
