### ISSUE TITLE
ANSI Codes tools\tips Needs completion

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#160]
https://github.com/wwivbbs/wwiv/wiki/ansi

At a minimum a screenshot of the pipe commands and CTRL+P commands or something that can be used as a cheat sheet.

**Comment by askpatrickw** [comment]
Did a little experimenting tonight and have some more notes

1). What does changing the NUCOLOR[] and NUCOLORBW[] linesin WWIV.INI do? I saw no effect changing nucolor-0 to 4 (red) from 7 (grey) on text colored with |#0 that I placed in a custom WELCOME.ANS

This part is DONE:
- //COLORS needs to be added to this page.
- //COLORS allows the USER to edit how colors appear to them. This also means that if one user on the BBS or another system has posted something with color code 5 (green on black) and you change your colors to be 5 (magenta on black, flashing) that's what you'll see.
  This does not affect ANSI art files, only the colors applied through the BBS Editors or in the BBS menu files.

**Comment by k1cty** [comment]
Ansi Substitution Codes for WWIV Ansi Menus
<img width="1280" alt="screen shot 2016-06-15 at 2 14 59 pm" src="https://cloud.githubusercontent.com/assets/18519465/16091887/9d766cf2-3303-11e6-953a-4ad4353dbc69.png">

**Comment by wwiv** [comment]
huh?

**Comment by k1cty** [comment]
Sorry I think I posted this comment in the wrong place but the screenshot shows how to add codes to an ansi menu screen and have it pull system info and display it within the ansi screen

**Comment by wwiv** [comment]
cool, 
@jsbkje 
do you have it as a text list you can post, I'll paste it into the doc as text vs. a screen shot.

**Comment by wwiv** [comment]
nevermind @jsbkje I found them.

Fixed in https://github.com/wwivbbs/docs/commit/029469f107226d9d1490788f3b13f58fefb17a4a
