### ISSUE TITLE
Chains not displaying properly Build 5.9.0.3685

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#1600]
Windows 10 w32

I have a situation where a chain is showing the wrong name in the list of doors.

Chain Edit:
![1](https://user-images.githubusercontent.com/13243281/236689274-fc1530d5-6026-433e-bf6c-183e8105a2bc.JPG)

Doors:
![2](https://user-images.githubusercontent.com/13243281/236689313-a39935c5-689e-4f2a-9e37-faf01effb767.JPG)

Note 21 & 22

J..

**Comment by BloodStoneBBS** [comment]
Strictly an issue with the display. Chain 22 runs as it should to initiate a manual mail toss.
.
HA! I didn't even realize that this affects the entire column,

![image](https://user-images.githubusercontent.com/13243281/236689806-c8f453e3-9d4d-4e88-a3e7-409c17fc5c3a.png)

**Comment by BloodStoneBBS** [comment]
Rolled back to 3684 - all good.

**Comment by wwiv** [comment]
can you share what it should look like - thanks

**Comment by wwiv** [comment]
Chainedit starts at 0 where chains display starts at 1.  I just doublechecked that's also the case in 5.8.  I can't tell what is wrong here from looking at this, please show a full screenshot of chains display (not chainedit) for the older build so I can understand what is different. Thanks

**Comment by BloodStoneBBS** [comment]
Sure, sorry for the delay, we had a visitor this weekend.

Here is a shot from 3684:
![image](https://user-images.githubusercontent.com/13243281/236713082-1db1cc4e-13eb-4eb2-842f-e384570a0af8.png)

**Comment by wwiv** [comment]
So strange, I have 3 chains on my test bbs, and it looks right for me, can you email me your chains.json?

**Comment by BloodStoneBBS** [comment]
You'll see that the even numbered doors are titled the same as the odd numbered doors. Purely aesthetic. they function correctly, you just don't know what's being launched.

Sure.. Will do.

**Comment by wwiv** [comment]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/6380534/236733543-e566f35c-262b-4f85-a615-e1acee07e055.png">

So strange, I just put your chains into my latest development version and it looks right.  Let me make sure I push all changes to github and let's see if that fixes it

**Comment by wwiv** [comment]
I can't reproduce this with your chains.json on 3685, 3686, or local builds.  Super strange.

**Comment by wwiv** [comment]
aha, you have usage on, I don't

**Comment by BloodStoneBBS** [comment]
Works great!  Thank you!!!
