### ISSUE TITLE
Q: Is the FIX utility still needed and used?

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#161]
https://github.com/wwivbbs/wwiv/wiki/fix

If so fix the page, if not delete it.

**Comment by BloodStoneBBS** [comment]
I had to use it recently to update date/time refrences in status.dat.
I'll dig around later this week to see if I can come up with a good description of what FIX does.

**Comment by askpatrickw** [comment]
That would be great, thanks!

**Comment by wwiv** [comment]
looks like the page is updated. closing
