### ISSUE TITLE
Update wiki and explain QWK mail usage

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#162]
There's a page for this...
https://github.com/wwivbbs/wwiv/wiki/qwkwwivmail

Update or note that they are no longer supported.

**Comment by wwiv** [comment]
It's an empty page.  There's no need for them since WWIV5 now has internal QWK.

**Comment by askpatrickw** [comment]
Can you elaborate... where could I out about the internal QWK support?
Is it just that this is now built in and I can use any QWK reader

**Comment by wwiv** [comment]
yes, //QWK from the main menu will let you download a QWK packet.  To read it, I'd use http://multimail.sourceforge.net/

**Comment by askpatrickw** [comment]
OK... Will add this to the wiki. For now I Added a section to the proper page and added a link to multimail

**Comment by askpatrickw** [comment]
The basics are in place. Good to go.
