### ISSUE TITLE
FSED color matching & Delete issues

### ISSUE THREAD

**Issue by the-godfather-007** [wwivbbs/wwiv#1622]
FSED's top divider / window lines do not match once system colors have been modified to the SysOps desired appearance.  See preview.
![Screenshot from 2024-02-04 22-26-25](https://github.com/wwivbbs/wwiv/assets/65839945/7ce3a521-4731-4718-a794-355903299d91)

Also, when moving arrows to edit text the delete key is backspacing (deleting text to the left of the cursor) from the point of cursor position as opposed to deleting the text to the right of the cursor.  I've only tested this in Netrunner.

**Comment by ericpareja** [comment]
Can you attach the relevant WWIV.INI or config for system colors? Thanks! :)

**Comment by the-godfather-007** [comment]
The system colors in wwiv.ini should not matter, the lower divider line should match whatever system colors we select as the default for all users who login as "new" to the sytem, should it not?

**Comment by ericpareja** [comment]
On Sat, Sep 28, 2024 at 11:24:04AM -0700, The Godfather wrote:
> The system colors in wwiv.ini should not matter, the lower divider line should match whatever system colors we select as the default for all users who login as "new" to the sytem, should it not?


They shouln't. However, I want to be able to replicate the conditions to reproduce the bug on my system.

**Comment by ericpareja** [comment]
> The system colors in wwiv.ini should not matter, the lower divider line should match whatever system colors we select as the default for all users who login as "new" to the sytem, should it not?

Hi again... they shouldn't matter, but to help me find what exact code lines aren't working properly, I need something to help identify what conditions make the bug visible. Otherwise, I have to try changing a lot of WWIV.INI settings. I have identified the block of code where I should be looking, but need your input to be able to track which specific lines aren't working properly. For reference, I've narrowed the search for the bug to *common/full_screen.cpp* in the FullScreenView::DrawBottomBar() function.

**Comment by the-godfather-007** [comment]
COLOR OPTIONS
;=============================================================================
;
; NOTE:  Although the BBS is capable of using over 90 color combinations,
; only the first ten may be set here.  The remaining colors are set from
; inside the BBS.
;
; Colors are selected numerically. To determine the value for a color, use the
; following chart:
;
;    0 = Black             8  = Dark Gray
;    1 = Blue              9  = Light Blue
;    2 = Green             10 = Light Green
;    3 = Cyan              11 = Light Cyan
;    4 = Red               12 = Light Red
;    5 = Magenta           13 = Light Magenta
;    6 = Brown             14 = Yellow
;    7 = Light Gray        15 = White
;
; Now, to calculate a color, you take the value for the background color and
; multiply by 16, then add it to the foreground color you wish. This will
; provide the value you should use for that color combination. Note that
; color values greater than 127 will result in blinking. In other words,
; you should probably restrict background colors to colors 0-7 above.
;
; An example: if you want to find the value for, say, bright yellow on
; magenta, it would be (5*16) + 14. This equates to (magenta * 16) + white.
;
; ----------------------------------------------------------------------------
NUCOLOR[0]     = 7
NUCOLOR[1]     = 15
NUCOLOR[2]     = 7
NUCOLOR[3]     = 7
NUCOLOR[4]     = 59
NUCOLOR[5]     = 11
NUCOLOR[6]     = 10
NUCOLOR[7]     = 7
NUCOLOR[8]     = 5
NUCOLOR[9]     = 7
NUCOLORBW[0]   = 3
NUCOLORBW[1]   = 15
NUCOLORBW[2]   = 15
NUCOLORBW[3]   = 15
NUCOLORBW[4]   = 112
NUCOLORBW[5]   = 15
NUCOLORBW[6]   = 15
NUCOLORBW[7]   = 7
NUCOLORBW[8]   = 7
NUCOLORBW[9]   = 7
;
; System Colors
;
TOPCOLOR               = 27           ; for topscreen info
F1COLOR                = 9            ; for F1 user editor
EDITLINECOLOR          = 31           ; current field in F1
CHATSELCOLOR           = 11           ; for selecting sysop
MSG_COLOR              = 2            ; for color msgs
;

**Comment by ericpareja** [comment]
Suggested fix... will push a PR when I can. TopBar and BottomBar color codes were different. Color difference is also visible when you change your own color code for Border in D)efaults 8) Change colors 7) Border.

```
diff --git a/common/full_screen.cpp b/common/full_screen.cpp
index 1c9b4518b..d060dce73 100644
--- a/common/full_screen.cpp
+++ b/common/full_screen.cpp
@@ -95,7 +95,7 @@ void FullScreenView::DrawBottomBar(const std::string& text) {
   const auto saved_color = bout.curatr();
   auto at_exit = finally([=] { bout.setc(saved_color); });
 
-  bout_.print("|09{:c}{}{:c}", static_cast<unsigned char>(198),
+  bout_.print("|#7{:c}{}{:c}", static_cast<unsigned char>(198),
               std::string(screen_width_ - 2, static_cast<unsigned char>(205)),
               static_cast<unsigned char>(181));
 
@@ -105,7 +105,7 @@ void FullScreenView::DrawBottomBar(const std::string& text) {
 
   const auto x = screen_width_ - 10 - ssize(text);
   bout_.goxy(x, y);
-  bout_.print("|09{:c}|17|14 {} |16|09{:c}", static_cast<unsigned char>(181), text,
+  bout_.print("|#7{:c}|17|14 {} |16|09{:c}", static_cast<unsigned char>(181), text,
               static_cast<unsigned char>(198));
 }
```

**Comment by ericpareja** [comment]
> Also, when moving arrows to edit text the delete key is backspacing (deleting text to the left of the cursor) from the point of cursor position as opposed to deleting the text to the right of the cursor. I've only tested this in Netrunner.

I'll open a separate issue for this part.

**Comment by the-godfather-007** [comment]
Almost fixed but caught one minor, see below.  This is the bottom line only.

@@ -105,7 +105,7 @@ void FullScreenView::DrawBottomBar(const std::string& text) {
 
   const auto x = screen_width_ - 10 - ssize(text);
   bout_.goxy(x, y);
-  bout_.print("|09{:c}|17|14 {} |16|09{:c}", static_cast<unsigned char>(181), text,
-  bout_.print("|#7{:c}|17|14 {} |16|09{:c}", static_cast<unsigned char>(181), text,
+ bout_.print("|#7{:c}|17|14 {} |16|#7{:c}", static_cast<unsigned char>(181), text,
               static_cast<unsigned char>(198));
 }

**Comment by the-godfather-007** [comment]
PS on my code I also took out the |17|14 and just made it |#4 so it matches background/foreground with the remainder of my theme.

**Comment by ericpareja** [comment]
> Almost fixed but caught one minor, see below. This is the bottom line only.
> 
> @@ -105,7 +105,7 @@ void FullScreenView::DrawBottomBar(const std::string& text) {
> 
> const auto x = screen_width_ - 10 - ssize(text); bout_.goxy(x, y);
> 
>     * bout_.print("|09{:c}|17|14 {} |16|09{:c}", static_cast(181), text,
> 
>     * bout_.print("|[user can't login #7](https://github.com/wwivbbs/wwiv/issues/7){:c}|17|14 {} |16|09{:c}", static_cast(181), text,
> 
> 
>     * bout_.print("|[user can't login #7](https://github.com/wwivbbs/wwiv/issues/7){:c}|17|14 {} |16|[user can't login #7](https://github.com/wwivbbs/wwiv/issues/7){:c}", static_cast(181), text,
>       static_cast(198));
>       }

Can you submit a patch?

**Comment by the-godfather-007** [comment]
Sure!  How do I do that and I’ll do so.On Dec 22, 2024, at 4:07 PM, xenos ***@***.***> wrote:﻿

Almost fixed but caught one minor, see below. This is the bottom line only.
@@ -105,7 +105,7 @@ void FullScreenView::DrawBottomBar(const std::string& text) {
const auto x = screen_width_ - 10 - ssize(text); bout_.goxy(x, y);
* bout_.print("|09{:c}|17|14 {} |16|09{:c}", static_cast(181), text,

* bout_.print("|[user can't login #7](https://github.com/wwivbbs/wwiv/issues/7){:c}|17|14 {} |16|09{:c}", static_cast(181), text,


* bout_.print("|[user can't login #7](https://github.com/wwivbbs/wwiv/issues/7){:c}|17|14 {} |16|[user can't login #7](https://github.com/wwivbbs/wwiv/issues/7){:c}", static_cast(181), text,
  static_cast(198));
  }


Can you submit a patch?

**Comment by the-godfather-007** [comment]
Just found another issue I'll try to dive into but it's Christmas Eve so likely won't be until this weekend.  If one Auto Replies to an Auto  Message post, it launches the FSED as it should, however some color setting is causing the top line divider to be a combination of background from system color #4 and foreground of system color #7 or #9.  For instance my divider line should be dark gray which I use as color #7.  Background should be |00.  Instead it's the input color #59 which is dark cyan.  It's an interesting mix (i.e. doesn't look very good ;)  I'll try to see if it's the auto message not turning off color before continuing or the tojp line needing to reset color prior to displaying the top bar later.
