### ISSUE TITLE
Who owns the copyright to WWIV 5?

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#163]
This page on licensing and copyright needs updates
https://github.com/wwivbbs/wwiv/wiki/license

**Comment by wwiv** [comment]
WWIV Software Services, LLC owns the copyright.

**Comment by wwiv** [comment]
What are you looking for in "TODO: Someone official should fill this part out."?

**Comment by askpatrickw** [comment]
I'm looking for someone who is privy to the particulars to sign off on the content there or to correct it.

**Comment by askpatrickw** [comment]
Page is up to date and complete enough to call done.
