### ISSUE TITLE
/E Not saving users added to a list for mass mailing

### ISSUE THREAD

**Issue by the-godfather-007** [wwivbbs/wwiv#1636]
/E to enter mass mailing list menu
A to add users
E / L states no users added or exist.

Linux Mint 22 latest version and kernel.

**Comment by ericpareja** [comment]
This feature has not yet been fully implemented, but I'm sure that it's broken in Linux. (I really should have a test Windows machine.)

This feature is in **bbs/multmail.cpp**.

**Comment by the-godfather-007** [comment]
Ah nice, ok, good to know.  I remember having this feature on old school WWIV back in the 90's and enjoyed having it to communicate to key co-sysops and sub moderators.  Appreciate all you do.  I'll check out bbs/multmail.cpp this weekend.

**Comment by ericpareja** [comment]
A quick test of `/E` on Weather Station shows that it worked on WWIV 4.x. `multmail.c` was introduced in WWIV 4.12.

**Comment by the-godfather-007** [comment]
Yeah feature would be a nice to have especially if one is experimenting with running WWIV as a network hub and would like to mass netmail multiple nodes; or as a sysop if they wanted to multi-mail more than one user.  Not urgent just a nice request.  I'm beating up the issues page as  I stress test using every WWIV feature ;)

**Comment by ericpareja** [comment]
I've debugged `multmail.cpp` and have a patch in the works. However, the current implementation doesn't allow adding network users, only local. I'm attaching a patch for testing if you want to try it out. Or wait for my Pull Request.
[multmail-fix.txt](https://github.com/user-attachments/files/17970508/multmail-fix.txt)

**Comment by ericpareja** [comment]
> Yeah feature would be a nice to have especially if one is experimenting with running WWIV as a network hub and would like to mass netmail multiple nodes; or as a sysop if they wanted to multi-mail more than one user. Not urgent just a nice request. I'm beating up the issues page as I stress test using every WWIV feature ;)

For multimail to network, it'll take a bit longer. The current /E implementation uses just an array of INTs to hold the list. Also, there are checks in place to see if the user in the list exists, so that won't work for network users.  I should test that on Mark's BBS.

Don't worry about beating up the issues page. This is what it's here for. Keep those issues coming so we can at least know about them and maybe work on them.

**Comment by ericpareja** [comment]
Tested /E on Weather Station and it does not accept multimail to network targets. It won't accept users who have mailboxes forwarded to network either. This will be an enhancement to /E that will be planned for.

**Comment by the-godfather-007** [comment]
Tested the additions/subtractions and it works.  One thing it is not doing is loading the users default editor.  In my case I use the FSED, yet it pulls up the line editor.  I tested regular email and posts and FSED defaults just fine.
