### ISSUE TITLE
Windows 10 not detected at logon. 

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#164]
Windows 10 is not detected at logon, but only identifies the operating system as windows 8. Using build 2112.

**Comment by wwiv** [comment]
problem is that I can't detect anything newer than Win8 as long as we still support XP...

**Comment by BloodStoneBBS** [comment]
A bit of a dilemma as Windows XP is no longer a supported OS and is not something that can easily be kept secure yet many people still use it. I hope someday, we will have the same issue with Windows 8 ;-)  -  Q: Is there perhaps a way to add a line in wwiv.ini that can override the display of the OS?

**Comment by wwiv** [comment]
depends on https://github.com/wwivbbs/wwiv/issues/214

**Comment by BloodStoneBBS** [comment]
Just tried this on Windows 10 Enterprise x64 (all I have atm) and Windows 10 is detected as Windows 8.

**Comment by wwiv** [comment]
Yeah,

**Comment by wwiv** [comment]
wondering if we should even display the version at all...  Maybe just (Windows | Linux x86 | Linux ARM)  WDYT?

**Comment by mmunson** [comment]
That would keep it simple.

Get Outlook for Android

On Mon, Aug 15, 2016 at 12:02 AM -0700, "Rushfan" notifications@github.com wrote:

wondering if we should even display the version at all...  Maybe just (Windows | Linux x86 | Linux ARM)  WDYT?

##
