### ISSUE TITLE
List Plus

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#165]
File list is choppy when the file list header is not added to List Plus.
![list-plus](https://cloud.githubusercontent.com/assets/13500419/9639042/d534a1e0-515e-11e5-86a2-32b029c5d4ab.jpg)

**Comment by askpatrickw** [comment]
I have noticed this as well!

**Comment by ericpareja** [comment]
What should it look like?

**Comment by mmunson** [comment]
I have a screen shot showing how broken it is.

Sent by Outlook for Android

On Fri, Sep 11, 2015 at 4:59 AM -0700, "Eric Manuel Pareja" notifications@github.com wrote:
What should it look like?

---

**Comment by ericpareja** [comment]
I know what it looks like broken. I want to know what it should look like. I guess I should visit Weatherman's board to check.

**Comment by askpatrickw** [comment]
Here you go...

![transferlist](https://cloud.githubusercontent.com/assets/4002194/9821726/f5a5c080-5870-11e5-87f9-b968092146c6.png)

**Comment by ericpareja** [comment]
Thanks. I'll look into this.

**Comment by wwiv** [comment]
hmm, it's now off-by-one when the header is enabled.

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/pull/219

**Comment by wwiv** [comment]
Thanks Xenos for the fix, that allowed me to narrow in on the problem (and that's the part that takes the longest)
