### ISSUE TITLE
WWIV5 Telnet Server not cleanly disconnecting when some users disconnect

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#168]
On nearly a daily basis, when I log into the console, I see an open session for (usually) node 1, I use nodes 1-5 for incoming and 6 for local, in a hung state.
The Telnet server still shows the connection with the guest IP address and the BBS is up in a window waiting for some sort of prompt. This is usually in the new user area where you would enter Y/N for "Is this line blinking , flashing etc..."
I'll provide screen shots as I am able to replicate.
WIndows 7 Pro x86, WFC displays v5.00 (Development)
## Accidently closed - Still an issue

Confirmed and easily reproduced.
Connect with SyncTerm, log in as new, follow prompts into NERUSER.MSG and disconnect. WWIV5 Telnet Server session remains connected and does not drop.

**Comment by BloodStoneBBS** [comment]
Confirmed and easily reproduced.
Connect with SyncTerm, log in as new, follow prompts into NERUSER.MSG and disconnect. WWIV5 Telnet Server session remains connected and does not drop.

**Comment by BloodStoneBBS** [comment]
Confirmed and easily reproduced.
Connect with SyncTerm, log in as new, follow prompts into NERUSER.MSG and disconnect. WWIV5 Telnet Server session remains connected and does not drop.

**Comment by BloodStoneBBS** [comment]
Occurs on both WIndows 7 Pro x86 and Windows Server 2008 x86. 
Both running build 1539.

**Comment by BloodStoneBBS** [comment]
Still occurs on b1586. 
But only if ANSI is not detected!

**Comment by BloodStoneBBS** [comment]
This is what I see almost daily. 
Sometimes, holding up 3 or 4 nodes.
All I have to do is hit any key while on the BBS window and it closes out the session.

![capture](https://cloud.githubusercontent.com/assets/13243281/10061666/c142f85a-620f-11e5-8587-8bd2ddb4b751.JPG)

**Comment by askpatrickw** [comment]
So they never timeout, or your new user is limit is high?

**Comment by BloodStoneBBS** [comment]
They never time out even though the session is clearly severed. nbtstat shows no external addresses.

**Comment by BloodStoneBBS** [comment]
Stuck like this for nearly 9 hours:
All I have to is click in the window and hit any key.
IP addresses are almost always from China.
And almost always using the Guest account. I may nuke it just to prevent these hangups.

![capture](https://cloud.githubusercontent.com/assets/13243281/10151114/26654ac0-65f9-11e5-81d5-73d18787a3dc.JPG)

**Comment by wwiv** [comment]
when that happens if you can launch visual studo, open the wwiv project
then attach to process bbs.exe (control-alt-P is the key I think)
then find the stacktrace window and post a stacktrace, that'd help

**Comment by BloodStoneBBS** [comment]
I'll see if I can free up enough space on that VM to install VS but I really think this is isolated to the Guest account which I just deleted. I'll know within a couple of days.

**Comment by BloodStoneBBS** [comment]
Well, I may not have done it correctly but... A new guest account had been created and when I came home today, the BBS was stuck at the same window as above. 
Launched VS and attached to bbs.exe yet the Stack window was clear. Clicked in the waiting window above and the session ended. The open window in VS closed and went back to the main window. Somewhere I can find the results of the stack window?

**Comment by BloodStoneBBS** [comment]
Not sure if any of this helps:
'bbs.exe' (Win32): Loaded 'C:\WWIV\bbs.exe'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-runtime-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-core-timezone-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-core-file-l2-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-core-localization-l1-2-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-core-synch-l1-2-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-core-processthreads-l1-1-1.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-core-file-l1-2-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-string-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-heap-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-stdio-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-convert-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-locale-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-math-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-multibyte-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-time-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-filesystem-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-environment-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-utility-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\nsi.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-conio-l1-1-0.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\lpk.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\usp10.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\mswsock.dll'. Cannot find or open the PDB file.
'bbs.exe' (Win32): Loaded 'C:\Windows\System32\WSHTCPIP.DLL'. Cannot find or open the PDB file.
The thread 0x1154 has exited with code 0 (0x0).
The thread 0xd44 has exited with code 0 (0x0).

**Comment by BloodStoneBBS** [comment]
Awesome! Thanks!
