### ISSUE TITLE
Errors on Local Node and Local Window

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#169]
Notice the 
"access returned: 0 errno: 2 file: c:\wwiv\data\email.dat" maeeages
They only appear on local node.

![errors messages on local node](https://cloud.githubusercontent.com/assets/4002194/9672309/65df8e4a-524e-11e5-976e-5a902d102731.png)

**Comment by askpatrickw** [comment]
These kinds of errors show up throughout the local session when a remote client is connected.

**Comment by BloodStoneBBS** [comment]
Just upgraded to 1542 from 1539, now seeing the same in the WFC.
![capture](https://cloud.githubusercontent.com/assets/13243281/9673796/eed2df1e-525c-11e5-9bc1-c6dd2336b7d0.JPG)

**Comment by BloodStoneBBS** [comment]
Also seen in 1541

**Comment by BloodStoneBBS** [comment]
And 1540

**Comment by BloodStoneBBS** [comment]
Back to 1539, all normal.

**Comment by wwiv** [comment]
Fixed by https://github.com/wwivbbs/wwiv/commit/ad42d1fc34ed0ec6303fb65e0e4c634075351a66
I left a debug line in there.. sorry about that.
