### ISSUE TITLE
BBS Crashes when user selected Download Message

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#176]
Unfortunately, this was a new user account and I was not available when it occurred but here is the error:

Log Name:      Application
Source:        Application Error
Date:          9/7/2015 3:08:29 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WWIV5
Description:
Faulting application name: bbs.exe, version: 0.0.0.0, time stamp: 0x55e8f502
Faulting module name: bbs.exe, version: 0.0.0.0, time stamp: 0x55e8f502
Exception code: 0xc0000005
Fault offset: 0x0006856c
Faulting process id: 0xdf0
Faulting application start time: 0x01d0e9b962ab230e
Faulting application path: C:\wwiv\bbs.exe
Faulting module path: C:\wwiv\bbs.exe
Report Id: f8105446-55ac-11e5-96e2-534e57000000
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-09-07T22:08:29.000000000Z" />
    <EventRecordID>8100</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WWIV5</Computer>
    <Security />
  </System>
  <EventData>
    <Data>bbs.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>55e8f502</Data>
    <Data>bbs.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>55e8f502</Data>
    <Data>c0000005</Data>
    <Data>0006856c</Data>
    <Data>df0</Data>
    <Data>01d0e9b962ab230e</Data>
    <Data>C:\wwiv\bbs.exe</Data>
    <Data>C:\wwiv\bbs.exe</Data>
    <Data>f8105446-55ac-11e5-96e2-534e57000000</Data>
  </EventData>
</Event>

**Comment by BloodStoneBBS** [comment]
![capture](https://cloud.githubusercontent.com/assets/13243281/9723718/fe7ef43e-557c-11e5-974b-65d0be1efe0e.JPG)

**Comment by ericpareja** [comment]
What protocols are available?

**Comment by ericpareja** [comment]
This happens only in the M)ail section. In Message base, Downloading a file works.

Mail {QSRIDAF?-+GEZPVUOLCNY@} : Y
E-mail download -

Filename: Y

Program received signal SIGSEGV, Segmentation fault.
0x0816fb56 in send_file (pszFileName=0x828abbc "/home/xenos/alcove/tmp/1/Y", 
    sent=0xbfffe4f8, abort=0x0, sfn=0x828abbc "/home/xenos/alcove/tmp/1/Y", 
    dn=-1, fs=1227) at /home/xenos/wwv/github/wwiv/bbs/sr.cpp:470
470   _abort = false;
(gdb) bt
#0  0x0816fb56 in send_file (
    pszFileName=0x828abbc "/home/xenos/alcove/tmp/1/Y", sent=0xbfffe4f8, 
    abort=0x0, sfn=0x828abbc "/home/xenos/alcove/tmp/1/Y", dn=-1, fs=1227)
    at /home/xenos/wwv/github/wwiv/bbs/sr.cpp:470
#1  0x0816bc1e in readmail (mode=0)
    at /home/xenos/wwv/github/wwiv/bbs/readmail.cpp:1197
#2  0x0811d494 in ReadEMail ()
    at /home/xenos/wwv/github/wwiv/bbs/menusupp.cpp:224
#3  0x080fb1d1 in wwiv::menus::__lambda43::operator() (__closure=0x82b2d98, 
    pMenuData=0x82a08b8, param1=..., param2=...)
    at /home/xenos/wwv/github/wwiv/bbs/menuinterpretcommand.cpp:244
#4  0x0810a741 in std::_Function_handler<void(wwiv::menus::MenuInstanceData_, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&), wwiv::menus::CreateCommandMap()::__lambda43>::_M_invoke(const std::_Any_data &, wwiv::menus::MenuInstanceData _, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > &, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > &) (__functor=..., __args#0=0x82a08b8, 
    __args#1=..., __args#2=...) at /usr/include/c++/4.8/functional:2071
#5  0x081196ae in std::function<void (wwiv::menus::MenuInstanceData_, std::string const&, std::string const&)>::operator()(wwiv::menus::MenuInstanceData*, std::string const&, std::string const&) const (this=0x82b2d84, __args#0=0x82a08b8, 
    __args#1=..., __args#2=...) at /usr/include/c++/4.8/functional:2471
---Type <return> to continue, or q <return> to quit---
#6  0x080fab39 in wwiv::menus::InterpretCommand (pMenuData=0x82a08b8, 
    pszScript=0xbfffefdb "ReadEMail")
    at /home/xenos/wwv/github/wwiv/bbs/menuinterpretcommand.cpp:82
#7  0x080f0795 in wwiv::menus::MenuExecuteCommand (menu_data=0x82a08b8, 
    command=...) at /home/xenos/wwv/github/wwiv/bbs/menu.cpp:333
#8  0x080ef502 in wwiv::menus::MenuInstanceData::Menus (this=0x82a08b8, 
    menuDirectory=..., menuName=...)
    at /home/xenos/wwv/github/wwiv/bbs/menu.cpp:131
#9  0x080ef337 in wwiv::menus::StartMenus ()
    at /home/xenos/wwv/github/wwiv/bbs/menu.cpp:109
#10 0x080ef1a0 in wwiv::menus::mainmenu ()
    at /home/xenos/wwv/github/wwiv/bbs/menu.cpp:81
#11 0x080ba523 in WApplication::Run (this=0x828a8c0, argc=3, argv=0xbffff434)
    at /home/xenos/wwv/github/wwiv/bbs/bbs.cpp:950
#12 0x080b9712 in WApplication::BBSMainLoop (this=0x828a8c0, argc=3, 
    argv=0xbffff434) at /home/xenos/wwv/github/wwiv/bbs/bbs.cpp:654
#13 0x080bb81e in bbsmain (argc=3, argv=0xbffff434)
    at /home/xenos/wwv/github/wwiv/bbs/bbs.cpp:1172
#14 0x080b7e28 in main (argc=3, argv=0xbffff434)
    at /home/xenos/wwv/github/wwiv/bbs/bbs_main.cpp:22
(gdb)

**Comment by BloodStoneBBS** [comment]
Latest build: 1565 on Windows 7 Pro x86
Note exception code "0xc0000005" Typically an access denied error?

![capture1](https://cloud.githubusercontent.com/assets/13243281/9833117/da5d676c-5940-11e5-8d86-f757bc0c9894.JPG)

Log Name:      Application
Source:        Application Error
Date:          9/12/2015 11:17:34 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WWIV5
Description:
Faulting application name: bbs.exe, version: 0.0.0.0, time stamp: 0x55e8f502
Faulting module name: bbs.exe, version: 0.0.0.0, time stamp: 0x55e8f502
Exception code: 0xc0000005
Fault offset: 0x0006856c
Faulting process id: 0xb34
Faulting application start time: 0x01d0ed872adbba3e
Faulting application path: C:\wwiv\bbs.exe
Faulting module path: C:\wwiv\bbs.exe
Report Id: 89dd4656-597a-11e5-96e2-534e57000000
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-09-12T18:17:34.000000000Z" />
    <EventRecordID>8136</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WWIV5</Computer>
    <Security />
  </System>
  <EventData>
    <Data>bbs.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>55e8f502</Data>
    <Data>bbs.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>55e8f502</Data>
    <Data>c0000005</Data>
    <Data>0006856c</Data>
    <Data>b34</Data>
    <Data>01d0ed872adbba3e</Data>
    <Data>C:\wwiv\bbs.exe</Data>
    <Data>C:\wwiv\bbs.exe</Data>
    <Data>89dd4656-597a-11e5-96e2-534e57000000</Data>
  </EventData>
</Event>

**Comment by BloodStoneBBS** [comment]
Happens on Windows Server 2008 as well:
Log Name:      Application
Source:        Application Error
Date:          9/12/2015 12:21:48 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Win2K8x32
Description:
Faulting application bbs.exe, version 0.0.0.0, time stamp 0x55e8f502, faulting module bbs.exe, version 0.0.0.0, time stamp 0x55e8f502, exception code 0xc0000005, fault offset 0x0006856c, process id 0xe08, application start time 0x01d0ed9023b71273.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-09-12T19:21:48.000Z" />
    <EventRecordID>1912</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Win2K8x32</Computer>
    <Security />
  </System>
  <EventData>
    <Data>bbs.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>55e8f502</Data>
    <Data>bbs.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>55e8f502</Data>
    <Data>c0000005</Data>
    <Data>0006856c</Data>
    <Data>e08</Data>
    <Data>01d0ed9023b71273</Data>
  </EventData>
</Event>

![capture3](https://cloud.githubusercontent.com/assets/13243281/9833402/1a6e94a8-594a-11e5-977e-f224e1792722.JPG)

**Comment by ericpareja** [comment]
Still occurs in Windows 7 and Server 2008. How do we proceed from here?

**Comment by wwiv** [comment]
I think the problem was that the bbs.exe on the jenkins builds were not updated, therefore did not contain your fix.  I'll close this out since it should be fixed. Please reopen if it's still broken.

You'll want build 1567 or later since I found a new crash that happens when you don't have a tag (which was uncovered by fixing that)

**Comment by BloodStoneBBS** [comment]
Build 1567 did the trick! Thanks Guys!
