### ISSUE TITLE
SBBSEXEC#.LOG full up with "!UNKNOWN VDD_OP: 14"

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#178]
Multiple SBBSEXEC#.LOG files, growing large 63MB & 77MB and full of this comment:
!UNKNOWN VDD_OP: 14

**Comment by BloodStoneBBS** [comment]
Following up, at the bottom of one log is this:
VDD_CLOSE: rdbuf=0 status_poll=3328543 inbuf_poll=0 online_poll=0 yields=0
           read=687 bytes (in 687 calls)
           wrote=269223 bytes (in 269223 calls)

Something to do with all the probes from China over the last couple of days?

**Comment by wwiv** [comment]
how big is it zipped.
can you try the sbbsexec.dll from the most recent wwiv zip files. I rebuilt it.

**Comment by wwiv** [comment]
Jimmy, is this still happening?

**Comment by BloodStoneBBS** [comment]
Yes however, I am only now seeing that you rebuilt sbbsexec.dll. I will swap it out today and watch it for a few days.

EDIT: Ugh... the one in my %systemroot%\system32 folder was from 2004. Swapped with new dated 11/08/2015. Build 1637?

**Comment by BloodStoneBBS** [comment]
Accidentally closed - Will test for a couple of days and then close upon confirmation the new build resolves this.

**Comment by wwiv** [comment]
Thanks, I didn't do anything to fix it, but at least I know what is in this one.

**Comment by BloodStoneBBS** [comment]
After updating my local copy of %systemroot%\system32\sbbsexec.dll to the later build, the log file is no longer being generated.
Thanks!
