### ISSUE TITLE
Need to get the sync fossil driver compiling

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#180]
Got the DDK, need to pull in enough other files to get it building.
Also we're ok to put it into the wwiv zip file, it's not linking the two and (DigitalMan also doesn't consider it linking), and we distribute the source to it anyway (so GPL is happy).  Since it's a small amount of code, maybe just include the source in a zip file in the wwiv zip to make it easy.

**Comment by askpatrickw** [comment]
Related to #147

**Comment by wwiv** [comment]
https://github.com/wwivbbs/syncfoss/commit/7ebb3b8c4221916ffb4d3f1e2d96c1ee1173fa8e got it building locally (at least)

**Comment by wwiv** [comment]
Note that the XP DDK is the last one that includes support for the VDDs
See https://support.microsoft.com/en-us/kb/322643

**Comment by wwiv** [comment]
it compiles.
