### ISSUE TITLE
tag files no longer appended to network posts

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#181]
general.tag or subtype.tag files no longer get appended to network posts.

in commit 2e6fb6cf3bda3d3db209fcdc06f1943b8425378b in the rewrite of inmsg.cpp to use string. FindTagFileName() seems to have stopped working.

in prior commit 20fbae3767b02ab29b5ec82c811c7e4e2bc74080, tag files get appended properly.

haven't investigated further, but will put notes here.

**Comment by askpatrickw** [comment]
What are all the .TAG files ? I don't see that listed anywhere. I see you mention these two, what do they do?
general.tag
subtype.tag

In wwiveedit there's BBSXXXX.tag which goes outbound on every message edited by WWIV.
In WWIVNet there's INTERNET.TAG which goes outbound on all email (& Subs?? not sure)

Anything else?

**Comment by ericpareja** [comment]
TAG files in WWIVEdit are for taglines added by the user, selectable at posting time.

TAG files on the BBS itself are like FidoNet Origin lines at the bottom of networked subs. On WWIV systems though, the TAG files appended to networked subs are prefixed with Ctrl-D on each line, and users have the option to display them partially, fully or not at all. See D)efaults.
O)ptional lines.

TAG files can also be customized on a per SUB basis. Hence, subtype.tag. General.tag is the default tag file used when subtype.tag is absent.

**Comment by askpatrickw** [comment]
Re-opening till the wiki is also updated.
Can you look at this and let me know if anything is missing:
https://github.com/wwivbbs/wwiv/wiki/taglines

Just put the notes here and assign it back to me. I'll update the wiki

Thanks,
-p

**Comment by ericpareja** [comment]
There's a report of taglines still not being appended on the Windows builds, so let's keep this issue open until it's resolved.l

**Comment by ericpareja** [comment]
@bloodstonebbs does it work in the newest windows build?

**Comment by BloodStoneBBS** [comment]
Not as of build 1564. Have to head out the door, will try the latest build this evening.

**Comment by wwiv** [comment]
Ok latest build (1567 i think) should have this working.  The problem was no new builds on windows of bbs.exe were happening (#191)

**Comment by BloodStoneBBS** [comment]
Build 1567 did the trick! Thanks Guys!
