### ISSUE TITLE
bbs -W needs to be finished

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#184]
Things that are obviously missing
- beginday support
- networkb listening support

**Comment by askpatrickw** [comment]
Can you configure the PORT on the command line parameter or with a config file?

**Comment by BloodStoneBBS** [comment]
Does bbs -w need to be up and running for the inbound telnet functions to work?

**Comment by wwiv** [comment]
Nope

**Comment by wwiv** [comment]
bbs -w is no more.
