### ISSUE TITLE
Linux Build information for wiki

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#194]
I added the windows information, someone else needs to do the linux section.

https://github.com/wwivbbs/wwiv/wiki/buildwwiv5

**Comment by BloodStoneBBS** [comment]
Has this: https://github.com/wwivbbs/wwiv/wiki/installlinux been tried on a Raspberry Pi? 
I managed to get it to compile after changing the libncurses for the ARM platform. But I am having difficulties with the //UE accepting the commands to change SL & DSL and have yet to figure out the xinetd & telnetd functionality. Have been able to create a user and login locally and elevated the user to SysOp in INIT. Will play with it more early next week and see if I can figure out what's going on. If successful, I'll add an addendum to the Wiki for Raspbian on the RPi2.

**Comment by askpatrickw** [comment]
No, no one is running on ARM. I thought about it too, then realized doors and all the other things for which we don't have source code or can't open source will not run on ARM so I decided not to bother.  You want an x86 Single Board Computer: https://en.wikipedia.org/wiki/Comparison_of_single-board_computers

**Comment by askpatrickw** [comment]
But, please don't use the Issues as a forum. Post these questions as NEW issues or on WWIVNet. thanks!

**Comment by granitepenguin** [comment]
Linux build info updated
