### ISSUE TITLE
BBS.exe does not redraw properly after events are triggered

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#199]
After BBS-W does stuff and spews activity on the screen, it does redraw the WFC screen.

Example:  

![bbs-w-redraw](https://cloud.githubusercontent.com/assets/4002194/9861214/ca419848-5ae5-11e5-9cf8-2191ac8551bc.png)

**Comment by BloodStoneBBS** [comment]
Same with 1586 on Win7
![capture](https://cloud.githubusercontent.com/assets/13243281/10008764/df7b6f2a-6087-11e5-84f2-40e0808dce18.JPG)

**Comment by askpatrickw** [comment]
This is not limited to BBS -W. It also happens with bbs.exe which we are now using for WWIVNet over BinkP

**Comment by askpatrickw** [comment]
Another thing I noticed. When you use "/" to force callout it exits and redraws the screen properly.

**Comment by granitepenguin** [comment]
looks like this also happens on linux.

**Comment by wwiv** [comment]
bbs -w is no more.
