### ISSUE TITLE
bbs -w is PAUSED (?) at a user mode prompt

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#202]
Occasionally I see BBS -W is paused waiting for Y\N\C user interaction. That seems bad.
After I hit Y it seems to continue on...

![bbs-w paused](https://cloud.githubusercontent.com/assets/4002194/9920168/a717cda4-5c86-11e5-93de-4b2f64506aaf.png)

**Comment by askpatrickw** [comment]
Another waiting at prompt.... 

![bbs-w waiting on prompt](https://github-cloud.s3.amazonaws.com/assets/4002194/10566255/05929430-7597-11e5-899b-96a89de54c72.png)

**Comment by wwiv** [comment]
bbs -w is no more.
