### ISSUE TITLE
bbs -w crashes when you type (R)ead all mail at the WFC

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#206]
Build is 1573
Windows 7

**Comment by wwiv** [comment]
doesn't crash for me

**Comment by BloodStoneBBS** [comment]
I can't replicate this either. Could it be the content of a specific message?

**Comment by askpatrickw** [comment]
I'll assign these to myself while I work on a repro...

**Comment by askpatrickw** [comment]
I've been trying and can't repro this.. closing.
