### ISSUE TITLE
BBS -W crashes after selecting an email to read

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#207]
At the BBS -w WFC
use M to go the read mail screen
select a message by number
-crash-

Build 1573
Windows 7

**Comment by wwiv** [comment]
doesn't crash for me.

**Comment by BloodStoneBBS** [comment]
Another I can't replicate. Does it happen regardless of message?

**Comment by askpatrickw** [comment]
I'll assign these to myself while I work on a repro...

**Comment by askpatrickw** [comment]
I've been trying and can't repro this.. closing.
