### ISSUE TITLE
version number is "(development)" in jenkins builds

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#210]
it's not updating for some reason.

**Comment by wwiv** [comment]
error: 
U\* pdating the Build Number in version.cpp

The system cannot f

From: 
http://build.wwivbbs.org/job/wwiv/1574/label=windows/console#L1,321

**Comment by ericpareja** [comment]
TextTransform is gone?

**Comment by askpatrickw** [comment]
I dunno how this works so I stopped, but a few days ago I did some googling on this topic to get the binaries properly stamped with versions and it looked to me like we did not have the version resources added to each binary. At least that's what this said: http://stackoverflow.com/questions/308307/setting-file-version-number-in-visual-studio-2005-c

It was a change I was uncomfortable making myself though.
