### ISSUE TITLE
Set Transfer Options File Tagging has no effect

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#218]
Changing the settings in Transfer Options -> [5] File Tagging has no effect.
ListPlus is always enabled.

**Comment by ericpareja** [comment]
Ok... this is actually in the codebase, switchable with FORCE_LP in listplus.h

**Comment by wwiv** [comment]
Hmm, if we're always going to force it, then I think it's make sense to remove it from the UI
