### ISSUE TITLE
Build is hung

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#222]
There has been a build hung for a day. It follows from your last merges to fix comments in Build.CMD.

Commit 72f430d1527ebd7158fd70ec9108c54346ef250a by rushfan
fix comments in build.cmd

**Comment by wwiv** [comment]
yup - hung trying to send an IRC message...

**Comment by wwiv** [comment]
I bounced jenkins slave using the services mmc page

**Comment by wwiv** [comment]
and now bounced the master too...

**Comment by wwiv** [comment]
and it's fixed

**Comment by askpatrickw** [comment]
Well you did say that would happen...
