### ISSUE TITLE
Modify Upgrade batch file to also copy syncfoss DLL

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#225]
sbbsexec.dll should also be copied \wwiv\ on upgrades
Unfortunately it also needs to go to \windows\system32\ not sure if that will be a problem or not

**Comment by wwiv** [comment]
yes - do to it easily you need to use explorer and approve the UAT. there may be better ways that use powershell or something.

**Comment by askpatrickw** [comment]
Going to look into this method later: 
https://sites.google.com/site/eneerge/scripts/batchgotadmin

**Comment by askpatrickw** [comment]
You can run it in an admin cmd window... that works.

**Comment by askpatrickw** [comment]
Fixed!
