### ISSUE TITLE
Add WWIVNet file maintenance steps

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#229]
What do you do to update your local copies of the files?

**Comment by BloodStoneBBS** [comment]
Since I run my own Usenet feeds, I have to copy and paste new information from Eli's network files into my own. If I don't, NEWS.EXE looks for 32767 via 1 which naturally, breaks news on my bbs.

**Comment by askpatrickw** [comment]
I diffed the files in http://build.wwiv.us/job/wwivnet/1/label=windows/
with my \nets\wwivnet\ files and here's what I think is up, please double check my notes.

There are three files which come in wwivnet-#.zip which have to edited if you have your own Usenet news feed.

| file | what needs to be changed |
| --- | --- |
| BBSLIST.0 | append a new line with `99` |
| BBSLIST.1 | remove the last line in the file `@32767      *704-854-NEWS #14400        !      [     ]  "WWIVNET Internet Gateway"` |
| CONNECT.0 | Modify the last line from `@32767      1` to  `@32767      99` |

**Comment by askpatrickw** [comment]
OK... we're rocking on the happy path to not have to do this.
If that fails for some reason, we'll re-open this

**Comment by BloodStoneBBS** [comment]
BBSLIST.99 containing the @32767 *###-###-NEWS #14400 ! [ ] "WWIVNET Internet Gateway" is still a requirement, correct?
As is CONNECT.99 ?
