### ISSUE TITLE
When did WWIV 5.0 start and when did the open source Era start?

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#234]
The history wiki is not accurate on this part.

**Comment by wwiv** [comment]
5.0 started in 2000. I can't find the exact time, but I'll look around.  Unfortunately the machine I had at that time died.

Beta-1 was December 10, 2003

Archive:  WWIV5B1U.ZIP
  Length     Date   Time    Name

---

```
15061  12-10-03 05:00   DOSXTRN.EXE
  340  12-10-03 05:00   file_id.diz
```

   151552  12-10-03 05:00   init50.exe
     4716  12-10-03 05:00   LICENSE.AGR
     1672  12-10-03 05:00   readme.txt
   118847  12-10-03 05:00   SBBSEXEC.DLL
    27327  12-10-03 05:00   sbbsexec.vxd
     3157  12-10-03 05:00   whatsnew.txt
   774144  12-10-03 05:00   wwiv50.exe
      207  12-10-03 05:00   WWIVTelnetServer.cnt
   421888  12-10-03 05:00   WWIVTelnetServer.exe
   240782  12-10-03 05:00   WWIVTELNETSERVER.HLP

---

  1759693                   12 files

it moved to sourceforge  on  2004-09-07 as open source

**Comment by wwiv** [comment]
ok, 5.0 started april 12, 1999

**Comment by wwivsoftwareservices** [comment]
Lemme look around.  I probably have the announcement message somewhere.

**Comment by wwiv** [comment]
I posted the announcement that wwiv is open source here:
https://github.com/wwivbbs/wwiv/wiki/WWIV-5.0-OpenSourcing-Announcement-%28September-18,-2004%29

**Comment by wwivsoftwareservices** [comment]
The April 12, 99 date is probably pretty accurate for when we first changed the version information and started developing the feature list.  The concerted effort did not take off until Mid-late 2003 or maybe even 2004.  I know because I started working on WWIV pretty much right after I retired in April 2003. Of course Atani and Rushfan did the lions share of the work even then….

**Comment by askpatrickw** [comment]
Thanks. I cleaned up the page name and added the facts to the history page.
