### ISSUE TITLE
Feature Request SSH for WWIVTelnet Server

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#237]
Have been thinking that adding the ability to switch from Telnet to SSH for BBS access could be a nice benefit.

**Comment by antdude** [comment]
I agree.

**Comment by wwiv** [comment]
libssh looks reasonable. Here's an example:
https://github.com/substack/libssh/blob/master/examples/samplesshd.c

We'd need to make the telnet server just work as-is on port 22 and put this into the bbs code so it can handle auth there.

**Comment by TRI0N** [comment]
Rush that is feasible.. We could have Telnet listen to both Port 23 (telnet) and Port 22 (SSH) and if on SSH send an added parameter to (ex: bbs.exe -ssh) to tell bss.exe the connection is SSH and do the Auth in C++.

**Comment by wwiv** [comment]
With this: https://github.com/wwivbbs/wwiv/pull/676 It works in the BBS now.  @TRI0N is adding support into the telnet server to listen to both 22 and 23 so you don't need to run 2 copies.

**Comment by TRI0N** [comment]
#685 SSH Enabled!
Enjoy!

**Comment by BloodStoneBBS** [comment]
So far, unable to get this to work. (using Sysop account)
I enter user number and then password but it errors out and sessions are left running on host.

![capture](https://cloud.githubusercontent.com/assets/13243281/12682393/04220a0a-c668-11e5-8adb-19b570bab142.PNG)
![capture](https://cloud.githubusercontent.com/assets/13243281/12682409/1bf2ec58-c668-11e5-9b73-de382ca55ed1.PNG)
