### ISSUE TITLE
Display issue in qwk message upload

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#245]
![wwiv_display](https://cloud.githubusercontent.com/assets/13500419/10124710/92fa3310-6510-11e5-8b77-0df2b4bce0ac.jpg)

It labels a message upload for the wrong network, but its more of a cosmetic bug.

**Comment by wwiv** [comment]
is this sub on more than 1 network?

**Comment by mmunson** [comment]
No just 1 network. 

home of Inlandutopia.com Matt Munson's official website

Date: Sun, 27 Sep 2015 13:51:13 -0700
