### ISSUE TITLE
WFC command T cannot be configured in INIT

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#249]
Older documentation shows that you can configure the WFC's "T" option to launch your terminal program as configured in INIT but the option is missing from INIT.
Still shows in WFC's ? menu. 
Broken or just not fully removed? It would be nice to be able to launch SyncTerm or other Terminal Pgm from the WFC.

**Comment by wwiv** [comment]
I removed it since I didn't think it was useful.  I can put it back in.

**Comment by BloodStoneBBS** [comment]
I'd love to see it back. I used the feature a lot back in the day but only recently noticed that it was gone. 
Maybe toss the idea among the others? 
If not, the WFC help menu still displays the option.
J..
