### ISSUE TITLE
Make a general purpose windows batch file for doors

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#256]
Copy this guy
https://github.com/ryanfantus/daydream/blob/master/daydream-2.20.0/DOCS/dosdoors.howto

**Comment by wwiv** [comment]
That link doesn't work, so I can't see what they were doing.

Also ideally making dosbox or dosemu easier is a better idea.  And for linux we have these:
https://github.com/wwivbbs/wwiv/blob/master/bbs/admin/unix/lib/door-lib-v0.sh
