### ISSUE TITLE
add checking for duplicate packets into networkb

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#262]
Not a full message level dup checker, but rather just just a crc of the packet file to ensure we don't keep receiving the same file over and over again

**Comment by BloodStoneBBS** [comment]
Looks like the dupe's are now flowing over Net37/38 as well. 
Two posts from the Blood Stone are duplicating over WWIVnet but I can't find any trace of them in the data or network directories. On 1@1's side?

**Comment by BloodStoneBBS** [comment]
I'm hoping someone here that sees this will contact Eli if they can. two subs are being flooded with dupes that originated from my BBS. I'm not sending out any duplicate packets.

**Comment by wwiv** [comment]
I think https://github.com/wwivbbs/wwiv/issues/258 covered most of it.

**Comment by wwiv** [comment]
yes #258 covers enough of it, other dupes should be caught at the msgid level.
