### ISSUE TITLE
Get All Systems to upgrade to Net38B3 

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#269]
When everyone is on the latest Net38, Rushfan will then work on a new EN\DE  to use with a new Netup to distribute net files.
http://www.wwiv.us/net38b3.zip

Status

| Node | Name | Net38 Status |
| --- | --- | :-: |
| @1 | Skulls & Crossbones | Done |
| @2 | Eagle's Dare | local mailbox full can't contact 18 Oct - 20 Oct same |
| @11 | Weather Station | Done |
| @50 | The Mountain Empire | Done |
| @60 | Aliens' Alcove | Done |
| @61 | Aliens' Abode | Done |
| @70 | The Gate BBS | Can not connect |
| @72 | Flashback BBS | No known telnet |
| @73 | The eSource BBS | No known telnet |
| @90 | The Wretched Beagle | Done |
| @206 | Cloud City BBS | Done |
| @255 | Alpha Centauri BBS | Done |
| @513 |  | Done |
| @514 | Mystic Rhythms | Done |
| @666 | Hawkeye's BBS | No known telnet |
| @707 | The Blood Stone | Done |
| @708 | Manic Arcade BBS | Done |
| @815 | Inland Utopia | Done |
| @71 | The Radio Shack | No port open |
| @177 | Dunedain BBS | No port open |
| @180 | Nitemare Cafe | No port open, HTTP says site is moving |

**Comment by BloodStoneBBS** [comment]
The Blood Stone BBS and ManicArcade are both up to date.
707/708

**Comment by wwiv** [comment]
514/513 are up to date

**Comment by W7PEA** [comment]
This is blocked because of the dupes on wwivnet I've had my site off the net which means I can't email anyone or get the replies to the messages I sent previously.

**Comment by askpatrickw** [comment]
With the Exception of Eagle's Dare who I can't contact. All the active boards are upgraded. We'll handle Frank separately if needed when we roll to BinkP
