### ISSUE TITLE
Starting in Build 1601 Can not login with #1 Account

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#272]
Starting with this set of changes and the 1601 build, I can not login with my #1 account.
https://github.com/wwivbbs/wwiv/commit/f11b3b21a3132815e0281a187d34e2680d6ccad9

Repros in 1602 and 1603.

Login says "Unknown user"

**Comment by BloodStoneBBS** [comment]
No problems on my Windows installs. 1602

**Comment by wwiv** [comment]
You are logging in by name, I'd assume?  How many users in your system. open up names.lst in a text editor, do you see your number 1 username in there?

**Comment by wwiv** [comment]
I can't repro this

**Comment by askpatrickw** [comment]
yes, logging in by name.
users.lst looks fine. Only 4 users on my board. (I've not opened yet).

1598 is the last build that works.

**Comment by BloodStoneBBS** [comment]
Odd that it works on both of my Windows installs. Something specific with this edit?
https://github.com/wwivbbs/wwiv/commit/f094954ab0d17a53810dac474cc4df2c27e89b6b

**Comment by askpatrickw** [comment]
Is the first line in your users.lst a blank line when you look at it in notepad?

**Comment by BloodStoneBBS** [comment]
Yes.

**Comment by wwiv** [comment]
I bet there's no user with a name that starts after P (lexicographical)
Add a user ZZZ and then see if you can log in, I bet you can

**Comment by wwiv** [comment]
hmm, that's not it...

**Comment by askpatrickw** [comment]
Fix confirmed to work!
