### ISSUE TITLE
Force Scan on Sub not working

### ISSUE THREAD

**Issue by ericpareja** [wwivbbs/wwiv#273]
Setting USE_FORCE_SCAN = Y and FORCE_SCAN_SUBNUM = 1 in WWIV.INI does not force users to read through the mandatory sub.

**Comment by wwiv** [comment]
I think the setting is FORCE_SCAN not USE_FORCE_SCAN

**Comment by ericpareja** [comment]
FORCE_SCAN now works, but FORCE_SCAN_SUBNUM references the wrong sub. Doesn't follow SUBNUM in //BE. Possibly because a SUB had been inserted in the linked list.

**Comment by BloodStoneBBS** [comment]
Should the entry in wwiv.ini for the sub# be interpreted as N-1? Or...?

**Comment by ericpareja** [comment]
I'm trying to track how it's interpreting the value in WWIV.INI

**Comment by wwiv** [comment]
should be N, not sure why it'd be anything else.

**Comment by askpatrickw** [comment]
I think the list of SUBs is a zero based array. So 0 = the first sub. That's what worked on my board.

**Comment by askpatrickw** [comment]
I'm closing this because I can see it works on my board.

**Comment by BloodStoneBBS** [comment]
I too have it working on my board using 0 in wwiv.ini for sub 0 in BE which shows as 1 on the BBS.
