### ISSUE TITLE
WWIV BBS Continuity Work

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#282]
This is just catch-all for things we need to figure out since Eli's passing, just add comments as you need.

**Comment by askpatrickw** [comment]
~~WWIVBBS.COM Domain~~
We're using WWIVBBS.org as our landing page, .com isn't necessary, not that holding it wouldn't be nice. We can try to grab it when it expires in 2016.

**Comment by askpatrickw** [comment]
~~IRC Server~~

Venom has moved this to his own server at his place.

**Comment by askpatrickw** [comment]
WWIVNet - ~~migration to a new SMTP\POP or~~ straight to BinkP

**Comment by BloodStoneBBS** [comment]
Pick one BBS to host the above conversations?

**Comment by wwiv** [comment]
find new @ 1
find new owner for all of Eli's subs (the ones hosted at @ 1, ideally just move them to the new @ 1)

@11      : Weather Station                 telnet://bbs.weather-station.org
will become
@1      : Weather Station                 telnet://bbs.weather-station.org

**Comment by wwivsoftwareservices** [comment]
What happened to Eli?

**Comment by wwiv** [comment]
I emailed dean.

**Comment by granitepenguin** [comment]
WWIVNet - discuss architecture again to help avoid the same problem happening again.  Ultimately, binkp will fix a lot of this, but we still have the issue of subs being hosted in only one place.  That one board goes away and the sub is lost.

**Comment by askpatrickw** [comment]
All of these issues have been addressed or moved into separate issues for future tracking.
