### ISSUE TITLE
DOS network code doesn't work against 64-bit BBS

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#294]
trying to configure binkp rushnet and testing with network3 isn't working.

net info is configured like this (it's the second network defined):

> Net Type  : WWIVnet  
> Net Name  : RushNet  
> Node #    : 3  
> Directory : nets/rushnet/

and the results from running network3 y .1 are : 

> WWIV Networking Software
> Copyright 1998-2015 WWIV Software Services.
> 
> network3: [net38b3](Jan 25 2015, 07:15:26)
> ■ Analyzing  connections...
> 
> No system number set in INIT...
> 
> Aborting.

Network3 successfully processes .0 network (WWIVnet)

**Comment by granitepenguin** [comment]
Tried net37.  Same result:

> net37: Analyzing  connections...
> 
> No system number set in INIT...
> Aborting.

**Comment by wwiv** [comment]
The problem is that net_networks_rec is 8 bytes too big on 64-bit compiles since the pointers are saved

**Comment by wwiv** [comment]
See http://stackoverflow.com/questions/5805874/the-proper-way-of-forcing-a-32-bit-compile-using-cmake
