### ISSUE TITLE
Get WWIV Registration List

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#299]
It would be great to have an archive of all the historical WWIV registrants for the archives. No addresses or phone numbers, just BBS, SysOP, Area Code, City.

**Comment by wwivsoftwareservices** [comment]
I have most of the data here somewhere.  There is a list that Filo compiled and passed on to me.  I have a database somewhere of all the post 1999 registrations as well.  I’ll have to dig around a bit and see what turns up.

**Comment by askpatrickw** [comment]
If you have it and can post it someplace I'll clean it up and get it online.

**Comment by JasonOlsen** [comment]
> If you have it and can post it someplace I'll clean it up and get it online.

I have a few colleagues that are fairly talented and a pretty wide range of platforms/tools available, so I'm happy to offer assistance on the cleanup/conversion/normalization effort.

**Comment by wwivsoftwareservices** [comment]
FYI:  I located the entire registration database and forwarded it to Rushfan.

The information therein is not for public consumption or posting. I really do NOT want to see it in some google search of the web. I think we would all view that as a violation of public trust.  And yes, I do believe the trust factor needs to be maintained even if the address information is 20 years old. Collectively, we have no right to release this information to third parties. 

As I told Rushfan, I have no issues with this group being privy to the contents.  As long as reasonable efforts to establish identity are made, we should and will provide registration information to the registered user on request. If you can verify a name and even a portion of an address, that’s good enough for me.

Dean

**Comment by granitepenguin** [comment]
Perfectly understandable and appropriate, Dean.  maybe we just note that we do have the information and document how someone can get their old reg number (i.e., fill out this form and we'll send it to you).

**Comment by JasonOlsen** [comment]
Agreed, this is a very valid concern and speaks well of the professionalism of everyone who has been and continues to be involved in WWIV. Thanks, Dean.

> maybe we just note that we do have the information and document how someone can get their old reg number

The web form idea seems like a good way to go.

**Comment by wwiv** [comment]
great idea, I'll make one for this

**Comment by TRI0N** [comment]
If anyone needs me to make a nice HTML5 jQuery Form let me know.. For example:
[http://www.gregsitservices.com/contact.php](http://www.gregsitservices.com/contact.php)
Field Validations and Spam Control.

**Comment by fcreid** [comment]
Absolutely agreed!

Frank

**Comment by wwiv** [comment]
The volume will probably be so low I was thinking just a Google spreadsheet
form on wwivbbs.org

**Comment by wwiv** [comment]
let's just make it simple, if you need your pw, ask me in irc, email me on my bbs 1@513 or rushfan@1.
