### ISSUE TITLE
Usenet Page needs a rewrite 

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#304]
https://wwivbbs.readthedocs.org/en/latest/usenet/
Since we simplified the net files this will all need updating.

**Comment by askpatrickw** [comment]
I'm working on this today. I asked @BloodStoneBBS  for some information on his setup at his bbs. I think the existing docs use outdated information based on the old smtp\pop days.

**Comment by wwiv** [comment]
@BloodStoneBBS Any updates? Did you move to a new network for your internet news vs. putting it into wwivnet?

**Comment by BloodStoneBBS** [comment]
Sorry... I got started on it but family obligations sidelined it a bit. I have it set uo best I can tell but when I run my batch, it tries using legacy and tries to dial out with a modem. Any suggestions?

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by wwiv** [comment]
I saw this where I had the wrong network number.
the command line should just be networkp.exe /n32767 .X (where X for me is 3)

**Comment by askpatrickw** [comment]
I saw the new info about using  a new network. I'll look at my config and switch to that and see if I can move forward. Even without that, at this point, I can get it to download newsrc and I can see it process messages, but it seems to be skipping all of them and not putting then in WWIV. Maybe alt.bbs and alt.bbs.wwiv are just too inactive and I should try a more active newsgroup.

**Comment by BloodStoneBBS** [comment]
Am now able to pull Usenet into new network (internet) but have yet to be able to post. The s32767.net doe not appear to be generating and no posting. Are there any additional files required in the alternative network folder? de1.exe or.... ?
network3 Y .1 results are looking clean.

**Comment by wwiv** [comment]
make sure you add 32767 as a subscriber of the sub.  

This is working for me.

**Comment by BloodStoneBBS** [comment]
In your Internet network, are you using *.net for your network files or the older *.0 or *.1 ?
While I have been able to get my usenet to pull messages and place them in the appropriate subs, I just can't seem to get it to post. 
Perhaps something additional in net.ini needs to be addressed? primary & secondary networks?

**Comment by wwiv** [comment]
It's actually .3.

Can you screen shot boarbedit for the sub?

**Comment by BloodStoneBBS** [comment]
Ok, mine is .1 for this install. Looked at BE and can clearly see that I flaked as somewhere along the way, I pooched the config. The networks under "J" were gone. So I just re-added the Usenet network and now my usenet is working!

Ok.. I'll try and outline the steps for the documentation Monday evening.

**Comment by askpatrickw** [comment]
That's great @BloodStoneBBS I'll hold off on changing my setup so I can test your docs.

**Comment by BloodStoneBBS** [comment]
Ok,
Sorry for the late reply - I just submitted a pull request (or 4, sorry) for the new doc on Git.
We may want to triple check the steps though. This was all from my notes setting up Usenet on a clean install of WWIV 5.0.0 with WWIVnet as net 0. My Usenet is .1.

**Comment by BloodStoneBBS** [comment]
@W7PEA It's up and ready if you want to try walking though the steps. 
Feel free to edit, append, format... etc.. My formatting skills are a tad lacking ;-)
http://wwivbbs.readthedocs.org/en/latest/usenet/

**Comment by askpatrickw** [comment]
Yay! I'm on Usenet!! Receiving and posting when I run the net updated from WFC.
I still have a couple of questions:
1. Does the email you put in for @1 in address.net need to be a valid email? Is the value significant in anyway? Where is it shared?
2. When you add a sub to the Usenet network, you selected to allow Auto-Add and to publish in Subs.lst. Should you really do that? Isn't this a net no one will join?
3. In your usenet-toss.bat you reference networkp. I believe with the updated NETXX binaries you should just use network.
4. Also on my windows10 box, that command (network or networkp) results in an error that COM1 cannot be opened. Can you confirm what you are running. Seems odd mine would fail so badly.

But overall this is awesome thank you!!

**Comment by BloodStoneBBS** [comment]
@W7PEA 
RE: 
    "Does the email you put in for @1 in address.net need to be a valid email? Is the value significant in anyway? Where is it shared?"

Good question. I am not certain but I continued to get errors with network3 as it could not find address.net si I simply replicated one using the WWIVnet address.net file. I suspect that it may work fine as an empty file.

```
"When you add a sub to the Usenet network, you selected to allow Auto-Add and to publish in Subs.lst. Should you really do that? Isn't this a net no one will join?"
```

Good point. Let's delete that step and make it not shared.

   " In your usenet-toss.bat you reference networkp. I believe with the updated NETXX binaries you should just use network."

Yes. I initially had some issues where using network would initiate legacy and try dialing out via modem. Neglected to change it back. I just tested CALL NETWORK /N32767 .1 and it worked.

```
"Also on my windows10 box, that command (network or networkp) results in an error that COM1 cannot be opened. Can you confirm what you are running. Seems odd mine would fail so badly."
```

My lab box is currently Windows Server 2008 x86. I'll see if I can dig up some time this weekend to install a new WinX box and try again but I found that every time I had that same issue, it was my network number config. .1 vs .0 etc...

**Comment by askpatrickw** [comment]
Thanks for the notes!

I'll look at the .x syntax today.

**Comment by askpatrickw** [comment]
This is rockin' now !
