### ISSUE TITLE
Need to document how to rotate logs

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#307]
Networkb log can get huge fast. Need to document log rotate on Windows

**Comment by askpatrickw** [comment]
See: https://github.com/wwivbbs/wwiv/wiki/logfiles

**Comment by askpatrickw** [comment]
I created a batch file in the ops folder
https://github.com/wwivbbs/ops/blob/master/wintools/wwiv5_logmover.bat

**Comment by askpatrickw** [comment]
Add Deleting to the batch fiel

**Comment by askpatrickw** [comment]
Batchfile works. You can schedule it with Windows Task Scheduler
