### ISSUE TITLE
Not receiving all messages in wwivnet sub

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#310]
OS linux
Build 1627

I noticed that in the WWIVnet Sysop sub (and possibly others, but I haven't dug in yet), I am not receiving all the messages that are being sent to @90.  Logging onto @1, It appears I am only getting messages that did not originate from @1, but that's currently anecdotal.  I noticed this because I saw a reply from @707 that had quoted text from @1 that I do not have.

**Comment by granitepenguin** [comment]
Problem seems to be bigger than just messages from @1 for me.  Here are the last few messages on @1 in wwivsys

│ <1488> Re: No more dupes?                       │ Jimmy Mac #1 @707         │
│_<1489> Can we merge the elements of filenet in w│ Matt Munson #1 @815       │
│_<1490> Re: Jah! You're freaking me out!         │ Jahmas #29 @707           │
│*(1491) Re: Can we merge the elements of filenet │ Weatherman #1 @1 (Mark)   │
[Sub]: WWIVnet Sysop Area [WWIVnet]             Read:[1-1491,^1491],? :

and here's the last few on @90
    <784> Re: No more dupes?                       │ Matt Munson #1 @815
    <785> Re: No more dupes?                       │ Jimmy Mac #1 @707
    <786> Re: No more dupes?                       │ Jimmy Mac #1 @707

1488@1 and 786@90 are the same message.  I haven't gotten any of the last few messages, regardless of where they originated, but I am getting _something_ from @1.  

I20151104:091736 RECV:  M_FILE: s90.net 450 1446641314 0
I20151104:091736        HandleFileRequest; request_line: s90.net 450 1446641314 0
I20151104:091736        remote_network_name(): wwivnet
I20151104:091738 RECV:  DATA PACKET; len: 450; expected: 450 duration:10000
I20151104:091738        file finished; bytes_received: 4294967745
I20151104:091738 SEND:  command: M_GOT: s90.net 449 1446641314
I20151104:091738        Sending EOB

This last one appeared to be only a test message to WWIV Networking (that did come directly from @1)

**Comment by granitepenguin** [comment]
The problem seems to exist in both directions, too.  I just checked a reply I sent to WWIV Networking and it does not appear to have made it to @1

**Comment by askpatrickw** [comment]
I think the best way to test this is to post a new message on 3 or 4 board and just put the date and time in the body of the message.

Then we can see when they all show up on @1 When they show up on the other nodes and in what order.

**Comment by granitepenguin** [comment]
Mark may have found the issue on his board, but we don't know why this matters yet.  The batch file he was using included a `SET WWIV_INSTANCE=1` line that, when removed, fixed the overwrite/append issue.  Still need to investigate why that makes a difference, especially since Rush can't reproduce the symptoms on his own system yet.

**Comment by wwiv** [comment]
Will be worked around in net38 beta-6
