### ISSUE TITLE
Unable to post to Usenet since moving to the new WWIVnet (networkb v38b5)

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#311]
Posts appear to be processed by networkb but do not reach outbound queue for NEWS.EXE to process.
Could be a simple net.ini issue but I have yet to resolve.

**Comment by BloodStoneBBS** [comment]
By commenting out network related fields, it appears that news is trying to poll via modem with networkp
Adding back [NETWORK] and [GENERAL] allows  news to connect and pull news.

**Comment by BloodStoneBBS** [comment]
Posting a message to a Usenet sub generates p1.net file. Could this be mistakenly routed to @1?
*\* Confirmed this - newtork1 changed p1.net to s1.net then watched toss si.net to @1. News packets headed there for distribution to subscribed nodes but nothing handled by news.exe

**Comment by BloodStoneBBS** [comment]
Confirmed with @1 that he received my s32767.net packets. They should be handled by WINS & news.exe instead.

**Comment by wwiv** [comment]
but you connect to 32767 in connect.net so it's unclear why the network software would package it up to mark

**Comment by wwiv** [comment]
if you have logs of it sending the packet as s32767.net then please provide it to me privately

**Comment by BloodStoneBBS** [comment]
Just checked the logs, no reference to s32767.net That was from Mark's post on the BBS.
 After posting a new message to alt.bbs.wwiv, a file "p1.net" (lower case) is generated.
After logoff, network1 changes that to "S1.NET" (upper case). Not sure where the s32767.net  is coming from. 
Forced callout to 32767 via / is WFC. S1.NET is still untouched.
Confirming that connect.99 and bbslist.99 no longer required and @32767 & "" is in callout.net?

**Comment by wwiv** [comment]
if you still have the s1.net - can you email it to me?

**Comment by BloodStoneBBS** [comment]
Did you ever receive the file via email? I used the address you provided quite some time ago.
Still unable to post to usenet from BBS. Still appears as though the file S1.net is being routed to @1 and not recognized as a usenet post destined for 32767.

**Comment by wwiv** [comment]
nope.

**Comment by wwiv** [comment]
I sent you my email address on your bbs in feedback

**Comment by BloodStoneBBS** [comment]
Both p1.net and S1.NET sent. - p1.net is created when posting to usenet sub, changes to S1.NET on logoff. Forced callout to 32767 shows no messages to post. Used / and select 32767 from WFC. Also have the command in my scheduled toss.

**Comment by BloodStoneBBS** [comment]
Progress! Removed 32767=0.00 from top line in connect.net. Usenet post now creates S32767.NET
Toss now shows:
 ! Unknown error during export!
 ■ WWIV Internet Network Support (WINS) Import/Export v5.00 (Build 12) ! EXP [filename] [net_data] [net_sysnum] [POPNAME] [DOMAIN] [net_name]
- [ & ] to replace greater than and less than brackets. They do not display on this.
  Appears as though NEWS.EXE is reliant on POP & SMTP info in net.ini?

**Comment by BloodStoneBBS** [comment]
Looks like I'm at the point where I need to change the script to call news.exe instead of network.exe:
S32767.NET waiting in my netdata folder. S1.NET transfers fine.

## 

þ WWIV Internet Network Support (WINS) Import/Export v5.00 (Build 12) ! [filename] [net_data] [net_sysnum] [POPNAME] [DOMAIN] [net_name]
(again, [&] for greater than and less than brackets.

 [DEBUG] CommandLine=[C:\WWIV\POP.EXE -send  wwivbbs.org C:\WWIV\DATA\WWIVSN\MQUEUE\ 0 0]
 ! Missing critical NET.INI settings!
 [DEBUG] CommandLine=[C:\WWIV\POP.EXE -r C:\WWIV\DATA\WWIVSN\INBOUND\ 1 0 n707]
 ! Missing critical NET.INI settings!
 þ WWIV Internet Network Support (WINS) Import/Export v5.00 (Build 12) ! EXP <filename> <net_data> <net_sysnum> <POPNAME> <DOMAIN> <net_name>

 þ WWIV Internet Network Support (WINS) News Retrieval v5.00 (Build 12)
- NNTP> 200 News.GigaNews.Com
  þ NEWSRC last updated 11/11/2015 05:56:42... no update required.
  þ [Esc] aborts session - [Space] skips group - [Tab] catches up group      
  
  þ Requesting alt.bbs.doors - [No new articles]
  
  þ No outbound news articles to post...      
  
  þ Requesting comp.sys.cbm - [No new articles]
  
  þ No outbound news articles to post...      
  
  þ Requesting alt.nature.mushrooms - [No new articles]
  
  þ No outbound news articles to post...      
  
  þ Requesting alt.bbs.ads - [No new articles]
  
  þ No outbound news articles to post...      
  
  þ Requesting alt.bbs.wwiv - [No new articles]
  
  þ No outbound news articles to post...      
  
  þ Requesting alt.sex.stories.moderated - [No new articles]
  
  þ No outbound news articles to post...      
  
  þ Requesting rec.games.video.arcade.collecting - [No new articles]
  
  þ No outbound news articles to post...      
  
  þ Requesting alt.rec.geocaching - [No new articles]
  
  þ No outbound news articles to post...      
  
  þ Requesting talk.atheism - [No new articles]
  
  þ No outbound news articles to post...      
  
  þ Requesting alt.homebrewing - [No new articles]
  
  þ No outbound news articles to post...      
  
  þ Requesting rec.radio.swap - [No new articles]
  
  þ No outbound news articles to post...      
  
  þ Requesting alt.2600.cracks - [No new articles]
  
  þ No outbound news articles to post...
  þ NEWS completed processing 12 newsgroups

WWIV Internet Network Support (WINS) v5.00 (Build 12) [Oct 31 2015]
Licensed under the Apache License.
Please visit http://www.wwivbbs.org/ and https://github.com/wwivbbs/wwiv for support and more information.

 þ Running under Win32 on instance 1 at 08:55PM, 09 Nov 2015
   Disk space : C:\ - 16.1GB
 þ Initiating newsgroup session...
 ! Unknown error during export!
 þ Preparing outbound packets... already in MQUEUE to be sent.
 ! Unknown error during export!
 þ Updating network connection records...
 þ WWIV Internet Network Support (WINS) v5.00 (Build 12) [Oct 31 2015] completed!

**Comment by BloodStoneBBS** [comment]
Update:
news.exe requires POPNAME and DOMAIN to be set in net.ini
Will follow up soon with updated documentation.

**Comment by askpatrickw** [comment]
Did you update the docs yet? If not, I think you should leave it open until you do. We don't want to forget about things.

I changed the label to docs and wiki. If you haven't updated the docs, please re-open. thanks!

**Comment by BloodStoneBBS** [comment]
Good point, I will not have time to fully test each step and update the document until later tonight. Reopening until I can confirm each step and update/append the documentation.

**Comment by BloodStoneBBS** [comment]
Wiki updated, tested on Manic Arcade - Following the Wiki steps does result in a working Usenet/NNTP system.
