### ISSUE TITLE
Callout.NET should be configurable to dial out whenever new posts exist

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#324]
Currently you can configure callout on wwivnet at 1 hour frequency. 
`@1 && /1 "Password`

I propose we add /0 which will callout anytime there is new outbound messages for that network.
`@1 && /0 "Password`

/0 isn't the important part, could /N or /NEW whatever is easiest to add.

**Comment by askpatrickw** [comment]
GP says if you leave off the /x it will do that. I'll try that and see if it does.

**Comment by askpatrickw** [comment]
It will call out when there are new local posts for the net. But it will NOT callout **unless** there are new local posts. So the /1 should be kept for now as our only automated way to force callout.

Still remains that despite the /1 setting, when there are new posts, they should be sent immediately so I will leave this open.

**Comment by granitepenguin** [comment]
I don't agree this is an always-on situation.  You shouldn't force someone to immediately post if they don't want to.  With no easy way to disable immediate sending, you couldn't postpone for things like packet validation (eg, testing issues), or simply relying on your normal schedule to run.  

This should be a configurable option, not a law.

**Comment by wwiv** [comment]
sounds like we can re-purpose an unused flag now in callout.net to handle always-call-on-post-waiting.

**Comment by wwiv** [comment]
Actually if there's pending messages we weight it higher and try to send it
