### ISSUE TITLE
allow networkb to run against all networks

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#326]
Instead of having to run an individual `networkb --send --network=foo --node=1`
it would be nice to have a  way to let it figure out all the networks and have it process on it's own.  For example, have `networkb --send` walk the network list and figure things out for itself.  INIT has the list of networks, and the callout.net files in each network config know where to send things, so let the system do things for you instead of putting specifics in shell scripts.

**Comment by wwiv** [comment]
question: should it try to send to everyone who has pending files for every network?

**Comment by wwiv** [comment]
Here's a good solution, not sure if it makes sense to put it in the binary.
assume your networks are wwivnet and rushnet

for net in wwivnet rushnet
do
    for pending in $(ls $net/s*.net)
    do
         node=$(echo $pending | sed "s/^$net\///g" |cut -c2- | sed 's/.net$//g')
         networkb --send --net=$net --node=$node
    done
done

**Comment by wwiv** [comment]
@granitepenguin closing as wontfix
