### ISSUE TITLE
There is a potential for issues with the new console in windows 10 and legacy doors or other applications

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#341]
See https://blogs.windows.com/buildingapps/2014/10/07/console-improvements-in-the-windows-10-technical-preview/

We need to document this.  network*.exe seems find under it, but I'm sure some doors will crash NTVDM unless using the legacy console (it's a checkbox in cmd.exe's properties, so it's an easy change to make)

**Comment by askpatrickw** [comment]
clarifying the title a bit, tagging as low priority. If we start to find issues on win10 we'll raise this u.

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/docs/commit/b21f1f856418cf8ad6025a27d82c393fcc3c699c
