### ISSUE TITLE
Feature request - BBS update subs.list when adding/hosting new sub

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#342]
Currently, when adding a new sub to host on the net an option comes up to "make available in subs list" comes up but this does not append the subs.list(s) on your BBS.

Would it be possible to make this work? Pros/cons? Reason it does not work? or is this merely for responding to a NC ping ala netup/net37?

**Comment by wwiv** [comment]
I think netup's subs ping will handle this

**Comment by wwiv** [comment]
Mark - this should be fixed once you start using netup

**Comment by askpatrickw** [comment]
Would implementing this imply that all member nodes in a wwivnet style net can be the master of the subs list? I thought it was required for the NC to add new subs. But maybe that was a limitation based on technology not an administrative desire.

**Comment by wwiv** [comment]
the NC/GC sends out a subs ping to collect the list of all subs hosted by everyone then compiles subs.lst from that.

mark - isn't this working now? @MarkHofmann11

**Comment by MarkHofmann11** [comment]
Yes, this is working.

**Comment by wwiv** [comment]
closing since it works now with netup
