### ISSUE TITLE
BBS not recognizing existing username

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#359]
On one BBS I call (The Arcade) running Build 1609, My username is not recognized but I can log in by number.
As a test, I was able to recreate my username with the exact same spelling and it created a new account.
had Sysop delete that account and I am able to login via user number but not username. Sysop ran FIX -U but that made no difference.

**Comment by wwiv** [comment]
try fix -u -x
and if that doesn't work then do this.

cd DATA
rename names.lst names.saved
cd ..
fix -u -x
cd data
dir names.lst names.saved

I'm guessing the sizes should be different.
then...

cd ..
bbs

now try to log in locally as Jimmy

**Comment by BloodStoneBBS** [comment]
Relayed this to Arcade Master - Will update when I hear back.
