### ISSUE TITLE
network.exe inbuild 1661 breaks news.exe and / in WFC

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#372]
Reproducible.
Rolled network.exe back to 1660 and error is gone. 
Updated to 1661, breaks my network call out to N32767

Error:
I20151123:174201 NETWORK version v5.00 (Build 1661) (Nov 20 2015, 07:23:16)
I20151123:174201 NETWORK starting at Mon Nov 23 17:42:01 2015
I20151123:174201 NETWORK exiting at Mon Nov 23 17:42:01 2015

I20151123:174201 ERROR: [network]: unknown_argument_error: key=
Stacktrace:

I20151123:174201 

2: BaseThreadInitThunk = 772fee5a
1: RtlInitializeExceptionChain = 77bc39c4
0: RtlInitializeExceptionChain = 77bc39c4

**Comment by BloodStoneBBS** [comment]
I noticed the changed in network.exe. Could the above error be due to my syntax?
From my mail.bat to handle usenet mail:

NETWORK /N32767 .0 /A /P707-585-NEWS /S57600 /T993228415 .0 

Still accurate?

**Comment by wwiv** [comment]
Ahh yes. For now just stop after .0
Leave the bug open and I'll fix it.

**Comment by BloodStoneBBS** [comment]
Tried 1661 after changing line to read only NETWORK /N32767 .0 and received the same results.
Low priority as using network.exe from build 1660 works.

**Comment by wwiv** [comment]
How did you change the commandline?   This works for me:

Z:\bbs>NETWORK /N32767 .0
I20151125:001630 NETWORK version v5.00 (Development) (Nov 15 2015, 21:44:07)
I20151125:001630 NETWORK starting at Wed Nov 25 00:16:30 2015
I20151125:001630 USE PPP Project to send to: Internet Email (@32767)
I20151125:001630 Executing Command: 'networkp /N32767 .0'

WWIV Internet Network Support (WINS) v5.00 (Build 12) [Dec 22 2014]
Licensed under the Apache License.
Please visit http://wwiv.sourceforge.net for support and more information.

 ■ Running under Win32 on instance 1 at 12:16AM, 25 Nov 2015
   Disk space : Z:\ - 11.2GB
 ■ Initiating newsgroup session...
 ■ Network clean-up... please wait... done.
 ■ No Internet mail or newsgroup posts to process.
 ■ Preparing outbound packets... already in MQUEUE to be sent.
 [DEBUG] CommandLine=[Z:\bbs\POP.EXE -send  skulls.wwivbbs.com Z:\bbs\WWIVNET\MQ
UEUE\ 1 1]
 ! Missing critical NET.INI settings!
 [DEBUG] CommandLine=[Z:\bbs\POP.EXE -r Z:\bbs\WWIVNET\INBOUND\ 1 1 n514]
 ! Missing critical NET.INI settings!
 ■ No Internet mail or newsgroup posts to process.
 ■ WWIV Internet Network Support (WINS) News Retrieval v5.00 (Build 12)
 ■ Invalid arguments for Z:\bbs\NEWS.EXE

 ■ Updating network connection records...
 ■ Network clean-up... please wait... done.
 ■ WWIV Internet Network Support (WINS) v5.00 (Build 12) [Dec 22 2014] completed
!

I20151125:001630 NETWORK exiting at Wed Nov 25 00:16:30 2015

**Comment by BloodStoneBBS** [comment]
Works as before. Thank you!
