### ISSUE TITLE
something wonky with file::last_write_time

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#380]
I'm wondering it the code to work around XP isn't working right

**Comment by wwivsoftwareservices** [comment]
Just a question here….  Why are we still supporting XP? With Microsoft’s abandonment of the OS, should we not sunset support for it?

**Comment by wwiv** [comment]
I was looking in the wrong file... nothing wrong here.

Also we're only supporting XP for networkb.exe (which the core libs support) till the 1st of the year or so -- until Mark can move to Win7 for his VM.
