### ISSUE TITLE
Builtin Fidonet Support

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#393]
This is probably many potential issues. FTN support could mean:
- Native FTN and Tossing
- Native FTN Sub Type to eliminate tosssing
- or?

**Comment by wwiv** [comment]
depends on https://github.com/wwivbbs/wwiv/issues/396

**Comment by wwiv** [comment]
Doesn't depend on 396's JAM support, just the type-2 support (which is already in place.)

rough networkf (F==fido) is done and sort-of works. Needs docs.

TLDR is make a fake outbound node in init for your FTN node # (I use 999).  set your in, out, and netmail directories to point to d'bridge's C:\db\inbound, C:\db\outbound, and C:\db\messages.  

run network3 .# (for your node number #), it'll create all of the wwiv files you need (BBSDATA._) you do not need to create any bbslist._ callout.\* etc.

Create a sub, add it to the network for your FTN. You'll now have a fake "host" of 999 (assuming that's what you used for your fake outbound node).
Go edit nNAME.net (i.e. nWWIV_TEST.net) in your ftn directory and add the uplink node you want in fidonet format, no@.

i.e.  `11:1/100` for Mark's D'Bridge HUB
That's it, the processing isn't automatic yet, but you can use the following commands to import from a fidonet bundle (i.e. 00000adb.su?) and export from s999.net to a fidonet bundle.

**Comment by wwiv** [comment]
not perfect, but works. I'll track enhancements as separate items now

**Comment by wwiv** [comment]
See https://github.com/wwivbbs/wwiv/projects/1
