### ISSUE TITLE
Create a MSGBase API for the core and add-ons

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#396]
Write a standard MessageBase API and make WWIV use it. (seperate out core MSGAPI from the BBS flow)
This could also be used for building adddons like an HTML web interface to the message boards

**Comment by wwiv** [comment]
We already have this for type2 message bases, and it's used to implement net51

**Comment by wwiv** [comment]
This is now done and can do everything needed.  Making WWIV use it will not be tracked by this bug.
