### ISSUE TITLE
PPP Project integrated with Network

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#400]

**Comment by wwiv** [comment]
really this just means internet email and nntp support natively (AFAICT)

**Comment by wwiv** [comment]
as discussed in the wwivdev thread, we'll do nntp probably but not email apart from notifications (i.e. here's a temporary password)

**Comment by wwiv** [comment]
Let's use https://github.com/wwivbbs/wwiv/issues/397 as the canonical one
