### ISSUE TITLE
Standard File Base API for WWIV and addons

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#403]
Write a standard FileBase API and make WWIV use it. (Seperate out filebase specific code, i.e. file listing, searching, etc. from the main bbs flow)

**Comment by wwiv** [comment]
This is done https://github.com/wwivbbs/wwiv/commit/1c40914f18dc28c979d52ed307d18be781fb6828 and https://github.com/wwivbbs/wwiv/commit/10409aa82bee9a433960e13588ccc820d1c56804 and many other changes around these
