### ISSUE TITLE
Finger Daemon

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#404]
Support FINGER for looking up system and user information

**Comment by mmunson** [comment]
Could we just state use FMD-22A.MOD as an inspiration for development of this idea. We could use the local information with that. Then use an external program or extra code to finger remotely?

**Comment by granitepenguin** [comment]
Maybe it isn't really finger that we are talking about here.  I think it's more along the lines of a global address list.  For example, it would be nice to be able to send mail to another board and actually know who you are sending to, rather than having to keep your own list.
