### ISSUE TITLE
Enhanced Menus

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#405]
Further extend Menus
Move all commands (i.e. Defaults, Automessage, BBSList, Chains) into Menus

**Comment by wwiv** [comment]
ok. need a real plan for the menus now that we're trying to use them more and use basic scripts too.

I'l start a wiki, comments/ideas welcome.

@granitepenguin @mmunson @MarkHofmann11 @BloodStoneBBS  please add ideas to https://github.com/wwivbbs/wwiv/wiki/Menus5.3

**Comment by wwiv** [comment]
QWK was moved into a menu already.
Defaults may not. 
Chains won't for sure.
BBSLIst and AutoMessage will.

**Comment by wwiv** [comment]
automsg added in https://github.com/wwivbbs/wwiv/commit/d4a081041066e24a754eb840187ae039499ca7bd
