### ISSUE TITLE
Public SDK/Libraries for writing utilities (i.e. Web Tools)

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#408]

**Comment by askpatrickw** [comment]
1. WWIV Command Line Utilities:  
   a. Post to sub  
   b. Send e-mail  
   c. Send SSM

**Comment by wwiv** [comment]
wwivutil can post to a sub already

**Comment by wwiv** [comment]
SSM is also in the SDK package.  closing as done
