### ISSUE TITLE
New Installation Program or Scripts

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#409]

**Comment by granitepenguin** [comment]
On the linux side, at least, this should be an install.sh (lowest common denominator) that is run as root that sets up all the necessary environmental bits (bbs user, systemd configs, fail2ban, etc).

**Comment by wwiv** [comment]
Hey @granitepenguin over to you.

**Comment by granitepenguin** [comment]
This is mostly done in 0cce9f7913be2d36ffef45ac14c7b92b36056166, but still have a few more cleanup items before I call it done and closed.

**Comment by granitepenguin** [comment]
fixed in:
400eddc12ce8bfb1b8a11ade0f96e62c226116b8
26cf970b6ca63f2f7c55ca482ab5e82a089eed89
102469c33bf796efe76b8c5fb466d4bbad436c66
and docs updated to reflect how to use the new installer in 5.3
