### ISSUE TITLE
internal chat "/c" doesn't work

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#411]
using chat on linux doesn't work.  You can go into the chat and see that people are there, but you can't talk to them.

**Comment by BloodStoneBBS** [comment]
It's been so long since I've looked at it. Just to let you know that it's working in Windows on b1672

**Comment by brentkastner** [comment]
I bumped into this as well running on the Pi 2 B. Seems its common to linux and not related to specific hardware.

**Comment by wwiv** [comment]
also doesn't work on windows for me either.

**Comment by wwiv** [comment]
nevermind, seemed to work on windows.. it didn't work since I had both users logged into the same node.

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/9a048058c0d35fd2f78f077f825a1aa2448c5bbd
