### ISSUE TITLE
GEOIP filter/block tools to WWIV Server

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#413]

**Comment by dunnaway** [comment]
Yeah, this would be awesome.  I'd surely like to block the china/korea/malaysia/etc.. Perhaps nigeria and parts of russia as well.  that would kill about 90% of all the idiot people trying to hack my non existent linux box.  LOL.

**Comment by wwiv** [comment]
https://arsofttoolsnet.codeplex.com/ looks like it has code to resolve TXT records (needed for using http://countries.nerd.dk/ for country code lookup).

We could also use it instead of the c# system.net.dns class for all RBL lookups

**Comment by wwiv** [comment]
Here's how net2bbs does it:
http://pcmicro.com/NetFoss/guide/net2bbs.html

**Comment by wwiv** [comment]
This is done on windows. on linux I'd propose just using fail2ban
