### ISSUE TITLE
Move the Wiki into its own repository

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#416]
Move the wiki into its own respository, assign it a WWIV subdomain.
We will want to keep it as markdown formated, but also skin it and improve the navigation.

**Comment by askpatrickw** [comment]
When this is done you'll need to update all the links to the wiki as well in README, CONTRIBUTING, WWIVBBS.github.io....

**Comment by wwiv** [comment]
isn't this done now?

**Comment by askpatrickw** [comment]
Yep, thought I closed it.
