### ISSUE TITLE
Replace Area Code based Regions with text string

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#418]
We currently have a regions listing that uses the phone number as the reference to a lookup against some flat files. Le'ts get rid of that and just use a string for location.

**Comment by MarkHofmann11** [comment]
I'm fine with that, but would like a mod for my old 4.24a code.  I might be able to look at the new routine and port it, but not sure.

**Comment by askpatrickw** [comment]
Another idea... add a new field to the data structure for this have 5.0 ignore the old one, but 4.x would still use it.

**Comment by granitepenguin** [comment]
We also need to understand exactly what this means.  Right now, the region data is read locally, which means it's more than just changing to use a string.  What's the data sent in packets that represents a node and can it be easily changed to include the node's location so the receiving side doesn't have to look it up?

**Comment by wwiv** [comment]
Not feasible, since all we have is the bbsnode number, and the phone comes from that.  Best we can do here is use a descriptive areacode + prefix.
