### ISSUE TITLE
Sublist and directory list issue crashes :(

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#419]
Using build 1674+ and I am finding out that im getting an error when im trying to get the sublist and dirlist listed. I am thinking it might be due to the conf.h change. 

bbs terminated by exception: bad allocation
stacktrace

**Comment by BloodStoneBBS** [comment]
Confirmed. \* to list subs, [space] to continue and immediately bumped off. No error on mine though.
5.0.0.1677
On both Windows 7 and 2008 x86.
