### ISSUE TITLE
WWIVTelnet Crashes if stopped with open connections

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#423]
The steps:
- With open connections to WWIVTelnet
- Click Server and then Stop
- WAIT
- CRASH

**Comment by wwiv** [comment]
I don't get a crash, just it hangs until all connections are closed.

**Comment by wwiv** [comment]
can't reproduce with the normal release build either.  need more info since i can't reproduce it.

**Comment by BloodStoneBBS** [comment]
I've actually seen this several times and I just recreated it in build 5.1.0.1687
If the Telnet server is stopped while a connection is active, when that session drops, the WWIV5 Telnet Server crashes. Windows 7.  Will test on Server 2008.
![capture](https://cloud.githubusercontent.com/assets/13243281/11631344/74ba277e-9cb6-11e5-85f8-a8075888ee2a.JPG)

Yep. 5.0.0.1678 on Windows Server 2008
![capture](https://cloud.githubusercontent.com/assets/13243281/11631698/15549d76-9cb8-11e5-97ae-6bc044581188.JPG)
