### ISSUE TITLE
DE1 crashes dosemu

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#435]
Whenever a packet comes in that causes DE1 to run for validation, it causes dosemu to crash (running in dosemu because net38 is DOS only).  This appears to be a CPU exception.  I've tried with FreeDOS and MS-DOS 6.22, it's not OS-specific.

Samples of crashes:

_Most recent WWIVNET DE1_
Fault out of DOSEMU code, cs:eip=33:46735c, cr2=2928, fault_cnt=1
ERROR: unexpected CPU exception 0x0e err=0x00000004 cr2=0117a02d while in vm86 (DOS)
leavedos(dosemu_fault1|204) called - shutting down

_Most recent RushNet DE1_
Fault out of DOSEMU code, cs:eip=33:46735c, cr2=2928, fault_cnt=1
CPU exception 0x05 err=0x00000000 cr2=0000f934 eip=000031c2
ERROR: Unhandled BOUND exception!
leavedos(int05|1528) called - shutting down

**Comment by wwiv** [comment]
how can I run this and see the results?

**Comment by granitepenguin** [comment]
If you have a basic dosemu setup (i.e., you followed my steps to set up wwivnet on linux), you can manually run dosemu then run de1.

Assuming you have a .dosemurc that looks like this:
ifdef u_virtual
serial { virtual com 1 }
endif

$_sound = (0)
$_cpu = "80586"
$_hogthreshold = (10)
$_dpmi_base = (0x10000000)
$_external_char_set = "cp437"
$_internal_char_set = "cp437"
$_layout = "us"

and the default setup of .dosemu/drive_c

just running dosemu as the wwiv user should get you to a dosemu env.  navigate to the nets/wwivnet directory and run de1

When (if) it crashes out, you can see the results in the boot.log file found in .dosemu

**Comment by granitepenguin** [comment]
This was an issue with grabbing the wrong thing (i.e., another GitHub misunderstanding).  What I was grabbing is the HTML page in GH that displays the de1.exe, not the actual file.  Grabbing the zip file that contains all the files includes the correct de1 file and appears to work as expected.

The trick is to get the correct link:
https://github.com/wwivbbs/wwivnet/raw/master/wwivnet/de1.exe
NOT https://github.com/wwivbbs/wwivnet/blob/master/wwivnet/de1.exe
raw, not blob
