### ISSUE TITLE
Possible issue with 5.1.0.1731 - NDR from #1@1 when sending email to 1@1

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#473]
## On both 2008 and Win7, when trying to send an email to 1@1, I receive a NDR from @1 with the following:

Msg:  [1/1] E-Mail
Subj: Your mail to  @1
Name: Weatherman #1 @1
Date: Tue Dec 15 16:20:42 2015
From: Weather-Station [410-838-INET] {NC}
Loc:  Bel Air, Maryland

There is no  @1 on this system.
## Your undelivered mail is:

Possibly some of the cleanup?
Will try rolling back this evening when I'm back at home.

**Comment by wwiv** [comment]
Try with 5.0 and let me know if it works

**Comment by BloodStoneBBS** [comment]
Sorry, rolled back to 1722 and that seems to work Nothing after 5.1.0.1722

Will try 5.0 now.
Update: 5.0.0.1689 appears to work as well. It looks as though build 5.1.0.1723 introduced this.
From 1723 on, any message I send to 1@1 gets an immediate NDR as posted above.

**Comment by BloodStoneBBS** [comment]
Could this be the cause?:
https://github.com/wwivbbs/wwiv/commit/ad5c692075d8f750784756eb1e0400b1b58a90f1

**Comment by wwiv** [comment]
yes, good catch, line 644 in msgbase.cpp should have included a line to set the user_number for the remote system.

Here's some packets I created and their dumps. the 1st with 5.1 latest.  the 2nd with 5.0 production, and the last one after my fix. Notice the 1@1 vs. 0@1 for the destination.  That was the bug.

Z:\bbs>netutil dump wwivnet\S1.NET
destination: 0@1
from:        1@514
type:        (main_type_email_name/0)
daten:       Wed Dec 16 06:11:49 2015
length:      116
Text:
 test Rushfan #1 @514
Wed Dec 16 06:11:48 2015
♦0R 38RC7 - 12/16/15 06:11:49 wwivnet ->514
test from latest 5.1

# 

destination: 1@1
from:        1@514
type:        (main_type_email/0)
daten:       Wed Dec 16 06:13:04 2015
length:      117
Text:
test from 5.0 Rushfan #1 @514
Wed Dec 16 06:13:03 2015
♦0R 38RC7 - 12/16/15 06:13:05 wwivnet ->514
test from 5.0

# 

destination: 1@1
from:        1@514
type:        (main_type_email/0)
daten:       Wed Dec 16 06:16:09 2015
length:      101
Text:
test3 Rushfan #1 @514
Wed Dec 16 06:16:08 2015
♦0R 38RC7 - 12/16/15 06:16:09 wwivnet ->514
test3
