### ISSUE TITLE
Feature request - process P#.net files on exit local node

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#486]
Currently, when using local mode from WFC, (space F)  if a message is posted on a networked sub, a P1.net file is generated and is not processed until after network1 is run,  when it is then converted to S1.net for sending to over the network.

Is there a way to automate this process such that network1 is run after the local mode exits in the same manner as when disconnecting from a telnet session?

**Comment by wwiv** [comment]
is this still an issue? It seems that wwiv will only run this on node1 (it's been that way forever, not sure why).

**Comment by BloodStoneBBS** [comment]
I'll give that a try! I've always used a higher node # for my local.  It would be nice to have a work around but if it works when using node 1 as the local, I'll just do that.
 EDIT:  
Moving local node to 1 works.  Any way to include all nodes or is this too much effort for too little gain?

**Comment by wwiv** [comment]
dunno, it's always worked this way AFAIK

**Comment by wwiv** [comment]
Added a new INI flag to set for the nodes you want to be able to
process network packets.  Or set it under [WWIV](like in the NETWORK OPTIONS part) for all nodes.  I'll default it to on for all nodes in 5.1 in here: https://github.com/wwivbbs/wwiv/commit/550dbec5ae2258f4f34428f0272cbc1fa6c0ea79

Example:

```
NET_PROCESS        = Y                      ; allow processing of network packets
                                            ; on this instance
```
