### ISSUE TITLE
5.1.0 does not run on Windows 10 after b1735

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#508]
Testing on Windows 10 Ent, w64 
WWIV5TelnetServer will launch and start but BBS will not launch, even in local mode.
Works in b1735, does not work on later builds.
Does not appear to be the language issue previously seen.
Only error that can be seen is "exiting at error level 1"

**Comment by BloodStoneBBS** [comment]
As 64 bit is not supported, good idea to kill this if working on x86

Just installed and tried on Windows 10 x86. Same issue.
Will verify to insure all pre-requisites are installed.

**Comment by wwiv** [comment]
is the problem the working directory is C:\bbs and not C:\wwiv
Can you run bbs.exe  from the commandline?

**Comment by wwiv** [comment]
I wonder if you hit this?
https://github.com/wwivbbs/wwiv/commit/4d921ffb29aa0f3ee7151910d5b55f60f0d7de9a

Was it a fresh install?

**Comment by BloodStoneBBS** [comment]
No, tried from command line as well.

**Comment by BloodStoneBBS** [comment]
Yes. Both were clean installs. Win10, x86 and w64.

**Comment by wwiv** [comment]
ahh, can you try with a newer install?

**Comment by BloodStoneBBS** [comment]
I just tried a fresh new install on both Windows 8.1 and Windows 10 and they both ran perfectly. 
Thank you!
