### ISSUE TITLE
WFC does not cleanly return from screen save mode

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#574]
I have noticed this for some time so I can't relate to the build number where it began but when waking WFC from screen saver mode, the colored ANSI text is not rendered. This does not occur every time but I will post an image when I can replicate.
Windows 7 Pro x86

**Comment by askpatrickw** [comment]
Is this the same thing as #199 ?

**Comment by wwiv** [comment]
no. i may just remove screen saver mode since it's not really needed.

**Comment by BloodStoneBBS** [comment]
No, I believe #199 is different.

**Comment by granitepenguin** [comment]
Granted, it's a diminishing use case, but old hardware is a likely candidate for running a BBS.  A screen saver may still be useful to some.

**Comment by BloodStoneBBS** [comment]
Not sure this is still an active bug, I haven't seen the issue in quite some time. 
OK to close?

**Comment by wwiv** [comment]
sgtm to close
