### ISSUE TITLE
network /N and --node should be identical

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#579]
According to rush, running network /N32767 ad network --node 32767 should have an identical behavior. I am not sure if the same thing is being run under the covers, but one appears to be running networkp and the other network0.

```
C:\wwiv>network /n32767
I20160103:140606 network version 5.0.0.1689 (Dec  9 2015, 00:59:23)
I20160103:140606 network starting at Sun Jan  3 14:06:06 2016
I20160103:140606 USE PPP Project to send to: Internet Email (@32767)
I20160103:140606 Executing Command: 'networkp /n32767'

NOTE: Launching legacy WWIV networking network0.exe
WWIV Networking Software
Copyright 1998-2015 WWIV Software Services.

network0: [net38b6] (Nov 29 2015, 05:53:39)
Protocols Available:

!! No external transfer protocols found!
=> Using internal Y-modem...


Need to specify system number and phone number.
I20160103:140619 network exiting at Sun Jan  3 14:06:19 2016


C:\wwiv>network --node 32767
I20160103:140628 network version 5.0.0.1689 (Dec  9 2015, 00:59:23)
I20160103:140628 network starting at Sun Jan  3 14:06:28 2016
I20160103:140628 Executing Command: 'network0'
WWIV Networking Software
Copyright 1998-2015 WWIV Software Services.

network0: [net38b6] (Nov 29 2015, 05:53:39)
Protocols Available:

!! No external transfer protocols found!
=> Using internal Y-modem...

Waiting for NET_RESP... <HANGUP>
No connection.  Hanging up.
I20160103:140631 network exiting at Sun Jan  3 14:06:31 2016
```

**Comment by wwiv** [comment]
problem is --node ### doesn't work. --node=#### is needed.

**Comment by askpatrickw** [comment]
Why does it try to run? Why doesn't it fail to run altogether?

**Comment by wwiv** [comment]
it does fail with an error message:

Z:\bbs>network --node 32676
I20160104:220817 network version 5.1.0.development (Jan  4 2016, 19:26:02)
I20160104:220817 network starting at Mon Jan  4 22:08:17 2016
I20160104:220817 Invalid node number: '0' specified.
Usage:
network [args]

program arguments:
--allow_sendback       Allow sendback (only used by legacy network0)
--bbsdir               (optional) BBS directory if other than current directory
--callout_time         Start time of the callout (only used by legacy network0)
--help                 displays help.
--network              Network name to use (i.e. wwivnet).
--network_number       Network number to use (i.e. 0).
--node                 Network node number to dial.
--phone_number         Network number to use (only used by legacy network0)
--speed                Modem Speedto use (only used by legacy network0)
/N####     Network node number to dial.
.####      Network number (as defined in INIT)

What do you expect it to do instead?
