### ISSUE TITLE
Updates WFC HELP and remove commands which do not work

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#582]
Remove the following commands which do nothing, remove them from the WFC Help (?) as well as the code that actually is behind them.

A - Answer Call
V - Send Internet email
X - Show Environment

**Comment by wwiv** [comment]
That should be fixed already in 5.1. I did it in this commit:

commit ea535e10d21f9151c626527fe07eae6b37585275
Author: RushFan rushfan@wwivbbs.org
Date:   Thu Dec 24 06:17:04 2015 -0800

```
Update menus to say 5.1
Remove some removed commands
```
