### ISSUE TITLE
Build 1811; pasting text into std editor prevents anytext from that line on from being posted

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#588]
I tried this a few times on the WWIVnet Networking sub today and each time I pasted text from notepad into the standard WWIV messge editor, the pasted line and any additional text below is stripped from the message on save.

Windows 7 x86 5.1.0.1811

**Comment by BloodStoneBBS** [comment]
Update: This is occurring while in local node. I did not test via terminal PGM.

**Comment by wwiv** [comment]
I can't reproduce this

**Comment by BloodStoneBBS** [comment]
Replicated on both Windows Server 2008 and Windows 7. Using RDP to manage VM's, open a text document with notepad, copy section of text, open new message in standard WWIV editor, type a couple of lines and then on new line, right click mouse to paste clipboard contents. Contents displays just fine and can append more text with keyboard, all looks good. /s to save new message. View new message and nothing from the point of paste is available in the message. It's as though it never existed.

**Comment by wwiv** [comment]
I've only tried with a local VM on Windows 10, and can't reproduce it.

**Comment by wwiv** [comment]
still can't. installed win7 on a vm.

pasted this:

```
Build windows (Jan 11, 2016 12:13:08 AM)

    Build Artifacts
    wwiv-build-win-1850.zip 2.46 MB view
    Changes
Found some tests not included on linux, included them. Found out on test (detail / githubweb)

Started by upstream project wwiv build number 1850
originally caused by:

Started by an SCM change
    Revision: 5104e0ea60d979b96f2f9af8ea85114a2e347afd
refs/remotes/origin/master
    Aggregated Test Result (no tests)
```

it worked in an email to myself. I got all of it.  I need more to go on here

**Comment by BloodStoneBBS** [comment]
I'll have to assume that it's my environment. My hypervisor is server 2012 r2. VMS are in hyper-v  and using RDP to server to manage. Let's close this since this setup is a bit rare.

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
