### ISSUE TITLE
Add CNAME for docs.wwivbbs.org to wwivbbs.readthedocs.org

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#603]
Add a CNAME record, when completed, I'll configure read the docs to respond to it.

**Comment by askpatrickw** [comment]
I can also add a Google analytics cider to the docs, sends need that privately.

**Comment by wwiv** [comment]
do you just need a UAT #?

**Comment by askpatrickw** [comment]
Yep... I assume you want a different one than one on www.wwivbbs.org. (not sure if it has to be different or not though.)

**Comment by askpatrickw** [comment]
Seems to ask be working now!
