### ISSUE TITLE
Add other Project Admins to ReadTheDocs Admins

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#608]
If you're an administrator of this project, I need to add you ReadTheDocs so we're not reliant on just me.

Contact me privately and give me an email address.

**Comment by wwiv** [comment]
you know my email address.

**Comment by askpatrickw** [comment]
Actually, I was wrong. You need to have an account, then tell need your username, which I bet I could guess.  https://readthedocs.org/accounts/signup/

**Comment by wwiv** [comment]
As I'm sure you can guess, it's 'rushfan'

**Comment by granitepenguin** [comment]
account created.  Go ahead, guess :-)

**Comment by askpatrickw** [comment]
OK... you're both maintainers on the RTD admin. Whew.. I can get hit by a bus now. ;-)
