### ISSUE TITLE
Windows 10 w32, 5.1.0.1833 New install

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#617]
In WFC, Space F to Log on to the BBS does not work. 
hit space to get the Log onto the BBS? prompt, hitting F in earlier builds would log you on as the Sysop. 
Now it does nothing. Can log on by selecting Y and then entering NN & PW
Bug or by design?

**Comment by wwiv** [comment]
F only works if your sysop user has a SL of 255 (always worked that way). Can you verify that the number 1 user has SL of 255?

**Comment by BloodStoneBBS** [comment]
Face-palm....
Sigh....
Works now.
