### ISSUE TITLE
Init should create the sysop account 

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#641]
Right now your install WWIV
Log in
Edit got account to sysop
Log back in

F1 user editor isn't available on linux so the flow is bad. Also there is no good reason not to ask the sysop info in init and create the account

**Comment by wwiv** [comment]
FYI - F1 user editor is now available on linux.

Still want to do this though

**Comment by granitepenguin** [comment]
F1 where?  Everywhere I've tried it doesn't work.
WFC = "Exit the BBS?"
./init = quits init
logged into BBS = logs out of BBS
