### ISSUE TITLE
Telnet server does not retain previous configuration when updated.

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#644]
Win7 latest builds. 5.1.0.xxxx

Would it be possible to modify the code such that an existing Telnet server configuration is retained when upgrading the WWIV5Telnet server?
When upgrading, a default configuration is used.

**Comment by wwiv** [comment]
Looks like each version get's it's own copy of the settings.

##### Here's what I have on my development machine:

```
Directory of C:\Users\rushfan\AppData\Local\WWIV_Software_Services\WWIV5TelnetServer.exe_Url_htjxy3ccpj1jzsgcdurdrzr0jh2rbdzy

01/18/2016  08:01 AM    <DIR>          .
01/18/2016  08:01 AM    <DIR>          ..
01/01/2016  03:57 PM    <DIR>          1.0.0.0
01/17/2016  09:32 PM    <DIR>          1.1.9.0
01/18/2016  08:01 AM    <DIR>          1.1.9.5
```

**Comment by wwiv** [comment]
@TRI0N any ideas?

**Comment by TRI0N** [comment]
The settings are internally and were updated. I do not believe it will do this now unless I modify the Properties (add things to it). The property setting should remain from now on. I do not have any plans to add more to it until I start tinkering with SSH.

**Comment by wwiv** [comment]
ok, I've not seen this happen in the last few months.. Closing
