### ISSUE TITLE
WWIVnet should be called WWIVnet

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#656]
The canonical capitalization of WWIVnet is _WWIVnet_. No other variation is allowed unless we are referring to a directory for the datafiles, then either all upper case or all lower case is allowed.

| Spelling | Use |
| --- | --- |
| WWIVnet | Referring to WWIVnet type networks or the actual network |
| WWIVNET | allowed if refers to a directory containing WWIVnet datafiles |
| wwivnet | allowed if refers to a directory containing WWIVnet datafiles |

**Comment by granitepenguin** [comment]
docs and code updated
