### ISSUE TITLE
net.log should be appended, not prepended

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#659]
The net.log file has its entries prepended; this is confusing.  Every log file in the universe puts new data at the END of the file, not the front (including all the other WWIV logs).

**Comment by wwiv** [comment]
it's done like this in network0 though (and ppp project)

**Comment by granitepenguin** [comment]
ok, but that's an aberration. Standard behavior (including your networkb.log) append.

**Comment by TRI0N** [comment]
This is needed for me to make the Log Viewer Enhancements that I'm doing. Thought I'm tinkering with the idea of making it read from bottom to top for the first 1,000 lines to limit size for trouble shooting it would be best if network.log and networkb.log appended to file as soon as possible.

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/acf2c7e1aac9d1d0e18f3d5f312263fecbd479b1
