### ISSUE TITLE
Last Caller List (L)

### ISSUE THREAD

**Issue by TRI0N** [wwivbbs/wwiv#674]
Using Build 1878
It appears that the (L) Last Caller List from main menu is broken. However this my be due to the Introduction of SSH.

**Comment by wwiv** [comment]
how is it broken

**Comment by TRI0N** [comment]
It does nothing.. You press L and it just reloads the main menu..

**Comment by wwiv** [comment]
do you have a gfiles\user.log? that's what that command prints

**Comment by wwiv** [comment]
ok, that's dumb, we have 2 last few callers... laston.txt and user.log. user.log seems pretty useless to me... it's gone
