### ISSUE TITLE
Redisplay door options when returning

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#679]
Currently, if you go into "On-line Programs ".", It displays a list of available doors.  When you exit a door and come back to the BBS, all you get is the prompt; you don't see the list of doors and have to hit "?" to list it again.

The list of doors should display when you come back to the BBS.

**Comment by askpatrickw** [comment]
Does this only happen when you have Xpert mode enabled?

**Comment by granitepenguin** [comment]
No, this is not tied to Xpert mode.  It does it whether it's enabled or disabled.
