### ISSUE TITLE
Document how to set a custom port on a WWIVnet style network

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#687]
This is missing from the documents on WWIVnet.

I need to do this on my own board, so I'll write it up.

**Comment by wwiv** [comment]
https://github.com/wwivbbs/wwivnet/blob/master/wwivnet/binkp.net

Look at the entry for node 1

**Comment by askpatrickw** [comment]
Is that file published by @1 on each net or just an edited local copy ?
NOTE: This also needs to be configured in your batchfile you use to run networkB as a receiver, commonly binkp.cmp

**Comment by wwiv** [comment]
Mark updates github from his version when he sends the files out, right @MarkHofmann11 ?

**Comment by askpatrickw** [comment]
Done and live on RTD.
