### ISSUE TITLE
Document Internet E-Mail using WINS

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#689]
Not sure if this is of any interest as improvements will hopefully eliminate WINS but I somehow managed to get my test BBS to send and receive Internet E-Mail, at least from the Sysop, using the parallel network I set up for Usenet. 
It was fairly complex as I also had to reconfigure my Exchange server to accept local plain text login as well as convert all inbound to my test email address to plain text but it's working.

I'll document the steps on Monday or Tuesday and submit if anyone is interested.

**Comment by BloodStoneBBS** [comment]
There is really very little to do to configure the BBS, I may just add the steps to the Usenet config for 5.1.0. The difficult part is going to be the smart host or local Mail Server that will be required to host mailboxes boxes and SMTP auth  etc...

**Comment by askpatrickw** [comment]
Yes, please do update the docs. Better docs == Better BBS Program!

**Comment by askpatrickw** [comment]
Hey @BloodStoneBBS  Any chance you were going to provide the docs for Internet E-Mail using WINS? Or if its not needed let's close this out.

**Comment by BloodStoneBBS** [comment]
Sorry - Been swamped. We can close it out but I'd like to address it in the future.
The only issue with the method is the lack of SMTP Auth so it requires a local E-Mail server with a relay send connector. May not be very practical.

**Comment by wwiv** [comment]
Wins will go away not going to address this
