### ISSUE TITLE
SSH appears to be missing a Carrage Return on Handshake. 

### ISSUE THREAD

**Issue by TRI0N** [wwivbbs/wwiv#696]
SSH on Build 1889 appears to be hanging at the Handshake requiring the user to press enter to continue with login.

**Comment by BloodStoneBBS** [comment]
Still fails on mine.
Allows for userID and password but then crashes.
"Error activating session"

![capture](https://cloud.githubusercontent.com/assets/13243281/12699302/7ac723d0-c76b-11e5-8e5a-b5a8acabf580.JPG)

**Comment by wwiv** [comment]
make sure you have the latest dll (cl32.dll) too, otherwie you will get this

**Comment by wwiv** [comment]
and what client are you using?

**Comment by BloodStoneBBS** [comment]
Syncterm. Will check for the dll.

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by wwiv** [comment]
please do, sounds like old dll. You need 1890 or later.

I also got it to work from mac's ssh using this:
ssh -o MACs=hmac-md5 mystic.wwivbbs.org
