### ISSUE TITLE
Failed SSH connections don't exit the bbs

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#700]
I had 3 sessions hung with this:

setting private key.
setting socket handle.
Looping to activate SSH Sessoin0
Error setting CRYPT_SESSINFO_ACTIVE -50
Looping to activate SSH Sessoin-50
Error setting CRYPT_SESSINFO_ACTIVE -41
Looping to activate SSH Sessoin-41
Error setting CRYPT_SESSINFO_ACTIVE -16
Looping to activate SSH Sessoin-16
Error setting CRYPT_SESSINFO_ACTIVE -16
Looping to activate SSH Sessoin-16
Error setting CRYPT_SESSINFO_ACTIVE -16
Looping to activate SSH Sessoin-16
Error setting CRYPT_SESSINFO_ACTIVE -16
Looping to activate SSH Sessoin-16
Error setting CRYPT_SESSINFO_ACTIVE -16
Looping to activate SSH Sessoin-16
Error setting CRYPT_SESSINFO_ACTIVE -16
Looping to activate SSH Sessoin-16
Error setting CRYPT_SESSINFO_ACTIVE -16
Looping to activate SSH Sessoin-16
Error setting CRYPT_SESSINFO_ACTIVE -16
We don't have a valid SSH connection here!

**Comment by BloodStoneBBS** [comment]
I found the same on my bbs.

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
