### ISSUE TITLE
Sub bug #605 is back 5.1.0.1899

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#709]
Just noticed that my local subs lost their place in the list, inbound messages going to the incorrect subs.
![capture](https://cloud.githubusercontent.com/assets/13243281/12734415/466f7b6a-c8f5-11e5-9947-38f596500b0c.PNG)

**Comment by BloodStoneBBS** [comment]
Odd. This is only showing up on my Windows 2008 test box. Seems OK on my Windows 7 VM.

**Comment by wwiv** [comment]
Could be specific to the subs on your text box.  Do the subs and order of
subs match between the two machines?

**Comment by wwiv** [comment]
Hmm, is it 2008 or 2008R2?
2008 == vista
2008R2 == winxp

**Comment by wwiv** [comment]
See https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions#Server_versions

**Comment by BloodStoneBBS** [comment]
Yes, it's 2008 (NT 6.0 - Vista). I would upgrade to 2008 r2 (NT6.1 - Win7) but it's 64 bit only.
I'll see if the other service this box is hosting will run OK on a WS OS. If so, I'll just move it to 8.1.
If you are certain that this is a 2008 issue, feel free to close and I'll upgrade when time permits.

**Comment by wwiv** [comment]
I'm not certain.  It could also be related to the order and types of the
subs.  Sorry I have nothing more specific

**Comment by BloodStoneBBS** [comment]
No worries. I'll close this and upgrade to a newer version of the OS some time this week. I found an easy upgrade path for the other service I'm running on that VM.
