### ISSUE TITLE
Qwk packer is broken.

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#723]
Build currently used 1909/win32
QWK reader using MultiMail 0.49 and 0.50

I write 2-3 replies, upload the messages and then the first message gets posted well, and then the 2nd message gets corrupted where the previous message gets appended to the second message. I think RF also noticed that in the wwiv development sub with the garbled text.

**Comment by wwiv** [comment]
I think I may have fixed this as part of fixing other stuff.... 

Please provide for specific info if you see it again.
Here's a good command that will give me information about the questionable messages.
Assume the sub file name is general and messages X-Y are bad.

Here's the command:

```
wwivutil messages dump --all --start=X --end=Y general> dumpfile.txt
```

Then attach `dumpfile.txt` to the bug report.  If you still have the .REP packet too, please also include that.
