### ISSUE TITLE
WWIV supports more pipe codes than documented

### ISSUE THREAD

**Issue by rob2885** [wwivbbs/wwiv#728]
From [whatsnew.txt](https://github.com/wwivbbs/wwiv/blob/master/bbs/admin/whatsnew.txt).  WWIV 5.0 (from 2004) supports more PIPE codes:
- |#<wwiv color code 0-9> as an alternative to the "heart" codes
- |@<macro character> as an alternative to ^O^O<macro char>
- Existing pipe codes are: |B<background char>, and |<2 digit code>
  for foreground colors. (Build36)

**Comment by askpatrickw** [comment]
This is already in the documentation
http://docs.wwivbbs.org/en/stable/ansi/#notes
