### ISSUE TITLE
BBS Hangs on disconnect again. b5.1.0.1914

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#729]
As seen before, the guest account appears to hang the session of a user disconnects without logging off.
Windows 7 w32, latest build. This was a problem before bit it had been resolved, perhaps something new causing similar actions?
![capture](https://cloud.githubusercontent.com/assets/13243281/13226611/30e66d78-d947-11e5-8543-56ca2c954b99.JPG)

**Comment by wwiv** [comment]
in this case the select in the titlebar explains what happened.  The process won't exit while you are selecting text in the console.

**Comment by askpatrickw** [comment]
Closing this as it sounds to me like this not something we can fix, its a function of the way Windows works. Reopen with more information if you disagree.
