### ISSUE TITLE
NEWS.EXE Not Leap Year or calendar Aware. 

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#730]
The program is saying news.rc last updated 2/30/2016 :(

**Comment by askpatrickw** [comment]
Mine says news.rc updated 3.3.2016, which is a day ahead from my machine time.
But downloads posts fine... 
-p

**Comment by wwiv** [comment]
Not going to fix this, WINS is not part of wwiv anymore, its still around but will go away
