### ISSUE TITLE
Broken GFiles Collection

### ISSUE THREAD

**Issue by ghost** [wwivbbs/wwiv#731]
Using latest github version on Linux.

Problem: G-files Menu 'G' Says to take a screenshot for rushfan then displays main menu again. If I add new G-files areas, they exists until logging out. The folders and files on the computer, but do not appear in the 'GE' tool.

I think I have a broken area referenced somewhere that it can't get past. When I made my first area I didn't realize the files had to be in 8.3 format, and I think that broke it.

I've tried a lot of things to fix it, like deleting folders and files related to new areas, so I may have made the problem worse as I haven't managed to fix it.

**Comment by ghost** [comment]
[wwiv_copy.tar.gz](https://github.com/wwivbbs/wwiv/files/168289/wwiv_copy.tar.gz)

The first group I made was called Old BBS Ansi Files and the filename was OLDANSI (it's been deleted since)

**Comment by ghost** [comment]
I managed to get my gfiles area sort of fixed. seems i was missing a "gfiles.dat" file in the data dir, I "touched" that and they seem to save the areas, although I am still getting that message.
![readerror](https://cloud.githubusercontent.com/assets/4301359/13721335/5ac9d4fe-e86f-11e5-9843-315df094850a.png)

**Comment by granitepenguin** [comment]
What version of linux are you using?

**Comment by granitepenguin** [comment]
based on what I saw in your tarball, my first guess is you used UPPERcase for the g-files filename (OLDBBS).  There are a lot of weird issues in the linux version related to filename case (expects one thing, looks for another).  Always use lowercase whenever possible.  If it isn't possible to use lowercase when setting up a g-files area (I haven't checked yet), that will be a bug that needs to be tracked.

Try using a symlink to fix it.  In your g-files:
ln -s OLDBBS oldbbs

This is an area that hasn't been tested much, so you may just be "lucky" that you get to help debug :-)

**Comment by ghost** [comment]
I'm using debian 8 on x86

using the symlink didn't make the message go away.

yeah it wasn't possible to write a little letter filename in the GE tool. It automatically converted my letters to uppercase.

i don't mind helping :-)

**Comment by wwiv** [comment]
Can you try with a newer build and let me know what file it's complaining about?
