### ISSUE TITLE
WWIV5 Telnet Server 

### ISSUE THREAD

**Issue by ghost** [wwivbbs/wwiv#732]
[Doc1.pdf](https://github.com/wwivbbs/wwiv/files/180626/Doc1.pdf)

My wwiv5 telnet server will not start, I get this error but I click ok and it opens it but will not let me go into local node mode

**Comment by granitepenguin** [comment]
This is on Windows Vista 32bit, correct?

**Comment by ghost** [comment]
Yes that is correct

**Comment by wwiv** [comment]
possible that things don't work on vista.  Since we use MSVC 2015 only Windows7 or newer is supported and known to work.

**Comment by ghost** [comment]
Ah I see, that could be why? I was having the same problem on my windows 10 computer

**Comment by askpatrickw** [comment]
I'm closing this since the min Windows is Windows 7.
