### ISSUE TITLE
Compiling Source code on Ubuntu Server 15.10 Causes ./bbs to Crash on Start

### ISSUE THREAD

**Issue by k1cty** [wwivbbs/wwiv#733]
After Following setup With all PreReqs For Compiling on Linux I compiled And saw Numerous Errors Listed while compiling. Afterwards The bbs would start but the ./bbs -w for wfc screen would cause a crash on startup.

**Comment by wwiv** [comment]
got a stack trace? Did you install the package from the build server 1st (that includes the data files, etc)?
@granitepenguin any ideas?

**Comment by granitepenguin** [comment]
I would need to get some details on the setup so I can try to reproduce here.
OS: is it 32 or 64 bit?
WWIV: what version are you trying to compile?
What is the output from compiling (i.e., what errors are you seeing during the compile)?

**Comment by k1cty** [comment]
Ubuntu 15.10 Server 64 bit Running inside Virtualbox on Windows 10 Machine. I was trying to compile 5.0 version Im am still a newbie when it comes to linux Rushfan was asking about a stack but I dont know how to find the logs to get info on the failed warning i got when compiling. If you want just delete this because It may be an error on my part.
sorry for any confussion

**Comment by wwiv** [comment]
No worries, I don't have 15.10, 15.04 was the latest and it worked there.  I'll try 16.04 now that it's out and see if things work there.

**Comment by wwiv** [comment]
Did you run init 1st? (It looks like install.sh says it's running init, but I still had to).

Also can you paste the output of when you get the crash in the bug?
You can get a backtrace by running

```
gdb ./bbs
```

then typing:

```
run
```

When it crashes use the bt command to see a backtrace.

**Comment by granitepenguin** [comment]
Tested the prebuilt 5.0.0 binaries on 64bit 15.10 server and those ran fine.  running sh install.sh also ran init with no issues.  I'll try doing a compile from source to see if things behave any differently.

**Comment by granitepenguin** [comment]
running ./bbs -w with the precompiled binaries worked fine, too.

**Comment by granitepenguin** [comment]
It occurred to me that it's not immediately obvious how to get the source for 5.0.0 off of git.  If you just go to the main page, that source will actually be for 5.1

**Comment by granitepenguin** [comment]
Just built source from wwiv500.  There were a couple warnings:

/home/drock/wwiv/wwiv-wwiv500/bbs/netsup.cpp: In function ‘void do_callout(int)’:
/home/drock/wwiv/wwiv-wwiv500/bbs/netsup.cpp:272:43: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 7 has type ‘time_t {aka long int}’ [-Wformat=]
               csne->phone, 0, tCurrentTime);
                                           ^
/home/drock/wwiv/wwiv-wwiv500/bbs/netsup.cpp: In function ‘void print_pending_list()’:
/home/drock/wwiv/wwiv-wwiv500/bbs/netsup.cpp:661:58: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘time_t {aka long int}’ [-Wformat=]
           sprintf(s1, "|#2%02lld:%02lld:%02lld", h, m, se);
                                                          ^
/home/drock/wwiv/wwiv-wwiv500/bbs/netsup.cpp:661:58: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘time_t {aka long int}’ [-Wformat=]
/home/drock/wwiv/wwiv-wwiv500/bbs/netsup.cpp:661:58: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 5 has type ‘time_t {aka long int}’ [-Wformat=]
/home/drock/wwiv/wwiv-wwiv500/bbs/netsup.cpp: In function ‘void print_call(int, int, int)’:
/home/drock/wwiv/wwiv-wwiv500/bbs/netsup.cpp:918:29: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘time_t {aka long int}’ [-Wformat=]
     sprintf(s, "%lld", tTime);
                             ^
/home/drock/wwiv/wwiv-wwiv500/bbs/netsup.cpp:934:29: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘time_t {aka long int}’ [-Wformat=]
     sprintf(s, "%lld", tTime);
                             ^
/home/drock/wwiv/wwiv-wwiv500/bbs/netsup.cpp:950:29: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘time_t {aka long int}’ [-Wformat=]
     sprintf(s, "%lld", tTime);
                             ^

but everything ran as expected.  ./bbs -w did not crash

Going to try a compile of 5.1 latest (which I assume is what was actually compiled, based on what the docs look like right now) and see if that behaves any differently

**Comment by granitepenguin** [comment]
Definitely reproducible.  Here's the bt output from compiling the latest 5.1

drock@ubuntu:~/wwiv$ gdb --args ./bbs -w
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bbs...done.
(gdb) run
Starting program: /home/drock/wwiv/bbs -w

Program received signal SIGSEGV, Segmentation fault.
0x000000000066170f in File::mkdirs (path=<error reading variable: Cannot access memory at address 0x7fffff7feff8>) at /home/drock/wwiv/wwiv-master/core/file.cpp:375
375 bool File::mkdirs(const string& path) {
(gdb) bt
#0  0x000000000066170f in File::mkdirs (path=<error reading variable: Cannot access memory at address 0x7fffff7feff8>)
    at /home/drock/wwiv/wwiv-master/core/file.cpp:375
#1  0x00000000006617a4 in File::mkdirs (path="") at /home/drock/wwiv/wwiv-master/core/file.cpp:381
#2  0x00000000006617a4 in File::mkdirs (path="") at /home/drock/wwiv/wwiv-master/core/file.cpp:381
#3  0x00000000006617a4 in File::mkdirs (path="") at /home/drock/wwiv/wwiv-master/core/file.cpp:381

**Comment by granitepenguin** [comment]
Just tried the precompiled 5.1.1920, and that has the same issue (on the off chance it's a gcc issue).

**Comment by granitepenguin** [comment]
Yeah, it isn't ubuntu-specific either.  I just tried it on my board on debian 8

wwiv@vps40748:~$ ./bbs -v
WWIV Bulletin Board System [5.1.0.1914]
wwiv@vps40748:~$ ./bbs -w
Segmentation fault

**Comment by granitepenguin** [comment]
It's worth noting that WFC on linux doesn't actually do much and isn't worth using yet (it's NOT the same thing as WFC in Windows).  Don't let it's non-functioning stop you from playing with other stuff.

**Comment by granitepenguin** [comment]
verified working in 1925

**Comment by wwiv** [comment]
http://stackoverflow.com/questions/26158510/gcc-float-pointer-casting-in-c-causing-sigbus-error looks like a similar issue
