### ISSUE TITLE
Download Directory editor - can't create or change to directory

### ISSUE THREAD

**Issue by torradan** [wwivbbs/wwiv#738]
When trying to set up the download section, I'm getting an error when trying to enter the path

The first time I enter the path, it gives me an error stating "can't create or change to directory"
It creates the directory, but the editor still reflects the default (c:\wwiv\dloads).

Entering the path for a second time, it changes to the directory, and says "The path for this directory has changed", and the setting reflects the directory I wanted it to use.

System is running on 32bit Windows 7, WWIV version 5.1.0.1914

**Comment by granitepenguin** [comment]
I see something similar on linux, too.  It's not exactly clear what's happening, as the example location that is given is /wwiv/dloads (or c:\wwiv\dloads).  If you keep the default location, no directory is created (i.e., it's very confusing what you are supposed to actually do in the first place).  If you, instead, define dloads/testdir, it throws the error:

> A) Name       : tester
> B) Filename   : tester
> C) Path       : /bbs/wwiv/dloads/
> D) DSL        : 10
> E) Min. Age   : 0
> F) Max Files  : 50
> G) DAR        : None.
> H) Require PD : No
> I) Dir Type   : 0
> J) Uploads    : Allowed
> K) Arch. only : No
> L) Drive Type : HARD DRIVE
> N) //UPLOADALL: No
> O) WWIV Reg   : No
> 
> (Q=Quit) Which (A-M,[,]) : C
> 
> Enter new path, optionally with drive specifier.
> No backslash on end.
> 
> The current path is:
> /bbs/wwiv/dloads/
> dloads/testdir
> Unable to create or change to directory.

**\* and if you immediately try again, it works ***

> The current path is:
> /bbs/wwiv/dloads/
> 
> dloads/testdir
> 
> The path for this directory is changed.
> If there are any files in it, you must manually move them to the new directory.
