### ISSUE TITLE
WFC Screen stats not reseting every day

### ISSUE THREAD

**Issue by torradan** [wwivbbs/wwiv#739]
I've been noticing that the WFC stats are not being reset at the beginning of the day.  I haven't had much time to spend with the BBS, and it's showing 1 caller today (last caller was 5/16/2016), and the message count, local messages, email, feedback, minutes used, etc just keep adding up.  I tried to look in the code to see where it pulls this info from, but I'm not really versed in c++ to dig through it to attempt to figure it out on my own.  Previous to that, it was working just fine.  I haven't made any changes at all since the 16th.

I've tried shutting down the telnet server and bbs instances to see if that helped, and it didn't.  Reboot didn't do anything either.

Win7 x32, WWIV 5.1.0.1914

**Comment by torradan** [comment]
Downloaded build 5.1.0.1934, overwrote executables, and the issue seems to have been resolved, at least for now.  Going to wait until tomorrow and check if stats have reset at beginning of day.

**Comment by wwiv** [comment]
ok, let me know

**Comment by torradan** [comment]
I just checked, and it's not reseting the stats even with the new build.

**Comment by wwiv** [comment]
The stats get reset when the beginday event is run. bbs -e will force it to
run.

**Comment by granitepenguin** [comment]
shouldn't WFC be able to manage the beginday event?  If it doesn't (and nothing else does), that seems like a good place for it.

**Comment by torradan** [comment]
Seems it should automatically be reseting stats at the beginning of the day, without adding a separate event?  

I'm pretty sure it did that all along (back in the 90s, and then just recently), and then one day it just stopped for some reason.  Maybe it's just my machine causing the grief?

**Comment by wwiv** [comment]
I leave a wfc up (running BBS.exe) and mine are updated.

**Comment by wwiv** [comment]
I can't reproduce this

**Comment by wwiv** [comment]
What's in your zlog, that should get updated every day when the beginday is run
and when you say wfc, you mean bbs.exe, not wwiv5telnetserver right?

**Comment by torradan** [comment]
WFC in bbs.exe.  Running net2bbs instead of the telnet server.

One day it did just up and reset the WFC stats to 0 (not including then the bbs polled for new messages and whatnot). Right now it's saying 295 messages today.

Not sure where to proceed from here with it.  It's not a super big deal and crashing the machine, just sort of annoying.

**Comment by wwiv** [comment]
I still can't reproduce this.  Sorry
