### ISSUE TITLE
Running Events on a Node Running Event Multiple times 

### ISSUE THREAD

**Issue by k1cty** [wwivbbs/wwiv#742]
When Setting up a Batch file to run as an Event on Node 1 local node, If the particular node gets locked up.
When Resetting Local node 1 aka WFC screen the event will run over and over again until it catches up to the current Time.
For Example I have a batch file that runs every ten minutes to process updates on an ansi logon screen.
If i have to reset the WFC screen and it was off or locked up for an hour, It will run 6 times in a row until caught up on the current time of the system

I am Running 5.1 on windows 7 32 bit with no Addons ie fossil driver or frontdoor just stock setup

**Comment by wwiv** [comment]
Thanks for the bug. I admit I don't use the events in the bbs, but I'll take a look
