### ISSUE TITLE
Can no longer login from WFC using [Space] then [F] b5.1.0.1941

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#745]
Running WIndows 7 - 
In the past, hitting the space bar followed with F, would allow for an immediate Sysop login. Now, hittinf F simply flashes and nothing happens.
Can still login by selecting Y and entering user name or number and password.

**Comment by wwivsoftwareservices** [comment]
Passing of a Icon  

```
I was contacted last night by Craig Dooley (aka Morgul) and informed that Filo (aka Wig de Moville) passed away yesterday.  For those who are too young to remember, Filo was a Vietnam Vet and @2.WWIVnet for many years.  He wrote and maintained most of the early BBS and network documentation as well as managed all the registrations during the hay days of WWIV in the 80’s and up until I purchase WWIV in 1999.  He was a prolific mod writer and many of his mods are part of what you know today as “stock” WWIV.

For the older crowd, you may or may not know that Filo’s second moniker was a product of his days as a Combat Engineer in Vietnam. The 12 Bravo’s were always first in, last out or FILO….
```

Rest in Peace my friend.

**Comment by wwiv** [comment]
@BloodStoneBBS make sure your #1 is SL 255.  This seems to work for me

**Comment by BloodStoneBBS** [comment]
Yes, #1 has been 255 since day 1. Just tried again on b5.1.0.1899 Still no go. Will try a few other versions this weekend, time permitting. 
Could this be due to my moving the VM from Hyper-V to ESXi? -
Tried via RDP and the ESXi console using multiple versions.
Maybe I'll just follow some of my own advice and reboot.

**Comment by wwiv** [comment]
probably not esx related.

**Comment by wwiv** [comment]
let me know, just to double check I downloaded the latest build "wwiv-build-win-1943.zip" and tried it and things worked for me.

I also have a SL255 #2 account for testing, so Space + F is the same as Space + 1 to log in as 1 (both worked.) Space +2 also worked to fast login as #2 for me

**Comment by BloodStoneBBS** [comment]
Ugh... I changed _nothing_ and it suddenly begins to work again.  Call it a Garage Gremlin.

Updating to 1952 next.
