### ISSUE TITLE
can't log in through nodemgr

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#747]
With version [5.1.0.1942], I can't log in via telnet anymore on linux going through the nodemgr.  I get the following output when I connect.

> Debian GNU/Linux 8
> WWIV 5.0 UNIX Node Manager Bootstrap.
> Please wait while node data is parsed.
> Found 0/6 Nodes in use.
> Invoking WWIV with command line:./bbs -N1 -XU
> 
> BBS Terminated by exception: Screen height must be at least 25, was: 24Exiting

I'm wondering if the -XU needs to be removed now

**Comment by wwiv** [comment]
ahh, no. it's trying to connect to a local terminal I think.

**Comment by wwiv** [comment]
make you terminal one line higher. This will be temporary

**Comment by wwiv** [comment]
Ok relaxed the lines needed in https://github.com/wwivbbs/wwiv/commit/6d8712d8a10eafe5eae4a062281445bde43131a4
