### ISSUE TITLE
Error of wwiv telnet server

### ISSUE THREAD

**Issue by rdfig** [wwivbbs/wwiv#755]
The Following Error Occured:  System.IndexOutOfRangeException: Index was 
outside the bounds of the array.
 at WWIVSTelnetServer:MainForm.Mainform_Load(Object sender,
EventArgs e)

**Comment by k1cty** [comment]
Because of this error WWIV-UPDATE is also Running error on start-up

**Comment by wwiv** [comment]
Thanks for the bug report.

What do you man by "Because of this error WWIV-UPDATE is also Running error on start-up" ?

**Comment by k1cty** [comment]
the indexoutofRange error was also happening when trying to run wwiv update.
I had to manually download and install the updated exe's to fix but since update everything is good. I would suggest closing this error report.

**Comment by rdfig** [comment]
When will there be an update to fix. 

RDFIG Computer Solutions
Http://www.rdfig.net

**Comment by wwiv** [comment]
What do you mean by "When will there be an update to fix." ?

**Comment by rdfig** [comment]
The error message when I invoke WWIV. I sent bug report. Also WWIV locks up when I press C to modify chain. Or it mets me in and so t let me modify an entry

RDFIG Computer Solutions
Http://www.rdfig.net

**Comment by k1cty** [comment]
rdfig try downloading the latest updated install package and unzip exe's into your wwiv directory and then try starting wwiv again I beleive the errors are fixed in the latest build

**Comment by rdfig** [comment]
A link would be helpful.

**Comment by granitepenguin** [comment]
https://build.wwivbbs.org/jenkins/job/wwiv/1955/label=windows/artifact/wwiv-build-win-1955.zip

**Comment by MarkHofmann11** [comment]
http://build.wwivbbs.org/jenkins/job/wwiv/

**Comment by rdfig** [comment]
I did download the latest and it is v 5.`.0.`955,  I closed wwiv and ran wwiv-update.  When I ran the telnet server same error occurred but I noted I was showing version

3.1.0.1949.  Should I just copy over the bbs.exe to the wwiv folder?

**Comment by rdfig** [comment]
Well I just copied bbs.exe to the wwiv dolder and now it snows the correct verison

**Comment by rdfig** [comment]
Do you know how I can pass on a user name or alias?  I connect to door party with wwiv bbs and all I need now to complete this is to pass on the user name.

Have not found that info online.  I looked under doors/chain info but nothing there tells me.  Right now I pass the node info as %1, so just need to pass on the

User name/alias.

**Comment by rdfig** [comment]
Have a question.  Got Door Party working, that is a connection to Throwback bbs door server with 160 plus games.  I need to e able to pass to a bat fle the uwername or alias.  I have not found the info on the wwiv documentation.  Would you knw?

**Comment by wwiv** [comment]
Marking as fixed
