### ISSUE TITLE
Is it possible to port over the news.exe from wins into a Linux version?

### ISSUE THREAD

**Issue by k1cty** [wwivbbs/wwiv#759]
I currently have a workaround but it requires using a Windows machine and network share to process the news msgs

**Comment by wwiv** [comment]
Probably not... the wins code isn't that great and I'd probably replace it with something better for nntp access using the newer message API that is being written for wwivutil and the new native network stack.

You are welcome to try it though, I ported it from DOS + packet driver -> Win32 once, so it's fairly platform agnostic.
