### ISSUE TITLE
Random App Crash

### ISSUE THREAD

**Issue by k1cty** [wwivbbs/wwiv#761]
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: bbs.exe
  Application Version:  0.0.0.0
  Application Timestamp:    575b4692
  Fault Module Name:    ucrtbase.DLL
  Fault Module Version: 10.0.10586.9
  Fault Module Timestamp:   5642c5f8
  Exception Code:   40000015
  Exception Offset: 0008469a
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    1033
  Additional Information 1: 3bdf
  Additional Information 2: 3bdf95095c724b8977e1dd3edf7c88fc
  Additional Information 3: 2e13
  Additional Information 4: 2e130b34cc34384ccc6fd9c501a7cb16

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by k1cty** [comment]
Only thoughts on this one are that i am getting excessive Linux bots trying to Login using "ROOT XC3511

**Comment by wwiv** [comment]
unfortunately this doesn't give me any details on the crash... anything else ya got?

**Comment by k1cty** [comment]
is there a log file i should look at?

**Comment by wwiv** [comment]
I'm not sure.  that code (40000015) is an abort() call.
http://stackoverflow.com/questions/5115611/in-windows-does-the-exception-unknown-software-exception-0x40000015-occurred

**Comment by wwiv** [comment]
ok, I saw this too on mine, but I had replaced my debug build with the latest through wwiv-update (bummer).  I rebuilt a new debug build and should be able to get a stacktrace next time it happens.

**Comment by wwiv** [comment]
I fixed a slew of crashes recently. closing. please open a new bug if you see these again
