### ISSUE TITLE
display duplicating text

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#762]
OS: linux
WWIV Version: 1955

Getting some kind of echo, scramble duplication when logged in over telnet.  logged in via WFC seems fine.
![screenshot 2016-06-13 17 21 39](https://cloud.githubusercontent.com/assets/913430/16025194/84cebab6-318b-11e6-824f-4daec3f27815.png)

**Comment by askpatrickw** [comment]
Did you try re-seating your phone into the coupler? ;-)

**Comment by wwivsoftwareservices** [comment]
I think the flux capacitor stopped fluxing…..

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/e93f1869e690b601a07062081343966834b6d406

**Comment by granitepenguin** [comment]
Verified at this end
