### ISSUE TITLE
Document WWIV FTN

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#763]
This should be in the docs

 Msg: [506/534] WWIV Networking
Subj: WWIVnet-FTN
Name: Weatherman #1 @1 (Mark)
Date: Saturday, June 11, 2016   8:42 am <EST>
From: WWIVNet- Weather-Station [410-838-INET] {NC}
Loc:  Bel Air, Maryland

We discussed ways of making WWIVnet available to all BBS systems for awhile.
We decided the best path of action right now was to make my system work as the
gateway between native WWIVnet and WWIVnet-FTN.

So here it is:  WWIVnet-FTN
## WWIVnet-FTN (Application)

```
Name................:
Location............:
BBS / System Name...:
BBS Software........:
Operating System....:
BBS Software........:
Operating System....:
Telnet address......:
Website URL.........:
Mail tosser.........:
Areafix Password....:
```
## BinkP Info

```
    Session Password:
```

   Binkp address/port...:
         Crash or Hold...:

---
## Notes

```
  -  The WWIVnet-FTN hub is running D'Bridge.  D'Bridge uses the same
      password for "Binkp Session Password" as the "Packet
     Password".  I can make them different, but when a Session Password
       is set - it will also set the Packet Password
     (will use the same PW).

  -  The destination BinkP port for my D'Bridge hub is 24555
       (as noted in the Nodelist).

  -  Current Nodelist:
      https://github.com/wwivbbs/wwivnet/tree/master/wwivnet

  -  To submit the application, please log into my BBS
     (bbs.weather-station.org) and email me the application or
     Internet email to:  mark@weather-station.org
```
## Echos Available

```
     WWIV_GENCHAT - General Chat
     WWIV_WEATHER - Weather
     WWIV_MUSIC   - Music
     WWIV_ANSI    - ANSI Art Gallery
     WWIV_MODS    - WWIV Mods
     WWIV_NET     - WWIV Networking
     WWIV_DEV     - WWIV Development
     WWIV_SYSOP   - WWIVnet Sysops
     WWIV_TEST    - Test Posts
     WWIV_AUTO    - Automotive
     WWIV_TECH    - Technology
```

:.:       Weather Station BBS · telnet://bbs.weather-station.org         :.:
:.:    http://www.weather-station.org/bbs · Bel Air, Maryland - USA      :.:

**Comment by wwiv** [comment]
dunno if it should be in the docs - maybe just a page on www.wwivbbs.org on how to join?  WDYT?

**Comment by MarkHofmann11** [comment]
If we have control of wwivbbs.org, I would try to keep everything there.
Either that or a link from wwivbbs.org to where the other docs are
located.  Peaboy could help with this if he is still around..

**Comment by wwiv** [comment]
we do, and the source for it actually lives in github here: 
https://github.com/wwivbbs/wwivbbs.github.io

wwivbbs.org is a CNAME for wwivbbs.github.io

**Comment by wwiv** [comment]
I documented FTN usage for 5.2 here: 
http://localhost:8000/network/ftn_nets/

**Comment by wwiv** [comment]
wrong issue.

For this one, We have wwivnet.org, I'll point it at a github repo and let's put instructions there.  WDYT @MarkHofmann11 ?

**Comment by wwiv** [comment]
We can add it here: https://github.com/wwivbbs/wwivnet

Then that'll appear at WWIVbbs.org/wwivnet and soon www.wwivnet.org

**Comment by wwiv** [comment]
This is now documented on http://www.wwivnet.org

**Comment by wwiv** [comment]
docs are live at http://docs.wwivbbs.org/en/latest/network/ftn_nets/
