### ISSUE TITLE
Write issue 

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#765]
The program asked me to submit a screen capture. 
![write-error](https://cloud.githubusercontent.com/assets/13500419/16546253/4f5c889a-40f9-11e6-9b24-eea2c00a63e5.jpg)

I posted the message and it did get sent to the network, but I wonder what is cooking.

**Comment by wwiv** [comment]
has this happened again since?

**Comment by mmunson** [comment]
No. I think it was a freak error.
