### ISSUE TITLE
Netfossil/net2bbs not working with builds 1937+

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#767]
Personally I prefer using net2bbs telnet front end that comes from Pcmicro http://pcmicro.com/NetFoss/ instead of the included telnet server. I found out in the newer builds net2bbs/netfossil isnt working with wwiv. I think the changes in 1937 are the culprit. Build 1936 works with net2bbs/netfossil. I did some backtracking to find out what is wrong. 

a. In 1937 no keyboard input possible remotely.
b. In 1969+ it just simply disconnects.

**Comment by wwiv** [comment]
I just tried to download it and windows defender won't allow it. Claims it has Trojan:Win32/Pocyx.F!cl  in it.

**Comment by wwiv** [comment]
I just emailed support@pcmicro.com about it. Let's see what happens.

**Comment by wwiv** [comment]
@mmunson what's the contents of your net2bbs.ini? I don't know what you are using

**Comment by wwiv** [comment]
I had an old 1.04 (from renegade) and that seemed to work.
