### ISSUE TITLE
add more detail to wwivutil log output

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#772]
When you run wwivutil, What gets put in the log is very minimal.  All you see is the start and end of the process, but you have no idea what it did when it ran.  At a minimum, I would expect to see the command line that was run.  You could get most of the information you need just from that.

**Comment by wwiv** [comment]
Fixed for _all_ tools in https://github.com/wwivbbs/wwiv/compare/572e28388d35...26d9be84ae9a
