### ISSUE TITLE
add verbose flag for logging network binaries

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#775]
several of the new network\* binaries are very wordy when logging.  networkb and network2 are good examples of ones that spray a lot of info.  For normal operation, they probably don't need to be as verbose.

It would be nice to define different verbosity levels and set a variable for each (maybe in wwiv.ini) to turn up or down the level depending if we are debugging or not.  We could have a global verbosity, and/or local verbosity for each process.

**Comment by wwiv** [comment]
flag is added to the binary. let me know what output you think should be gated by the verbose flag.
still to do is see if I can make it a wwiv.ini setting (unclear if that's a great idea since that would mean each binary will need to parse wwiv.ini at startup, which takes time)

maybe a $0.ini instead (we use $0.log for logging, so could use $0.ini for logging options for each binary, or defaulting any command line flags).

GP: WDYT?

**Comment by granitepenguin** [comment]
What about something in-between?  Have a network.ini where things can be set for all of them, with different sections for each $0?  All the network\* binaries are related, so we could define globals that make sense (eg, log location) and use the individual sections for specific things.

It would be a lot smaller (i.e., faster) than mucking with the wwiv.ini, but would avoid having a dozen ini files to maintain.

**Comment by granitepenguin** [comment]
I'll have to think a little about what should be what verbosity level.  I was thinking at least a level 1-3 where 3 was everything and 1 was just the essentials. (for example, the debug1-debug3 in openssh)

debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /Users/drock/.ssh/id_dsa (0x7ff2f9d04e60),
debug2: key: /Users/drock/.ssh/id_rsa (0x0),
debug2: key: /Users/drock/.ssh/id_ecdsa (0x0),
debug2: key: /Users/drock/.ssh/id_ed25519 (0x0),
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey

**Comment by wwiv** [comment]
Done in https://github.com/wwivbbs/wwiv/compare/eb9318ab50f6...e42d90a0656e
