### ISSUE TITLE
Test & Document Trashcan.txt functionality

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#777]
It is in the code... not sure if it works yet.
https://github.com/wwivbbs/wwiv/search?utf8=%E2%9C%93&q=trashcan

**Comment by askpatrickw** [comment]
related to #766

**Comment by granitepenguin** [comment]
best I can tell, it does **not** work.  I also can't tell what the format of the file is supposed to be, so I don't know if I'm just doing it wrong.  I tried two different single-line entries (once with uppercase, and once with lowercase) and neither prevented the new userid from being created.

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/docs/commit/11ca72f6bbd03fc2b99afaae4ab94937b08e6e30
