### ISSUE TITLE
network2 should write to dead.net on error

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#785]
A side-effect of #783 is finding network2 is not gracefully handling error conditions.  We need to make sure if an error does occur, we don't wipe out the incoming local.net.  We can't just leave it laying around, because that will create an endless processing loop, but we need to save the data in dead.net so it can be processed later after a fix is found.

basically all fatal errors should be caught and addressed before removing local.net

**Comment by granitepenguin** [comment]
Updated a few of the message handling functions with https://github.com/wwivbbs/wwiv/commit/682221e51533aabc4b3592a0fb62aeba087d7dc3, but still need to deal with the subs.cpp functions.

Not sure how the resp() functions work, so not sure how to implement the same dead.net logic (or even if it makes sense to do so)

**Comment by wwiv** [comment]
resp is a macro-like function call (it's actually a lambda). 

It calls send_sub_add_drop_resp with different args.  If it fails, then we just failed to notify the requester, but still handled the request.  I wouldn't bother re-trying it.

**Comment by granitepenguin** [comment]
If we find more we will open a new issue
