### ISSUE TITLE
Implement RG style pipe codes

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#788]
http://renegadebbs.info/files/QUICKREF.PDF

**Comment by wwiv** [comment]
Also from Mystic's Docs: (link: http://wiki.mysticbbs.com/doku.php?id=displaycodes)

```
 ---------------------------------------------------------------------
 Available MCI Codes
 ---------------------------------------------------------------------

 Codes 00 through 15 can be used to set the foreground color:

      00 - Black foreground.
      01 - Dark blue foreground.
      02 - Dark green foreground.
      03 - Dark cyan foreground.
      04 - Dark red foreground.
      05 - Dark magenta foreground.
      06 - Dark yellow foreground.
      07 - Light gray foreground.
      08 - Dark gray foreground.
      09 - Light blue foreground.
      10 - Light green foreground.
      11 - Light cyan foreground.
      12 - Light red foreground.
      13 - Light magenta foreground.
      14 - Light yellow foreground.
      15 - White foreground.

 Codes 16 through 23 can be used to set the background color:

      16 - Black background.
      17 - Blue background.
      18 - Green background.
      19 - Cyan background.
      20 - Red background.
      21 - Magenta background.
      22 - Yellow background.
      23 - Grey background.
```

**Comment by wwiv** [comment]
looks like (from my testing and looking at the code), |16-|23 work

What's missing in wwiv 5.0?

**Comment by granitepenguin** [comment]
most likely what's missing is proper documentation on how to use them.

Another piece of this is how do you type a pipe character if you actually want one?

I'll do some testing and see if I can validate they all work.  I tried a couple of them yesterday and they _did_ show up immediately in the built-in editor.  It may be that FSEDs are the ones that can't see them (WWIVedit, for example, is probably not designed to see them).

**Comment by granitepenguin** [comment]
found some minor fail issues, but overall working reasonably well.  They do, in fact show up in the built-in editor, but there's a difference in what they look like while editing compared to displaying (and not in a good way)

Here's what it looks like while editing 
![editing](https://cloud.githubusercontent.com/assets/913430/17142276/285cec48-5315-11e6-8a73-37e690cc9641.png)

and here's what it looks like when displaying
![displaying](https://cloud.githubusercontent.com/assets/913430/17142288/32bbf68e-5315-11e6-9e36-991952d52759.png)

In both cases, this is being viewed in SyncTERM.  Note that the FG color when displaying didn't stay blue.  granted, I was hacking this up pretty badly toward the end, so it might be an issue with reading multiple pipe codes and getting confused while processing them.

Regardless, there's still consistency issues in presentation vs creation that should be looked at.  It may be that way for all forms of colors, not just |nn

**Comment by granitepenguin** [comment]
for completeness, here's what it looks like in a terminal session.  What's interesting is how **some** of the FG colors on BG colors worked, but not all of them.  Probably need to look at the actual message and see what color codes are in it.

![screen shot 2016-07-26 at 11 25 04](https://cloud.githubusercontent.com/assets/913430/17146347/b33a270a-5323-11e6-941c-a41b14e356b4.png)

**Comment by granitepenguin** [comment]
and even more interesting... here's what they look like on weather station

![screen shot 2016-07-26 at 11 45 54](https://cloud.githubusercontent.com/assets/913430/17147072/9b50b96c-5326-11e6-96b6-a5ffea634cfb.png)

So the older 4.24 that Mark's running sees them just fine (with a small hiccup where the rainbow word "interesting" got an extra CR/LF for some reason).

**Comment by wwiv** [comment]
GP figured it all out :) anyone want to take a stab at documenting it?

**Comment by wwiv** [comment]
I documented it here: https://github.com/wwivbbs/docs/commit/7416f2d95fa6ba259537f248b155371f5dc90471

**Comment by wwiv** [comment]
Feel free to reopen if there's more to do, or better yet, send a pull request
