### ISSUE TITLE
using --net for anything other than 0 sends to 0

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#789]
This sends correctly to network 1 (rushnet on mine)

```
./network --network_number=1 --node=1 --bbsdir=${WWIV_DIR} --sk
ip_net --v
```

This sends to network 0, even though network 1 is set  (the --net flag is not getting parsed properly)

```
./network --net=1 --node=1 --bbsdir=${WWIV_DIR} --sk
ip_net --v
```

**Comment by wwiv** [comment]
network.exe doesn't use my wrapper class to handle network command line args...
