### ISSUE TITLE
Make it easy to run DOS doors under DOSBox for WWIV

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#803]
Right now it's not really done in the WWIV community.
Here's a rough sketch of what has to happen:
- Make it easy to get DOSBox with the socket inheritance fix.
- Documentation on how to run it
- Helper scripts, etc to make it easy to run it.

**Comment by wwiv** [comment]
Synchronet has this link for how to do it http://dosbox.bbsdev.net/
They also have a patched version of 0.63 of DOSBox.

**Comment by wwiv** [comment]
For WWIV, I've taken the most recent SVN version of DOSBox and verified the socket inheritance works as expected.  Also started fixing some issues (crash on invalid socket handle, and faked out share). The code is here:
https://github.com/wwiv/dosbox

**Comment by wwiv** [comment]
Another reference doc:

http://cyberia.darktech.org:8080/articles/qemu-howto.html

**Comment by granitepenguin** [comment]
Looks interesting.  I'm going to play around with this and see what I can get working.  The first thing I noticed is using ``apt-get install qemu`` brings in a LOT of extra stuff we probably don't need.  We only care about DOS, so I'm trying with ``apt-get install qemu-system-x86`` instead.  For example, the install footprint is 212MB with qemu, and 32MB with qemu-system-x86.  I doubt we need sparc, MIPS, and ppc architectures.

**Comment by wwiv** [comment]
I think even better is QEMU. I got this working pretty well and documented it.
