### ISSUE TITLE
networkb needs to pass through verbose flag to network1 and network2

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#804]
if verbose is set in networkb, it is not using the verbose flag when it calls network1 and network2

**Comment by wwiv** [comment]
are you planning on doing this? if not, I can, just assign it to me

**Comment by granitepenguin** [comment]
Yes, I can do it.  RL is just getting in the way right now.

**Comment by wwiv** [comment]
hmm.. gets a bit trickier since legacy network software doesn't support --v

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/wwiv/commit/e5cc28fec0ca27eff02b78235b496dc0e7a14a71
