### ISSUE TITLE
merge wwivnet docs for windows and linux

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#812]
with net51 we don't need dosemu anymore, can these be merged?

**Comment by granitepenguin** [comment]
Probably.  dos\* is needed for other stuff, but not WWIVnet

**Comment by wwiv** [comment]
We point to these docs from the dosemy config for doors, should copy the dosemu stuff over there

**Comment by granitepenguin** [comment]
yes, some general reorg is in order

**Comment by granitepenguin** [comment]
Fixed in https://github.com/wwivbbs/docs/commit/c05aa558aef32a608b0863ad2ad9fafa5f922ffc
