### ISSUE TITLE
install.sh needs to be updated for the native network stack

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#817]
Right now it setups network{1,2,3}.bat. Not needed anymore
Also I thought init unzipped things, why does install.sh need to do it?

**Comment by granitepenguin** [comment]
because init does not properly extract stuff on linux (at least it didn't at the time).  It's also assuming zip exists, which it doesn't on most linux distros by default.  I'll test it on a fresh build

**Comment by granitepenguin** [comment]
clean install looks like init is unzipping data files properly now (assuming unzip is installed, but we pre-check for that in the script).  Should be safe to take out the cruft.

**Comment by granitepenguin** [comment]
fixed in https://github.com/wwivbbs/wwiv/commit/41ec5aa7e2216015fe5d0b179b090a45b059123c
