### ISSUE TITLE
DoorParty & BBSLinks

### ISSUE THREAD

**Issue by rdfig** [wwivbbs/wwiv#824]
Ok, these were working fine until the last couple of updates.  I could telnet into bbs and select either one and it will work.  Now when I telnet in it never appears to do anything until I look at the computer where wwiv is located open up the windows and I can see the output there but not on the computer where I used my netrunner to telnet in.  Not sure I am clear.  Does not display on computer I use to telnet in, but see the screen output on the wwiv machine where I see user logged in.  it was working and now not and no changes were made.

**Comment by wwiv** [comment]
What version used to work?  How is this setup? I'll try to reproduce it, but haven't used doorparty so don;t know what to install, etc

**Comment by rdfig** [comment]
It was about 3 updates from 5.1.0.2060.  It was working for a while, then quit and then was working again for about 2-3 updates.  And now it quite working again.  The only thing that quit working is the fact from the telnet client you don’t see the output to the screen until you go to the computer that host thw wwiv bbs.  There you see the screen output.. 

BBSLInks would be easiest to use.  It does require yuu contact the sysop and get approved for connection.  I can zip up my bbslinks folder that contains my authorization codes to connect.

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net mailto:rdfigsupport@rdfig.net 

General Support:  rdfigueroa@gmail.com mailto:rdfigueroa@gmail.com 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net http://www.rdfig.net/

**Comment by wwiv** [comment]
Sure, sounds good.

**Comment by rdfig** [comment]
Maybe try the wlord.bat in that bbslinks folder also.

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net mailto:rdfigsupport@rdfig.net 

General Support:  rdfigueroa@gmail.com mailto:rdfigueroa@gmail.com 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net http://www.rdfig.net/

**Comment by wwiv** [comment]
which bbslinks folder?

I just tried with telnetdoor directly and that worked as expected with these settings:

```
Editing Chain # 6

A) Description  : telnetdoor
B) Filename     : U:\bbs\tdoor\telnetdoor.exe -Smystic.wwivbbs.org -D%E
C) SL           : 50
D) AR           : None.
E) ANSI         : Optional
F) DOS Interrupt: NOT Used
G) Win32 FOSSIL : No
J) Local only   : No
K) Multi user   : No
L) Registered by: AVAILABLE
M) Usage        : 10
N) Age limit    : 0 - 255
```

**Comment by rdfig** [comment]
Try the wlord.bat file or the wmenu.bat file.

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net mailto:rdfigsupport@rdfig.net 

General Support:  rdfigueroa@gmail.com mailto:rdfigueroa@gmail.com 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net http://www.rdfig.net/

**Comment by wwiv** [comment]
sorry I don't know where those bat files are, to try them.

**Comment by rdfig** [comment]
What is the -D%E

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net mailto:rdfigsupport@rdfig.net 

General Support:  rdfigueroa@gmail.com mailto:rdfigueroa@gmail.com 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net http://www.rdfig.net/

**Comment by rdfig** [comment]
Should be in the bbslinks archive which should have depcompressed to a folder named BBSLINKS.

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net mailto:rdfigsupport@rdfig.net 

General Support:  rdfigueroa@gmail.com mailto:rdfigueroa@gmail.com 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net http://www.rdfig.net/

**Comment by wwiv** [comment]
ok, the archive never made it here, can you email it to me rushfan at wwivbbs dot org, this email is going to the github issues list not private email.

-D%E is -D is path to door32.sys, %E is replaced by wwiv to be the path to door32.sys

**Comment by wwiv** [comment]
current working theory is this was broken in https://github.com/wwivbbs/wwiv/commit/45896c0b08eea180006400d99a1ea2e3e2289d6c

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/e599d9d65dd03cb4b65783156dd4470251a708d9

**Comment by rdfig** [comment]
Thanks.  Working like you said in fix.

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net mailto:rdfigsupport@rdfig.net 

General Support:  rdfigueroa@gmail.com mailto:rdfigueroa@gmail.com 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net http://www.rdfig.net/
