### ISSUE TITLE
subs list corrupted

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#829]
Something "bad" happened between 2064 and 2070 that corrupted my subs.  I noticed the problem because my scan for new posts didn't find anything even though I knew there were new ones that got processed.

This is what it looked like before (on 2064)
![subs_list_before](https://cloud.githubusercontent.com/assets/913430/17786364/23ee8cb0-654a-11e6-9d7a-b63996b1f471.png)

and this is what they look like after (on 2070)
![subs_list_after](https://cloud.githubusercontent.com/assets/913430/17786372/2a6905b6-654a-11e6-8d99-06404f6ae7cf.png)

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/issues/829
