### ISSUE TITLE
build 5.2.0.2074 - Network2 cannot write to deadfile and crashes on every toss

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#830]
Rolled back to an earlier version and all works OK.

Snippet of network2.log:

[errors.txt](https://github.com/wwivbbs/wwiv/files/428947/errors.txt)
[dead.net.txt](https://github.com/wwivbbs/wwiv/files/428948/dead.net.txt)

**Comment by wwiv** [comment]
I know it sounds odd but is local.net (the file) wedged? can you delete it yourself? I've seen this happen a few times in windows where a file thinks that it's locked but the process that had it locked is already terminated.

**Comment by BloodStoneBBS** [comment]
It was deleted when I rolled network2 back to a previous build.

**Comment by wwiv** [comment]
try with 2075 and later and let me know if you still see it.  I think this could all be related to the malformed messages from 2074

**Comment by BloodStoneBBS** [comment]
Will do

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by BloodStoneBBS** [comment]
Still happening on build 2079: 
Unhandled exception at 0x6E91D160 (vcruntime140.dll) in network2.exe:0xC00000005: Access violation reading location 0x2E736E77.

**Comment by wwiv** [comment]
Hmm... which network file was doing that? (network2, 1, etc?)
can you share the contents of your p_.net and s_.net files with me?

**Comment by BloodStoneBBS** [comment]
Network2.exe but no s_.net or p_.net files that I can see.

**Comment by BloodStoneBBS** [comment]
This seems to be resolved.
