### ISSUE TITLE
Build 5.2.0.2082 - WWIVServer crashes when forced closed by remote

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#834]
The Bots are persistent!

I've seen this with earlier builds as well. 

Debug info:

System.Net.Sockets.SocketException was unhandled
Message: An unhandled exception of type 'System.Net.Sockets.SocketException' occurred in System.dll
Additional information: An existing connection was forcibly closed by the remote host

**Comment by wwiv** [comment]
where do you get this debug info?

**Comment by wwiv** [comment]
I found a place where I call a socket method without catching SocketException.

**Comment by wwiv** [comment]
probably fixed in https://github.com/wwivbbs/wwiv/commit/0a87d26b52c606ba75e890d4faa67eb6579bcbf2

let me know if it still happens once you have a build with this fix.

**Comment by BloodStoneBBS** [comment]
I get my debug info from the VS2013 Just in time debugger. Happens to be installed on my BBS VM.
