### ISSUE TITLE
New messages don't show up till a post

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#836]
@BloodStoneBBS reported this.

What I need to know is 
- how to reproduce it exactly
- does it happen with which combinations of (wwiv and network software).  This matrix I need to know

wwiv 5.x and netxx

**Comment by wwiv** [comment]
I can't repeat this. I did the following.

launched wwiv. node 1
logged in to it.
did a "/a"

opened new cmd.exe
network /n1

went back to node 1 bbs
did /a
saw new posts

**Comment by BloodStoneBBS** [comment]
Easy enough for me to replicate. I just wait to see that I have received a new packet from 1 and then log into the BBS. I select N scan for new messages and see no new messages. I then post a message (using test sub) and after posting, I can then new scan and see all of the new messages.
This could be on me though.

Since network2 was crashing on every begin day or net toss, I rolled it back a snapshot from 8/10. Not certain as to the version but I’ll check.

WWIV 5.2.0.2084 with the network files that accompany the build upgrade.

I suppose it could be because I also call network1 and network2 in my toss batch file but now I see that I am also having WWIVServer crashes as well.

I will try and spend some time digging into this more this evening to see which builds this occurs in and try and track down when it began.

J..

**Comment by wwiv** [comment]
Here's what I did that works.

console1

```
launch wwiv
log in as sysop
new scan
log off
wait at wfc

console2
```

run network /n1

console1

```
log in
new scan
see new messages.

This works, I'm on the latest network code and bbs.

Let's discuss the crash in the other bug
```

**Comment by BloodStoneBBS** [comment]
I followed the above example and did not see any new messages. I then posted on a Usenet Sub I host and after /s, I new scanned and had weeks of new Usenet messages in the Usenet Subs. 
Sorry I did not catch the date of the first.

Will have more time Saturday to test and document my exact steps and results.

**Comment by BloodStoneBBS** [comment]
Just an update - This morning, launch local node WFC. I can see that there are 6 new messages today. 
Login remotely using SyncTERM, select "Scan All Message Areas For New Messages?" and there are no results.
Disconnect, reconnect, Scan all... again and I now see the 6 new messages.  
Not quite the same as what I was noticing before but still odd.

Reply to a couple in the test Sub, new scan completes... Jump to Usenet conference, hit N, there were three new messages.

Is the New message scan in all conferences related to what I'm seeing over here? Conferencing?

**Comment by BloodStoneBBS** [comment]
More oddity - 
After reading all new messages I hit N again, nothing.  I then hit /a and have another message to read.
There was a toss before I ran the above Usenet new scan but I did not see any new messages received.

**Comment by wwiv** [comment]
Well "N" just scans the current conference, where "/A" scans all conferences.  That could explain that behavior.

**Comment by BloodStoneBBS** [comment]
Is that new? It used to scan all conferences:

Conference: General
[1] [System Announcements]: N

New message scan in all conferences?

The above is the menu prompt. I jumped into each conference and tested. N did work in WWIVnet and Usenet but it used to work to show all new messages in all conferences.

**Comment by wwiv** [comment]
oh  you are right, N asks to scan all conferences. /A always scans all conferences.

are you saying N and answering Yes to "scan all conferences" is not scanning all conferences?

**Comment by BloodStoneBBS** [comment]
Exactly. but not really just that, on many occasions, new messages do not show up at all until after a post.  I can see now why messages in a different conference have not been showing up (in the last month or so) if the N no longer scans all messages. 
There is still the issue that regardless of conference, N does not show any new messages until after a post, then it shows several - assuming of course that there are actually new messages.

**Comment by BloodStoneBBS** [comment]
Just now, I launched the local node WFC. It shows 4 new messages. I log in remotely and at the New message in all conferences prompt (set in wwiv.ini) I select Y - the scan runs and I see no new messages. 
I see that I am currently in the WWIVnet conference. I jump to the Usenet and scan for new. Two messages. I jump back to the WWIVnet conference, scan for new (N both times) and I now see the two remaining new messages.

I'm wondering if Matthew is experiencing the same issue?

**Comment by wwiv** [comment]
possibly.  I think this may be conference related and not networking related (dunno, still trying to figure out how to reproduce this so I can fix it...)

**Comment by BloodStoneBBS** [comment]
I do not see any of this in 5.1.0.2063.

**Comment by BloodStoneBBS** [comment]
Running well all day on 5.1.0.2063. All posts are being delivered when using the New message scan at login.
