### ISSUE TITLE
WFC Total Users displaying capacity, not current number

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#839]
Windows 7, 5.2.0.2105 but noticed in 5.1.

In the WFC, the Total Users field displays 65535, not the current total number of users. While I would LOVE to have that many callers, I'm sure it's a lot closer to 200.
![capture](https://cloud.githubusercontent.com/assets/13243281/18215200/eb580216-7104-11e6-9c21-050fb17e1f98.PNG)

Related? - When using U from WFC or //UE remotely, moving to the end of the list takes you to user 5000 rather than the last occupied user number. 
![capture1](https://cloud.githubusercontent.com/assets/13243281/18215292/61ed323e-7105-11e6-8c18-9191fc96c56f.PNG)

**Comment by wwiv** [comment]
can you try the user editor in init and let me know how that one works?

**Comment by BloodStoneBBS** [comment]
Just looked in INIT. Same experience. When I go to the end of the user listing I see 5000 user accounts mist are being shown as deleted users. Will post a screen shot.

Sent from my Verizon Wireless 4G LTE smartphone

**Comment by BloodStoneBBS** [comment]
![capture](https://cloud.githubusercontent.com/assets/13243281/18252008/6ffb341e-7341-11e6-9c49-43bfbe2f5bad.PNG)

**Comment by BloodStoneBBS** [comment]
I'll try changing my max number of users in INIT.

**Comment by BloodStoneBBS** [comment]
Changed my max from 5000 to 5005 yet the user editor still shows 5000 as above.

**Comment by wwiv** [comment]
one more, what's the exact filesizes of your 

C:\wwiv\data\user*
C:\wwiv\data\name*

**Comment by BloodStoneBBS** [comment]
USER.DAT 37,200 bytes
USER.LST 5,121,024 bytes
USER.QSC 2,740,548 bytes
names.lst 10,098 bytes

User\* all caps
names lower

**Comment by BloodStoneBBS** [comment]
Have not run FIX. Is it still an option?

**Comment by wwiv** [comment]
It's now part of wwivutil.  Try this:

```
wwivutil fix users
```

**Comment by BloodStoneBBS** [comment]
GRIN... increased count by 5. Now at 5005.

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by wwiv** [comment]
well, those file sizes tell me you really have that many users listed in the users datafile... wowza.

poke through them in useredit, are they duplicated or empty records?

**Comment by wwiv** [comment]
did new users join to make records 5002 through 5005? If so, you could use fsutil from windows to set the new filesize (make a backup first).

`fsutil file seteof <filename> <size in bytes>`

user.lst should be 1024 bytes per user (plus 1024 bytes for the header). so 2 users = (2+1)*1024=3072 bytes.

after doing this, try running `wwivutil fix users --exp`

If that works, then we can also trim the QSC file the same way.

**Comment by BloodStoneBBS** [comment]
All but 200 or so are empty, deleted user accounts

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by BloodStoneBBS** [comment]
Nope. No new users :-(

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by wwiv** [comment]
cool, then the fsutil command should work (but backup stuff 1st)

**Comment by BloodStoneBBS** [comment]
Looks like fsutil uses different parameters now:

C:\WWIV\DATA>fsutil file seteof user.lst 315392
seteof is an invalid parameter.
---- FILE Commands Supported ----

findbysid               Find a file by security identifier
queryallocranges        Query the allocated ranges for a file
setshortname            Set the short name for a file
setvaliddata            Set the valid data length for a file
setzerodata             Set the zero data for a file
createnew               Creates a new file of a specified size
queryfileid             Queries the file ID of the specified file
queryfilenamebyid       Displays a random link name for the file ID

C:\WWIV\DATA>

**Comment by BloodStoneBBS** [comment]
Decided to roll the files back to the point where the size was more of an indication of the accurate number of users. All better – ATM.

Still very curious what could have happened.

**Comment by wwiv** [comment]
me too - if you see what is trouncing it, please let me know so I can fix it.  closing since you have it working
