### ISSUE TITLE
Existing malformed messages cause errors in the log

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#840]
It looks like if there are any malformed messages in a sub, any time you touch the sub (e.g., to add a new message) it generates error messages in the log about the malformed message.

It appears that touching a sub involves touching every message in the sub.  I'm sure that's by design, but is it possible to not do that?  In this case, it's generating misleading error messages in the logs.  They are not incorrect (the messages are, indeed, malformed), but it shows a lot of message overhead that maybe shouldn't be happening.

**Comment by wwiv** [comment]
What log level are they logged at?
