### ISSUE TITLE
//who showing inaccurate results

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#842]
Windows 7 x86, 5.2.0.2107

Pretty minor but when using the //who command via telnet or locally, the results are inaccurate.
Example in the image below. I am connected to node 1 locally with no others connected:

![capture3](https://cloud.githubusercontent.com/assets/13243281/18399031/13673b30-7684-11e6-8ffe-80d172d947fb.PNG)

When connected remotely, it shows node 1 as offline but nodes 2 and 3 both show me logged in and accessing the Main Menu.

Does the //who command simply look at the drop files in the associated tempx folders? Just not deleting on disconnect?

All of the other nodes, including those listing 'Getting User ID' are actually offline.

**Comment by wwiv** [comment]
you can delete data\instance.dat to get it reset.  This happens, especially if the bbs crashes and the node isn't ever used again.  unclear why 1-3 are wedged.  maybe we're not cleaning it up?

**Comment by wwiv** [comment]
or just launch each node once to clear it.

**Comment by wwiv** [comment]
on my setup, exiting the node causes it to reset the data in instance.dat
