### ISSUE TITLE
WWIVServer 5.2.0.2126 - Cannot launch local node from Server

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#847]
And telnet connections will not connect. Just a flash on the screen and then nothing.
Windows 7 x86.

Build 2119 (previous version) works fine.

**Comment by wwiv** [comment]
run init

**Comment by BloodStoneBBS** [comment]
That worked!

**Comment by BloodStoneBBS** [comment]
Perhaps something to mention or add a blurb for those who use the upgrade tool moving forward?

**Comment by wwiv** [comment]
It's in the what's new.txt

**Comment by BloodStoneBBS** [comment]
Perhaps I should read more ;-)
Thanks, as always!

**Comment by wwiv** [comment]
This tells me WWIV update hurts... I need to figure something out... Or
find someone who will help.

**Comment by BloodStoneBBS** [comment]
It's definitely a benefit and a useful tool, just limited ATM. 
I wish I knew C. Every time I get started down the learning path, work and family take a hit. Perhaps after I get this dang VMWare cert out of the way.
