### ISSUE TITLE
ListPlus issue 2129+

### ISSUE THREAD

**Issue by mmunson** [wwivbbs/wwiv#848]
I noticed a new field is appearing in my ListPlus display. The photos will be attached. 
![listplus-cfg](https://cloud.githubusercontent.com/assets/13500419/18812010/459ac64c-827a-11e6-9f28-6803bd2b5dda.jpg)
![listplus-lst](https://cloud.githubusercontent.com/assets/13500419/18812012/4a1e5aee-827a-11e6-8fea-4b74402e0331.jpg)

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/wwiv/commit/dbb906f29f397ff2d1ea699c819eaa4665f393d7

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/9f61299eb9bde9acee25866eb88861c47bb1aeb1 for reals
