### ISSUE TITLE
Userlist corruption?

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#851]
For some time now I have been noticing odd issues with the user records such that they seem to display inaccurately or incorrectly. 

Example, the list of last callers beginning with a specific number display only as the user number, no alias or name. Also, when I receive the SMS notification of a new user, it shows extra "%"character in the SMS.

![capture](https://cloud.githubusercontent.com/assets/13243281/18893933/df2ed31a-84c4-11e6-89fe-4c70c0270ac3.PNG)

Everything looks fine in the //UE and INIT user editors.
WWIVUTIL FIX USERS only shows a single issue where I have a duplicate username in the list.

**Comment by wwiv** [comment]
The % in the SSM isn't related, I'll fix that. it was just a typo.

Unclear what could cause the logs to not show username, I'm looking now at the code

**Comment by BloodStoneBBS** [comment]
Great! Thanks for all your hard work.  About to submit another unrelated issue though.

**Comment by wwiv** [comment]
Is it possible your user # 308, 309 and 311 have no username?

**Comment by BloodStoneBBS** [comment]
No, they all have names.
311 = Trance
310 = BKJ
309 = Goonie
308 = The Wanderer
307 = Merlin

All have names.
Feel free to add a user and test away. If you like, I can set you up as CoSysop.

**Comment by wwiv** [comment]
I just logged in and see no name by 313. 

```
Time Left: 499 minutes
Conference: General
[3] [Introductions]: E


Enter user name or number:
:313

E-mailing  #313

Title:
Aborted.

```

What about 313?

**Comment by wwiv** [comment]
308 and later seem to have no name... strange.

**Comment by wwiv** [comment]
1st. zip up your names.lst and email it to me.

Then try this (and paste the output into the bug)

```
fix users --exp
```

Then check to see if its' fixed by trying to email 313. 

if not, delete names.lst and try that again.

**Comment by BloodStoneBBS** [comment]
Exactly - I'll email you the file shortly -
After backing up the names.lst file, I ran wwivutil fix --exp and have the following:
C:\WWIV>wwivutil fix users --exp
2016-10-11 16:59:02,809 INFO  Runnning FixUsersCommand::Execute
2016-10-11 16:59:02,814 INFO  Reading C:\WWIV\DATA\status.dat...
2016-10-11 16:59:02,819 INFO  Checking USER.LST... found 313 user records.
2016-10-11 16:59:02,825 INFO  TBD: Check for trashed user recs.
2016-10-11 16:59:02,830 INFO  Reasonable number.
2016-10-11 16:59:02,857 INFO  [skipping duplicate user: WEATHERMAN #144]
size=312 10296
2016-10-11 16:59:02,903 INFO  Checking NAMES.LST
2016-10-11 16:59:02,907 INFO  STATUS.DAT contained an incorrect user count.

I then verified that there was no change in the display of user names nor E-mail.

Deleted Names.lst file and Re Ran the above command. Results below:

C:\WWIV>wwivutil fix users --exp
2016-10-11 17:03:08,093 INFO  Runnning FixUsersCommand::Execute
2016-10-11 17:03:08,097 INFO  Reading C:\WWIV\DATA\status.dat...
2016-10-11 17:03:08,102 INFO  Checking USER.LST... found 313 user records.
2016-10-11 17:03:08,107 INFO  TBD: Check for trashed user recs.
2016-10-11 17:03:08,111 INFO  Reasonable number.
2016-10-11 17:03:08,145 INFO  [skipping duplicate user: WEATHERMAN #144]
size=312 10296
2016-10-11 17:03:08,184 INFO  Checking NAMES.LST
2016-10-11 17:03:08,187 INFO  C:\WWIV\DATA\names.lst does not exist, regenerating with 312 names

Now e-mail to a user now only shows "E-mailing" with no username or user number.
I believe I just interrupted you at a login.

**Comment by wwiv** [comment]
ha, I wondered what happened. 👍

**Comment by BloodStoneBBS** [comment]
Just an FYI -

The username does not show up in the log either: 

WWIV 5.2.0.2163, inst 10, brought up at 10:40:37 on 10/11/2016.
!!! Wanted to run the beginday event when it's not required!!!

80:  #313 10:28:58 10/11/2016   115200 - 2 (2)

**Comment by BloodStoneBBS** [comment]
Post wwivutil fix:

78      #313                         English    20:19 10/10 115200                2
79      #313                         English    09:09 10/11 115200                1
80      #313                         English    10:28 10/11 115200                2
81     Jahmas #29               English    15:19 10/11 115200                1
82     Rushfan #156            English    16:12 10/11 115200                1
83     Rushfan #156            English    16:19 10/11 115200                2
84                                       English    17:12 10/11 115200                3
85                                       English    17:16 10/11 115200                4

84 & 85 were you.

**Comment by wwiv** [comment]
I have no idea what's going on with that... maybe put back in your old names.lst?

**Comment by BloodStoneBBS** [comment]
I'm such a DOLT.
names.lst NOT names.lst-after del and fix
Renamed and I am beginning to see names again for pre 308. Have not checked 308 and up yet.

**Comment by BloodStoneBBS** [comment]
Appears to be better. 309 was a test account I made. Is now showing the user.

**Comment by BloodStoneBBS** [comment]
Fixed...  

Sorry about that last bit. working as it should now.

Any suggestion as to what to do about the duplicate user?  - I can check with Mark to see which one he uses and delete the other.

**Comment by wwiv** [comment]
yeah ask him or just delete the one which has the earliest last logon
