### ISSUE TITLE
chat whisper not displaying text

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#855]
OS: Linux
Version: 5.2.0.2153

Using whisper in chat (/username msg) is not working properly.  The notification that a message was sent works, but there's no text with it.

sender:

```
: /TESTUSER hello
[Message sent only to TESTUSER]
:
```

receiver:

```
From FOOBAR [WHISPERED]:
```

note how "hello" is not visible on the receiving end.

**Comment by wwiv** [comment]
fixed
