### ISSUE TITLE
finish wwivd

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#856]
need try..catch around main method.

**Comment by granitepenguin** [comment]
add IP blocking
allow daemon mode
enable defining of port
ssh support
ini file for config options
make wwivd more resilient against script-kiddies (i.e., clean up defunct processes on crap disconnects)

**Comment by wwiv** [comment]
what config options do we need?

port

what else?

**Comment by granitepenguin** [comment]
maybe multiple ports? Not sure if we need to be able to have more than one telnet port (one seems like enough, but it would be interesting to be able to define more than one).

how about log levels?
log location?

ability to change user privileges  (i.e., need root to bind to port 23, but should switch to the bbs user to run the binary; security blah blah).

**Comment by wwiv** [comment]
added ssh support, can set telnet and ssh ports.

**Comment by wwiv** [comment]
don't think we need multiple ports for same service, nor log levels (you can use -v=xxx on commandline to wwivd). 

I'd prefer if we could use fail2ban vs. own blocking if possible, I think that'd be a more robust solution. What should I add to the logs to help make that easier?

Also I thnk syslog support for events is needed, but that's probably about it. Happy to hear other thoughts

**Comment by granitepenguin** [comment]
fail2ban is actually pretty straightforward.  It's just defining a jail and filter for it.  for example:

```
jail:
[wwivd]
enabled   = true
filter    = wwivd
port      = 23
logpath   = /bbs/wwiv/wwivd.log
findtime = 600
maxretry  = 3
bantime  = 86400

filter:
[INCLUDES]
before = common.conf
[Definition]
failregex = INFO   Connection from: <HOST>$
```

This looks for 3 times in 10 minutes and blocks for a day and works off what we currently have.  We are assuming just looking for repeat logins is enough.  we only need to change logging if we want to get more fancy about what to look for, but that will be more complicated.  We would need to be able to tell more from bbs itself.  For example, if we could recognize trashcan-type activity and log it, that would be another thing we could filter and block on; but for simple wwivd, what we have now works.

**Comment by granitepenguin** [comment]
would there be any value in defining nodes to specific connection types?
for example:
telnet on nodes 2 and 3
ssh on nodes 4 and 5
etc

What about per-node settings, similar to the WWIV-1, WWIV-2 sections in wwiv.ini?

**Comment by granitepenguin** [comment]
what about using wwivd to manage a binkp listener?

**Comment by wwiv** [comment]
ok, possible to add binkp support in here... maybe I'd do that in wwivserver on windows too to match.   I'll open a new issue to track that.

as far as a basic wwivd, I think this is done. I'll also add an issue to document and improve logging to make fail2ban easy (well https://github.com/wwivbbs/wwiv/issues/864 covers improving logging I think)
