### ISSUE TITLE
wwivd cleanup defunct processes

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#857]
we are having a general issue with script-kiddies that are doing two things; tying up nodes and causing zombie wwivd processes.  From what I can see, wwivd works by having a parent process and spawns child wwivd processes.  When we don't get a clean disconnect, the child processes are being left out there as zombies.

``` bash
28491 pts/1    S+     0:00          \_ ./wwivd
28567 pts/1    Z+     0:00              \_ [wwivd] <defunct>
28583 pts/1    Z+     0:00              \_ [wwivd] <defunct>
28587 pts/1    Z+     0:00              \_ [wwivd] <defunct>
28591 pts/1    Z+     0:00              \_ [wwivd] <defunct>
28620 pts/1    Z+     0:00              \_ [wwivd] <defunct>
28624 pts/1    Z+     0:00              \_ [wwivd] <defunct>
```

I think they are related to return 134

2016-10-07 11:34:40,030 INFO   Invoking WWIV with command line:./bbs -XT -H6 -N3
2016-10-07 11:34:41,828 INFO   Connection from: 72.48.8.220
called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
Aborted
2016-10-07 11:35:14,891 INFO   Node #3 exited with error code: 134

We need to find a better way to tell when "bad things" happen.  Part of the issue is also that the bbs binary is getting hung and not properly cleaning up nodeinuse.\* files on exit.

**Comment by granitepenguin** [comment]
Just verified that ALL wwivd children are zombies, regardless of how the bbs binary is closed out.  Even on known good sessions (i.e., I logged in myself and checked the PID), when you log off the BBS, the wwivd process becomes a zombie.

**Comment by wwiv** [comment]
maybe I just need to call signal(SIGCHLD, SIG_IGN);
according to http://beej.us/guide/bgipc/output/html/multipage/fork.html

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/wwiv/commit/af16a8aca175451219796fc97f4cd0f09b6dc0e9
