### ISSUE TITLE
using /C disconnects

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#859]
OS Linux
version 5.2.0.2159

This doesn't happen all the time, unfortunately.  Sometimes when a user uses /C to enter chat, the bbs disconnects instead.

**Comment by wwiv** [comment]
oh, I saw this before on my test account, and the reason was I was out of time.  (I had a SL=10 account). is that the case here?

**Comment by granitepenguin** [comment]
I don't _think_ so, but that would certainly be a reason.

**Comment by granitepenguin** [comment]
Definitely not.  I have an SL=20 that has 19 minutes left on it that does it repeatedly.

**Comment by wwiv** [comment]
still doesn't reproduce for me

**Comment by wwiv** [comment]
Still can't reproduce, chat works for me.
