### ISSUE TITLE
bbs binary doesn't clean up nodeinuse files

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#860]
OS Linux

This is mostly a script-kiddie issue.  It seems that there are many cases where if the bbs binary does not exit cleanly, the nodeinuse file gets left behind and locks up that node because wwivd thinks it's in use.

**Comment by wwiv** [comment]
so is bbs still running too?

**Comment by granitepenguin** [comment]
no.  just orphaned semaphore files that prevent new instances from being started

**Comment by wwiv** [comment]
ok, I clean those up at startup now in https://github.com/wwivbbs/wwiv/commit/8ac6600e4c67bc6efeb64119619c6e08e8d18b7b
