### ISSUE TITLE
stopping wwivd should clean up semaphores

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#861]
If you stop wwivd (currently the only way is to kill the wwivd process directly), it leaves semaphores behind related to child processes.  Killing the parent should clean up after itself

**Comment by wwiv** [comment]
still happening?

**Comment by granitepenguin** [comment]
Yes. This is different than cleaning up when a session ends when someone logs out. This is cleaning up when you stop the parent wwivd

**Comment by wwiv** [comment]
got it, doing it at stop is hard, but doing it at start is easy. so I'm doing it at start now.

https://github.com/wwivbbs/wwiv/commit/8ac6600e4c67bc6efeb64119619c6e08e8d18b7b
