### ISSUE TITLE
make wwivd a proper service

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#862]
This is just notes about what kind of cleanup would be nice to properly package wwivd as a systemd service.  This may not be practical, but this outlines what I'm using right now and what would be "nice to have"

Right now, I'm using some script hackness to make wwivd a "service" for systemd.  To do that, I have a shell script in ${WWIV_DIR}/bin with the following:

``` bash
#!/bin/bash
#
# Start wwivd service
#
source ~/.wwivrc
cd ${WWIV_DIR}
./wwivd
```

and a systemd.service unit /etc/systemd/system/wwivd.service that looks like this

``` ini
[Unit]
Description=WWIV node manager
[Service]
ExecStart=/bin/su -s '/bbs/wwiv/bin/wwivd.sh' wwiv
[Install]
WantedBy=multi-user.target
```

so basically, systemd is calling the wwivd.sh script as the wwiv user, which sets up all the environment variables, makes sure the permissions are run as the wwiv user, etc.

Things that we would need to make this a "proper" service
1. figures out its own environment so it can find things like config.dat and runs from the wwiv directory
2. forks a child with the "right stuff" (i.e., the classic run as root, then drop privs so the important stuff is run as the wwiv user). 
3. logging that isn't so weird.  What makes it weird is syslog is getting entries because of systemd that are doubling up on datestamps because of stdout/stderr in addition to the stuff going to wwivd.log the result looks like this:

```
Oct 07 23:48:12 vps40748.vps.ovh.ca su[445]: 2016-10-07 23:48:12,706 INFO  Nodes in use: (1/5)
Oct 07 23:48:12 vps40748.vps.ovh.ca su[445]: 2016-10-07 23:48:12,715 INFO  [491] Invoking WWIV with command line:./bbs -XT -H6 -N3
Oct 07 23:48:43 vps40748.vps.ovh.ca su[445]: 2016-10-07 23:48:43,554 INFO  [477] Node #2 exited with error code: 0
Oct 07 23:48:51 vps40748.vps.ovh.ca su[445]: terminate called after throwing an instance of 'std::system_error'
Oct 07 23:48:51 vps40748.vps.ovh.ca su[445]: what():  Resource deadlock avoided
Oct 07 23:48:51 vps40748.vps.ovh.ca su[445]: Aborted
Oct 07 23:48:51 vps40748.vps.ovh.ca su[445]: 2016-10-07 23:48:51,914 INFO  [491] Node #3 exited with error code: 0
Oct 07 23:48:52 vps40748.vps.ovh.ca su[445]: 2016-10-07 23:48:52,338 INFO  Connection from: 223.115.144.30
Oct 07 23:48:52 vps40748.vps.ovh.ca su[445]: 2016-10-07 23:48:52,338 INFO  Nodes in use: (0/5)
Oct 07 23:48:52 vps40748.vps.ovh.ca su[445]: 2016-10-07 23:48:52,345 INFO  [496] Invoking WWIV with command line:./bbs -XT -H6 -N2
```

on the plus side, this captures info that does NOT make it into wwivd.log (ssh logging, for example)
4. options for the service in /etc/default.  This is where we would put things like verbosity and other command line options.  for example, this is what /etc/default/ssh looks like

``` bash
# Default settings for openssh-server. This file is sourced by /bin/sh from
# /etc/init.d/ssh.

# Options to pass to sshd
SSHD_OPTS=
```

**Comment by wwiv** [comment]
added sample files for systemd

**Comment by wwiv** [comment]
I think this is now fixed.  with https://github.com/wwivbbs/wwiv/commit/da0898d11d5091e92c2ce9151c945006f9e7b62e and https://github.com/wwivbbs/wwiv/commit/58825cc2f5dfac560893821a51547855089ed94a
