### ISSUE TITLE
Consolidate connection logs

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#864]
We should try to get all logging in one place as much as possible. Right now, there are so many logs of different formats all over the place.

**Comment by wwiv** [comment]
ideas appreciated on how this should look

**Comment by granitepenguin** [comment]
couple ideas to start with:
1. anything service-related should be logging as syslog facilities. 
2. items that are logging to syslog should not be also logging to separate files.

For example, looking at wwivd; all stdout/stderr (what you used to see on the console) already goes to syslog. In the case of ssh connections, that's the _only_ place you see the connection details/error messages.  All the other info is duplicated; written to both syslog and wwivd.log.  It should all go to one place.  

Biggest problem I see ATM with fixing this: unix and Windows are different; and it means different things (i.e., there's no syslog in Windows, so we'd have to log Windows events to accomplish the same thing).  talking about wwivd as an example is tough because it's a unix-only application.  For something like network*, writing to local logs in the WWIV_DIR is handy to make it the same for both, but is duplicating effort.

Ultimately what I'd like to figure out is a single place to log everything so we aren't looking for one piece in syslog, another in WWIV_DIR, another in gfiles, another in the Event Viewer, etc.

**Comment by wwiv** [comment]
Logs are now almost entirely in the logs dir.
