### ISSUE TITLE
5.2.0.2174 bbs.exe crashing - Appeared to be at logoff

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#869]
Saw activity on console, JAH posting on the General SUB, glanced back a moment later and say that bbs.exe had crashed.
Windows 7 x86 

![capture1](https://cloud.githubusercontent.com/assets/13243281/19221106/6bb80740-8df1-11e6-8a04-847fa6edeebd.PNG)

**Comment by wwiv** [comment]
really without a stack trace from a debug build, this doesn't help me. if you can compile bbs.exe and run that and get a stack trace from it that'd be great.

**Comment by BloodStoneBBS** [comment]
I'll give that a try but only if upgrading to the latest build(s) don't already resolve the issue.  It looks like you have been very busy since I opened this ticket and haven't seen anyone else discuss crashing. Probably unique to my setup. 
Closing for now, will open a new ticket if it continues with later builds and I can get a stack trace.
