### ISSUE TITLE
need net52 replacement for lnet

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#871]
probably put in wwivutil

**Comment by mmunson** [comment]
Would it be more like LNET-II the dos program by Ken Harris?

**Comment by wwiv** [comment]
I've not really run it, so unclear.  Do the docs have screenshots?  I have it, but it's not registered so the nag at startup is annoying.  Do you have Ken's email address? Maybe he'll give me a key to look at it

**Comment by wwiv** [comment]
I wonder if it'd be enough just to let wwivutil net handle this vs. being interactive.

something like:
```wwivutil net rm --num=2 [packet file name]```
or
```
wwivutil net rm --start=2 --end=10 [packet file name]
```

similar to wwivutil messages dump

**Comment by wwiv** [comment]
This is now done in 5.8
