### ISSUE TITLE
net commands called from WFC spraying to screen

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#873]
when running WFC and a net callout is run, the network\* binaries are spraying to stdout and the formatting is a mess.

When being managed by WFC, the call should be silent, or formatted differently.

**Comment by wwiv** [comment]
can you add a screenshot?

**Comment by granitepenguin** [comment]
![spray_formating_output](https://cloud.githubusercontent.com/assets/913430/19425944/17e9f6ec-93fe-11e6-9c47-6eb59cba5b50.png)

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/wwiv/commit/7b6b9ff1629bb23723cdf35e7717dc22ff8e9e0d
