### ISSUE TITLE
Move auto callout from WFC to wwivd

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#874]
It would be better headless operation for the server services to manage call out instead of WFC.

**Comment by wwiv** [comment]
Implemented in 
https://github.com/wwivbbs/wwiv/commit/5a17d00604c75cf1bd309178e3dc0734e7a4680e
and
https://github.com/wwivbbs/wwiv/commit/5455ed7a98568ca368cc8b8ed1f3e3ff598329a0

**Comment by wwiv** [comment]
wwivd does everything needed for callouts.  Next up is to remove auto callouts from bbs.exe entirely.  Also since bbs.exe is no longer expected to stay up, we'll remove events too.
