### ISSUE TITLE
bbs Resource deadlock error

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#875]
OS: Linux
version: 5.2.0.2199

in the wwivd log, I'm seeing the following error message 

```
Oct 16 15:11:30 vps40748 wwivd[27079]: 2016-10-16 15:11:30,988 ERROR Caught system_error with code: generic:35; meaning: Resource deadlock avoided
Oct 16 15:11:31 vps40748 wwivd[27079]: 2016-10-16 15:11:31,030 ERROR !carrier(); threads_started_ = false
Oct 16 15:11:31 vps40748 wwivd[27079]: terminate called without an active exception
Oct 16 15:11:31 vps40748 wwivd[27079]: Aborted
```

It appears to be related to script-kiddie disconnects; real logoffs don't do it.

**Comment by wwiv** [comment]
This is benign, and may be fixed in https://github.com/wwivbbs/wwiv/commit/334e3ce6b2e0cbc8c2384d5069fa5f4368ca3266

**Comment by wwiv** [comment]
holler if you still see if after the last fix
