### ISSUE TITLE
trashcan does not log IP address

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#876]
Trashcan.txt file works, but it did not put the IP address in the log.

`Oct 16 17:43:24 vps40748 wwivd[27079]: 2016-10-16 17:43:24,832 INFO  Trashcan name entered from IP: ; name: ROOT`

**Comment by granitepenguin** [comment]
also, if trashcan is triggered by a new user setup, it successfully disconnects, but nothing is logged at all.

**Comment by granitepenguin** [comment]
looks like the "no IP logged" is only when ssh is used to connect.  if connected via telnet, the IP address is captured

`Oct 16 17:53:36 vps40748 wwivd[27079]: 2016-10-16 17:53:36,244 INFO  Trashcan name entered from IP: 71.201.51.130; name: ROOT`

**Comment by wwiv** [comment]
is there any log entry at all on ssh?

**Comment by granitepenguin** [comment]
if a trashcan name is used to try a login, trashcan logs the attempt, but if it's over ssh the IP address is empty.

if a trashcan name is used during NEW user setup, regardless of connection type, it logs nothing at all.

**Comment by granitepenguin** [comment]
not quite there yet...  SSH returns the loopback IP, not the remote IP

Trashcan name entered from IP: `127.0.0.1`; name: ROOT

new user setup input looks better, though.

```
Oct 16 19:07:32 vps40748 wwivd[933]: 2016-10-16 19:07:32,475 INFO  New User Attempt from IP Address: 71.201.51.130
Oct 16 19:07:55 vps40748 wwivd[933]: 2016-10-16 19:07:55,590 INFO  Trashcan name entered from IP: 71.201.51.130; name: ROOT
```

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/wwiv/commit/c67c7c334ee743798f9fb11fceaa59826375ddc5
