### ISSUE TITLE
log username and IP of new login attempts

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#877]
I'd like to see the IP address and username used for new login attempts get logged so it's possible to see what usernames are being used by bots so trashcan.txt can be updated to block them.

**Comment by wwiv** [comment]
what do you mean by new login attempts?

**Comment by granitepenguin** [comment]
Right now, there's no way to see what names are being used when login attempts are made.  If you look at the gfiles/*.log files, you see things like

`*** NEW USER 10/16/2016   17:49:47    115200 (6)`
and 
`### ILLEGAL LOGON for Root #14 (17:30:22)`

I'd like to see better info in this log that details names attempted to be used and the IP address.  trashcan isn't very helpful because we have to guess what names people are going to try to use.  I'd like to have logging of every name attempted at login, whether it was successful or not so we can identify things to add to trashcan.txt.  Ideally, we could even have failed names auto-added to trashcan.txt for us.

A successful login has:

```
652: Root #14 17:20:40 10/16/2016   115200 - 6 (3)

   Remote IP: 187.85.205.100

  Logged Off At 17:20:40
```

but the format of the log is atrocious for parsing (eg, to use for fail2ban) and we don't get any of this on Unsuccessful attempts
