### ISSUE TITLE
Events seem borked, keep looping

### ISSUE THREAD

**Issue by rdfig** [wwivbbs/wwiv#894]
Running event called fido to execute the networkf for import and export.  When executes continues in a loop and never exits back to the bbs.exe

[events.txt](https://github.com/wwivbbs/wwiv/files/614377/events.txt)

open up with wordpad

**Comment by wwiv** [comment]
as an aside, you can now use networkc to invoke networkf if needed (as well as calling the rest of the network*.exe commands to process whatever mail is waiting)
