### ISSUE TITLE
Replying to FT Netmail from bbs doesn't work

### ISSUE THREAD

**Issue by rdfig** [wwivbbs/wwiv#895]
Here is attached networkf.log on responding to netmail received from hub.
[networkf.txt](https://github.com/wwivbbs/wwiv/files/614404/networkf.txt)

**Comment by wwiv** [comment]
It seems that the to: line isn't being set right from wwiv when replying to a FTN netmail

**Comment by wwiv** [comment]
wwiv doesn't have the contents of the sender text line apart from inside of read_type2_message. We need it outside of there so we can set the TO line properly.

**Comment by wwiv** [comment]
Try it now. I may have fixed it as part of my message base code cleanup yesterday.  @rdfig

**Comment by rdfig** [comment]
Works.  Need some cosmetic changes but it is functional.

**Comment by rdfig** [comment]
Addressing correctly.  But for some reason I see the netmail get imported into Mystic but I don’t see the netmail.  A mystic issue maybe.  I might try and go DB route and see if I can make that work better.

 

Echomail traffic works fine the way I have it setup (place traffic in folder so either system can send and receive), just does not do it for netmail  Also have *.dlo files left in the  folder

 

 

Ruben D. Figueroa, Owner

RDFIG Computer Solutions

Email Support:      rdfigsupport@rdfig.net <mailto:rdfigsupport@rdfig.net> 

General Support:  rdfigueroa@gmail.com <mailto:rdfigueroa@gmail.com> 

Cell Phone          :  (972) 839-9551

Web Location     :  http:// www.rdfig.net <http://www.rdfig.net/>
