### ISSUE TITLE
fullscreen reader hangs if inactive

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#901]
OS: Linux
version: 2327

If you are using the new reader and do not send any keypresses (eg, walk away from the computer), after about 3 minutes, the viewer won't accept any more keyboard input.  This locks up the node.  It happens whether connected through the local WFC or via syncterm.  At least in syncterm, you can hang up, but it doesn't clean up the node and leaves it hung (I had to manually kill the bbs process to clean it up).

To repro:
1. log in
2. use the new viewer to read a message
3. don't send any keyboard input for 3 minutes

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/wwiv/commit/8acadad6436d5a45d9e33a8fd5e741f498ffa09a

**Comment by granitepenguin** [comment]
Not fixed -- avoided.  I tried testing this and the new hangup exception handler is being too aggressive.  If I try to leave the reader up to see if it locks up, I get disconnected at 3 minutes

```
652: Granitepenguin #1 11:45:48 12/03/2016   KB - 5 (1)

  S
   hangup_error:GRANITEPENGUIN hung up.
Read: 3   Time on: 3
```

So I can't tell if this is fixed or not because the hangup_error is stepping in and knocking me off, even when logged in as sysop (which should not time out).

**Comment by wwiv** [comment]
Sysop login always times out for me. Or is supposed to :-)

The hangup error is supposed to happen. Instead of every for loop checking
hangup this error is thrown.

**Comment by wwiv** [comment]
I removed the "hangup_error" word from the log, but this is fixed.  The problem that you weren't getting disconnected locally was a bug that we weren't checking the timeout right (and was also affecting some remote users I think since I've seen it hung up on my bbs)
