### ISSUE TITLE
WFC Minutes used race condition

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#902]
OS: Linux 2.6.32-42 64bit
Build: 2328 (jenkins build)

Some kind of weird race condition of the Minutes Used display in WFC.  In the span of about 15 minutes after updating and restarting, it went from 0 to 2600 minutes used

```
12/03 10:42  Mins Used Today... 0 Mins (0.0%)
12/03 10:49  Mins Used Today... 1290 Mins (89.6%)
12/03 10:53  Mins Used Today... 1949 Mins (135.3%)
12/03 11:00  Mins Used Today... 2609 Mins (181.2%)
```
Possibly related to this, some of my userrec appears to have been corrupted.  Some of my user defaults (ANSI, 24hour time, possibly more) were changed.  

I restored my 2327 and it's fine again.  Going to play around a bit and see if I can reproduce it.

**Comment by granitepenguin** [comment]
ok, I made sure I've got everything shut down, wwivd stopped, etc and finished updating to 2328 and everything looks ok now. (possible?) source of confusion is wwivd.  When I updated, the way I do it is I pull the build from Jenkins and copy the new binaries with
``cp -v bbs init wwivutil network networkb networkc networkf network1 network2 network3 wwivd build.nfo whatsnew.txt /bbs/wwiv/
``
I'm thinking maybe because the wwivd service was still running, it might have borked something when I stopped it and re-copied the new wwivd binary.  That's only a theory at best, though.

**Comment by granitepenguin** [comment]
Well, that wasn't it.  It's still doing it even after a clean restart of all the binaries and recopying while I know everything is shut down.

**Comment by granitepenguin** [comment]
It's also "better" than before.. it jumped to 1420 minutes right away, but it hasn't gotten any worse.  Just leaving it to run for a while to see if it stays stable.

**Comment by granitepenguin** [comment]
Ok, definitely related to wwivd and external logins.  If I have WFC running, but do not have wwivd up, the counter doesn't climb.  If I have wwivd enabled so external logins work, as there's activity, it's jumping up by hundreds of minutes at a time instead of one.

**Comment by wwiv** [comment]
This should fixed in https://github.com/wwivbbs/wwiv/commit/d737c38e7ee927b4fc579fae560b6a1fd666d694
