### ISSUE TITLE
fullscreen reader does not support animated ANSI art 

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#903]
Not like this is surprising or anything, but if you go back and view animated art (for example, one of Mark's old animated weather maps in the Ansi Art Gallery), it doesn't play as animation; you just page through the multiple pages.

**Comment by wwiv** [comment]
So for these subs, you should disable the full screen reader (it's now also a per-sub option).  (P) is the letter for the option in boardedit.
