### ISSUE TITLE
fullscreen reader hide/customize header display

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#904]
It would be nice to be able to control what headers are displayed, or have a toggle to enable/disable viewing it (so there's more viewable space).

**Comment by wwiv** [comment]
a bit unclear...

how would you envision this working.

per message you can toggle off some headers, all headers, something else?
per user setting or per-message base, or per system?

**Comment by wwiv** [comment]
Will do not per-user, but the sysop can change the header via editing a msg file

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/b3bad0235a72cc6725b7195ffd4014fb0bfc66f0 and related pushes
