### ISSUE TITLE
fullscreen reader not displaying taglines

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#907]
OS: Linux
Build: 5.2.0.2336

Noticed that the full-screen reader does not honor/display tags.

**Comment by wwiv** [comment]
can you post an example of the message. Also dump it using wwivutil message dump and include that too please.

**Comment by wwiv** [comment]
dump it with -all.  I see taglines

**Comment by granitepenguin** [comment]
here's an example without tags in the FSreader

![screen shot no tags](https://cloud.githubusercontent.com/assets/913430/21086589/7c2fed3a-bfe3-11e6-9c5d-b08b0de29cd6.png)

and the same message with tags in the traditional reader

![screen shot tags](https://cloud.githubusercontent.com/assets/913430/21086597/830af94c-bfe3-11e6-8bde-5efd3030339b.png)

**Comment by granitepenguin** [comment]
Message [1841.txt](https://github.com/wwivbbs/wwiv/files/645041/1841.txt)

Generated by ``wwivutil messages dump  --start=1841 --end=1841 --all genchat> 1841.txt``

**Comment by granitepenguin** [comment]
just loaded up 2374.  Looks good.
