### ISSUE TITLE
node hung with perpetual error filling bbs.log b2331 and b2337 so far

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#909]
Windows 7 w32 b2331 and b2337

Two days now, finding session repeating ERROR !connected(); threads_started_ = true.

bbs.log grew to 24 mb in 24 hours.
wwivsync.log grown to 111 MB 

[wwivsync.zip](https://github.com/wwivbbs/wwiv/files/634084/wwivsync.zip)

[bbslog.zip](https://github.com/wwivbbs/wwiv/files/634078/bbslog.zip)

**Comment by wwiv** [comment]
Should be fixed in latest build. I saw this and fixed it last noght

**Comment by BloodStoneBBS** [comment]
Thanks, I upgraded to the latest build this morning. Will keep an eye on it.

**Comment by wwiv** [comment]
let me know if you still see it. I don't see it anymore today

**Comment by BloodStoneBBS** [comment]
No, don't see that exact issue anymore but there is still something funky going on. Hard to describe but I am finding some sessions locked up with a b/w ansi menu with no functional prompts. I'll try and capture more info and open a new ticket if it still occurs after updating to the latest build.

**Comment by wwiv** [comment]
Yup, I saw that too.

**Comment by wwiv** [comment]
https://github.com/wwivbbs/wwiv/commit/68f157dcc6b601e88d5e19258d7337f610dcf78d should (hopefully) fix it.
