### ISSUE TITLE
timeout kicking off without warning while in the fullscreen reader

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#911]
It's fine if you get logged off after the three minute inactivity timeout, but there should be a warning (visual and audio) that you are going to get logged off.  Right now, you just get uncerimoniously dropped with no warning.

**Comment by wwiv** [comment]
Fixed in https://github.com/wwivbbs/wwiv/commit/3be44667f89ed9e05e5ccd45de6a6b31ddda388a
