### ISSUE TITLE
add ability import echos easily

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#917]
1) Auto import unknown areas, using data from backbone.na and merging it with default values
2) Also integrate with areafix, so you request an area, then auto-add it with a set of defaults.

**Comment by ericpareja** [comment]
isn't backbone.na fidonet specific?

**Comment by wwiv** [comment]
the backbone.na import support is in wwivutil now.

**Comment by wwiv** [comment]
with backbone.na support (or any file name in that format, I used fsxnet.na) this is done
