### ISSUE TITLE
B 5.2.0.2363 - Win 7 - Unable to "A" reply to e-mail.

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#921]
Also noticed in previous build. When attempting yo reply to an e-mail message I get either:
"Deleted network,"
-or-
"Unknown system number."

Occurs with both new FSED and traditional.

Residual from earlier default settings glitch?

**Comment by BloodStoneBBS** [comment]
"A" does appear to work in the SUBS.

**Comment by wwiv** [comment]
Is it fixed now in 2363? @BloodStoneBBS

**Comment by wwiv** [comment]
should be fixed

**Comment by BloodStoneBBS** [comment]
Yes! Works now. Thanks!

Sorry, was out of town. Justvupdatedcthis morning.


Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
