### ISSUE TITLE
title display not honoring page up / page down locally

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#931]
OS: Linux
Build: 2376

The new fullscreen title display is not responding correctly to page up / page down keys if run locally through WFC.  It does work through SyncTERM

**Comment by wwiv** [comment]
are you sure the keystroke is getting though.  in bash I typed control-v and then the key to see the next key stroke and didn't see it register page up or down

**Comment by granitepenguin** [comment]
I know it's trying to respond because I can see the screen repaint happening.

**Comment by granitepenguin** [comment]
on a whim. I was looking up scan codes for the pageup/down issue; I'm on an iMac with a full keyboard hitting 9 and 3 on the numeric keypad works to send page up/down but the page up / down keys don't work in a terminal window but do work in sync term.

So there's some weird case with the Apple keyboard sending a slightly different code that it doesn't like.  Is it possible to capture the actual code sent?

**Comment by wwiv** [comment]
when in a terminal window, are you telnet'ed into the bbs or running at console?

**Comment by granitepenguin** [comment]
telnet (ssh). Using [karabiner](https://pqrs.org/osx/karabiner/index.html.en) I was able to see the codes being picked up by the system:

eventType:KeyDown         code:0x74       name:Page Up         flags:Fn                                 misc:KeyCode::PAGEUP	 characters:    
eventType:KeyUp           code:0x74       name:Page Up         flags:Fn                                 misc:KeyCode::PAGEUP	 characters:    
eventType:KeyDown         code:0x5c       name:9               flags:NumPad                             misc:KeyCode::KEYPAD_9	 characters:9   
eventType:KeyUp           code:0x5c       name:9               flags:NumPad                             misc:KeyCode::KEYPAD_9	 characters:9   

The 0x5c works as a page up, the 0x74 does not.

**Comment by wwiv** [comment]
happy to accept a patch on this one, but I'm not likely to dig in.

**Comment by granitepenguin** [comment]
Issues with Prompt iOS application pgup/pgdn probably the same issue as this.

**Comment by wwiv** [comment]
What terminal app are you using?

**Comment by granitepenguin** [comment]
I've tried various, but the main one is iTerm2 (better ANSI/ASCII display)

For local, what I typically do is:
1. open iTerm2
2. ssh to the BBS box's OS (not connect to the BBS directly)
3. run a GNU screen session (so I can reconnect to it later)
4. su to the wwiv (bbs) user
5. run ./bbs to get WFC
6. Fast logon

I have also tried telnet directly to the BBS
1. open iTerm2
2. telnet to the BBS (not the OS)
3. login normally

Both do the same thing, so it isn't a problem with weird interpretation by extra layers.  It's just something about the scan code generated by the Mac keyboards.  I'm not surprised that Prompt behaves the same way, since it's written by Mac users.

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/wwiv/commit/16266b0c8df158309a28c39f0083e992d5151b3b
