### ISSUE TITLE
fullscreen "are you there" message doesn't go away

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#932]
When the "Are you There?" message gets displayed, if you hit a key it doesn't go away.  Instead of clearing out, it keeps displaying "Are you there?" even though you are navigating, scanning titles, etc

Repro:
1. scan titles
2. wait for message to display
3. hit keys to scan up/down/etc
4. see that message doesn't go away

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/wwiv/commit/e002623f07ecd0c9c8280346eadad2ef78912bcc
