### ISSUE TITLE
Implement FTS-0009 REPY kludgeline

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#935]
See http://ftsc.org/docs/fts-0009.001

**Comment by MarkHofmann11** [comment]
You might want to look at this, also.  INTL kludge, which I added to
WWIVTOSS a few years ago.  http://ftsc.org/docs/fsc-0081.001

**Comment by wwiv** [comment]
1st part done here: https://github.com/wwivbbs/wwiv/compare/f399ce9d60d6...32c9f3c2794d

**Comment by wwiv** [comment]
Finished here: https://github.com/wwivbbs/wwiv/compare/b97f521cc5b4...e5057c9c9849
