### ISSUE TITLE
Feature Request: Add the ability to go to a specific message # in FS-Reader.

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#939]
Great new tool but there is currently no way (that I know of) to jump to a specific message. Can this be added?

**Comment by wwiv** [comment]
pressing J should do this.

**Comment by wwiv** [comment]
make sure you have the latest help screen copied out of the distribution files into your ```gfiles\ ```directory

**Comment by BloodStoneBBS** [comment]
Of course.. Thanks!
