### ISSUE TITLE
traditional title display needs cleanup

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#942]
OS Linux:
Build: 2392

With the updates to the Title scan display to work with the new Full-Screen reader, there are some odd display issues with the traditional reader Title scan output now.  Most notable, there's a blank line at the top of the list, and no bottom footer bar.  It's not necessarily "wrong" but it doesn't feel quite right.

![screen shot 2016-12-20 at 13 26 51](https://cloud.githubusercontent.com/assets/913430/21364825/17da808a-c6b8-11e6-8bc8-b55276dda081.png)

More importantly, when the From field is too long, it wraps and breaks the formatting 

![screen shot title formatting](https://cloud.githubusercontent.com/assets/913430/21364759/bd8792b2-c6b7-11e6-8793-4f3f68ba7575.png)

**Comment by wwiv** [comment]
odd, I don't see the space
