### ISSUE TITLE
Traditional Editor: "Q" no longer takes you from messages to Main menu.

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#952]
OS Windows 7 Build 5.2.0.2405

Logged in as a test user and read a few past messages. Hit Q to leave the SUB and return to the Main menu but Q only quits the SUB that you are in and takes you to the next SUB.

**Comment by wwiv** [comment]
I'll need more to go on. I did this in 5.2.2416

//unqscan (make all messages new)
N
then Q from the read prompt
Said no to post.
back at main menu.

N
T to go to the title scan
then Q from the read prompt
Said no to post.
back at main menu.

**Comment by BloodStoneBBS** [comment]
DId not //unqscan but logged in as a test user I have on my board that has not read many messages.  When offered to read new messages, Y
Read first couple of messages, hit Q. No additional prompt to post, jumped right to first new message in next SUB.
Easily seen om my system Will e-mail you the password for user 5

**Comment by wwiv** [comment]
well I can't repro it on my own account on your bbs either :(

**Comment by wwiv** [comment]
ok, it's only with the non-full screen reader

**Comment by BloodStoneBBS** [comment]
Maybe something with SyncTerm?
Will try a few more things tomorrow.


Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
