### ISSUE TITLE
WFC "S" status is missing a CR/LF

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#953]
OS: Linux (and sounds like Windows, too)
WWIV Version.... 5.2.0.2416

Looks like the status screen on WFC (hitting the "S" key) has a display bug.  Note that the first item in the list starts at the end of the field separator (i.e., there's a missing CR/LF)

![screen shot 2016-12-27 at 08 52 40](https://cloud.githubusercontent.com/assets/913430/21501955/ea9a772e-cc11-11e6-9404-d7b6f599775b.png)

**Comment by granitepenguin** [comment]
Just updated to build 2421, issue still there.

**Comment by wwiv** [comment]
@granitepenguin fixed this in https://github.com/wwivbbs/wwiv/commit/035400e362dc0ec64506b3a282c5249e11152fdf
