### ISSUE TITLE
Intermittent - Deleting old message in SUB crashes BBS

### ISSUE THREAD

**Issue by BloodStoneBBS** [wwivbbs/wwiv#958]
OS Windows 7 x86
Build 5.2.0.2421 - Had not tried earlier versions for this bug.

Deleted a message in my System Notifications sub 0, and the BBS crashed right at "Post credit removed = 0"
Closed out the error screen and found the message to be gone. Tried again in the same sub and I was able to delete a couple more without issue. Them moved to a networked sub and tried to delete a couple of my old test posts, was able to delete two before crashing again at the same point. Closed out the error and tried again. Crashed on the first attempt. Same spot, just after the post credit removed = 0.
 Seems like an access violation based on the Just in time debugger.  0xC0000005:
All done from local login.

**Comment by wwiv** [comment]
looks like when you delete the 1st post, it crashes.  All others are fine.

**Comment by wwiv** [comment]
doesn't reproduce in 5.1.2076

**Comment by wwiv** [comment]
only reproduces with the full screen message reader.

**Comment by BloodStoneBBS** [comment]
You ROCK!
