### ISSUE TITLE
can't set user to 255 with UE

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#959]
OS: Linux (debian on x86_64 or raspbian on ARM)
Build: 2421

Stumbled across this while setting up myself as a cosysop on my RPi test board, but the issue exists on the regular linux board, too.  It happens when validating a user via feedback, and also when running //UE

If I am logged on as the sysop user (1), and try to change the SL of another user to 255, it fails with the following.

```
S) SL           : 10                                                            
T) DSL          : 0                                                             
Z) Restrictions :   M                                                                                                                                           
(Q=Quit, ?=Help) User Editor Command:                                                                                                                           
New SL? 255                                                                     
You can not assign a Security Level to a user that is higher than your own.
```

Obviously, I'm not setting it to something higher than myself, I'm setting it to something equal to myself (255).

However, if I run init and use the User Editor there, it works.  This appears to be isolated to in-BBS UE only (//UE and WFC "U").

**Comment by wwiv** [comment]
Moving to 5.3. It's been this way since 4.24 at least 

```
        case 'S':
          if (u.sl >= actsl)
            break;
          nl();
          prt(2, get_string(76));
```

**Comment by granitepenguin** [comment]
I guess it's just rare to see it because you almost never set other people to 255 (at least, not outside of init).  Still, it's a fail to give the wrong error message.
