### ISSUE TITLE
changing user settings for online user gets overwritten

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#960]
OS: Linux (both x86_64 and ARM)
Build: 2421

If I user is still logged in while I make changes to their info with //UE (setting SL, restrictions, etc). The settings do not stick.  It looks like the user's current settings at logon are stored and get written back to disk at logout, overwriting the changes.  The user has to be offline for my changes to stick.  I understand this is known, but not documented and not expected.  We need to more intelligently handle the situation, even if it's disabling the ability to modify an online user (display a note that you can't do it, etc).  That would be better than silently not working.

Ideally, figuring out a way that you _can_ do it would be even better.  I have not been able to test the Function keys part of this because they don't work for me in linux.  That may be a separate issue with not using a "real" console and being logged in via screen over ssh

**Comment by BloodStoneBBS** [comment]
I have seen this as far back as 4.30. Thought it was simply because the user record was locked while the user was online.

**Comment by granitepenguin** [comment]
Which is fine, except how it does it is confusing and non-intuitive.  We need to clean up the UX so it makes sense instead of silently failing.

**Comment by BloodStoneBBS** [comment]
Agreed. If possible, a fix would be the best solution.

**Comment by wwiv** [comment]
Having a functioning ```F1``` on linux would make this work too :)

**Comment by ericpareja** [comment]
I suppose the trouble stems from the model for user data updating having been designed for a single instance BBS, user data being loaded into memory when the BBS is started up, then only being written out to disk on logout. If the on-disk data for the user is updated mid-session, this gets trashed by in-memory user data being written to disk on log-out. User records are written out in full, not just the "updated" bits. 

We could re-do userrec struct to separate the bits that (a) self can change, (b) extern can change, (c) other scenarios. Possible fixes include: 1) reading in userrec from disk just before writing to check for any change then merging the changes in, 2) locking userrec on disk while user is online, 3) adding a semaphore(?)

What we're trying to avoid is the race condition of userrec changing on disk while user is online, right?

**Comment by wwiv** [comment]
Fix changing user settings for online user gets overwritten (#960)

    Add a new internal semaphore file in scratch dir: readuser.wwiv
    This will cause the bbs to reload the current usernumber.

    This will likely get replaced with an instance message to the node soon.
