### ISSUE TITLE
instructions for linux need to ensure unzip is installed.

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#964]
On debian8, unzip isn't installed by default, and is needed to be installed.

I wonder if we should have a meta-package for debian that has the requirements init?

@granitepenguin WDYT?

**Comment by granitepenguin** [comment]
probably easier than trying to check for everything in the installer, but it doesn't help on non-delian systems

**Comment by granitepenguin** [comment]
I added this as part of the patches to the installer (i.e., it's fixed in 5.3 and the 5.3 docs), but how do we add this to the 5.2 docs?
I'm not familiar with adding something to older branches

**Comment by wwiv** [comment]
oh the 52 docs are on the wwiv52 branch on the docs repository

See 
```
https://github.com/wwivbbs/docs/tree/wwiv52
```

**Comment by granitepenguin** [comment]
addressed in https://github.com/wwivbbs/docs/commit/2623fc41c6a5c3c0cc351cab5b9e67907f63a773
