### ISSUE TITLE
create install Makefile targets

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#973]
We should be able to allow someone compiling from source to do a make --install and have it behave correctly.

**Comment by wwiv** [comment]
what should this build though?  The wwiv-win-5.3-buildno.zip file?  Or the image on disk after you unzip that artifact?

**Comment by granitepenguin** [comment]
no, you are missing my point.  "make install" should actually install the software.  Normally on linux, you have a configure script that figures out everything, then you run make to build all the binaries.  Then you run make install to set everything up.  This would be similar to what the install.sh script does (more or less) today, just in a more expected "normal" format/process.

**Comment by k5jat** [comment]
Might as well do a "make upgrade" for those that don't need a full install.

**Comment by wwiv** [comment]
This now works. Example
```
export WWIV_DIR=/wwiv
  cmake .. -DCMAKE_INSTALL_PREFIX=${WWIV_DIR}
  cmake --build . --target install
```

Then you just have to run wwivconfig to complete the install.
