### ISSUE TITLE
logon script not rendering header correctly

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#977]
OS: Linux (debian)
build: 2448

Something odd is happening with the rendering of the one-liner script
![screen shot 2017-01-09 at 17 49 22](https://cloud.githubusercontent.com/assets/913430/21788415/28e78f3a-d694-11e6-8c6d-a16f54eebfc7.png)

This used to look fine, and the file hasn't changed

```mono
wwiv@vps40748:~/gfiles$ ls -l oneliner.msg
-rw-r--r-- 1 wwiv wwiv 368 Dec 31 10:41 oneliner.msg

wwiv@vps40748:~/gfiles$ cat oneliner.msg
|10     WWIVbasic Presents:
|11                           | |(_)
|11           ___  ____  _____| | _ ____  _____  ____ ___
|11          / _ \|  _ \| ___ | || |  _ \| ___ |/ ___)___)
|11         | |_| | | | | ____| || | | | | ____| |  |___ |
|11          \___/|_| |_|_____)\_)_|_| |_|_____)_|  (___/
|11
|03                                   Based on oddliners by Eli!
```

**Comment by wwiv** [comment]
looks like my code to move pipe code expansion to bputs (from bputch) broke |

**Comment by granitepenguin** [comment]
This isn't fixed.  It's working locally (ssh to a terminal), but it's still broken via SyncTERM (although it's broken differently than before).

This is a better illustration, at least.  Looks like the pipe characters are getting stacked at the beginning instead of being used in the output as expected (similar to what we were seeing in message subs)

![screen shot 2017-01-10 at 09 22 32](https://cloud.githubusercontent.com/assets/913430/21812428/889117a6-d718-11e6-9925-7455eeb04715.png)

**Comment by wwiv** [comment]
ok, only with syncterm mac, not syncterm windows

**Comment by granitepenguin** [comment]
Ok, looks like it's fixed to me

**Comment by wwiv** [comment]
fixed in https://github.com/wwivbbs/wwiv/commit/1d5e8962e990f62299f3053a5ddbe790ef4d115b
