### ISSUE TITLE
bbs -V leaves log in current dir

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#980]
If you run bbs -V, it not only outputs the version info, it writes a few lines of information to the log.

```
2017-01-11 07:45:29,871 INFO  bbs version 5.3.0.2454 (Jan 11 2017, 05:53:12)
2017-01-11 07:45:29,871 INFO  bbs starting at Wed Jan 11 07:45:29 2017
2017-01-11 07:45:29,871 INFO  command line: -V
```

The problem is, if you are not in your wwiv directory when you do it, it leaves little log turdlets wherever you currently are on the filesystem.  For example, if you are in the scripts directory when you run ~/bbs -V, you end up with a bbs.log file in scripts instead of appending to bbs.log in the wwiv directory.

We should probably think about forcing a log location for binaries, especially for one-off options like -V.  

Realistically, do we need logging at all when running something like version?  Maybe binary start data is not INFO, but a v=1 or v=2, since the main value of it is for debugging?

**Comment by wwiv** [comment]
hmm... do you think having the command line args at INFO is useful? I do. That'd still leave logs.  Also even if I moved these to v=1, it'd still create empty log files.

**Comment by granitepenguin** [comment]
The problem I see is not every single thing a binary does makes sense to log by default.  The default mode of operation should be relatively quiet (if not completely silent) for some things. bbs -V is a good example of something that fits this category.  All it does is tell you the version, why does it need to spray log data to disk by default?

The empty log file issue is still a problem regardless. If we have to log, we should really think about consolidating a logging location for binaries. The default behavior of just dumping wherever we are at the time is the root issue.  IIRC, I have something similar to this in another issue somewhere (EDIT: #864).  An ini setting for logging in general would probably be helpful so all binaries log to a central location.  Ideally, on a linux system anything that logs should really be to syslog.

**Comment by wwiv** [comment]
one problem with putting the bbs.log next to bbs.exe is that I often run a bbs.exe from ~/git/wwiv/bbs/bbs vs. current dir. that'd put the log in the wrong place

**Comment by granitepenguin** [comment]
That's a variation on the same issue. Ultimately the problem is logging behavior is fundamentally flawed in general. That's why I say if it's going to log, where it logs should be configurable.

**Comment by wwiv** [comment]
I'm now thinking the start/stop log isn't super useful anymore.
