### ISSUE TITLE
WFC log output in a curses window instead of stdout

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#983]
When WFC calls out, it would be nice to the log scroll with the header would leave the header destination stay on the screen.  

![screen shot 2017-01-13 at 19 55 50](https://cloud.githubusercontent.com/assets/913430/21951347/9beac0ea-d9ca-11e6-887c-94f00b676181.png)

What it does now is you briefly see the callout header, then it gets blown away by the logging.

**Comment by wwiv** [comment]
hard to do since the output from networkb is a new binary, not part of the bbs which is using curses.  best I can do is just nuke the header. WDYT @granitepenguin

**Comment by granitepenguin** [comment]
Hmm... yeah, I don't know.  Is it worth the effort to clean that up?  there are a few different ways to look at it:
1. the log details aren't necessary in the first place (everything is logged to disk already).  You could just write a comments in the dead space on the bottom of the WFC (eg, "Calling WWIVnet Node 1", "WWIVnet call complete", etc).
2. Drop the header would be the easiest short term solution
3. change the network* binary to a curses interface if called from WFC.  Not sure that level of effort is needed, certainly lower on the food chain.

**Comment by wwiv** [comment]
Not going to fix this, am moving callouts to wwivd.
