### ISSUE TITLE
Move binaries into their own zip file (starting with wins)

### ISSUE THREAD

**Issue by wwiv** [wwivbbs/wwiv#984]
Since the basics work without wins (you just need it for nntp/internet email somewhat currently) and the default is just FTN/WWIVnet out-of-the-box. I'm going to move it to it's own zip file (it'll still be in the bbs zip , but unside a wins-exe.zip or something like that).

I may also move the rest of the exe's into a exe.zip too, then install.{sh.cmd} can unzip that as-needed.

**Comment by wwiv** [comment]
@granitepenguin WDYT?

**Comment by granitepenguin** [comment]
I think this is good idea, but I'd go one step further.  Put all the *zip file in a subdirectory (eg, zipfiles) so they aren't cluttering up the root wwiv directory.

ie, this:

```bash
-bash-4.2$ ls
bbs        changelog.txt  menu.txt  network2  networkc         systemd       wwiv-linux-5.3.2472.tar.gz
bin        init           network   network3  networkf         whatsnew.txt  wwivutil
build.nfo  install.sh     network1  networkb  readme-wwiv.txt  wwivd         zipfiles
```

Looks better than this:

```bash
-bash-4.2$ ls
bbs            data.zip      install.sh  network2  networkf         syncfoss-source.zip  wwiv-linux-5.3.2472.tar.gz
bin            gfiles.zip    menu.txt    network3  readme-wwiv.txt  systemd              wwivutil
build.nfo      inifiles.zip  network     networkb  regions.zip      whatsnew.txt         zip-city.zip
changelog.txt  init          network1    networkc  scripts.zip      wwivd             
```

**Comment by wwiv** [comment]
what if instead of zipfiles, we called it arcs/${BUILD_NUMBER} and baked that into the sh script (we have it from the build).

That way you could even revert easily to an older build.

**Comment by granitepenguin** [comment]
That would probably be ok.  One thing I did notice that I didn't before is the zip files get blown away by init expanding them, so we'd have to make sure we take that into account to avoid wiping them out.  Otherwise, we'd have a bunch of empty arcs/${BUILD_NUMBER} directories.

**Comment by wwiv** [comment]
Oh init moves these zip files to DLOADS/SYSOP by default... not sure why, it's not useful there at all.  I figure we'd just leave them in the old location.  WDYT @granitepenguin ?

**Comment by granitepenguin** [comment]
yeah, that works

**Comment by wwiv** [comment]
I removed WINS from the archives.
