### ISSUE TITLE
init segfault on new sysop creation

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#985]
Looks like there is an issue with a segfault in init (more carryover from FB).  Trying to get more details about reproducing.

**Comment by granitepenguin** [comment]
Jay, if you could detail an exact list of commands, start to finish that you are doing, what version of CentOS you are running (a uname -a should be enough to get a good ballpark).  It sounds like there's a bit of confusion regarding how all the bits stick together that we just need to get cleared up.

**Comment by granitepenguin** [comment]
Looks like this is a general problem, not CentOS-specific.  Working on getting a backtrace right now.

**Comment by granitepenguin** [comment]
Steps to repro:

1. untar latest tgz into a new wwiv directory
2. run init
3. When prompted "Would you like to create a sysop account now?", say "Y"
4. segfault (see bt below)

```gdb
Program received signal SIGSEGV, Segmentation fault.
0x000000000060f25f in wwiv::sdk::User::CreateNewUserRecord (u=0x7fffffffd520, 
sl=10 '\n', dsl=0 '\000', restr=4, gold=100, 
colors=std::vector of length 0, capacity 0, 
bwcolors=std::vector of length 0, capacity 0)
at /bbs/build/wwiv/sdk/user.cpp:129
129   u->SetColor(i, colors[i]);
(gdb) bt
#0  0x000000000060f25f in wwiv::sdk::User::CreateNewUserRecord (
    u=0x7fffffffd520, sl=10 '\n', dsl=0 '\000', restr=4, gold=100, 
    colors=std::vector of length 0, capacity 0,
    bwcolors=std::vector of length 0, capacity 0) at /bbs/build/wwiv/sdk/user.cpp:129
#1  0x000000000059a757 in create_sysop_account (config=...) 
    at /bbs/build/wwiv/init/sysop_account.cpp:99
#2  0x0000000000562c9f in CreateSysopAccountIfNeeded (bbsdir="/tmp/wwiv/") 
    at /bbs/build/wwiv/init/init.cpp:187
#3  0x0000000000563730 in WInitApp::main (this=0x8be600, argc=1,
    argv=0x7fffffffe718) at /bbs/build/wwiv/init/init.cpp:288
#4  0x00000000005628dc in main (argc=1, argv=0x7fffffffe718)
    at /bbs/build/wwiv/init/init.cpp:156
```

**Comment by wwiv** [comment]
didn't crash for me on 2463 with this fix
