### ISSUE TITLE
fbackhdr.net mangled in WWIVnet report

### ISSUE THREAD

**Issue by granitepenguin** [wwivbbs/wwiv#990]
When you run network3 to generate a report, the resulting packet is really messed up.

![screen shot 2017-01-16 at 09 26 41](https://cloud.githubusercontent.com/assets/913430/21989118/5a5d5f96-dbcf-11e6-811d-8a5e4b40c0f3.png)

Still working on understanding exactly what issue I'm seeing.

**Comment by wwiv** [comment]
If you still have this can you check if it's mangled on the non-full screen reader? (I deleted mine already)

**Comment by granitepenguin** [comment]
traditional reader looks fine, so this is a display issue.
